rh-hideout/pokeemerald-expansion

data/battle_scripts_2.s

In an attempt to match the structure of upstream, I reintroduced the comments that point out the Poké Balls affected by each BallThrow battlescript in `gBattlescriptsForBallThrow`. 
Lunos#4026
As usual, if there's anything wrong please let me know.

Added comments for each entry of gBattlescriptsForBallThrow

---

src/daycare.c

By default, when merging with Pokémon Expansion, breeding Pokémon like Munchlax doesn't require the use of incenses. This will fix that.

Added breeding effects for Incenses.

---

include/battle_util.h
include/constants/battle_config.h
src/battle_main.c
src/battle_util.c
src/pokemon.c

In the Gen. 4 of mainline Pokémon games, the stat boosts provided by having certain badges were removed.
I decided to reincorporate them behind a battle configuration option because why not.
Lunos#4026
I don't think I missed anything, but if I did, let me know.

Reincorporated badge based stat boosts

---

include/constants/battle_config.h
include/pokemon.h
include/wild_encounter.h
src/battle_interface.c
src/battle_script_commands.c
src/data/battle_moves.h
src/wild_encounter.c

- Tweaking `battle_config` to accomodate `pokemon_config` and `item_config`
- Configurable double wild battle chance, surfing double battles and flag for forcing them.
- Organized interface settings into their own category.
- Adapting move changes to `battle_config`

More Battle Config options

---

include/constants/battle_config.h
src/battle_script_commands.c

Mirror of [#368 on Egg's repo](https://github.com/DizzyEggg/pokeemerald/pull/368). Adds a couple options for experience calculation.
`B_SPLIT_EXP` - If set to >=`GEN_6`, all participating Pokémon receive the full yield, and unsent mon with an Exp. Share receive half.  
`B_SCALED_EXP` - If set to `GEN_5` or >=`GEN_7`, experience yields are weighted based on relative level and the denominator in initial calculation is changed (/5 instead of /7).
MandL27#1732

More exp options in battle_config

---

src/data/text/abilities.h

fix quotes around "effective" in some ability descriptions
eg. `“super effective.“` -> `“super effective.”`
ghoulslash#3839

Fix ability description strings

---

src/battle_anim.c

For whatever reason, the labels used to enable/disable new or old move animation particles were named differently in the file where they act, than in the file in which they're defined.
This PR fixes that.
Lunos#4026

Fixed anim. settings labels in src/battle_anim.c

---

src/battle_anim_water.c

The anim. setting `B_NEW_SURF_PARTICLE_PALETTE` wasn't doing anything at all, so I went ahead and gave it a reason to exist.
When set to `TRUE` it'll make Surf use a more Gen. 4 like palette for its animation.
Lunos#4026

Added functionality to the B_NEW_SURF_PARTICLE_PALETTE anim. config label

---

data/battle_scripts_1.s

Increases the `pause` length in `BattleScript_AbilityPopUp` to prevent multiple ability popups from overwriting the previous.
**OLD**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **NEW**

Prevent Ability Popup overwrites

---

data/battle_scripts_1.s

This was causing every move after judgment to use the wrong effect (off by one).
Thank you eatthepear for catching this and providing a fix

Remove Techno Blast and Judgment from battle scripts

---

src/battle_message.c

No example for this one since I couldn't think of an example to use. I found it by testing a custom ability in my game that is a special attack version of intimidate, which uses `PREPARE_ABILITY_BUFFER`.

Fix Buffering abilities > 255

---

data/battle_anim_scripts.s

I notice this in a random test. babydoll eyes when used on the player appears behind the mon. This PR fixes the issue:

Fix Babydoll eyes animation

---

src/battle_util2.c

Previously, ending a battle with an active terrain would mess up the battle transition/background on subsequent battles. Setting `gFieldStatuses` to 0 at the end of battle resolves this.

Fix Terrain BG on new battles

---

src/battle_anim_new.c

I'm PR'ing this now because I'm not sure if I'll be able to solve the animations crashing the game.
Partly solves #1266
Techno Blast's animation was set out of a handful options depending on the holdEffectParam of the item the user was currently holding.
I made it check for `HOLD_EFFECT_DRIVE` and use their secondaryId, which is where they have their types set for use.
Lunos#4026

Made Techno Blast's animation change depending on the Drive held

---

include/constants/battle_config.h
src/battle_script_commands.c

Addresses #1284.
From Gen. 4 onwards, Spite always reduces 4 PPs from the foe's last used move, and it doesn't fail even if said move only has 1 PP left.
I don't think anyone in their right mind would ever want to use its Gen. 3 effect, but I added a config anyway.
Lunos#4026

Updated Spite

---

data/battle_anim_scripts.s
src/battle_anim_new.c

Currently, shadow sneak does not properly return the ANIM_TARGET from the background, causing the level up box to not appear properly: https://discord.com/channels/442462691542695948/533083367818657792/785921673915793420
This PR replaces the shadow sneak animation with the CFRU one, shown in the GIF below. It's a better animation and fixes the issue above.

Fix Shadow Sneak Animation

---

src/data/pokemon/base_stats.h

There isn't an `ABILITY_AS_ONE` defined in the `include/constants/abilities.h` of the battle_engine branch, so this wasn't building a ROM correctly.
https://github.com/rh-hideout/pokeemerald-expansion/blob/pokemon_expansion/src/data/pokemon/base_stats.h#L34158
https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/include/constants/abilities.h#L290
This PR adddresses that.
Lunos#4026

Corrected the ability 1 of Calyrex's forms

---

data/battle_scripts_1.s
src/data/battle_moves.h

After #1287, I decided to look into Final Gambit since it had the same effect as Dragon Tail assigned to it for some reason.
I found out that the move's true effect was already done. It was simply not assigned to the move in its data, for whatever reason.
On top of that, it was also missing the `FLAG_KINGSROCK_AFFECTED`, so I threw it in.
Lunos#4026

Corrected Final Gambit's move data and tweaked its effect

---

src/battle_util.c

Flower Gift is only supposed to boost Attack, in other words, physical moves.
Its ability effect within `CalcAttackStat` was missing a relevant check.
Lunos#4026

Added missing check to Flower Gift (offensive)

---

src/data/pokemon/base_stats.h

Some ifdefs for items were accidently BATTLE_ENGINE instead of ITEM_EXPANSION which led to breaking builds of just Battle Engine Upgrade + Pokemon Expansion since these items are only defined in Item Expansion. This PR changes them to ITEM_EXPANSION therefore fixing the issue.
UltimaSoul#4017

Corrected Defines for Item Expansion-introduced Items in Gen 8 Species Data

---

src/battle_util.c

Fixes mummy activating on the turn an attacker uses Dig/Fly

Fix Early Mummy Activation

---

include/battle_debug.h
include/constants/battle_config.h
src/battle_controller_player.c
src/battle_util.c

It was brought to attention yesterday that unlike every other battle related configuration, the constant that toggled the in battle debug menu was located outside of `include/constants/battle_config.h` so I moved it there for consistency sake.
I also tweaked the comments for `HIDE_HEALTHBOXES_DURING_ANIMS` and `B_TERRAIN_BG_CHANGE` because they were inconsistent with many many comments above them.
Lunos#4026

battle_config.h tweaks

---

src/data/pokemon/item_effects.h

This PR complements #1276 and makes it so the X Sp. Def can work if the user sets the battle_engine branch's `X_ITEMS_REWORK` flag to `TRUE`.
Lunos#4026

Reworked the effects of the X Items #2

---

src/battle_controllers.c

~See comments in change.~
the call to `BattleAI_SetupAIData` isn't necessary, and is dangerous if we just finished a double battle as this function modifies array elements by using `gActiveBattler` as the index (e.g. during the `SaveBattlerData` call done by `AI_CalcDamage`) and `gActiveBattler` isn't reset upon entering a battle
this bug affects vanilla as well, but vanilla does not perform any array element writes and any garbage values due to the result of reading an invalid array element are reset when the AI chooses its move

Fix AI corruption bug.

---

src/battle_util.c

Adds missing parenthesis to fix wrap-style moves.
They dealt 8/16 fixed damage instead of dividing the targets max HP by that value.
Karathan#1337

Fix wrap-style move damage

---

src/data/battle_moves.h

Corrected Mind Blown's category after BigAngryDev pointed out on Discord that the battle_engine had the wrong one.
Lunos#4026

Fixed Mind Blown's category

---

src/battle_script_commands.c

The list was missing a few abilities that are not supposed to be affected by Gastro Acid, as per the following list.
https://bulbapedia.bulbagarden.net/wiki/Category:Abilities_that_cannot_be_suppressed
I also ordered them alphabetically because it was easier to read, but I can undo that if it's a bad idea.
Lunos#4026

Updated the list of abilities unaffected by Gastro Acid

---

src/data/battle_moves.h

Fire Blast previously had 120 power for `B_UPDATED_MOVE_DATA >= GEN_6` instead of 110. This PR swaps them so the updated move data is correct
see https://bulbapedia.bulbagarden.net/wiki/List_of_modified_moves#Generation_V_to_Generation_VI

Fix Fire Blast Power

---

src/battle_util.c

Make `CANCELLER_THAW` reference a function `IsThawingMove` to update the list of thawing moves to include scald, flare blitz, pyro ball, and others.

Update Thawing Moves

---

src/data/pokemon_graphics/front_pic_anims.h

This PR fixes an issue with Keldeo Resolute's animation brought up by @kevinmc37 in #1335
**Before**:
**After**:
Lunos#4026

Fixed Keldeo Resolute's animation

---

src/battle_main.c

According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Magic_Room_%28move%29), Magic Room blocks the speed drop of macho brace/power items, which is not the case in the Battle Engine.

Magic Room Affects Macho Brace/Power Item Speed Drop

---

include/constants/battle_config.h
src/battle_script_commands.c

Add config option `B_TAILWIND_TIMER` to update tailwind to last 4 turns instead of 3

Update tailwind timer To Gen5

---

src/battle_util.c

Ghost types can switch from abilities such as Shadow Tag, but not from moves (Mean Look, Infestation, etc.). This PR fixes the latter.

Fix Ghost Types Unable to Escape

---

data/battle_scripts_1.s

Stop Spiky Shield freezing the game if an attacker faints itself before taking damage from Spiky Shield.
Spiky Shield no longer tries to hurt a Pokemon that has already fainted. Previously this would freeze the game if Jump Kick recoil fainted a Pokemon due to the target using Spiky Shield. 
I'm pretty sure recoil if miss is the only effect that can cause this, but this should also prevent any future issues with Spiky Shield damage.

Fix Spiky Shield/Jump Kick freeze

---

src/battle_anim.c

On the latest commit involving the `src/battle_anim.c` file, the header file `include/constants/battle_moves.h` was included to be read even though there isn't such a file in the project, and as a result, a ROM of the battle_engine couldn't be built.
The correct file to make `src/battle_anim.c` read is `include/constants/moves.h`.
Lunos#4026

Fix src/battle_anim.c

---

src/battle_util.c

Currently, Mega Evolutions don't check for a Keystone item, like the Mega Bracelet present in the ITEM_EXPANSION branch.
Lunos#4026

Added a check for the Mega Bracelet in CanMegaEvolve

---

src/battle_util.c

Addresses #1269
Currently, powder moves work incorrectly if the user is a grass type and the move targets the user. E.g. This means Amoonguss is immune to its own Rage Powder, making one of its best moves completely useless for it.
Add a condition to skip the powder canceller check if the target is the move's user.

Fix powder immunity for self-targeting moves

---

src/battle_script_commands.c

Prevents the 'charge-up' turn of two-turn moves failing if there is no target. see linked issue

Fix Two-Turn Moves Failing Innapropriately

---

src/battle_util.c

Issue: status orbs don't check if the holder is alive, so they'll inflict status conditions on a fainted mon. When the mon is revived it will still have the status condition. They also affect mons with Water Bubble (which should be unaffected by the Flame Orb) and Comatose (which should be unaffected by both orbs).
Fix: Added a check to both orbs to make sure the holder isn't fainted, and checks for Water Bubble and Comatose.
Discord: Buffel Saft#2205

Fix Toxic Orb and Flame Orb affecting Pokemon they shouldn't

---

data/battle_scripts_1.s
src/battle_script_commands.c

Big Root should increase the amount of HP recovered by Absorb, Giga Drain etc. This part of its effect wasn't implemented.
This PR fixes this by calling manipulatedamage DMG_BIG_ROOT after each use of setdrainedhp in battle scripts. 
Because GetDrainedBigRootHp and setdrainedhp both change the sign of the damage calculated (so it heals instead of damaging the attacker), I've removed the sign change from setdrainedhp to stop them from cancelling each other out. Without this change GetDrainedBigRootHp would make gBattleMoveDamage a negative number, and then setdrainedhp would make it positive again.
GetDrainedBigRootHp is always called after setdrainedhp, so this doesn't affect anything elsewhere.

Make Big Root affect absorb moves

---

src/data/pokemon/level_up_learnsets.h

LEVEL_UP_END is already defined in constants/pokemon.h

Remove superfluous define of LEVEL_UP_END

---

src/data/battle_moves.h

The contact flag was removed in Gen 4, and the base power was lowered in Gen 6. Currently, the changes are flipped around.

Corrected the move data for Gen 4 Overheat

---

src/battle_interface.c

the function `HideMegaTriggerSprite` is missing a check to make sure the sprite ID actually exists. If the sprite doesn't exist, `gBattleStruct->mega.triggerSpriteId` is set to `0xFF`, which means `gSprites[gBattleStruct->mega.triggerSpriteId].tHide = TRUE` is setting some unknown value outside the bounds of the sprite data to 1.
This bug appeared in my own game as setting one of the trainer's pokemon's max HP to 1, resulting in battle-breaking problems. It is likely the culprit for several unexplained bugs we've seen in the past.
The fix is simple, we just need to make sure `gBattleStruct->mega.triggerSpriteId != 0xFF` in `HideMegaTriggerSprite`

Fix data corruption from HideMegaTriggerSprite

---

include/constants/pokemon.h
include/pokemon.h

Introduce `NUM_ABILITY_SLOTS` to eliminate an `ifdef`
Depends on #1464

Introduce NUM_ABILITY_SLOTS

---

src/pokemon.c

`EVO_LEVEL_DARK_TYPE_MON_IN_PARTY` wasn't working, and now it does.
Lunos#4026

Fixed Pancham's evo method

---

include/constants/pokemon.h
src/battle_util.c
src/data/battle_moves.h

Add a new move flag that allows a ground type move to hit airborne targets, and fix Thousand Arrows' effect chance.
Thousand Arrows can do now damage to:
- Flying type targets; it'll do 1x damage regardless of their secondary typing.
- Targets with Levitate
- Targets holding an Air Balloon
- Targets under the effect of Magnet Rise and Telekinesis
Also fix Thousand Arrows' effect chance; it should be 100%, not 0%. This will make it knock any airborne targets it hits to the ground.

Fix Thousand Arrows

---

src/data/text/item_descriptions.h

"Pokéblock ingredient" doesn't fit in a single line of the box in which item descriptions are printed, which is why the `{POKEBLOCK}` character was used.
This PR reverts some descriptions to make use of it again.
Before -> After
Lunos#4026

Corrected the item descriptions of some berries

---

src/data/pokemon/base_stats.h

the .noFlip value for all Pokemon was wiped and incorrectly restored at some point in the creation of the pokemon expansion. I have corrected the values using both vanilla emerald and a few other sources, including: pokediamond, hgss/bw2 overworlds, and oras/usum menu sprites.
this is partially incomplete as i am unable to look through the raw hex data for bw2 and oras.
i also took the liberty of adding the flag to spiky-eared pichu as it shared pichu's data in gen 4, its only appearance, while being clearly asymmetrical.

restore and add noFlip values

---

src/battle_ai_main.c

There's a call in `src/battle_ai_main.c` to a function that is not present anywhere in the rest of the branch.
This creates issues for users using merged branches. More specifically, users who may make use of the item_expansion branch along the battle_engine branch.
I decided to comment it out, in case the original author of the code eventually decides to incorporate the function.
Lunos#4026

Commented out call to inexistent IsZMove func

---

src/pokemon.c

If B_X_ITEMS_BUFF is set to GEN_8, it will go back to boost only one stat. This PR fixes it.

Fixed B_X_ITEMS_BUFF boosting 2 stages only in Gen 7

---

src/data/text/abilities.h

Title. There is not a single reason to make them read the abilities from `ABILITIES_COUNT_GEN8`, and it can get in the way of users who want to implement original abilities in their projects.
Lunos#4026

Made gAbilityNames and gAbilityDescriptionPointers read from ABILITIES_COUNT

---

src/battle_util.c

Like the title says. From bulbapedia for reference:
`During harsh sunlight, Flower Gift increases the Attack and Special Defense stats of the Pokémon with this Ability and its allies by 1.5×. `

Add Sunny Check to Flower Gift Ally Boosts

---

include/battle.h
include/battle_controllers.h
src/battle_controller_player.c
src/battle_controllers.c
src/battle_script_commands.c

This should provide support for gaining ridiculously large amount of exp, much larger than anyone would ever need. Correct number of points is printed in the message and given to the Pokemon.
Fixes #1455
Here's an example.
Note: Actually, you would get less than 100k points for fainting a 100k blissey with all boosts(lucky egg, traded mon), but I raised the modifiers for testing purposes.
https://i.imgur.com/iDZHBaz.gif

Allow larger exp gains

---

src/pokemon_animation.c

Egg originally did add `NUM_SPECIES` here to have placeholder entries for added mons, but it was recently removed in the sync PR #1469. Adding this back fixes #1522.
UltimaSoul#4017

Add back NUM_SPECIES to sSpeciesToBackAnimSet definition.

---

include/global.h

Allows testing for defines when the branch doesn't exist

Include expansion_branches.h in global.h

---

src/battle_script_commands.c

Simple fix that reverts Busted Mimikyu, Schooling Wishiwashi, Blade form Aegislash, Zen Mode Darmanitan and Minior Meteor to their base forms when caught.

Undo form changes on capture

---

src/battle_script_commands.c

After #1565, the battle_engine branch has been unable to produce a ROM of its own because the calls to `UndoFormChange` in `src/battle_script_commands.c` were not updated.
Lunos#4026

Fixed calls to UndoFormChange in battle_script_commands.c

---

include/battle.h
include/battle_util.h
src/battle_ai_util.c
src/battle_script_commands.c
src/battle_util.c

From Bulbapedia:
"Generation VI onward
Grass-type Pokémon, Pokémon with Overcoat, Stalwart, Propeller Tail, and Pokémon holding the Safety Goggles are now immune to Rage Powder, such that their attacks are not diverted by it.
Fixes #1417

Rage powder updated to gen6

---

src/data/battle_moves.h

Liquidation is affected by Sheer Force, Sparkling Aria hits both foes and ally.

Correct Liquidation and Sparkling Aria move data

---

include/battle.h
src/battle_script_commands.c

Addresses #1609. Makes Protect-like moves (King's Shield, Spiky Shield etc.) activate only if the attacker would've touched the target. I.e. the extra effect of these moves won't activate if the attacker's move fails for some other reason, or if it's a charge turn, etc.
This is done by moving the check for activating these effects into the attack canceller for Protect (this is similar to what the CFRU does).
Also fixes Sucker Punch to behave correctly vs Protect, as it was printing the "target protected itself!" string:
Tested in USUM - "But it failed!" is the correct string.

Fix protect-like moves

---

include/battle.h
src/battle_script_commands.c
src/battle_util.c

Addresses #1619 
`moneyMultiplier` was being doubled every time a mon with `HOLD_EFFECT_DOUBLE_PRIZE` switched in, or happy hour was used.
This PR adds two flags to `moneyMultiplier` that prevent `HOLD_EFFECT_DOUBLE_PRIZE` and Happy Hour from infinitely increasing it. `moneyMultiplier` can't be more than 4 (unless O-powers are implemented at some point), so reducing it to 6 bits is fine.

Fix stacking effect on HOLD_EFFECT_DOUBLE_PRIZE

---

src/battle_ai_switch_items.c
src/party_menu.c

- block AI from using items
- block the player from using an item on an embargo'd mon
- `GetBattlerHoldEffect` already handles embargo negating hold effects

Add Embargo Effect

---

src/battle_script_commands.c

`gLastUsedItem` was not getting updated during the some checks, causing the string to print incorrectly sometimes (see #1638)
This fixes:
- Power Herb
- Resist Berries
Closes #1638

Fix Item Activation Messages

---

include/battle.h
src/battle_script_commands.c
src/battle_util.c

Fixes Echoed Voice. `echoVoiceCounter` was redundant, and so was removed and replaced with `gBattleStruct->sameMoveTurns`, which is what the metronome item uses for the power boost.
Closes #1640

Fix echoed voice power boost

---

src/battle_util.c

increments basePower by 40 * same move counter instead of multiplying base power by the counter, so 2nd usage of echoed voice will be `basePower += 40`, 2nd usage `basePower += 80`, etc.
Also caps base power to 200.

better echoed voice power boost

---

src/battle_script_commands.c

Changed GetNaturePowerMove to return the right move when used with terrain active based on:
https://bulbapedia.bulbagarden.net/wiki/Nature_Power_(move)#Generation_VII
Just a simple switch to check for each terrain.
alterrp#2960

Fixed Nature Power move on different terrains.

---

include/decompress.h
src/decompress.c
src/evolution_scene.c

Gender differences were not handled in the evolution animation. This PR fixes that.
`DecompressPicFromTableGender()` could be moved to `src/evolution_scene.c` as it's only used in that file, but I put it in `src/decompress.c` so that it's easier to use for custom features.

Show gender differences in evo scene

---

src/pokedex.c

Third time's a charm x)
(in BE because gTypeNames[TYPE_FAIRY] is not defined in PE)

Add fairy to dex search

---

include/battle_controllers.h
src/battle_controller_opponent.c
src/battle_controller_player.c
src/battle_controllers.c
src/battle_main.c
src/battle_message.c

Takes care of  #537
It is now possible to start a double battle with only one pokemon alive, or simply with one pokemon in the party. The battle should play normally, as it would do in a normal double battle where only one pokemon remains on the field.

Support for double battles with only one pokemon

---

src/battle_util.c

Fix bugs with the Download ability.
Download had two problems:
1. It didn't set the user as the attacker and then called a battle script that raised the attacker's stat, causing it to regularly raise the foe's stats instead of the user's.
2. When looping through opposing battlers to determine which stat to raise, instead of checking the foe's ally's stats in the second iteration, it checked either the user's stats or its ally's stats, causing it to raise the wrong stat.
This PR fixes both issues.

Fix Download

---

data/battle_scripts_1.s
src/battle_script_commands.c

Addresses #1651:
The extra waitmessage command is ugly but appears to be needed - if it's moved after the printstring, the message isn't displayed long enough on single hit moves, so I've left it there and added another one, which is needed for multihit moves.

Fix multihit moves vs damage reducing berries

---

include/battle_script_commands.h
src/battle_ai_util.c
src/battle_script_commands.c

Changes how AI calculates critical hits in its simulated damage by providing expected move damage instead of fishing for crits in its simulation.
Karathan#1337

[ai] use expected value move dmg calculation

---

src/data/battle_moves.h

Reverts rh-hideout/pokeemerald-expansion#1671 as it was an incorrect change. Scald always thawed the user.

Revert "Scald thaw flag config for Gen 5"

---

src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

An edge case with weak armor + eject pack was conflicting with lash out. This PR fixes it and allows for further testing of the move effects.
basically, I had added a "disableEjectPack" field for when u turn is used on a weak armor'd mon holding eject pack. If this field was set, .statFell was not updated. Which prevents lash out from activating
so I moved that disableEjectPack check directly to the hold effect code
(and tested to make sure there was no regression)

Gen8 move effects Fixes

---

src/battle_interface.c

The indicator sprite currently overlaps the "100", so this PR just shifts it to the left if the mon is level 100 (or higher, as there's no harm in having it work with that).

Move mega indicator for lv 100 mons

---

src/data/text/item_descriptions.h

Improve ifdef for Mental Herb's description to be vanilla description when B_MENTAL_HERB is not equal to GEN_5 or greater and vice versa. Addresses the comment made by me in #1627 which was saying that this toggle should've been included like it was originally in #1355.
UltimaSoul#4017

Enable Mental Herb Description Toggling Based on B_MENTAL_HERB Config

---

src/data/items.h

Companion PR to #1714.
Assigns `FORM_ITEM_USE` constants to secondaryId field of items used for item-use form change methods.
UltimaSoul#4017

Assign FORM_ITEM_USE Constants

---

src/data/battle_moves.h

Psychic Fangs' power was set incorrectly.
Source: https://bulbapedia.bulbagarden.net/wiki/Psychic_Fangs_(move)
(Supersedes #1502 , resubmitted with Fontbane's permission)

Fixed Psychic Fangs power

---

src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

There are multiple instances where Gastro Acid isn't affecting abilities due to abilities being called directly from `gBattleMons[].ability` instead of `GetBattlerAbility`.
So far, it fixes it for:
- Sticky Hold (Addresses #1711)
- Run Away
- Using Perish Song with Soundproof
- Using Heal Bell with Soundproof
- Waking up from uproar
- Early Bird
- Pressure
- Yawn with Vital Spirit/Insomnia
This PR can potentially open the way to implementing Neutralizing Gas.
(I tested each instance before and after to confirm that they weren't working before and if they were fixed.)

Fix instances where Gastro Acid is not affecting the ability

---

src/battle_script_commands.c

Makes the following changes to Simple Beam:
- No longer freezes the game
- Now fails if the target's ability is already Simple
- Explicitly checks and changes the target's ability instead of gActiveBattler's ability

Fix Simple Beam

---

include/constants/battle_config.h
src/battle_util.c

In Gen 3, if both sides have a mon with Shadow Tag, neither side can escape. This was changed in Gen 4.

Config for Shadow Tag vs Shadow Tag

---

src/battle_ai_main.c

This will make the AI account for the type of moves like Weather Ball, Hidden Power and Revelation Dance when considering abilities that make them useless. E.g. Water-type Hidden Power vs. Storm Drain.
Example:
Kyogre only has Dark Pulse and Weather Ball here. After Dry Skin is revealed it knows that Weather Ball will do nothing, so it uses Dark Pulse instead.

AI handles dynamic move types

---

data/battle_scripts_1.s
src/battle_util.c

Addresses #1713 as well as fixing the string in `BattleScript_PerishSongBlocked`

Fix Soundproof cancelling out user's Perish Song

---

src/battle_script_commands.c
src/battle_util.c

Several of my PRs had mishandled the argument ordering of `DoesSubstituteBlockMove`, likely from copying directly from CFRU. This PR fixes those.

Fix DoesSubstituteBlockMove calls

---

src/battle_script_commands.c
src/battle_util.c

Rather than include prankster checks as a CANCELLER case, which messed with multi-target moves, I moved it to `ABILITYEFFECT_MOVES_BLOCK`, which still gets called for multi-target moves but does not require playing with the `atkCancellerTracker` value.

Redo Prankster

---

data/battle_scripts_1.s
include/battle.h
include/battle_util.h
src/battle_ai_main.c
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

Addresses #1813 
- `usedHeldItems` is expanded for each party member and side to remember consumed items even after switching
- Harvest now actually restores the berry using `tryrecycleitem`
Harvest:
Recycle:

fix recycle and harvest

---

data/battle_scripts_1.s
include/constants/battle.h
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

Addresses #1823 by adding a check for `(gHitMarker & HITMARKER_PASSIVE_DAMAGE)` in `Cmd_healthbarupdate` and `Cmd_datahpupdate`. It also documents `HITMARKER_PASSIVE_DAMAGE` and `HITMARKER_SKIP_DMG_TRACK`
OLD:
NEW:

Fix iteam healing after a failed move

---

data/battle_anim_scripts.s

As I was testing out a fix for the BGs' tilemaps, I came across this completely inconsequential typo.
As irrelevant as it may be, I think the right thing to do is to fix it.
Lunos#4026

Fixed Move_SPECIAL_REND typo

---

src/battle_util.c

I think I brought this up at some point inside the Discord server, but it was never fixed.
Lunos#4026

Fixed battlerId in Poison Touch's confusionSelfDmg check

---

src/battle_debug.c

Fixes rh-hideout/pokeemerald-expansion#1825
Sets init value to 2 which is inferred anyways due to the overflow
Karathan#1337

[battle_debug] fix charbase overflow

---

src/battle_util.c

Previously, the `species` data needed to be in a certain order and the `i` variable under `if (isSwitchingOut)` needed to be changed every time a new form that doesn't change when switching was added. Now it just needs to update data table to specify if the form reverts when switching.

Refactored UndoFormChange to make it more user friendly

---

src/data/items.h

To calculate the amount of power they boost, the battle_engine branch makes use of their `holdEffectParam`, as it can be seen in the `CalcMoveBasePowerAfterModifiers` function.
However, they don't have a `holdEffectParam` set, which means that a Dialga, Palkia or Giratina holding them won't see any benefits at all.
Lunos#4026

Gave a holdEffectParam to the Adamant, Lustrous and Griseous Orbs

---

include/constants/battle_config.h
src/battle_util.c

In Gen 3 and 4, if a mon with Synchronize was badly poisoned, it would regular poison the opponent. In Gen 5 onwards, it also badly poisons the opponent.

Config for Synchronize's interaction with toxic poisoning

---

src/battle_util.c

Kleneexfeu brought up the Soul Dew's effect in Pret's Discord, and I instantly remembered that I forgot to ensure that the offensive side of its Gen. 3-6 effect only applies to special based moves.
The defensive side already handles it thanks to `!usesDefStat`.
Lunos#4026

Fixed the offensive boost (Gen. 3-6 specifically) of the Soul Dew

---

data/battle_ai_scripts.s

There's a battle script that checks for some items using `.byte`, but after the recent revamp in the item_expansion, those items are placed well beyond the limits of a byte, causing a buffer overflow.
This PR fixes that, for the people who may use the IE without using the BE.
Lunos#4026

Fixed a small buffer overflow in AI_CV_Recycle_ItemsToEncourage

---

include/constants/battle_script_commands.h
src/battle_script_commands.c

All of the `MOVE_EFFECT_<stat>_<up/down>_x` effects were not showing the proper stat up/down animation when used by/on a battler with contrary. Addresses #1783 
Treecko has Contrary:
It isn't the prettiest solution, but it works

Fix Contrary Animation

---

include/constants/battle_config.h
src/battle_script_commands.c

Addresses #1669 
```
In Gen 4+, Brick Break can also break screens on the ally's side of the field. Not sure why anyone would want to do that, or if it's worth making it a config option.
In Gen 5+, Brick Break doesn't remove screens if the target is immune to Brick Break.
More importantly, it should also break Aurora Veil.
```

Update Brick Break with config

---

include/constants/battle_config.h
src/battle_script_commands.c

According to [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Wish_%28move%29), in Gen5+ wish heals half the user's max hp instead of the target's. This PR addresses that.

wish update

---

include/constants/battle_config.h
src/battle_util.c

Addresses #1886.
Added a config for Knock Off's damage boost. Also fixed the conditions it checks to do bonus damage:
- Shouldn't do bonus damage if the target can't lose its item
- Should do bonus damage if the target has Sticky Hold

Fix Knock Off, add config

---

src/battle_ai_util.c

PartyBattlerShouldAvoidHazards was using GetBattlerPartyData with an index party instead of a battlerId.
This caused GetBattlerPartyData to load wrong data. In my tests I had this function returning value like 0x207XXXX. I don't even know what kind of consequences it can have.
But it could potentially loads data from the PC, the flag area, etc.
PartyBattlerShouldAvoidHazards would then use this value as a pointer to a party data. So, when read, this "party data" would be turned into a bad egg -because of course it would have a wrong checksum- which means setting two bits in the RAM to 1 -one for being an egg, one for being a bad egg.
Since this "party data" isn't actually, in most cases, what it should be, it means values are randomly set in the ram. It could create bad eggs, set flags, …

PartyBattlerShouldAvoidHazards fix

---

include/constants/battle_config.h
src/battle_script_commands.c
src/battle_util.c

Now Leek should properly benefit Sirfetch'd and Galarian Farfetch'd.
**EDIT:** Now there's also a config for Leek's added effect on high-critical hit ratio moves in Gen 6+, and removed some redundant Gastro Acid checks.

Updated Leek's effect with config

---

src/battle_util.c

Unseen Fist allows contact moves to bypass protect effects, but doesn't lift their effects.
Addresses #1043

Implement Unseen Fist

---

src/battle_util.c

Fix parentheses in Unseen Fist check

Fix unseen fist check

---

include/constants/battle_config.h
src/battle_main.c

As the name suggests, after mega evolving, the turn order will be recalculated, as in genVII. Meaning a pokémon gaining/loosing prankster on the turn it mega evolves will actually have an effect if it uses a status move.
Same thing with speed boosting abilities or simply the speed being changed upon mega evolving.

Mega Evolution alters turn order

---

src/battle_script_commands.c

Gen 4+ Brick Break should remove screens on the target's side, not the attacker's (unless they're on the same side).

Fix Brick Break

---

include/battle_ai_main.h
include/battle_ai_switch_items.h
include/battle_main.h
src/battle_ai_main.c
src/battle_ai_switch_items.c
src/battle_controller_opponent.c
src/battle_controller_player_partner.c
src/battle_main.c

Addresses #1953 by removing the AI's consideration of its chosen move during `ShouldUseItem`
I could not reproduce the bugs reported in #1953 prior to the changes so this PR is experimental.

revert ai item usage code

---

src/battle_ai_main.c

previously was just resetting a single battler's protect struct

Fix AI protect struct reset

---

src/battle_util.c

As I was working on my project I noticed that while the data of Pikachu's forms in the pokemon_expansion branch shows they can hold a Light Ball, the Light Ball's effect itself inside the BE is hardcoded to `SPECIES_PIKACHU`.
This PR fixes that, and also improves readability for similar effects within the `CalcAttackStat` function.
Lunos#4026

Updated Light Ball's effect and improved readability

---

include/item_use.h
src/battle_interface.c
src/item_use.c

This PR clarifies some confusing semantics particularly with `CanThrowBall` previously returning `0` for success, and removes a redundant repetition of `CanThrowLastUsedBall`'s logic later on in `TryAddLastUsedBallItemSprites`.
Spherical Ice#4683

Refactor CanThrowLastUsedBall and related functions

---

src/data/items.h

Poisinium Z -> Poisonium Z.
Lunos#4026

Fixed a typo in the items' data

---

data/battle_scripts_1.s
src/battle_script_commands.c

Complements #1862
- Adds some more battle-will-end checks for other move effects such as overheat, superpower, etc
- Cleans up some code from #1862. Mainly, `gBattlescriptCurrInstr++` is not needed if `NoAliveMonsForEitherParty()` returns `TRUE` because the move effect is zeroed out at the end of the function.
- Small fixes to v-create's effect battle script

More battle-will-end checks on stat-changing damaging effects

---

include/pokemon.h
src/evolution_scene.c
src/pokemon.c

Starting from Gen. 7 there's moves that a Pokémon can learn during evolution, regardless of the level at which they evolve.
This feature is directly related to the different Pokémon species, so I see no reason why it shouldn't be a part of the pokemon_expansion.
Since it's not the type of functionality that doesn't get in the way and I don't think anyone wouldn't use, I didn't add a config, but if y'all deem it worthy to have one, I'll add one. 
Lunos#4026

Implemented evolution moves

---

include/constants/daycare.h

Changes `EGG_MOVES_ARRAY_COUNT` to 19 to actually include all the added egg moves in `u16 gEggMoves[]` and let them be learned e.g. at the daycare.
The max value seems to be 19 with Buneary using it (checked by AsparagusEduardo#6051).
TheXaman#5612

Change `EGG_MOVES_ARRAY_COUNT` to 19 to include all added egg moves

---

src/party_menu.c

There is no reason to flat out prohibit the Player from teaching the new TMs.
If the concern is that they don't have a move set, it's worth considering that the Player would never be able to get those TMs by default, and projects that made them available would 99.9% surely give them an actual move.
Lunos#4026

Tweaked CanMonLearnTMTutor

---

data/battle_scripts_1.s
include/constants/battle.h
src/battle_script_commands.c

> I don't like how the battle moves window remains opened as the ability pop up slides though. I feel we should probably make Protean print an empty string.
Before:
https://user-images.githubusercontent.com/4485172/149034487-33e10da3-78f7-495a-9555-8615299000df.mp4
After:
Lunos#4026

Tweaked Protean's effect's InGame appearance

---

src/battle_script_commands.c

Missing companion PR to #2016, was causing issues while merging both PE and BE.

Fixed Pokémon Expansion flag name in Battle Engine

---

src/battle_main.c
src/item.c

`IsAbilityOnOpposingSide(battler1, ABILITY_UNNERVE)` should've been changed to `IsUnnerveAbilityOnOpposingSide(battler1)`, but that's already handled by `HasEnoughHpToEatBerry`, so I'm removing the redundancy.
Also, removed the redundant ifdefs for `HOLD_EFFECT_CUSTAP_BERRY` and `HOLD_EFFECT_MICLE_BERRY`, as Battle Engine's hold effects are now supposed to be in sync with Item Expansion's

Removed redundant checks for Unnerve

---

include/constants/battle_config.h
src/battle_script_commands.c

Updated Conversion's effect

---

src/berry.c

Quick PR that fixes the names in src/berry.c (the ones that appear by interacting with berry plants).
SubzeroEclipse#7867

Decapitalization of berries 'names

---

data/battle_scripts_1.s
src/battle_util.c

Moving glare check against ghost types to `CalcTypeEffectivenessMultiplierInternal` so AI knows how to use it.

move glare effectiveness exception to code

---

src/data/text/move_descriptions.h

Quick PR that fixes a few move descriptions:
Wood Hammer - Added a dot to the first phrase
Drain Punch - Pointed to Mega Drain's description (it was pointed to Draining Kiss', but it doesn't heal 75%)
Mystical Fire - Corrected to its actual effect (before it said that may lower SpA, but always does that)
Behemoth Bash - sheild -> shield 
SubzeroEclipse#7867

Fixed some move descriptions

---

src/battle_util.c

`CanMegaEvolve` was reading the E-Reader Ligma Berry's effect if the battler scanned by it was holding the Gen. 4+ Enigma Berry.
Lunos#4026

Fix Enigma Berry check in CanMegaEvolve

---

data/battle_scripts_1.s

The labels for the battle scripts used by move effects have always closely reflected the actual move effect labels.
I'm not sure why was this not the case with `EFFECT_FLINCH_STATUS`, but now everything's alright. This PR brings balance to The Force.
Lunos#4026

BattleScript_EffectFlinchWithStatus -> BattleScript_EffectFlinchStatus

---

src/battle_message.c

I failed to notice in #1923 that the battle string was not being added to where normally are. This PR fixes that.

Moved Sky Drop battle string to where other battle strings are

---

src/data/text/move_descriptions.h

Noticed that both moves' description imply that the moves only have a single target, when it's not the case.

Adjusted description of Glacial Lance and Astral Barrage

---

src/pokedex.c

Addresses #2063.
As discussed in that issue, later gens show the dex entry upon catch with the personality of the caught mon, so to this PR applies that behavior to fix the edge case.

Addressed inconsistency in behavior with Shiny mon with gender differences upon catch

---

src/battle_message.c

There isn't a reason to keep a placeholder or an example put inside the array directly.
People playing through a project created with the battle_engine and that use trainer 0x291/657 could unexpectedly come across it in their projects which isn't nice.
I also took the chance to `#include "constants/opponents.h"` so trainer constants can be used.
Lunos#4026

Updated trainer slide-in array

---

src/pokedex.c

A recent change to pokemon expansion replaced CreateMonSpriteFromNationalDexNumber  with CreateMonPicSprite in Task_DisplayCaughtMonDexPage.
The former asks for national dex number while the latter asks for species number.
This causes no issues unless the dex order or species order is changed. If they are changed,  the wrong sprite is created.

Fix potential dex pic bug

---

src/battle_util.c

Addresses #1968. Bolt Beak now deals double damage if the target switches in. Uses the fact that isFirstTurn is set to 2 when a switch is made (because it is decremented after the turn ends) instead of creating a new variable; doesn't seem to cause issues. Gifs showcase damage boost applying after switching out and after U-turn.
**Regular Switch-In**
**U-turn**
**Before Fix**
Agustin#1522

fixed bolt beak switch-in boost

---

data/battle_scripts_1.s
include/constants/battle_config.h
src/battle_script_commands.c
src/battle_util.c

Heal block now stops healing from the following:
- Strength Sap
- Leftovers / Black Sludge
- Grassy Terrain
- Berries
- Shell Bell

Add missing Heal Block functionalities

---

include/constants/battle_config.h
src/battle_util.c

Added a config for these behaviors:
Generations III-VI
A confuse Berry, when held by a Pokémon, will restore 1/8 of its HP when its HP drops to ½ or below, but causes confusion to Pokémon that dislike the its flavor.
Generation VII
A confuse Berry now restores ½ of the holder's HP when it drops to ¼ or below.
Generation VIII
The restored amount decreased to 1/3 of the holder's HP.
Requires https://github.com/rh-hideout/pokeemerald-expansion/pull/2122 to work

Update Confuse Berry Hold Effect (Battle Engine)

---

src/data/items.h

Added a config for these behaviors:
**Generations III-VI**
A confuse Berry, when held by a Pokémon, will restore 1/8 of its HP when its HP drops to ½ or below, but causes confusion to Pokémon that dislike the its flavor.
**Generation VII**
A confuse Berry now restores ½ of the holder's HP when it drops to ¼ or below.
**Generation VIII**
The restored amount decreased to 1/3 of the holder's HP. 
Requires https://github.com/rh-hideout/pokeemerald-expansion/pull/2123 to work

Update Confuse Berry Hold Effect (Item Expansion)

---

src/pokemon.c

If a wild pokemon is a given an item through e.g. `setwildbattle`, the item will not get overwritten by `SetWildMonHeldItem`.

prevent overwriting wild mon held items

---

src/pokemon.c

Currently, the individual species for Castforms' forms that were added to the pokemon_expansion at some point glitch up InGame because they try to use a 2nd frame even though they lack one.
This PR fixes that by making `HasTwoFramesAnimation` filter them out. It's either that or copy-pasting a 2nd frame to each Castform form species' `anim_front.png`. This solution is probably cleaner.
Lunos#4026

Added Castform's forms to HasTwoFramesAnimation

---

data/battle_scripts_1.s
src/battle_gfx_sfx_util.c

Fixes Cherrim using Fire Castform's pallete when both are present under the sun.
Fixes Castform (and Cherrim) not swapping to their base form when weather effects fade.

Fix castform battle interactions

---

spritesheet_rules.mk

Add missing berry tree spritesheet rules

---

include/battle.h

Battle Engine adds a third type to BattleMons to support moves like Trick-or-Treat and sets its value to TYPE_MYSTERY for every mon that enters a battle.
Currently, the only known issue caused by this is that it makes self-inflicted damage by the confusion status receive STAB.
By making sure that a third type is ignored unless it's not Mystery, any similar problem can be prevented.

IS_BATTLER_OF_TYPE ignores third type if it's Mystery

---

include/battle_ai_util.h
include/constants/battle_ai.h
src/battle_ai_main.c
src/battle_ai_util.c

Adds missing AI interactions with x8 and x0.125 effectiveness attacks and removes a check for Strong Winds as that is already calculated in MulByTypeEffectiveness.

Type effectivess related AI bugfixes

---

include/constants/pokemon_config.h
src/data/pokemon/base_stats.h

Adds macros to handle assigning base stat values to Pokemon with multiple forms that have few or no differences from the base form.
Also fixes a few minor inconsistencies such as missing legendary flags.

Condense base_stats.h and make mass editing Pokemon forms/variants easier

---

src/battle_ai_switch_items.c

GestBestMonOffensive finds a mon whose types are super effective against the enemy's types that also has a SE move, not even checking for STAB.
Renamed it to GetBestMonTypeMatchup and made it find a mon that least resists the enemy's type combination and still has a SE move.

AI chooses most resistant mon instead of best offensive type

---

src/battle_script_commands.c

I suppose nobody found this until now because no one other than me tried to use the BE and the PE without the IE in recent times, but currently, a branch that only contains those 2 branches cannot build due to references to `ITEM_BEAST_BALL`, an item that only exists in the item_expansion.
Lunos#4026

Updated Cmd_handleballthrow

---

src/data/items.h

Current name implies the item is called "Castelia Cone", when it shouldn't. The item is called "Casteliacone" in the official games.
Lunos#4026

Updated the Casteliacone's name

---

src/data/battle_moves.h

Z-Move power wasn't being updated based on `B_UPDATED_MOVE_DATA`.

Updated Z-Move power for Gen 8 moves and moves with power varying by Gen

---

src/battle_ai_util.c

`IsBattlerTrapped` wasn't accounting for `B_GHOSTS_ESCAPE` config.

Ghost Escape config AI fix

---

src/battle_ai_main.c
src/battle_ai_util.c
src/battle_script_commands.c

- Sky Drop was using lbs in the formula instead of hectograms (kg * 10). This has been fixed.
- Sky Drop is now affected by weight modifiers like Float Stone.
- Enabled AI_CheckBadMove for Sky Drop.

Sky Drop fixes

---

include/constants/battle_config.h
src/battle_ai_util.c
src/battle_script_commands.c

Title.
Also, adjusted order of `else if`s to match Bulbapedia's description:
> If a Pokémon with Sturdy is holding a Focus Sash, Sturdy will activate first.

Config for Sturdy's Gen5+ effect.

---

src/battle_z_move.c

Spotted by blecoutre#8678.
The `IS_MOVE_STATUS` macro is expected to take a move as a parameter, not a move's category.
Lunos#4026

Fixed a wrong instance of IS_MOVE_STATUS in IsViableZMove

---

src/battle_script_commands.c

Fixed the odds for # of hits for mulithit moves in Gen 5 and later
The odds for multihot moves in Gen 5 and later were incorrect, causing those moves to hit 3, 4, or 5 hits more often than they should.
I've adjusted the calculation to match Gen 5 and later, see: https://bulbapedia.bulbagarden.net/wiki/Bullet_Seed_(move)
or: https://www.smogon.com/dex/bw/moves/bullet-seed/

Fixed Gen5+ multihit odds.

---

src/battle_main.c

`i` value was being stepped on when the shed shell check was added (not quite sure how, likely due to setting the value mid-if-statement). reversing the check on the if statement fixes the problem, though.

fix IsAbilityPreventingEscape message in party menu

---

src/graphics.c

This frees up approx 0x584FC bytes, about 0,36 MB

Get rid of garbage bytes in graphics.c

---

include/constants/pokemon_config.h

Fixed P_UPDATED_ABILITIES's comment

---

src/battle_util.c

Before this, Origin Form Giratina wasn't benefiting from Griseous Orb's boost.

Fixed creation trio orbs not boosting power for non-base forms.

---

include/decompress.h
include/pokemon.h
include/pokemon_icon.h
src/battle_anim_mons.c
src/battle_gfx_sfx_util.c
src/contest.c
src/contest_painting.c
src/contest_util.c
src/decompress.c
src/egg_hatch.c
src/menu_specialized.c
src/pokeblock_feed.c
src/pokemon.c
src/pokemon_debug.c
src/pokemon_icon.c
src/pokemon_jump.c
src/pokemon_storage_system.c
src/pokemon_summary_screen.c
src/pokenav_conditions.c
src/trade.c
src/trainer_pokemon_sprites.c

- Simplified LoadSpecialPokePic (fixes #1948).
- Changed most gender difference flag checks to use the new function `ShouldShowFemaleDifferences`.
- Removed redundant functions used only for `pokemon_debug.c`
- `HandleLoadSpecialPokePicCustom`
- `CreateMonIconCustom`
- `LoadSpecialPokePicCustom`
- `GetMonIconPtrCustom`
- `GetMonIconTilesCustom`
I wanted to also fix #2246, but that may be caused by something else in `pokemon_debug.c`.

LoadSpecialPokePic adjustments

---

src/item_use.c

Fixes the message produced by escape rope being incorrect when on gen 8 mechanics.
When on gen 8 mechanics, the call to RemoveUsedItem is ignored, which results in gStringVar4 not being set to the escape rope message. This pull request makes it so on gen 8 mechanics, gStringVar4 is properly set to the escape rope message.
Lemon Rush#2220

Fix Escape Rope Message when on gen 8 mechanics

---

src/battle_script_commands.c

The check only checked if the mon had an ability that was NOT the first one. So if the mon had it's hidden ability, index 2, the function would look for the second ability, index 1. If the species had pickup as the second ability, it would run a check for it. As a side note, this function is a bit wonky. Unnecessary nesting and repeated checks, but I decided to not touch any of that so the bug fix wouldn't get mixed with general refactoring.

Fixed pickup running when it shouldn't in some cases.

---

README.md

Updated the Master branch's README.md

---

src/battle_util.c

I just noticed that the `for` loop inside this function was missing a constant.
Lunos#4026

Updated GetBattleMonMoveSlot

---

src/battle_script_commands.c

In battle_script_commands.c, there was what appears to be a copy/paste error (someone must have hit "v" on their keyboard, instead of "ctrl + v") for Gen 3-5 Water Sport. This fixes that.
Literally just changes "v" to "STATUS4_WATER_SPORT". This was verified to be correct by MGriffin, Lunos, and AsparagusEd on Discord.
Yak Attack#8512
Uh I'm Petuuuuhhh, I'm banned from RHH; don't really care though, and if you decide you don't want to accept my PR because of this, I don't really care about that, either.

v -> STATUS4_WATER_SPORT (battle_script_commands.c)

---

include/pokemon.h

[3 years and 2 days ago](https://github.com/RH-Hideout/pokeemerald-expansion/commit/cef9dfe22c3760f6d61b896330009367a313ef0f), when `abilityNum` was changed to have 2 bits, its previous field was eliminated instead of renamed to unused. This caused ribbon shifting and confusion regarding the remaining available space in Saveblock.

Fixed PokemonSubstruct3 alignment

---

src/battle_pike.c

Comatose prevents Battle Pike's status effects.

---

data/maps/BattleFrontier_BattleFactoryPreBattleRoom/scripts.inc
src/data/union_room.h

Battle Factory calculates for Fairy type anyway, it was just missing the message.

Added missing uses of Fairy type for Union Room and Battle Factory

---

include/constants/battle_config.h
src/battle_script_commands.c

Config to limit the moves called by Metronome (by generation)

---

include/constants/battle_ai.h
src/battle_ai_switch_items.c
src/battle_controller_opponent.c

EDITED by @AsparagusEduardo:
- Fixes #2333.
Original description
> Removed ACE_POKEMON_FUNCTIONALITY.
> For some reason, if this AI Flag was not turned on, this skipped over the functionality of choosing the next pokemon inline.
> Functionality works when this flag is enabled, but not when it is not...?
>Removing functionality for now. I will fix it with another pull request.

Fixed ACE_POKEMON_FUNCTIONALITY

---

src/battle_z_move.c

I'm not entirely sure why, but whether a Z-Move could be used or not depended in whether an item that does not exist in this project was defined at all or not.
Since there's no point for that I removed it, and I fixed the check to use the `ITEM_Z_POWER_RING` as it should.
Lunos#4026

Updated IsViableZMove

---

include/battle.h
src/battle_ai_util.c
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

Now that the AI remembers all party info, we don't want to Record temporary ability changes (e.g. from Worry Seed, Simple Beam). This PR adds `overwrittenAbilities` to store these temporary changes, and `AI_GetAbility` will use this field if set over anything else

Add overwrittenAbilities field

---

src/field_specials.c

*Obviously*, if the Player accesses a PC once, the tile in front of them is no longer gonna be the tile with a PC's screen turned off, duh.
**EDIT**: Before | After
Lunos#4026

Fixed IsPlayerInFrontOfPC

---

include/pokemon_icon.h
src/pokemon_debug.c
src/pokemon_icon.c

Fixes: #2246 
The function previously used is only used in the base game to load genderless mail icons, this PR introduces a new function that takes the personality into account
TheXaman#5612

Fixes: Pokémon Debug isn't loading female icon palettes correctly

---

src/battle_interface.c
src/party_menu.c

Multi battle interface fix

---

src/battle_util.c

If the mon hits exactly half HP it won't trigger on the same turn because of the second check. The next turn it won't activate because of the firt check.

Fixed berserk not activating if mon falls to exactly half HP.

---

src/battle_util.c

Currently, moves that use EFFECT_TRIPLE_KICK deal too much damage. This can be fixed by just changing a "+=" to "=" in battle_util.c.
However, the battle script for this effect has some hard coded checks to find out what the base power of the move should be and utilizes a global when there is really no need to.
I decided to change it into a more flexible form that simply uses the move's base power and multiplies it based on the number of hits.

Triple kick power calc rework

---

src/battle_ai_util.c

AI was giving minus score to moves like strange steam and water pulse in misty terrain instead of moves like confuse ray, this should fix that.
Tennis#4004

Fix AI issue giving decrementing score to confuse hit instead of confuse

---

include/constants/battle_config.h
include/constants/trainers.h
src/battle_main.c

Starting from Gen. 7, trainer NPCs have a preset type of Poké Ball to keep their Pokémon in based on their trainer class.
This PR implements that.
**Notes**:
-Every trainer class that is not present in the table will use good ol' Poké Balls.
-`TRAINER_CLASS_AQUA_LEADER` and `TRAINER_CLASS_MAGMA_LEADER` use a Master Ball based on the events of USUM's Rainbow Rocket Episode, though arguably it makes sense even within the confines of Gen. 3. Archie has a Master Ball lying around in their own room at Team Aqua's Hideout in Lilycove City, for example.
-As the stand-in for Ace Trainers, "Cooltrainers" were set to use Ultra Balls.
Lunos#4026

Added class-based Poké Balls for trainers

---

include/constants/overworld_config.h
src/bike.c

Config for running indoors

---

data/battle_anim_scripts.s

Before it was very rigid. I added some movement and the cross impact at the end:

Improve psycho cut anim

---

src/party_menu.c

Fixed an bug that caused the game to lock after teaching a TM/HM
When a pokemon learns a move by level up the struct gPartyMenu.learnMoveState gets setted to 1 in order to check whether there is another move to learn at the same level or not.
When learning a TM/HM it should be set at 0 or the game locks.
The bug was introduced on  #ed02c4b425028a4fe2cf622653f352ec10914736
Because of how counterintuitively coded it originally was...
Discord Mauro#5782

Fix lock when teaching a TM/HM after learning a move by level up.

---

include/constants/overworld_config.h
src/debug.c
src/pokemon_storage_system.c

Complements the already merged #2356.
Lunos#4026

Removed worthless DEBUG_FLAG_PC_FROM_DEBUG_MENU config

---

include/fldeff.h
include/item_use.h
src/data/items.h
src/fldeff_sweetscent.c
src/item_use.c

Ever since its introduction in Gen 4 until SwSh, Honey could be used in the field for the same effect as Sweet Scent.
This PR implements that. Thanks to @ghoulslash for help with the textbox.

Implemented Honey's Sweet Scent functionality

---

src/battle_util.c

Fixed Bad Dream's ability popup message

---

ld_script_modern.txt
src/rom_header_gf.c

Restoring the GFHeader to vanilla. Adding information about the GFHeader and why it should remain exactly as it is in vanilla. Also pinning the header to the front of the modern build, like it is in the non-modern build.
Tustin2121#6219

GF Header and Modern Builds

---

src/battle_script_commands.c

Prettified the function a bit and addresed #2419.
Lunos#4026

Updated CanTeleport

---

src/battle_z_move.c

Fixes an issue brought up by Aaghat#2527 in which a Z-Move could be chosen even if the base move didn't have PP left.
Before:
After:
Lunos#4026

Made Z-Moves unusable without PP

---

asm/macros/battle_script.inc
src/battle_script_commands.c

Add `callnative` command for battle scripts.
Lots of users get confused by `various`, so now they can use callnatives for separate battle script cmd funcs

add callnative bs func, convert metal burst dmg calc

---

src/battle_script_commands.c

Enforce `gBattleScripting.battler` before calling `BattleScript_TrainerSlideMsgRet` in case it is not previously set. I've noticed if it is set to the player's side it can cause graphical issues.

Set battler before BattleScript_TrainerSlideMsgRet

---

asm/macros/battle_script.inc
data/battle_scripts_1.s
include/battle.h
include/battle_scripts.h
include/battle_util.h
include/constants/battle_script_commands.h
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

Remember how I optimized Bad Dreams a few days ago *(#2434)* and mentioned how Intimidate was similarly complex even though it didn't need to?
I decided to fix that because I wanted to so that's another battle script command freed to use moving forward.
As far as I tested, everything's working normally, but more tests are always welcomed.
Before:
https://user-images.githubusercontent.com/4485172/201494549-5f1e810f-95a5-4a27-ab8c-d73297852b49.mp4
After *(this PR)*:
https://user-images.githubusercontent.com/4485172/201494560-f1a46ee3-8627-4d54-8ab3-73cb0b1c71d4.mp4
"*But... doesn't that look exactly the same?*"
I know! Isn't it awesome? Less code to deal with which means manipulating or copying Intimidate is super easy now! ![teddiawwrsa](https://user-images.githubusercontent.com/4485172/201 …

Optimized Intimidate's code

---

src/battle_util.c

The function in which `ENDTURN_PLASMA_FISTS` is located *(`DoBattlerEndTurnEffects`)* loops across all battlers by default.
When I wrote that ENDTURN effect, I didn't really know about that.
This PR removes the pointless `for` loop I made it run.
Please test before merging anyway, to be extra sure.
Lunos#4026

Updated ENDTURN_PLASMA_FISTS

---

src/battle_script_commands.c

For w/e reason, the constants `STAT_CHANGE_WORKED` and `STAT_CHANGE_DIDNT_WORK` were defined twice in `src/battle_script_commands.c` which is the file that uses them.
This PR removes the pointless copies.
Lunos#4026

Removed repeated stat change defines

---

src/battle_util.c

Removes sInverseTypeEffectiveness table, replaces it by a simple lookup based on the modifier of the normal effectiveness table.
Here is a small test case to prove this is equivalent: https://gist.github.com/SBird1337/90a8a0a02c4a6f73c10ea3496e46083e
Karathan#1337

Refactor sInverseTypeEffectivenessTable to implicit lookup

---

src/battle_script_commands.c

4e6a459b143 unified the terrain timers, so there's no need for the `timer` pointer anymore, and we already have a convenient macro for all four terrain flags orred together :)

Cleanup HandleTerrainMove

---

include/battle.h
include/config/battle.h
src/battle_script_commands.c

- Fix 'mon with Flying in `type3` but not `type1` or `type2` is set to uninitialized `roostTypes`.
- Remove unread third `roostTypes` element.
- Option for Gen IV pure-Flying behavior (`B_ROOST_PURE_FLYING`).
The bug is currently theoretical because there's no move that sets `type3` to `TYPE_FLYING`, but it would allow a player to Roost with a Flying-type and later Roost with a Flying-`type3`, and at the end of the turn the second Pokémon would change to the types of the first.

Minor Roost fixes/cleanup

---

asm/macros/battle_script.inc
data/battle_scripts_1.s
include/battle.h
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

Instead of using `gBattleCommunication[0]` to keep track of the current Beat Up slot for its damage calc, this PR introduces a dedicated field in `gBattleStruct`, `beatUpSlot`, which gets initialised to `0` at the start of battle. This fixes #2540, as the damage calculation was being called by AI calculations before the script for Beat Up was ran to set `gBattleCommunication[0]`, leading to an out-of-bounds array access. For an abundance of caution, the incrementing of `gBattleStruct->beatUpSlot` has also been moved to occur after the damage calculation takes place, so that no shenanigans with `- 1` needs to take place. I also overloaded the `Cmd_trybeatup` battle script command so that it's more clear that Beat Up's effect changes depending on the `B_BEAT_UP` setting, as before it wasn't …

Fix Beat Up's battle script to avoid an out-of-bounds array access

---

src/battle_main.c
src/battle_script_commands.c

These are some misc. changes that I applied to #2534 but that weren't entirely in-scope, so I'm instead PR'ing them separately here.
-Made setbeakblast affect a specified battler instead of the gBattlerAttacker to justify the macro's layout.
-Added Shell Trap to the list of moves unaffected by Encore.
-Renamed CheckFocusPunch_ClearVarsBeforeTurnStarts into CheckChosenMoveForEffectsBeforeTurnStarts because that function doesn't just check for Focus Punch anymore, and it doesn't clear any variables either.
-Added an empty space between its `switch` statement and the condition of that `switch` statement for consistency's sake.
Lunos#4026

Applied minor tweaks

---

include/battle_util.h
src/battle_ai_util.c
src/battle_util.c

In its current state, PartyBattlerShouldAvoidHazards is flawed and incomplete.
- It checks for Levitate against Stealth Rock
- It sets a nonsensical value to holdEffect so Heavy Duty Boots are not checked for
- It ignores type effectiveness for SR
- It ignores the amount of laid spikes and some spike immunities.
- It does not account for spikes and SR overlapping.
I fixed the above issues and added more checks that make sense.
A function was added to check for SR damage against a non battler, instead passing a max HP and two type arguments.

PartyBattlerShouldAvoidHazards rewrite

---

include/config/pokemon.h
src/pokemon.c

Doing research, I realized that simply adding an extra roll to 1/8192 shiny chances doesn't equate to 1/4096 shiny chances. The more rolls, the more of a difference there is. Only really the first roll chances ends up being equivalent.
I think I want to add a field in #2372 to determine if a mon is shiny and that way users changing SHINY_ODDS will not change existing mon from and into shinies.

Reverting P_SHINY_BASE_CHANCE implementation as it wasn't accuerate to Gen6+

---

data/battle_anim_scripts.s
src/battle_anim_new.c

This function was working correctly before, but it wasn't laid out correctly.
It's supposed to set the first battle animation argument to either the Red or the Blue Orb to decide which Primal Reversion animation to play.
I noticed it just now and decided to fix it.
Lunos#4026

Updated AnimTask_PrimalReversion

---

include/config/battle.h
include/pokemon.h
src/battle_controller_link_opponent.c
src/battle_controller_link_partner.c
src/battle_controller_opponent.c
src/battle_controller_player.c
src/battle_controller_player_partner.c
src/battle_controller_recorded_opponent.c
src/battle_controller_recorded_player.c
src/battle_controller_wally.c
src/battle_util.c

Starting in PLA+, obedience checks also apply to non-outsider Pokémon but reference the met level instead. This allows you to put overly strong Pokémon in the wild (in an open world-ish fashion) that only become reliably useful once you have enough badges for them to obey you.
This adds a new config. I currently labeled it as Gen8+ because PLA doesn't have a separate config. It could also be Gen9+, in which case it is disabled by default for the time being because GEN_LATEST is still Gen8.
Jasper#5206

Add PLA+ obedience mechanics (with config)

---

src/battle_util.c

Prevents orb effects/sticky barb from triggering if the holder is fainted

add hp check to ITEMEFFECT_ORBS

---

src/battle_script_commands.c

Psycho Shift prints a string for each status effect you're transferring to an opponent; however, the index isn't buffered beforehand so it just prints index 0 (poisoning) every time.
I just reformatted it to buffer the appropriate index, not exactly elegant but it works. I tried to check open PRs to see if this had been covered and didn't see it, sorry if it's already been caught, I just noticed it earlier and figured Id submit a PR. 
Archie#5000

Fix Psycho Shift not buffering the string index for its printfromtable call

---

src/battle_main.c

Fixes issues with throwing balls when the player has only a single pokemon in a double wild battle.
Without this patch, if one of the player's pokemon faints and they don't have another pokemon to replace it, throwing a ball results in odd behavior, such as the player's turn getting skipped. The game already checks to ensure that if the player would like to throw a ball in a double wild battle, the player does not get multiple turns by setting the action of the player's other mon to `B_ACTION_NOTHING_FAINTED`. This patch ensures that both the player's actions don't get set to that.
If there's a better way to do this, I'm happy to learn. This is my first attempt at making a change to the battle engine.
walkingeye#6360

better handle throwing balls in a double wild battle

---

src/battle_debug.c

This was the intended behavior since everywhere that SELECT_BUTTON is used it also allows B_BUTTON to be used. 
This breaks without checking the current active window, which I assume that's the reason Egg didn't bother adding B_BUTTON there and called it a day.
Jaizu#0001

Allow exiting the Battle Debug menu pressing B

---

src/data/battle_moves.h

Wood Hammer was set to 1/4th recoil before, now its 1/3rd
Archie#5000

Fix Wood Hammer To Have 1/3rd Recoil

---

src/battle_script_commands.c

- VARIOUS_SWAP_STATS and moveend could branch inside their own arguments.
- VARIOUS_JUMP_IF_LAST_USED_ITEM_BERRY was implemented in reverse.

Fix uses of gBattlescriptCurrInstr

---

src/battle_util.c

Checks battler's side for gSideStatuses instead of gBattlerAttacker

Fix toxic debris side status check

---

src/egg_hatch.c

This SetMonData was making the feature introduced in 1b0ce96e12f876821333f43ce555552e0ff3f65d broken and useless, since the Egg would reset the ball when hatching.
Jaizu#0001

Fix ball resetting when hatching an Egg

---

data/battle_scripts_1.s

Fixes #2630 
I believe this was changed in Gen4, that Thunderwave could also heal mon's HP. I didn't add a config define for this, because it's a little detail, too small to bother creating a config for this.

Fix Volt Absorb not activating on Thunderwave

---

data/battle_anim_scripts.s
src/battle_anim_ice.c

Add configuration control handling mulitple targets by Poison Gas
Fixes #2606

Fix Poison Gas Anim for MOVE_TARGET_BOTH

---

src/battle_ai_main.c

Consider Heal Pulse and Pollen Puff in double battles.
Add logic to consider EFFECT_HEAL_PULSE EFFECT_HIT_ENEMY_HEAL_ALLY on partner pokemon in AI_DoubleBattle.

Add Logic for Heal Pulse effects in double battles

---

src/battle_ai_main.c

As discussed in issue #2611 Pollen Puff got a -10 score on enemy mons because it used `EFFECT_HEAL_PULSE` as a second check. The changes prevent Pollen Puff the second check.
Fix by AsparagusEduardo.

Fixes Pollen Puff issue #2611

---

test/ability_cloud_nine.c
test/ability_compound_eyes.c
test/ability_damp.c
test/ability_drizzle.c
test/ability_insomnia.c
test/ability_intimidate.c
test/ability_limber.c
test/ability_oblivious.c
test/ability_sand_veil.c
test/ability_speed_boost.c
test/ability_stench.c
test/ability_volt_absorb.c
test/ability_water_absorb.c

Adds tests for the following abilities:
* Damp ✅
* Intimidate ❌ [Bug: #2619 ]
* Speed Boost ✅
* Volt Absorb ✅
* Insomnia ✅
* Stench ✅ [Missing: Multi Hit interaction due to RNG]
* Drizzle ✅
* Limber ✅
* Sand Veil ✅
* Water Absorb ✅
* Oblivous ✅
* Cloud Nine ✅
Tests currently failing due to issues with the test system:
* Compound Eyes: Fails due to a statistical anomaly when checking against OHKO moves.
Karathan#1337

Add some tests for gen1-3 abilities

---

Makefile

Fixes the error Jaizu found when `ROM_NAME` is changed.

Patchelf use ROM name variable

---

tools/mgba-rom-test-hydra/main.c

`tmpnam` generates a warning when linked into a program, even though we're using it safely (or as safely as possible given that there's no way to tell mgba to open a ROM by fd). This PR replaces `tmpnam` with a PID-based filename for Hydra process ROMs.
Feel free to change the pattern from `/tmp/file%05d` to whatever you think is more appropriate. Perhaps `/tmp/hydra-%d.elf`? Note that the pattern in used in two places.

Hydra: remove tmpnam

---

Makefile
make_tools.mk

Makes the list of tools for each target explicit, should build patchelf and hydra only for check.

check-tools target

---

src/battle_controller_player.c
src/battle_util.c

When changing the placement of moves the z move indicator and move stayed on it's original place.
The fix checks if the newly placed move is a viable z move again. (Fixes issue #2676)

Fix switching Z-Moves when pressing SELECT in battle

---

src/battle_z_move.c

Fix for issue #2425
The PR fixes an issue with the Z-move indicator. It was displayed in the wrong battler health box.

Z-Move Indicator was wrongly displayed in double battles

---

src/battle_script_commands.c

Fixes #2296
This is one of textbook examples of how a missing parenthesis can cause a seemingly that-shouldn't-be-happening kind of bug.

Fix Jaw Lock locking player pokemon

---

src/battle_message.c

Fixes Z moves keeping the pp color of the original move. (Fix for #2410)

Fixes the pp color of Z moves 

---

data/battle_scripts_1.s
src/battle_script_commands.c

Fixes #1586
Also renames BattleScript_LeafGuardProtects, because the Battlescript is actually used for more than than Leaf Guard.

Fix Shield Down Ability pop-up

---

test/test_runner.c

Tests that are expected to fail, and do fail are now displayed as `KNOWN_FAILING` with a yellow CLI color to indicate it.
Karathan#1337

Improve Hydra output

---

asm/macros/battle_script.inc
src/battle_script_commands.c

~**NOTE**: This is an incomplete draft so that I can get opinions before I do the work to convert every command.~
**EDIT**: This is now complete.
Introduces a `CMD_ARGS` macro which automatically computes the offsets of the arguments and the total size of the arguments. Also captures `gBattlescriptCurrInstr` when invoked, so that the arguments can be referenced even after a jump or advancing the pointer\*.
Examples:
```diff
static void Cmd_setbyte(void)
{
-    u8 *memByte = T2_READ_PTR(gBattlescriptCurrInstr + 1);
-    *memByte = gBattlescriptCurrInstr[5];
-    gBattlescriptCurrInstr += 6;
+    CMD_ARGS(u8 *bytePtr, u8 value);
+
+    u8 *bytePtr = cmd->bytePtr;
+    *bytePtr = cmd->value;
+
+    gBattlescriptCurrInstr = cmd->nextInstr;
}
static void Cmd_jumpifstatus(void)
{
-    u8 …
```

Readable BattleScript command arguments

---

include/battle_util.h
src/battle_controller_link_opponent.c
src/battle_controller_opponent.c
src/battle_util.c
src/data/pokemon/species_info.h

Fixes #2624
There is an other Illusion issue opened atm, but it will be done in a separate PR(if and when no idea :D )

Fix buggy pokemon anims with Illusion 

---

asm/macros/battle_script.inc
data/battle_scripts_1.s
include/battle.h
include/battle_scripts.h
include/constants/battle_script_commands.h
src/battle_script_commands.c
test/ability_overgrow.c
test/ability_swarm.c
test/ability_torrent.c
test/hold_effect_red_card.c
test/move_effect_hit_switch_target.c
test/move_effect_roar.c

Move effects: Roar, Dragon Tail.
Abilities: Overgrow, Swarm, Torrent.
Hold effects: Red Card.
Fixes:
- Dragon Tail activates Red Card if the target does not switch.
- Dragon Tail does not print the "But it failed!" message if the target does not switch.
- Roar is not implemented with rejection sampling.

Battle Tests (Feb 19)

---

Makefile
test/test.h
test/test_runner.c
tools/mgba-rom-test-hydra/main.c

- Shows SKIP log line when `ASSUMPTIONS` fail.
- Prints any buffered output at exit.
- Prints a summary of how many tests ran/passed.
- Removes some unused code.
- Makes the `pokemerald-test.elf` file depend on `tools`.

Hydra fixes and improvements

---

data/battle_scripts_1.s
include/battle_scripts.h

Fixes #1487
The battlescript referenced in that issue isn't used in the current version of expansion. The problems mentioned must've been fixed at some point, but the issue was never closed.

Remove unused script BattleScript_TargetAbilityStatRaiseOnMoveEnd

---

src/battle_ai_util.c

fix uninitialized ai modifier variable in ai calc damage

---

src/battle_ai_main.c

Fix AI mon getting lower score when it is faster

---

src/battle_ai_util.c
src/battle_util.c

Fixes #2742
Before:
After:
In the example Sand Attack previously got a -20 score against flying types even though the move should be able to hit flying types.

Status moves should not be considered for type effectiveness

---

src/battle_ai_util.c
src/data/battle_moves.h

Fixes  #2775
Credit to Benício Gonçalves from Discord.
Turns Nature Power into the appropriate move in `AI_CalcDamage`.

Consider Nature Power in AI_CalcDamage

---

data/battle_anim_scripts.s

Fixes #2784
It's best to have this tested a bit to make sure the issue is fixed.
The cause was createspriteontargets was used instead of createsprite.

fix createspriteontargets on electricy anim

---

data/battle_scripts_1.s
include/battle_scripts.h
include/constants/battle_string_ids.h
src/battle_message.c
src/battle_script_commands.c
src/battle_util.c

Addresses my #2728. I had some issues with Breakneck Blitz just turning into Growl, but since I worked on a clean branch I am assuming it is a savefile issue or something. The implementation is pretty simple so hopefully not buggy, but wasn't extensively tested. Demo below:
Agustin#1522

Z-moves bypass protection

---

src/battle_util.c

Z status moves were blocked when they shouldn't if Taunt, Torment, Disable, Encore, Imprison, or Heal Block were used. 
Credit: ghoulslash for the help, AaghatIsLive for finding the bug

Fixes certain moves preventing Z status moves.

---

include/battle.h
src/battle_util.c

It was brought to my attention that the stat boost provided by Supreme Overlord is not supposed to be affected by whether you revive allies or not.
The effect reads the amount of fainted allies at the specific time in which the user is sent out.
Thus, I made a quick change to solve that.
Lunos#4026

Updated Supreme Overlord's effect's code

---

test/test.h
test/test_runner.c
test/test_runner_battle.c
tools/mgba-rom-test-hydra/main.c

Added some more details to the test results.
`KNOWN_FAILING` and `FAILED` results don't show if there are none.

More detailed hydra test results

---

src/battle_ai_main.c

Removed check from `EFFECT_ELECTRIFY` that checks if the predicted move is a normal type.

Electrify works on all move types, not just Normal

---

src/battle_ai_main.c

The AI didn't get a minus score when it was slower then the player when trying to use Electrify.
Before:
After:
Bulbasaur faster then Chinchou:
Bulbasaur slower:

Fixes the check for speed on electrify

---

data/scripts/debug.inc
include/config/debug.h
include/config/overworld.h
src/debug.c
src/event_object_movement.c

HunarPG#2786 and I spotted some weird things in the debug menu, so I decided to go ahead and correct most of them.
- Updated the text string used by Debug_FlagsNotSetMessage.
- Renamed Debug_FlagsNotSetMessage to Debug_FlagsNotSetOverworldConfigMessage.
- Added an equivalent for the battle config file called Debug_FlagsNotSetBattleConfigMessage,
- DEBUG_FLAG_NO_COLLISION -> OW_FLAG_NO_COLLISION
- And moved it to include/config/overworld.h, because at the end of the day it's still an overworld flag just like the other 2 already in that file.
- Corrected miswritten preproc config in DebugAction_Flags_CatchingOnOff.
- Updated the comment that describes the effect of DEBUG_OVERWORLD_MENU reducing the number of characters a tiny bit and fixing a typo.
- Added a new option to clear the PC boxes …

Debug Menu improvements

---

src/battle_ai_main.c

Work Up and Growth got a -10 / -8 score when either only a Special or Physical move were present.
Since those moves increase both Special Attack and Attack they shouldn't get a decrease if one split move is present.   
Before:
After:

Fixed score for Work up and Growth

---

src/battle_interface.c

Fixes a bug noticed in another project where ability popup tiles were corrupted due to half-word alignment of ability popup gfx and CpuCopy32 and maybe other functions require word-alignment.
Simple fix is to just add `ALIGNED(4)` to all INCBIN_U8 defined arrays

Word-align battle_interface.c u8 array gfx

---

src/battle_util.c

It turns out `CanBeConfused` doesn't properly use check its argument `battlerId`, and instead checks `gEffectBattler`. This was giving me grief. Easy fix!
Agustin#1522

CanBeConfused properly checks the battlerId passed into it

---

include/random.h
src/battle_script_commands.c
src/battle_util.c
src/random.c
test/ability_compound_eyes.c
test/ability_cute_charm.c
test/ability_sand_veil.c
test/ability_stench.c
test/hold_effect_red_card.c
test/move.c
test/move_effect_accuracy_down.c
test/move_effect_defog.c
test/move_effect_evasion_up.c
test/move_effect_hit_switch_target.c
test/move_effect_rampage.c
test/move_effect_roar.c
test/move_effect_sleep.c
test/random.c
test/status1.c
test/test.h
test/test_battle.h
test/test_runner.c
test/test_runner_battle.c

Replaces `Random()` calls that are tested by a `PASSES_RANDOMLY` battle test to be either `RandomUniform` or `RandomWeighted` (depending on use). This allows the battle test runner to run the battle the minimum number of times to exhaustively test the outcomes.
See `include/random.h`.
Incorporates #2696 to write tests against the non-test implementations of `RandomUniform` and `RandomWeighted`.

Speed up PASSES_RANDOMLY via structured RNG

---

src/battle_script_commands.c
test/ability_compound_eyes.c

Changes `tryKO` to use the new rng tags. This fixes the compound eyes test against ohko moves.
Karathan#1337

fix compound eyes ohko test

---

data/battle_scripts_1.s
src/battle_script_commands.c
test/ability_intimidate.c

Currently Intimidate when targetting in two trainer doubles with one side dead will falsely postpone until end of turn instead of activiating on that one side. This fixes that. Also fixes issue where when intimidating that pokemon get intimidated.
Tennis#4004

Fix Intimidate targetting dead sides and false postpones

---

include/battle_main.h
include/constants/trainers.h
include/data.h
include/global.h
src/battle_main.c
src/data.c
test/trainer_control.c

Implements fully customizable trainer parties for enemy trainers according to the following structure:
```c
struct TrainerMonCustomized
{
const u8 *nickname;
const u8 *ev;
u32 iv;
u16 moves[4];
u16 species;
u16 heldItem;
u16 ability;
u8 lvl;
u8 ball;
u8 friendship;
u8 nature : 5;
bool8 gender : 2;
bool8 isShiny : 1;
};
```
Karathan#1337

Implement Customizable NPC Trainer Parties

---

src/battle_script_commands.c

currently, a pokemon that is locked into a move due to gorilla tactics will be able to choose a new move after an item is knock off it through Knock Off. this fixes that so that the move stays locked. 
Addresses #2851 
added a simple ability check and only set choicedMove to 0 when ability is not gorilla tactics.
Salem#3258

add check for Gorilla Tactics when resetting choicedMove from knock off

---

src/battle_util.c

`CalcMoveBasePower` is using battler addresses which will mess with AI damage calcs. Use function args instead

Fix CalcMoveBasePower using battler addresses

---

include/config/overworld.h
include/strings.h
src/field_control_avatar.c
src/field_poison.c
src/strings.c

Adds a config for OW Poison behaviour (no fainting in Gen4, no damage whatsoever in Gen5+).
I totally stole the code from @LOuroboros (https://www.pokecommunity.com/showpost.php?p=10068565&postcount=32). Sorry!
Jasper#5206

OW Poison configs

---

src/field_control_avatar.c

We can't have that config under a define, otherwise the Pokémon will never take damage from being poisoned.
Jaizu#7841

Fix overworld poison not working on newer generations config

---

src/field_control_avatar.c

Reverts rh-hideout/pokeemerald-expansion#2891

Revert "Fix overworld poison not working on newer generations config"

---

data/battle_scripts_1.s
test/terrain_electric.c
test/terrain_grassy.c
test/terrain_misty.c
test/terrain_psychic.c

Fixes #2880. This PR removes an erroneous call to `activateswitchinabilities` in the `TerrainSeed` loop and combines both the `TerrainSeedLoop` and `TerrainAbilitiesLoop` into one loop for terrain effects so you don't have to call each individually (and so it doesn't have to loop over every battler twice).
This PR also adds tests for every terrain effect! This includes some edge cases for Psychic Terrain that appear to be inaccurate at the moment, so they have been marked with `KNOWN_FAILING`. These bugs have been pointed out in #2882, but are not fixed in this PR.

Fixed switch-in abilities activating on terrain change

---

include/config/battle.h
src/wild_encounter.c

[Original Dicussion](https://discord.com/channels/419213663107416084/1077168246555430962/1090625094327488602)
In the current version of expansion, regardless of the value of `B_DOUBLE_WILD_CHANCE`, if the player only has one Pokémon in their party, all generated wild battles will be single battles.
This is due to a check in `TryDoDoubleWildBattle`, which, if the player only has one Pokémon, the game will not generate a wild double battle.
```c
if (GetSafariZoneFlag() || GetMonsStateToDoubles() != PLAYER_HAS_TWO_USABLE_MONS)
```
```c
#define B_DOUBLE_WILD_CHANCE        100
```
The first battle occurs when the player has two Pokémon in their party and starts a wild battle, which is a double battle. 
The game is then reset, the player is only given one Pokémon in their party, and a wild …

Added B_DOUBLE_WILD_REQUIRE_2_MONS to use of B_DOUBLE_WILD_CHANCE even when there is only one Pokémon in the party

---

include/battle_ai_util.h
src/battle_ai_main.c
src/battle_ai_util.c

Eg. Dream Eater's check was like this:
```c
case EFFECT_DREAM_EATER:
if (!(gBattleMons[battlerDef].status1 & STATUS1_SLEEP) || AI_DATA->abilities[battlerDef] == ABILITY_COMATOSE)
score -= 8;
else if (effectiveness == AI_EFFECTIVENESS_x0)
score -= 10;
break;
```
Meaning that if the target had Comatose, it would reduce points from the score when it shouldn't.

Fixed Comatose AI checks

---

include/battle_main.h
src/battle_main.c
src/battle_tower.c
test/trainer_control.c

Fixing my mistake when I added the case `F_TRAINER_PARTY_EVERYTHING_CUSTOMIZED` in `FillPartnerParty`.
The Prolbem was that the partner pokemon where created in the first 3 slots instead of the last 3 which removed the players team.
The changes were tested with this script:
```
MultiBattle_EventScript_ChoosePartyForMultiBattle::
special SavePlayerParty
fadescreen FADE_TO_BLACK
special ChooseHalfPartyForBattle
waitstate
goto_if_ne VAR_RESULT, 0, MultiBattle_EventScript_2VS2
special LoadPlayerParty
goto MultiBattle_EventScript_Won_Lost
MultiBattle_EventScript_2VS2::
multi_2_vs_2 TRAINER_ROBERT_1, MultiBattle_Generic_Text, TRAINER_COLIN, MultiBattle_Generic_Text, TRAINER_BRENDAN_ROUTE_103_TORCHIC, TRAINER_BACK_PIC_BRENDAN
specialvar VAR_RESULT, GetBattleOutcome
goto_if_eq …
```

Modify "FillPartnerParty" to work with "Everything Customized"  

---

include/random.h
src/battle_script_commands.c
src/random.c
test/move_effect_dire_claw.c
test/move_effect_tri_attack.c
test/random.c
test/test_battle.h
test/test_runner_battle.c

Converts Tri Attack and Dire Claw to use structured RNG via `RandomElement`, so that their `KNOWN_FAILING`s can be removed.
Also introduces `WITH_RNG` which allows tests to specify an exact RNG value for any arbitrary RNG tag (instead of just the ones supported by `hit:`, `criticalHit:`, and `secondaryEffect:`), I suspect this is mostly only useful with tags used in `RandomElement` calls.
NOTE: `WITH_RNG` currently only works if the element type is 32-bit or smaller.

RandomElement for structured RNG

---

src/battle_ai_switch_items.c

Previous AI logic was vanilla's, which assumed that the only ability nums where 0 and 1.
Also optimized species reading in those same sections, as there really was no need to call `GetMonData` 3 times in a row.

Fixed AI not considering Hidden Abilities in its team during switching logic

---

data/battle_scripts_1.s

Fixes Ability Pop up freeze when the ability Wandering Spirit was triggered 
Ability Pop up freeze without the fix:
After the fix:
Fixes #2844

Fix Ability PopUp freeze

---

src/battle_script_commands.c

1. gBattleMons was using party indices instead of battle indices, therefore only ever healing a mon whichs party index matches with its battle index.
2. added brackets for readability
3. fix nightmare only being healed in double battles by moving the check into the scope of the entire function. 
fixes #2919 
Salem#3258

fix several issues in BS_ItemCureStatus

---

include/config/battle.h
src/data/battle_anim.h

In the current version of expansion, `B_NEW_ROCKS_PARTICLE` is called, but never defined.
```c
#if B_ROCKS_PARTICLE
{gBattleAnimSpritePal_NewRocks, ANIM_TAG_ROCKS},
#else
{gBattleAnimSpritePal_Rocks, ANIM_TAG_ROCKS},
```
```c
#if B_ROCKS_PARTICLE
{gBattleAnimSpriteGfx_NewRocks, 0x0C00, ANIM_TAG_ROCKS},
#else
{gBattleAnimSpriteGfx_Rocks, 0x0C00, ANIM_TAG_ROCKS},
```
```c
// Animation Settings
#define B_NEW_SWORD_PARTICLE            FALSE    // If set to TRUE, it updates Swords Dance's particle.
#define B_NEW_LEECH_SEED_PARTICLE       FALSE    // If set to TRUE, it updates Leech Seed's animation particle.
#define B_NEW_HORN_ATTACK_PARTICLE      FALSE    // If set to TRUE, it updates Horn Attack's horn particle.
#define B_NEW_LEAF_PARTICLE             FALSE    // If set to TRUE, it updates …
```

Added config to enable NEW_ROCKS_PARTICLE

---

src/item.c
src/item_use.c

these battle items werent working correctly. this fixes that.
Dire Hit checked if the pokemon did **not** have `STATUS2_FOCUS_ENERGY` to increment the `cannotUse` counter.
It now checks if it does already have the status.
The case for paralysis was missing, so I added it. 
Salem#3258

fix dire hit and paralyze heal

---

src/battle_z_move.c

Fixes status z-moves overwriting damage dealing z-moves. This happened when the status move was slotted in a slot the came after a regular damaging dealing move, as long as both had the same typing.  
Previously:
After the PR:
Status z moves still work like intended:
Fixes  #2558

Fixes status z-moves overwrting damage dealing z-moves

---

include/battle.h
include/battle_util.h
include/config/battle.h
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

In Generation 9 Held Items, except for berries, are restored after each battle. 
This PR adds `B_RESTORE_HELD_BATTLE_ITEMS`. 
The functionality was already implemented but some things got renamed:
`StolenItem` -> `LostItem`
`TryRestoreStolenItems` -> `TryRestoreHeldItems`
`itemStolen` -> `itemLost`
I was also thinking to add the define to `TrySaveExchangedItem` but you still need it for berries. 
Previously:
With the PR:
Berries are not restored after the PR:

Adds define `B_RESTORE_HELD_BATTLE_ITEMS` following Gen9 

---

data/battle_scripts_2.s
src/battle_message.c
src/item_use.c
src/party_menu.c

In Gen 8/9, items used in battle don't print a message on success inside the bag or party menu. My last PR messed up this behavior. It also makes it so "restored HP" and "cured status" messages print after the battle box is updated.
Updated behavior:
Fixes #2913 
Agustin#1522

Fixed duplicate item strings in Bag/Party menus with battle items

---

include/config/battle.h
src/overworld.c

[\[Original discussion\]](https://discord.com/channels/419213663107416084/1077168246555430962/1089621327272497274)
In the current version of expansion, when the flag `B_FLAG_INVERSE_BATTLE` is set and the player whites out, the flag is still set for all other battles the player participates in until it is explicitly turned off.
The most common use cases of the flag are for specific battles (similar to its actual usage within the core series of the franchise) or at most, a series of battles that utilize the mechanic.
The current implementation is broken - if the goal of the flag is to allow a quick and easy flag to be set for developers to enable different battles, then that functionality should also cover the range of expected functions within the game, which includes whiting out. …

Reset battle vars and flags after player whites out

---

src/battle_ai_util.c

Replaces `gBattleResources->battleHistory->usedMoves[battlerDef]` with `GetMovesArray(battlerDef)`.
Technically a small bug because the AI couldn't see the players moves on turn one if `CanTargetFaintAi` was called with `AI_FLAG_OMNISCIENT` but I also feel like it is a leftover because everything else uses `GetMovesArray` involving moves.

Adds GetMovesArray in CanTargetFaintAi

---

sound/direct_sound_data.inc

Moved the definition for Cry_EnamorusTherian to below Cry_LandorusTherian, which fixes a compiler error that would occur if GEN 7 and GEN 8 pokemon were disabled.
lucas#7562

Fix issue with Enamorus Therian cry define order

---

data/battle_scripts_1.s
test/terrain_electric.c
test/terrain_grassy.c
test/terrain_misty.c
test/terrain_psychic.c

Fixes Grassy Terrain freezing the game when it was about to end. A test is included that times out without the fix.
https://user-images.githubusercontent.com/93446519/235130482-19f06df7-41cd-4a14-bbc1-f441b1978fad.mp4
Fixes #2948

Fix grassy terrain freezing the game

---

src/battle_util.c

Anger shell currently activates if the target faints. this fixes that.

Fix anger shell activating when fainted

---

data/battle_scripts_1.s
include/config/battle.h
test/ability_dry_skin.c
test/ability_hydration.c
test/ability_ice_body.c
test/ability_leaf_guard.c
test/ability_rain_dish.c
test/ability_sand_veil.c
test/ability_snow_cloak.c
test/ability_water_absorb.c

I had need for some weather related ability tests, so I made some. In doing so I found that Leaf Guard isn't interacting correctly with Rest, so I fixed that. Since Generation 5, Leaf Guard prevents the user from using Rest under sun, but on Upcoming it currently doesn't work (there's no jumpifleafguardprotected in the script).
For reference, this is from the [Bulbapedia page](https://bulbapedia.bulbagarden.net/wiki/Leaf_Guard_(Ability)) on Leaf Guard:
And here is a Showdown match against myself demonstrating it:
https://replay.pokemonshowdown.com/gen9customgame-1852491367
This was my first time writing these things, I just referenced already existing tests for them. Let me know if they can be improved.
N/A
Shae#9032

Weather related Ability tests, fix for Leaf Guard not preventing Rest.

---

include/constants/pokemon.h
src/battle_ai_util.c
src/battle_util.c
src/data/battle_moves.h
test/move_effect_triple_kick.c
test/move_flag_three_strikes.c

Fixes Triple Dive effect by adding `FLAG_THREE_STRIKES`. The flag is additionally used for Surging Strikes. 
Triple Dive:
Surging Strikes:
Fixes #2795

Fixes Triple Dive effect

---

data/battle_scripts_1.s

Fixes Ceaseless Edge and potentially Axe Kick (move effect not done yet).
There was a 'visual' bug after Ceaseless Edge was used to faint a mon because the move didn't end correctly.
Fixes  #2958

Fix for Ceaseless Edge/Axe Kick visual glitch

---

Makefile
tools/mgba-rom-test-hydra/main.c
tools/patchelf/elf.h
tools/patchelf/patchelf.c

Adds OSX support for Hydra (and tests!)
Adds support for Hydra on OSX. For now, any OSX users will need to manually compile mgba (https://discord.com/channels/419213663107416084/774393519569502268/1068701184250097694) or the tests will not work. `stdbuf` is also a requirement and can be downloaded with `brew install coreutils`.
Fixes #2629 
Jasper#5206

Hydra OSX support

---

src/battle_util.c

Plus/Minus currently powers up move regardless of category. Since this should strictly power up Special Attack, I added a special move check. See also https://discord.com/channels/419213663107416084/1077168246555430962/1103274476898103317
Jasper#5206

Fix Plus/Minus to only work with special moves

---

test/test_battle.h

The documentation incorrectly stated that `HP_BAR(battler)` fails if the hp of the battler changes at all, when the opposite is the case and intended. this fixes this.
Salem#3258

fix incorrect test runner documentation

---

include/config/pokemon.h
include/pokemon.h
src/daycare.c
src/pokemon.c

Manually ports @ExpoSeed's daycare_expansion to upcoming.
Manually ports ExpoSeed's daycare_expansion to upcoming (as the the old repo was too old to meaningfully merge in). No new features have been added and two features remain on the to do list (ability inheritance and learning Egg Moves from the other Pokémon in the Day Care if possible). Since several of the old daycare configs were already taken care of in the general Pokémon config, the remaining daycare configs have been moved to this file as well for consistency.
Fixes #2345 
Jasper#5206

Manually port daycare expansion to modern standards

---

gflib/malloc.c
gflib/malloc.h
include/gba/defines.h
include/global.h
test/test.h
test/test_battle.h
test/test_runner.c
test/test_runner_battle.c

Can use `KNOWN_LEAKING;` to specify that a test is known to leak memory. This is not particularly useful for battle tests, but could be useful for the generic tests introduced by #2696.
The location information is available in regular game builds. Thus it is available for use in debugging leaks in-game too. In the future we should consider replacing it with `NULL` if `NDEBUG` is defined. This is not currently possible because the tests do not force `NDEBUG` to be undefined.
To avoid changing the size of `struct MemBlock`s, I have stuffed the pointer into unused bits.
Example:
```diff
--- a/test/move_effect_absorb.c
+++ b/test/move_effect_absorb.c
@@ -12,6 +12,7 @@ SINGLE_BATTLE_TEST("Absorb recovers 50% of the damage dealt")
+        void *x = Alloc(0x8);
```
```
$ make check
Absorb …
```

Detect memory leaks in tests

---

src/battle_anim.c

In a battle tower tag battle for example, when `returnopponentmon1toball` and `returnopponentmon2toball` are called, the healthboxes reappear at the end due to the 2nd argument of `UpdateOamPriorityInAllHealthboxes` being TRUE in `Cmd_end` of battle anims. This PR moves the `hideHpBoxes` boolean to EWRAM so it can be passed to both instances of the function and fix this issue.

Fix healthbox reappearing from B_ANIM_SWITCH_OUT_OPPONENT_MON

---

src/debug.c

Fixes abilities with a value of over 255 looping back to 0 when selecting the ability in the custom GiveMon feature of the OW debug menu.
Fixes #2997 
Jasper#5206

Fix ability select in debug givemon

---

src/data/battle_moves.h

Esper Wing's power was updated to match Gen9, but its accuracy wasn't. This PR fixes that
Frankfurter#8828

Updated Esper Wing's accuracy if B_UPDATED_MOVE_DATA is Gen9

---

src/script_pokemon_util.c

Fixes issue with scripted wild double battles where one mon was centered. Issue was caused by `gEnemyPartyCount` having the wrong value because the second mon was set to the 4th slot in function `CreateScriptedDoubleWildMon`. The correct count was needed by `WhichBattleCoords`.
Changes were tested with the script provided by ghoulslash:
```
givemon SPECIES_XATU, 40, 0
givemon SPECIES_AGGRON, 40, 0
setwildbattle SPECIES_VOLCARONA, 40, 0, SPECIES_VOLCARONA, 35, 0
dowildbattle
```
Fixes  #2993

Fix for wrong mon position for scripted wild doubles

---

src/party_menu.c

In Scarlet and Violet, the Ability Patch is able to switch a Pokémon's ability from a Hidden Ability to its first slotted ability. This PR implements that
Frankfurter#8828

Updated Ability Patch for Gen 9 functionality

---

src/battle_util.c

Makes overleveled Pokémon disobey the player again when Gen 7 mechanics are set by removing a check which overrode setting levelReferenced.
All credit for the fix goes to i0brendan0.
#2984 
SubzeroEclipse#2104

Fixed mons mot disobeying with Gen8 mechanics disabled

---

data/battle_scripts_1.s
src/battle_anim_throw.c
src/battle_util.c

When an Illusion user is sent out, the shiny animation (stars) does not respect the shininess of the illusion target (which of course ruins the illusion... ☹️)
This fix will instead use the result of `GetIllusionMonPtr` if it is non-null.
This also fixes #2971 - the Imposter ability no longer reveals the ability of the opponent in the ability popup and instead properly shows 'Imposter'.
|**Illusion user is shiny, target is not**|**Target is shiny, Illusion user is not**|**Fixed**|
|-|-|-|
|![illusionShinyNoAnim](https://user-images.githubusercontent.com/39687914/236861110-e5777833-8461-4a45-938b-76c4826b6d1a.gif)|![illusionNotShinyAnim](https://user-images.githubusercontent.com/39687914/236861611-da724ffb-7b56-4c26-8cec-a8f42614d54f.gif)|![illusionFix](https://user-images.githubusercontent …

Fix shiny animation not respecting Illusion mon target and Imposter revealing opponent ability

---

data/battle_scripts_1.s

Revival Blessing's effect script plays its animation even if the move were to fail due to not having fainted allies.

---

test/test_runner_battle.c

There was a variable `u32 element` that wasn't assigned a value when used, so when data was copied onto it there would sometimes be junk bits leftover.
Agustin#1522

Fixed testrunner UB with RandomElement.

---

include/money.h
src/debug.c
src/money.c

In the current version of expansion, when the player uses the Debug Menu to give themselves `MAX_MONEY`, they do not actually give themselves that value. The script is hardcoded to give the player ¥999999. If the developer changes the value of `MAX_MONEY` to something else, this debug script could accidentally give the player a surprising amount.
```c
static void DebugAction_Give_MaxMoney(u8 taskId)
{
SetMoney(&gSaveBlock1Ptr->money, 999999);
}
```
1. Change `DebugAction_Give_MaxMoney` to give `MAX_MONEY` instead of 999999.
2. Move the define for `MAX_MONEY` from [`src/money.c`](https://github.com/PokemonSanFran/pokeemerald-expansion/blob/a85ca13a504c8b335eddcd5d5aaf32008eae8030/src/money.c) to [`include/money.h`](https://github.com/PokemonSanFran/pokeemerald-expansion/blob/a85ca13a504c8b3 …

Changed 999999 in DebugAction_Give_MaxMoney to MAX_MONEY constant

---

src/battle_util.c

As AaghatIsLive commented in an already closed issue (#2948) terrains (except grassy terrain) froze the game after a mon fainted.
The PR should fix it.
Before:
After:

Fixes Terrains freezing the game after player mon faints

---

data/scripts/debug.inc
src/debug.c

`DebugAction_Util_CheckSaveBlock`, which is the function that tells a person the current size of the most relevant savefile structs as well as their maximum size, was using hardcoded values instead of a proper calculation that can reflect the size of those structs dynamically.
This PR fixes that.
Lunos#4026

Updated DebugAction_Util_CheckSaveBlock

---

data/battle_scripts_1.s
src/battle_util.c

Small clean up in `EndTurnTerrain` and `BattleScript_GrassyTerrainLoopEnd`. Somewhat related to to PR #3016. A bug was fixed there that makes this clean up possible.

Small clean up in EndTurnTerrain, BattleScript_GrassyTerrainHeals

---

include/config/battle.h

Due to the fact that we're not changing default obedience levels, any Pokémon caught above level 10 will disobey until badge 2, which is causing users a bit of a headache.
This PR will disable the feature by default to avoid running into the issue unknowingly. 

Disable Gen8+ Obedience Mechanics by default

---

data/battle_scripts_2.s
data/scripts/debug.inc
src/battle_controller_player.c
src/battle_script_commands.c

I should've gotten to these sooner, but this fixes a few outstanding issues.
This was a simple fix. The battle script to send out the revived battler was changed to use `BS_SCRIPTING` and `gBattleScripting.battler` was set when an item required a revive animation. Originally, it was using `BS_ATTACKER`, meaning it would perform a send out animation on the battler that used the item.
I don't understand this fix if I'm being totally honest, but it works. In `battle_controller_player.c`, where `B_ACTION_CANCEL_PARTNER_ACTION` is supposed to be returned, I removed the Poke Ball check to return an item to the player's bag when cancelling an action after the first battler used an item. This was not meant to be the fix, but I couldn't find where to look next, and when doing some debug printing I …

Battle Item Refactor Fixes

---

data/scripts/debug.inc

Scripts used for the Overworld Debug menu were using callnatives to call functions that ended up not existing when the setting was off. This PR fixes that issue by surrounding the file by the same ifdefs used in `src/debug.c`.
Fixes #3023 

Fixed compile issue when disabling overworld debug menu

---

include/battle_ai_util.h
include/battle_util.h
src/battle_ai_main.c
src/battle_ai_util.c
src/battle_script_commands.c
src/battle_util.c

Aka: Edu's PR Idea N°1 for when he had to rest his hands.

Optimized battle gender checks

---

src/battle_ai_util.c
src/battle_util.c

When the damage for `TRIPLE_KICK_EFFECT` was calculated, the BP was first calculated as `basePower * 4` and on top of it if it was either multiplied with 5/6 depending if the user had Skill link or not. 
The fix calculates the damage for `TRIPLE_KICK_EFFECT` as it would always get 3 hits when it is considered for usage, otherwise for each hit.
Triple Axle:
``` 
[INFO] GBA Debug: Multi Hit Counter: 0
[INFO] GBA Debug: Base Power: 120
[INFO] GBA Debug: Multi Hit Counter: 3
[INFO] GBA Debug: Base Power: 20
[INFO] GBA Debug: Multi Hit Counter: 2
[INFO] GBA Debug: Base Power: 40
[INFO] GBA Debug: Multi Hit Counter: 1
[INFO] GBA Debug: Base Power: 60
```
Triple Kick:
```
[INFO] GBA Debug: Multi Hit Counter: 0
[INFO] GBA Debug: Base Power: 60
[INFO] GBA Debug: Multi Hit Counter: 3
[INFO] GBA …
```

Fixes Triple Kick effect and Z move damage calc

---

.github/workflows/build.yml
Makefile
gflib/malloc.h
include/test_runner.h
src/recorded_battle.c
src/test_runner_stub.c
test/test_runner_battle.c

Separates the regular `make` build from the `make check` build. Means that building check will not be able to reuse any artifacts from the regular build, but also means that we can have separate definitions in the check build. Currently we use `TESTING` to differentiate between these two build modes (`TEST` is already taken).
This is a draft, I still need to port all the `MgbaPrintf_`-style functions over to `mini_printf` now that we have a way to force that to build.

Separate build directory for tests and TESTING define

---

include/config.h
include/test_runner.h
src/battle_main.c
test/test_battle.h
test/test_runner_battle.c

There isn't a way to test abilities that aren't attached to Pokémon yet, so I added a way to force abilities in tests. Thanks to @mrgriffin for mentioning `gBattleStruct->overwrittenAbilities`, since I think this is actually a pretty non-hacky way of making things work. I haven't tested it in edge cases like Skill Swap or Trace, but I want to say it would work fine.
Agustin#1522

Test Runner support for illegal abilities

---

include/constants/pokemon.h
src/data/pokemon/evolution.h
src/pokemon.c

Ported from #2363.
In Gen 8, with Affection's effects being integrated into Friendship, so too was Eevee's evolution method into Sylveon, meaning that it now requires high friendship instead of high enough affection. This PR addresses that change.

Fixed Sylveon's evolution method

---

src/item_menu.c

Fixes the issue by also checking the importance field when selling items, which will also allow to buy Key Items while not being able to sell them.
Fixes #3046 
AsapragusEduardo

Fixed selling TMs set as reusable

---

test/test_runner_battle.c

Marks a test as invalid if it has more than one `PASSES_RANDOMLY`. Currently the first is just silently ignored.

At most one PASSES_RANDOMLY per test

---

include/battle_util.h
src/battle_ai_switch_items.c
src/battle_util.c

Fixing issue [#3059](https://github.com/rh-hideout/pokeemerald-expansion/issues/3059) from the other day, solved with Salem's help. See that issue for links to the details.
Fixes [#3059](https://github.com/rh-hideout/pokeemerald-expansion/issues/3059)
@pawkkie

Fix bug due to variable overflow when AI chooses new Pokemon to send out

---

src/battle_interface.c

Reviewing the last ball shown code, the following 2 bugs were seen:
1. The ball and window do not fully move the same speed due to the Window's starting location being closer than the ball's by one pixel. It's hard to notice, but can be seen by cycling through frames. subtracting by one showed this issue to go away.
2. When first creating the window, the ball's sprite ID gets written as unhidden rather than the window. This doesn't cause issues functionally, as sHide (data[0]) defaults to 0.
devolov#4853

Window Track With Ball When Unhiding; Properly Show Window as Unhidden on First Creation

---

src/battle_ai_util.c

**Current behaviour:**
If the player revealed any priority move, `AI_WhoStrikesFirst` always returns AI_IS_SLOWER if `consideredMove` is of priority 0.
**New behaviour:**
As a rule of thumb, the AI should exclude status priority moves from consideration since this function is about who STRIKES first. Granted, not the best solution but better than current behaviour.
As a middle ground, any move that does not faint the AI in two hits (this includes status moves) and is of higher priority than `consideredMove` is excluded from consideration.
Feedback appreciated since this is my first PR. :)
joggel

Fixed AI_WhoStrikesFirst considering status priority moves when it shouldn't

---

test/hold_effect_air_balloon.c

This adds tests for the existing `HOLD_EFFECT_AIR_BALLOON`. I was playing around with some of this stuff for fun and thought these tests might be useful for others as well.
The tests here are based on the information I could find online (e.g. Bulbapedia.) The case that Thief and Covet cause the Air Balloon to pop before it can be stolen currently fails, but I'm not comfortable enough with the rest of the code base to fix that.
hetoord

Tests for Air Balloon

---

test/test_runner.c

Credit to MGriffin
- Fixed non-battle tests omitting errors when failing.
- Fixed non-battle tests showing false positive memory leak errors due to the test failing for a different cause.

Fixed 2 test runner issues

---

data/battle_scripts_1.s
include/battle_scripts.h
src/battle_script_commands.c
test/ability_clear_body.c
test/ability_full_metal_body.c
test/ability_hyper_cutter.c
test/ability_inner_focus.c
test/ability_own_tempo.c
test/ability_pastel_veil.c
test/ability_scrappy.c
test/ability_white_smoke.c
test/hold_effect_clear_amulet.c

Fixes Clear Amulet visual bug. A wrong message was displayed when Intimidate on Clear Amulet was used.
Also removed some code in the Intimidate script that was not needed and added a couple of tests.
Fixes #3054
rainonline

Fix Clear Amulet visual bug + Tests

---

src/debug.c

Fixes #3041
The menu was freezing, because the list menu task was not getting removed in some cases. Which means that after X tries, there would be no free tasks to create one.

fix debug menu not removing list menu task

---

src/pokemon_debug.c

- Shadows only break because they're accessing data that doesn't exist until state 2, so added a check
- Two castform-related functions in this file were throwing warnings on modern due to lack of arg type signatures, so lumped a quick fix in with this PR
Fixes #3091
`crater.`

Fixed shadows in viewer

---

data/battle_scripts_1.s
test/move_effect_teatime.c

This adds tests for Teatime and fixes some interactions.
I noticed Teatime would skip some Pokémon. For example, when not being used by the player, the player Pokémon would not consume its berry.
I added some tests based on the very niche interactions around Electrify/Plasma Fists and Volt Absorb, Lightning Rod and Motor Drive, which should trigger their effects (heal, raise Sp. Atk or raise Speed.) These interactions are based on what Bulbapedia and Pokémon Showdown do, as I'm not able to test this interaction in an official game. If this is a problem, I'm happy to revert to the old behaviour with regards to these abilities.
hetoord

Teatime tests (and fixes)

---

test/test_runner.c

After #3076, memory leak checks were running despite the test exiting an expected result. Now they should only run if the test itself passes and when it's not expecting leaks.
No more of this:

Fixed KNOWN_FAILING tests running memory leak checks when unneeded

---

include/random.h
src/random.c
test/random.c

I couldn't see an implementation of `Shuffle`, so here's one that's specialized for 8-/16-/32- bit data (for better performance), and also has a generic implementation for larger data sizes.
The `static inline` function should dispatch to the correct size at compile-time. You can see an example of this on [Compiler Explorer](https://cexplore.karathan.at/z/nfVAqo).

Array shuffle implementation

---

src/battle_anim_throw.c
src/battle_controller_player.c
src/battle_gfx_sfx_util.c
src/battle_script_commands.c
src/reshow_battle_screen.c

Fixes https://github.com/rh-hideout/pokeemerald-expansion/issues/2934
Cause & why this wasn't spotted:
In vanilla, there were usually 2 checks to verify a mon in battle: has more than 0 HP and is not an egg. But it didn't check if the mon was actually a mon, that is its species was not SPECIES_NONE.
The problems with repro stemmed from the above. Sometimes, the non mon data had 0 HP/egg bit set, but sometimes it was just species zeroed out.
I believe these should be all the places where adding the additional check fixes the 2vs1 battles once and for all 🤞

Fix graphical/exp bugs with 2 vs 1 trainer battles

---

include/pokemon.h
src/battle_ai_util.c
src/pokemon.c

With the new beat up system in #2541 , the AI calc was only handling the first party member. This fixes that. It's a bit more computationally costly unfortunately but meh.

Beat Up AI Damage Calc

---

include/battle.h
include/battle_ai_util.h
include/battle_util.h
include/fpmath.h
include/global.h
src/battle_ai_switch_items.c
src/battle_ai_util.c
src/battle_dome.c
src/battle_util.c
test/fpmath.c

Provides inlined fixed point math operations for `Q_4_12` FP format.
Introduces new type `ufp_4_12_t` for unsigned fixed point numbers in specified format, as well as inlined version of `add`, `sub` and `multiply`.
Refactors battle damage modifier calculations to use the new functions in order to improve readability and performance. (See Discord conversation)
This PR does not alter any of the other usages of FP math.
Karathan

Fixed Point Math

---

include/fpmath.h

Reverts some changes I deemed insignificant in #3115
fixes #3120 
Karathan

[battle, fpmath] revert changes to Q_24_8 format

---

src/battle_interface.c

Previously fixedPopup = FALSE was unconditional, but it was erroneously changed in f1b9872bf0a.

Clear fixedPopup when gTestRunnerHeadless

---

test/test_battle.h
tools/mgba-rom-test-hydra/main.c

Currently Hydra always runs `nproc` number of processes, regardless of the `-j` parameter passed to `make`. This PR makes Hydra parse `MAKEFLAGS` and set `nrunners` to the specified number, if one is specified. If one isn't specified, or plain `-j` is passed, then Hydra has its current behavior of spawning `nproc` processes.
EDIT: For the release notes, let's encourage people to `make check -j` or `make check -jN` rather than just `make check` :)

Make Hydra respect -jN

---

ld_script_test.txt
test/test.h
test/test_runner.c

Stores some information at the bottom of the IRQ stack. The IRQ stack is not cleared in `crt0.s`/`main.c`, which means that even if the game resets the values will still be there. We use this to report that the current test crashed, and resume running the tests from the next test.
I cannot stress strongly enough that `.persistent` should not be used because the IRQ stack is tiny. (The name was taken from Crater's ld script proposal).

Detect test runner crashes

---

include/battle_ai_util.h
src/battle_ai_main.c
src/battle_ai_util.c

Fixes #2944
Right now AI treats a move as a MOVE_POWER_WEAK when it has to be used against the target more than 2 times, compared to the best damaging move, to faint the target.
So for example if Tackle deals 10 dmg, Ember deals 30, and the target has 45, it treats Tackle as weak, because it needs 5 hits and Ember only 2.
Also, made a little change to always hits moves. In a scenario, where Shock Wave and Thunderbolt would both faint the target in the same number of turns, but the mon's accuracy is lowered, 1 point is given to Shock Wave.

Fix how AI categorizes Weak moves and give priority to always hits moves when needed

---

data/battle_scripts_1.s
include/battle_scripts.h
include/battle_util.h
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c
test/primal_reversion.c

Fixes #3028
Replaces #3029
Changes:
- added tests for primal reversion
- handled the mentioned edge case of eject button
- moved the primal reversion switch-in order, so it happens after the hazards just like in the games

Fix Primal Reversion not activating when switching in after fainting

---

src/battle_util.c
test/ability_protosynthesis.c
test/ability_quark_drive.c

Currently both Atk/Sp.Atk and Def/Sp.Def are boosted if either of them is the highest stat.
This should fix it.
Protosynthesis Nidoqueen.
Before:
After:
rainonline

Fix Protosynthesis and Quark Drive boosts 

---

include/battle.h
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c
src/pokemon.c

Previously, it only tracked the player's form changes, which caused caught Pokémon to not transform back to their original forms.
Before vs After
Fixes #3145 

Fixed enemy parties not reverting to their original form post-battle

---

data/battle_scripts_1.s
include/constants/battle_move_effects.h
src/battle_ai_main.c
src/battle_ai_util.c
src/battle_util.c
src/data/battle_moves.h
test/move_effect_collision_course.c
test/move_effect_make_it_rain.c
test/move_effect_spin_out.c

Adds:
* `EFFECT_COLLISION_COURSE`
* `EFFECT_SPIN_OUT`
* `EFFECT_MAKE_IT_RAIN`
The `EFFECT_MAKE_IT_RAIN` script is basically a copy from Lunos but in doing so I also cleaned up some existing code, included the effect in `sIgnoredPowerfulMoveEffects` and added a Test for all three effects.
Also changed a score value when checking for Contrary to avoid situation like this: 
I think that +3 should be enough when Contrary is present. 
And I removed `EFFECT_OVERHEAT` from HPAware. I don't think it is needed there since it is already present in `sIgnoredPowerfulMoveEffects`
Fixes #2492
Fixes #2501
Fixes #2502
Fixes #2503 
rainonline

Adds some gen9 moves

---

src/debug.c

TheXaman's debug menu used PC_ITEMS_COUNT as an artifact, which would lead to memory issues if it was reduced in value (more specifically any reduction below 19). This PR fixes this issue by introducing a new DEBUG_MAX_MENU_ITEMS and a failsafe by limiting totalItems to the value of DEBUG_MAX_MENU_ITEMS if it would be larger, causing a limit in the amount of items shown rather than silently overwriting memory.
bassoonian

Fix debug memory overflow

---

data/scripts/debug.inc
src/debug.c

I ported from my personal branch an option to force a Pokémon Egg to hatch because the expansion didn't have it, and it helps speed up debugging tasks involving Pokémon Eggs.
lunos4026

Added a debug option to hatch eggs

---

include/battle_main.h
src/battle_main.c
src/battle_tower.c

Fixes `MON_DATA_OT_GENDER` not being set in `FillPartnerParty` (Credit to Crater for the suggestion)
Also `CustomTrainerPartyAssignMoves` was still missing in `FillPartnerParty` for `F_TRAINER_PARTY_EVERYTHING_CUSTOMIZED`
Fixes #3158

Set otGender + Moves in FillPartnerParty

---

src/battle_util.c
test/ability_beads_of_ruin.c
test/ability_sword_of_ruin.c
test/ability_tablets_of_ruin.c
test/ability_vessel_of_ruin.c

Damage Calcs were wrong for these four abilities.
```
ABILITY_VESSEL_OF_RUIN
ABILITY_SWORD_OF_RUIN
ABILITY_TABLETS_OF_RUIN
ABILITY_BEADS_OF_RUIN
```

Fix Ruin ability calcs + Tests

---

Makefile
include/overworld.h
src/battle_gfx_sfx_util.c
src/fieldmap.c
src/overworld.c
src/pokemon.c

After this, all that stderr outputs are some palette issues with some item sprites that I'll PR later tonight probably.
There may still be additional fixes needed for other arguments that MGriffin was toying around with, but I think this is a good start and gets the core issues out of the way.
The change that looks big is the one in pokemon.c, but it's relatively simple - just separates the encrypted and unencrypted boxmon data behind an if/else instead of just playing fast and loose with the substruct pointers. The rest is relatively simple, but some of it revolves around some messy derefencing that we could clean up a bit better eventually. For the time being, some of these just check for null in the critical sections and output a warning via debug logging, which is at least safer than …

Fixed outstanding null dereferencing errors with -fanalyzer on modern

---

data/battle_anim_scripts.s

Cleans up animation script macro usage to use `ANIM_x` defines and convert hex numbers to positive and negative decimals.
For these, I used `shasum` to make sure it didn't break anything. 
- `visible`
- `monbg`
- `invisible`
- `createvisualtaskontargets`
- `AnimTask_ShakeMon`
- `createvisualtask`
- `SoundTask_PlayDoubleCry`
- `SoundTask_PlayCryHighPitch`
- `AnimTask_WindUpLunge`
- `AnimTask_TranslateMonEllipticalRespectSide`
- `AnimTask_SwayMon`
- `AnimTask_Splash`
- `AnimTask_ShockWaveProgressingBolt`
- `AnimTask_ShakeMonInPlace`
It also fixes the following bad uses of macros (original checksum: `7a05d0b5b2cd65346597a9a598c7f7cde1570475`)
- `createvisualtask`
- `SoundTask_PlayCryWithEcho` (checksum changed to `35eae7f4357391b1ce38f0d79715f47f92c82087`) in:
- Move_RELIC_SONG
- …

Animation script cleanup and fixes - Part 1

---

src/battle_script_commands.c

I asked for opinions before submitting this change but I basically only got 1, so I decided to just submit it and handle any discussion here directly.
I modified `GetTotalAccuracy` for readability purposes and to make it easier to introduce new accuracy-changing ability effects by structuring it in a similar fashion than functions such as `CalcAttackStat`, `CalcDefenseStat`, etc.
I wasn't sure whether to submit this to Master or Upcoming, but since this isn't a new feature, I ended up going with the former.
There's a chance that the `if` statement for Victory Star inside the `switch (atkAllyAbility)` may be pointless, but I'm not completely sure, so I kept it in when I moved the different `if`/`else` statements to the `switch` statements.
Lunos#4026

Revamped GetTotalAccuracy

---

data/battle_anim_scripts.s

Cleans up animation script macro usage to use `ANIM_x` defines and convert hex numbers to positive and negative decimals.
For these, I used `shasum` to make sure it didn't break anything. 
- `createvisualtask`
- `AnimTask_ShakeMonInPlace`
- `AnimTask_ShakeMon2`
- `AnimTask_ShakeMon`
- `AnimTask_ScaleMonAndRestore`
- `AnimTask_RotateMonSpriteToSide`
- `AnimTask_RockMonBackAndForth`
- `AnimTask_PositionFissureBgOnBattler`
- `AnimTask_HorizontalShake`
- `AnimTask_FlailMovement`
- `AnimTask_ElectricChargingParticles`
- `AnimTask_CentredFrozenIceCube`
- `AnimTask_CanBattlerSwitch`
- `AnimTask_BlendMonInAndOut`
- `AnimTask_BlendColorCycle`
It also fixes Rage Powder's not turning the user red as it was likely meant to be.

Animation script cleanup and fixes - Part 2

---

gflib/sprite.c
include/gba/io_reg.h
test/random.c
test/sprite.c
test/test.h

Optimizes `BuildOamBuffer`:
- Only sorts visible sprites.
- ~~Uses quicksort.~~ Uses insertion sort with minimal writes for better performance on mostly-sorted data (which sprites typically are).
- Sorts on a single `u32` key which is computed up-front.
- Eliminates ~~`sSpriteOrder` and~~ `sSpritePriorities` and the replacement lives in IWRAM (on the stack).
- Only copies `gDummyOamData` to OAM slots that aren't already dummied.
- Only copies matrices that are in use.

Optimize sprite.c

---

src/battle_main.c

Fixed the bug in the Trainer class ball feature as discussed in Discord by moving the ball variable inside of the party loop. Thanks to AsparagusEduardo for the fix =)
Fixes #3057 
subzeroeclipse

Fixed Trainer class ball not assigned to second Pokémon

---

asm/macros/battle_script.inc
data/battle_scripts_1.s
src/battle_script_commands.c
test/move_effect_teleport.c

Fix by redirecting to the Baton Pass script when it's a trainer battle.
Fixes  #3164

Fix Teleport ending trainer battles

---

test/test_runner.c

Needs confirmation from @pkmnsnfrn, but hopefully this should fix their problems with some of the flags appearing to be set.
The issue seems to be that `gSaveBlock1Ptr` was `NULL`, so reading the flags gets garbage.
Closes #3214

Initialize save to empty in test runner

---

include/battle_util.h
include/fpmath.h
src/battle_script_commands.c
src/battle_util.c
test/ability_contrary.c
test/ability_dry_skin.c
test/ability_fluffy.c
test/ability_swarm.c
test/damage_formula.c
test/status3.c
test/weather_snow.c

Refactors the damage calculation and fixes any (to my knowledge) inconsistancies to the calculation of later games.
Key notes are:
* Gamefreak often times rounds down on n.5 in their fixed point mathematics.
* fixed point arithmetic (multiplication) is not associative, this changes the order of operations to match the original games.
* A lot of the damage calculation function was quite messy, some aspects were factored in at the wrong place.
* The main damage calculation should now be clearer to read.
Also fixes the contrary test against intimidate, which was using a wrong multiplier.
Adds tests for the basic damage calculation using an example from https://bulbapedia.bulbagarden.net/wiki/Damage#Example
Changes the test in `weather_snow.c` against solar blade from `KNOWN_FAILING` to …

[battle, damage] refactor damage formula to match gen5+

---

data/battle_scripts_1.s
test/move_effect_recoil_if_miss.c

Replaces #3195, due to my screw up of force-pushing to master to remove #3152 from it, as seen here:
Haven't reviewed it myself, just cherrypicked the commit to solve the issue with that PR.
Originally by @DizzyEggg 
Fixes #1410 

Fixed Jump Kick's recoil not happening after Spiky Shield's damage

---

src/data/battle_moves.h

Steam Eruption had `soundMove`  instead of `sheerForceBoost`.
This PR fixes that very small issue.
pcg06

Remove soundMove from Steam Eruption and replace it with sheerForceBoost

---

src/battle_script_commands.c

For whatever reason, right now the expansion's `Cmd_jumpifnopursuitswitchdmg` battle script function *(which handles the usage of Pursuit when an opponent is about to switch out their Pokémon)* uses Pursuit's move ID instead of its effect ID.
This is a bit limiting for a user who may very well want to add add copies/clones of Pursuit, as they would have to go there and modify things by themselves.
This PR addresses that by making the function read the effect of Pursuit, which is `EFFECT_PURSUIT`, instead of hardcoding `gCurrentMove` to Pursuit's move ID. That way, any moves that a user may want to add and that also use that same effect besides Pursuit itself can work normally too.
lunos4026

Made Cmd_jumpifnopursuitswitchdmg and Cmd_pursuitdoubles use Pursuit's effect ID instead of its move ID

---

data/battle_scripts_1.s
src/data/items.h

Alex/rainonline told me in the Discord server that the conditionals we were using for the preproc configs that handle Rapid Spin's speed-raising effect and the power of the Gem items were incorrect.
Rapid Spin can still raise the Speed stat in the Gen. 9 games so using checking if the preproc config was set to `== GEN_8` was incorrect, and the power of the gems started to be 30 on Gen. 6, it was 50 on the Gen. 5 games.
lunos4026

Corrected the conditionals used for B_SPEED_BUFFING_RAPID_SPIN and I_GEM_BOOST_POWER

---

sound/cry_tables.inc

For the past 6 months, female Basculegion's cry was missing from the cry table. This meant that if anyone added species or farms after SPECIES_BASCULEGION_FEMALE, the cry indexes would be one off.
bassoonian

Add female Basculegion to cry table

---

src/battle_util.c
test/battle/hold_effect/metronome.c

Fixes metronome reducing damage instead of increasing it; Regression introduced by #3196 
Also adds ~~a test~~ tests for metronome. 2 of them are `KNOWN_FAILING` and have been assigned issues respectively.
Fixes #3244 
karathan

[item, metronome] fix metronome damage multiplier

---

src/battle_ai_switch_items.c

Adds consideration for Sap Sipper, Storm Drain, Dry Skin, Motor Drive, and Lightning Rod to the `FindMonThatAbsorbsOpponentsMove` function, which is called by the ShouldSwitch function and affects the switch AI.
This works fine for Flash Fire, Water Absorb, and Volt Absorb by default, just adding the missing abilities. This was initially brought up by EZBREEZY on [Discord](https://discord.com/channels/419213663107416084/1077168246555430962/1138553428755349624), and Alex suggested I PR it.
Pawkkie

Add missing absorbing abilities to FindMonThatAbsorbsOpponentsMove

---

src/battle_ai_main.c
src/battle_ai_util.c

- Make more use of `AI_GetHoldEffect` to prevent the AI from going for unfavorable moves if hold effect becomes known
- `ShouldFakeOut` changes. Mostly new additions that prevent flinching but also removed `ShouldTryToFlinch` from this function
- A small `ShouldTryToFlinch` addition and now returns zero if conditions don't apply. I personally think that a move shouldn't get an increase if there is only a chance (unless the chance is increased) for the effect to occur because it might mess with the highest damage move which is likely better in most cases
- Added minor `EFFECT_EARTHQUAKE` and `EFFECT_MAGNITUDE` check

Prevent certain status moves when item is known + Fake Out changes

---

Makefile

Makes `-fanalyzer` optional when building the `modern` target.
Compilation is particularly slow when static analysis is performed during code generation. This does not remove the ability to perfrom static analyis, but rather adds a flag `ANALYZE` to manually enable `-fanalyzer` when compiling, e.g.
```
make modern ANALYZE=1
```
karathan

[Makefile] make -fanalyzer optional

---

data/battle_scripts_1.s
include/battle_scripts.h

`BattleScript_EffectTeleport` always calls `attackcanceler` and `attackstring`, but then it jumps to `BattleScript_EffectBatonPass` under certain conditions, when that battle script calls them too.
This PR addresses that by relocating those `attackcanceler` and `attackstring` calls and adding a new battle script to jump to during trainer battles.
Lunos#4026

Fixed redundant calls in Teleport's battle script

---

include/battle_util.h
src/battle_anim.c

Previously, GetBattleAnimMoveTargets assumed the original target was always viable. This adjusts to target only the alive battlers. It also adds a failsafe check for if there are no viable targets (which shouldnt happen anyway, of course)

fix GetBattleAnimMoveTargets logic

---

src/battle_bg.c

The text describing Z status moves in battle is cut off when it exceeds a tile width of 8. The description in the first image below should say "Reset Lowered Stats" as per `battle_z_move.c`.
The reason for the cutoff is that the `B_WIN_MOVE_NAME_3` window template only has a width of 8. This PR extends it to 16 as per the change to `B_WIN_MOVE_NAME_1` to accommodate Z move names.
Before
After
`gamebriel#4784`

Fix Z effect descriptions being cut off

---

src/item_use.c

I was checking the code for the recently implemented Gen. 6 Exp. Share and noticed that its `ItemUseOutOfBattle_ExpShare` was calling `DisplayItemMessage` and passing hardcoded values for its fontId parameter.
lunos4026

Made ItemUseOutOfBattle_ExpShare use FONT_* labels when calling DisplayItemMessage

---

test/battle/hold_effect/cure_status.c

Originally made for PR #3275 but since it would introduce a regression (found through tests), I'm PR'ing them so they don't get lost. 
One failing test passes with PR #3275 but others fail.

Tests for status curing berries

---

src/debug.c
src/item_use.c
src/scrcmd.c
src/script_menu.c

Adds a `struct ScriptContext` argument to `NativeFunc` to allow more convenient scripting with `callnative`. We can make macros similar to battle scripts with .byte fields afterwards and use those in our callnative function
e.g.
```
.macro gettilebehaviorat x:req, y:req
callnative NativeFunc_gettilebehaviorat
.2byte \x
.2byte \y
.endm
void NativeFunc_gettilebehaviorat(struct ScriptContext *ctx)
{
u16 x    = VarGet(ScriptReadHalfword(ctx));
u16 y    = VarGet(ScriptReadHalfword(ctx));
gSpecialVar_Result = MapGridGetMetatileBehaviorAt(x + MAP_OFFSET, y + MAP_OFFSET);
}
```

Callnative functions take ScriptContext argument

---

data/battle_scripts_1.s
src/battle_ai_util.c
src/battle_util.c
test/battle/ability/toxic_debris.c

Battlers weren't swapped back which caused some effects not to go off and 2 layers can be set up.   
Also fixes a small index issue in `CanTargetFaintAi`.

Fixes Toxic Debris + CanTargetFaintAi index issue

---

include/battle.h
include/battle_ai_main.h
include/config/debug.h
src/battle_ai_main.c
src/battle_controller_player.c
src/battle_main.c

Adds a timer which counts how long it takes for the AI to decide which action and move to choose.
The number of frames will be displayed in the battle box replacing the "What will PKMN do" text.
Uses new config define DEBUG_AI_DELAY_TIMER
I also changed GetAiLogicData function's name to SetAiLogicDataForTurn, because it made more sense to me, but I can revert it or change to something else if needed.
Current benchmarks on upcoming are:
- 11 frames when choosing a move
- 48 frames when AI switches(note it may actually be closer to 30 or 50 depending on how many pokemon the AI party has). It takes too long, and the lag is way too noticeable, it'll be fixed in #3253
- 45 frames in a double battle
When building with modern these all take less frames(which is all the more reason to ditch …

Add ai delay timer

---

include/battle.h
include/battle_anim.h
src/battle_ai_main.c
src/battle_ai_util.c
src/battle_anim.c
src/battle_anim_effects_2.c
src/battle_anim_fight.c
src/battle_anim_ice.c
src/battle_anim_mons.c
src/battle_controller_player.c
src/battle_controllers.c
src/battle_debug.c
src/battle_gfx_sfx_util.c
src/battle_main.c
src/battle_message.c
src/battle_script_commands.c
src/battle_util.c
src/pokemon.c

Replaces #3201
I only fixed conflicts, removed an unnecessary extern and changed arguments from u8 to u32. Other than that, gruxor's PR was good and ready to merge.

Remove redundant side macros/funcs

---

include/test/battle.h
ld_script_test.txt
test/battle/move_effect/stockpile.c

Title.
As per Discord discussion.
```C
#define MESSAGE(pattern) QueueMessage(__LINE__, ( const u8 []) _(pattern))
```
On modern, this puts the pattern variable on stack instead of .rodata, which leads to all the invalid opcodes issues.
Putting `static` fixes the issue, as the variable is always placed in the `.rodata` section.

Fix tests breaking on modern

---

src/battle_util.c

It should pretty much make all tests pass on modern. (Well, it's possible 2 will still fail for some weird reason.)

Fix no return in isbattlergrounded

---

src/debug.c

Fix flag debug screen corrupting subsequent message boxes

---

include/battle.h
include/config/item.h
src/battle_main.c
src/battle_script_commands.c

Fixes #3318 
Changes the order of messages when mons obtain exp, so that it's first the mons via sent-out, and then via exp-share(with the 'The rest of your team got Exp Points' msg).
Also does some clean-up.

Fix order of messages in gen6 exp share

---

data/battle_scripts_1.s
src/battle_util.c

Fixes seed sower in doubles and probably other abilities. Also makes `BattleScript_ActivateTerrainAbilities` use gBattlerTarget as an iterator (with savetarget/restoretarget)
Also fix ABILITYEFFECT_ON_TERRAIN setting gBattlerAbility incorrectly

Fix TryChangeBattleTerrain overwriting gBattlerAttacker and ABILITYEFFECT_ON_TERRAIN

---

include/config/overworld.h
src/pokemon_storage_system.c

Adds a simple config. In Gen4+, pressing B while holding a Pokémon in the PC is equivalent to placing them down. This config (set to GEN_LATEST by default) trivially adds said functionality for a more modern feel.
bassoonian

Adds support for placing Pokémon in the PC with the B button

---

data/battle_scripts_1.s
test/battle/move_effect/protect.c

Fixes #3304 
Fixes #3312
Adds tests for all protect moves.

Fix protect recoil issue and add tests for protect

---

src/pokemon_storage_system.c

I'll try to do 1.6.1 as soon as this is merged.
#3354 

Fixed deleting PC mon by placing another one on top with B

---

src/data/pokemon/species_info.h

Updates Pokémon abilities to Gen9 standards.
Added configs for SV ability updates:
- Gallade (base game)
- Shiftry (DLC)
- Piplup line (DLC)
Also added a corresponding config for Koffing and Wheezing, who were updated in Gen8 but lacked a config.
bassoonian

Updates Pokémon abilities to Gen9

---

data/battle_scripts_1.s
test/battle/hold_effect/red_card.c

Fixes #3340
New tests + added expect for old tests to make sure the item does get consumed in all of the cases.

Fix Red Card not getting consumed after Sticky Web activation

---

test/battle/move_effect/multi_hit.c
test/battle/trainer_control.c

I believe this to be the last failing test. With this merged,  #3305 should be good to go and we could finally enter the modern era.

Fix CreateNPCTrainerPartyForTrainer test failing on modern

---

include/battle.h
include/config/battle.h
src/battle_util.c

In Gen 4+, Light Ball multiplies the base power of physical moves by 2, and Sandstorm multiplies the Special Defense of Rock types by 1.5. Added constants to be able to reverse these effects in the damage calc.
```c
#define B_LIGHT_BALL_ATTACK_BOOST  GEN_LATEST // In Gen4+, Light Ball multiplies the base power of physical moves by 2.
#define B_SANDSTORM_SPDEF_BOOST    GEN_LATEST // In Gen4+, Sandstorm multiplies the Special Defense of Rock types by 1.5.
```
Part of the overall concept of #1401
yakattack_

Add calculation boosts for Light Ball and Sandstorm

---

include/battle_util.h
src/battle_util.c
test/battle/ability/rivalry.c

- It was doing the opposite if neither attacker or target were genderless.
- It wasn't accounting for genderless mon.
Thanks to @PCG06 for finding this issue.
Note: maybe the function names could be renamed, but not sure to what.

Fixed Rivalry's effect + Tests

---

include/config/item.h
src/battle_util.c

Added missing description on how to use the Exp. Share flag.
Also fixed flawed implementation that didn't allow to use the flag in scripting without setting the item itself to Gen6+.

Made Gen6 Exp Share flag easier to understand

---

include/test_runner.h

`MgbaPrintf_` was already defined in `include/test/test.h`, and adding it again caused issues with how IDEs like VSCode detected
`u32`.
AsparagusEdoardo

Fixed VSCode shenanigans

---

data/battle_scripts_1.s
src/debug.c
test/battle/move_effect/salt_cure.c

Fixes Salt Cure visual bug if mon fainted by direct attack

---

include/test/battle.h
test/test_runner_battle.c

AI battle tests use too much heap, so I put ai log lines in EWRAM outside heap.

fix broken move anims in tests

---

test/test_runner.c

Fixes #3043
Example output when `ASSUME` fails in `ASSUMPTION` block:
```
[0] Multi hit Moves hit the maximum amount with Skill Link: ASSUMPTION_FAIL
test/battle/move_effect/multi_hit.c:6: ASSUME failed
[0] Multi hit Moves hit twice 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit thrice 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit four times 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit four times 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit at least four times with Loaded Dice: ASSUMPTION_FAIL
[0] Multi hit Moves hit five times 50 Percent of the time with Loaded Dice: ASSUMPTION_FAIL
- Tests PASSED:        0
- ASSUMPTIONS_FAILED:  7
- Tests TOTAL:         7
```

Fix ASSUMPTIONS not working

---

include/test/battle.h
test/battle/move_effect/salt_cure.c
test/battle/status1/bad_poison.c
test/battle/status1/burn.c
test/battle/status1/poison.c
test/battle/status1/sleep.c
test/test_runner.c

Includes a [missing change](https://github.com/rh-hideout/pokeemerald-expansion/pull/3368#discussion_r1342333793) from #3368.
Also changes `i` to be `const` [as suggested on Discord](https://discord.com/channels/419213663107416084/1077009799293710357/1161728544745984030) which prevents developers from assigning to `i`, which is important to prevent accidentally interfering with `PARAMETRIZE`. This is the first time I've ever wanted to apply `const` to a non-pointer parameter, so that's interesting!

Test improvements

---

gflib/malloc.c
include/fieldmap.h
include/test/battle.h
src/fieldmap.c
test/test_runner_battle.c

[Pawkkie found a situation where adding just a small amount of data to `AiLogicData` caused the tests to blow up](https://discord.com/channels/419213663107416084/1077168246555430962/1162249269445677156). #3398 is a similar story where adding data to `BattleTestRunnerState` caused tests to blow up.
This PR:
1. Makes a test fail on the spot of `Alloc` returns `NULL`.
2. Makes `gBattleTestRunnerState` alias `sMapLayoutData`, a 20kB buffer that goes unused in battle tests.
It seems unlikely that anybody would write battle code which relies on, e.g. `MapGrid_GetMetatileAt`, but if they do it will no longer work. Of course that would probably be broken in the tests anyway because they don't load a map, but the output will be much more confusing now.
It's possible that in the future we'll want …

Move battle tests off the heap

---

data/battle_scripts_1.s
include/random.h
src/battle_main.c
test/battle/ability/beast_boost.c
test/battle/ability/ice_scales.c
test/battle/ability/leaf_guard.c
test/battle/ability/neuroforce.c
test/battle/ability/purifying_salt.c
test/battle/ability/quick_draw.c
test/battle/ability/sharpness.c

Sorry Eduardo! :)
Adds tests for the following six abilities:
- Sharpness
- Purifying Salt
- Ice Scales
- Neuroforce
- Beast Boost
- Quick Draw
Also fixes the following bugs:
- Quick Draw now uses weighted RNG
- Purifying Salt makes Rest fail
It also updates Leaf Guard's test to be in line with Purifying Salt's (see Discord & the reviews)
bassoonian

Tests for 6 more abilities

---

src/data/pokemon/species_info.h

Closes #3418.
Cresselia's base defenses were nerfed in SV.
lunos4026

Updated Cresselia's base stats

---

src/battle_util.c

A complement for the already merged #3247.
I missed a function that was also supposed to use the new `B_MSG_TERRAIN` constants that I added for the battle text strings used by the field terrains at the beginning of their effect.
lunos4026

Made AbilityBattleEffects use the B_MSG_TERRAIN constants for the field terrain intro text

---

src/battle_main.c

Title.
Yesterday, I was looking at `CB2_InitBattleInternal` for reasons and I noticed that it was running 2 for loops to apply changes on the Pokémon in the Player's and the Opponent's parties.
However, it only really needs to run 1, as far as I can tell.
lunos4026

Removed pointless for loop in CB2_InitBattleInternal

---

src/pokemon.c

Fixing a potential issue found by @Pawkkie, where using `Get(Box)MonData` in a macro caused issues without a `NULL` as the 3rd argument.
eg.
```diff
#define CALC_STAT(base, iv, ev, statIndex, field)               \
{                                                               \
u8 baseStat = gSpeciesInfo[species].base;                   \
s32 n = (((2 * baseStat + iv + ev / 4) * level) / 100) + 5; \
-   u8 nature = GetNature(mon);                                 \
+   u8 nature = GetMonData(mon, MON_DATA_NATURE);               \
n = ModifyStatByNature(nature, n, statIndex);               \
if (B_FRIENDSHIP_BOOST == TRUE)                             \
n = n + ((n * 10 * friendship) / (MAX_FRIENDSHIP * 100));\
SetMonData(mon, field, &n);                                 \
}
```
Discord …

Converted Get(Box)MonData2 to proper functions

---

src/battle_script_commands.c
test/battle/ability/parental_bond.c

Fixes Parental Bond after #2952.
TODO: the rest of the tests.
#3407 

Fixed Parental Bond

---

.gitignore

Title.
`src/data/map_group_count.h` is a file containing an array with map group counts that is automatically generated through mapjson and used by TheXaman's debug menu.
Realistically, there's no reason to taint the commits of the users by letting it be included in a commit.
lunos4026

Added src/data/map_group_count.h to .gitignore

---

.github/workflows/build.yml

Switches the build environment in the CI to a DKP docker container.
Seemed like one of the easiest ways to get an up to date arm toolchain, it's also what a lot of people use to build the project, so it should match the user environment as well as provide a modern toolchain.
Depends on #3428 
/
karathan

use dka container for a more modern gcc

---

src/battle_util.c
test/battle/ability/beads_of_ruin.c
test/battle/ability/sword_of_ruin.c

Moves the ruin abilities effect into the attack and defense stat calculation instead of the move damage calculation.
This should fix Sword and Bead of Ruin not reducing as much def and sp def as it should.
Fixes #3411
kittenchilly

Fixed and more accurate Ruin abilities

---

asm/macros/battle_script.inc
data/battle_scripts_1.s

I came up with the thought to replace the bunch of `printstring STRINGID_EMPTYSTRING3` and `waitmessage 1` commands that we're using to flush the text box in battles with a macro, so I did it.
Not only it makes the code that composes the affected battle scripts slightly more readable, it reduces the number of lines in the file. Granted, it's not a huge gain, but it's still a gain in the end.
lunos4026

Added a macro to flush the text box in battles

---

test/random.c
test/test_runner.c

Fixes tests rng

---

include/clock.h
src/clock.c
src/debug.c

Time-based events were not running when doing a Cheat Start, causing headaches for testing new RTC features.

Fixed Cheat Start not initiating time-based events

---

test/battle/ability/prankster.c
test/battle/hold_effect/critical_hit_up.c
test/battle/hold_effect/jaboca_berry.c
test/battle/hold_effect/kee_berry.c
test/battle/hold_effect/maranga_berry.c
test/battle/hold_effect/rowap_berry.c
test/battle/move_effect/bug_bite.c
test/battle/move_effect/multi_hit.c

- Removed duplicated Prankster TO_DO test.
- Corrected Multi-hit test names (4 and 5 hits stated 35% instead of 15%).
- Grouped Maranga Berry's Physical vs Special tests using `PARAMETRIZE`.
- Improved Jaboca, Kee and Rowap tests by @AlexOn1ine 

Test cleanup and improvements

---

asm/macros/battle_script.inc
include/battle.h
src/battle_script_commands.c
test/battle/move_effect/reflect_type.c

Closes #3266.
This PR updates Reflect Type's effect to handle 3rd types, including an edge case in which the target of Reflect Type may have lost its first 2 types, but acquired a 3rd one.
Misc. Changes:
-Turned the `VARIOUS_TRY_REFLECT_TYPE` into a callnative battle script.
-Introduced a macro `IS_BATTLER_TYPELESS` that checks if the specified battler has no valid type *(or in other words, that checks if its 3 types are set to `TYPE_MYSTERY`.)*
lunos4026

Made Reflect Type handle 3rd types

---

include/config/battle.h
src/wild_encounter.c

Fixes Synchronize's devnote to mention Natures rather than Abilities. Since the ability also loses its out-of-battle effect in SV, I updated the config to reflect that, too.
Fixes #3443 
bassoonian

Fix Synchronize devnote + Gen9 behaviour

---

Makefile
include/test/test.h
test/test_runner.c
tools/mgba-rom-test-hydra/main.c

`gTestRunnerState.test = __start_tests - 1;` is UB. Rearranged the test runner code so that we can initialize to `__start_tests` instead.
Also:
- Creates a separate `modern-test` directory so that you can switch between `make check MODERN=0` and `make check MODERN=1`.
- Buffers `GBA: `-prefixed lines, so that something like an illegal opcode error gets reported as belonging to the right test.
Once this lands we should merge `master` with `upcoming` so that we can switch to building with `MODERN=1` by default. The "CreateNPCTrainerPartyForTrainer generates customized Pokémon" test fails when built with modern, but not with agbcc. I haven't looked into this, and I don't think it's related to this PR(?)

Fix test_runner.c modern warning

---

src/data/items.h
src/data/pokemon/item_effects.h

Currently a Razor Fang can't be used from the bag to evolve Pokemon even when I_USE_EVO_HELD_ITEMS_FROM_BAG is set to true. This PR fixes that by changing Razor Fang's type to EVO_HELD_ITEM_TYPE and fieldUseFunc to EVO_HELD_ITEM_FIELD_FUNC
Frankfurter#8828

Gave Razor Fang EVO_HELD_ITEM type/fieldUseFunc properties

---

data/scripts/debug.inc
ld_script.txt
ld_script_modern.txt
ld_script_test.txt
src/debug.c

Based on [this Discord comment](<https://discord.com/channels/419213663107416084/1077168246555430962/1162078321224458310>).
Currently 23.22MB/32MB on agbcc and 23.17MB/32MB on modern (GCC 13.2.0). Obviously a byte count like in the save block message would be completely useless. So I chose to round to two decimal places, with `ROUND_CEILING` because I think it's more annoying to think you have enough space and actually not, than the opposite.
TBH it might make more sense to print out how much free space is available (both for the ROM and for save blocks)?

ROM space on debug menu

---

.github/workflows/build.yml
Makefile

With modern now being the default output and agbcc requiring the explicit mention that modern used to require, it only makes sense to rename the output files to accomodate this change.
bassoonian

Rename output roms

---

data/scripts/debug.inc
src/battle_bg.c

Fixes legendary backgrounds

---

src/battle_controller_player.c
src/battle_main.c
src/battle_util.c

Fixes #3434
Fixes #3466
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/6dba78b3-ed37-4595-b1e9-566bd865d4aa
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/56d4474f-a731-43a4-b0f8-c50f53887d72

Fixes dynamax move target and canceling in doubles

---

include/config/battle.h
src/battle_util.c

Changes max obedience level to be increased by 10 per badge, as in ORAS.
This also means we can set B_OBEDIENCE_MECHANICS to GEN_LATEST without breaking anything.
kittenchilly.

Obedience levels now increase per badge

---

include/config/battle.h
include/config/overworld.h
include/wild_encounter.h
src/pokemon.c
src/script_pokemon_util.c
src/wild_encounter.c

This PR fixes Synchronize's OW effect (which was still limited to Emerald's and didn't include gift Pokémon etc) and adds configs (with appropriate changed effects) for all other abilities with OW effects (if appropriate, of course).
bassoonian

Fixes Synchronize's OW effect and adds configs

---

include/test/battle.h
src/battle_script_commands.c
test/battle/ability/defiant.c
test/battle/ability/sheer_force.c
test/battle/ability/weak_armor.c
test/battle/hold_effect/white_herb.c
test/battle/move_effect/encore.c
test/battle/move_effect/last_resort.c
test/battle/move_effect/stealth_rock.c

Out of curiosity I decided to take a look at Pokemon Inclement Emerald's known bugs doc. It uses an older version of pokemon expansion, but I wanted to check if any of the bugs managed to persist until now. 
So far I only checked the first page, and wrote tests for all the scenarios. And surprisingly there were _still_ 2 bugs present! 
I may take a look at the doc later and check the rest, but in any case I feel like this PR is big enough currently.
Fixes Sheer Force's issue #3055 but only partially. Shield Dust fix will have to wait for a separate PR.
Fixes Sleep Talk interaction with Last Resort. No issue submitted for this one.

New tests + Sheer Force / Last Resort minor bug fixes

---

data/battle_scripts_1.s
include/config/battle.h
test/battle/ability/weak_armor.c

Added config for Weak Armor's Gen 5-6 effect

---

src/battle_util.c
test/battle/ability/defiant.c
test/battle/ability/sap_sipper.c

Fixes Sap Sipper activating only for the first of Bullet Seed.
Also has one test for Defiant + Sticky Web.

Fix Sap Sipper not blocking Bullet Seed

---

src/battle_util.c
test/battle/terrain/psychic.c

fix psychic terrain blocking moves it shouldnt block

---

src/battle_controller_player.c

When looping through Poke Balls, GetNextBall was selecting the current ball as the next one, which prevented it selecting the correct next ball. This PR fixes that by having it actually look at the next ball.
Fixes #3496
frankfurter0

Fixed issue with GetNextBall not working properly

---

data/battle_scripts_1.s
src/data/pokemon/species_info.h
test/dynamax.c

Fixes Dragon Tail and Pumpkaboo spelling

---

data/battle_scripts_1.s
include/battle.h
include/battle_scripts.h
include/constants/battle_string_ids.h
src/battle_message.c
src/battle_script_commands.c
src/battle_util.c
src/data/pokemon/form_change_table_pointers.h
src/data/pokemon/form_change_tables.h
test/battle/ability/zero_to_hero.c

Closes #2765
I haven't written tests for the Power of Alchemy, Receiver, Mummy, Lingering Aroma, and Wandering Spirit interactions because I think it would be better to do in it's own file for each ability.

Adds ability Zero to Hero

---

src/daycare.c

The `IS_DITTO` macro used by the `P_NATURE_INHERITANCE` preproc config at `include/config/pokemon.h` was sorely outdated and was blocking the compiler from building a ROM when set to a value like `GEN_3`.
This PR fixes that.
lunos4026

Fixed IS_DITTO macro

---

test/test_runner.c

Currently, the test runner's name prefix matching process is extremely slow. For example, if I do `make pokeemerald-test.elf TESTS='Spikes' DINFO=1 -j`, and boot the test elf in mgba, it takes ~36 seconds (upcoming: ~40 seconds) to actually get into the battle scene.
The state machine in `CB2_TestRunner` is not efficient. If a non-assumption test doesn't match the specified prefix, it will wait two frames before trying to match the next test.
We can simply ignore Vblank and run serial code until we find a suitable test or run out of tests. The waiting time (before battle scene) can be reduced to less than 10 seconds with the change.
jiang

Performance improvement for specific tests

---

include/config.h
src/pokemon_summary_screen.c

Incorporates @DizzyEggg's [nature color branch](https://github.com/DizzyEggg/pokeemerald/tree/nature_color) (as such, don't squash when merging!). It also adds a config to easily toggle them and updates the reduction color to blue per @AsparagusEduardo's [tutorial](https://github.com/pret/pokeemerald/wiki/Colored-stats-by-nature-in-summary-screen).
Fixes #2535 
bassoonian

Adds configable nature colors

---

data/battle_scripts_1.s
test/battle/move_effect/attack_up_user_ally.c

Fixes Howl activating if partner has Soundproof

---

src/battle_controller_player.c
src/pokemon_summary_screen.c

Ivy Cudgel (and Tera Blast, which is for later) are the only moves in SV where the actual type used in calculations is shown in interfaces (as opposed to Raging Bull, Judgment etc, which just show the default type). This PR adds the Ivy Cudgel logic to the interfaces to show the correct type.
bassoonian

Reflect Ivy Cudgel type in interfaces

---

include/battle.h
src/battle_util.c
test/battle/ability/protosynthesis.c
test/battle/ability/quark_drive.c

Fixes #3255
Abilities were activated each turn if a field effect was on the field. 
Two tests fail because of illegal abilities. Once this is ported back to upcoming, I'll change it to the correct species.

Fixes Protosynthesis and Quark Drive ability pop up

---

include/config/overworld.h
include/rtc.h
src/battle_script_commands.c
src/pokemon.c
src/rtc.c

Provides a config for the hours each time of day falls between
Fixes #3574 
Frankfurter0

Add config for times of day

---

src/party_menu.c

Fixes two oddities in the fusion system:
- Selecting an incompatible species at any point froze the game (because it didn't check if said species had any fusion data at all, so we're lucky it didn't just outright crash!)
- The second species was not taken into account, leading to fusions of Kyurem and Zekrom into White Kyurem.
Fixes #3601 (that disppeared mysteriously)
bassoonian

Fix fusions

---

data/battle_scripts_1.s
include/constants/battle.h
src/battle_script_commands.c

Fixes #3584 
Introduces HITMARKER_DISABLE_ANIMATION in addition to HITMARKER_NO_ANIMATIONS.
HITMARKER_NO_ANIMATIONS is only set at the start of battle for when battle scene is turned off, so `bicword gHitMarker, HITMARKER_NO_ANIMATIONS` in e.g. bug bite would override that setting. This adds a new hitmarker replacing an unused bit to disable battle animations when HITMARKER_DISABLE_ANIMATION is set, similar to how the former works.
This does not check HITMARKER_DISABLE_ANIMATION for pokemon animations or send out animations since it is not relevant then

add HITMARKER_DISABLE_ANIMATION for bug bite consumeberry

---

data/scripts/debug.inc

Fixes https://github.com/rh-hideout/pokeemerald-expansion/issues/3615#issue-2015546179
psf
Thread: https://discord.com/channels/419213663107416084/1127465784004837376

Fix issue where Sky Battles cause upcoming not to compile when debug menu is turned off

---

gflib/sprite.c
src/battle_anim_new.c
src/scrcmd.c
src/start_menu.c

Fixes the name of some static variables that started with `g` to reflect their actual staticity.
bassoonian

Fix static variable names

---

src/battle_script_commands.c
src/battle_util.c
test/battle/ability/stamina.c
test/battle/hold_effect/eject_button.c

Fixes Substitute triggering Stamina and Eject Button on crash damage

---

data/battle_scripts_1.s
test/battle/move_effect/fling.c

Fixes #3661
The test `Fling - thrown berry's effect activates for the target even if the trigger conditions are not met` was failing for `ITEM_ORAN_BERRY` because Fling did to much damage after the damage calcs were fixes so I just reduced the attack of Wobbuffet to 1. I don't think reducing it to 1 matters much because the damage isn't what the test is testing.

Fixes Fling damage calcs

---

test/battle/item_effect/cure_status.c

Ice heal heals being frozen, not paralyzed
roseareazero

Fix Ice Heal typo in test

---

include/config/battle.h
src/battle_script_commands.c
src/item_use.c

In Gen4+, trying to catch a Trainer's Pokémon by using a Poké Ball doesn't actually consume the item.
bassoonian

Config for trying to catch a Trainer's Pokémon

---

src/data/pokemon/form_change_table_pointers.h

Replaces the generational defines in the form change table pointer defines with family-based defines. I don't think I currently have the ideal solution since this is all rather finicky, and we should probably include `P_FUSION_FORMS` in here too, but it quickly turns into a config fest. Thoughts are very welcome!
Fixed #3691 
bassoonian

Fix form change table pointer defines

---

src/battle_main.c

Fixes z-move priority

---

src/data/battle_moves.h

Some species/physical moves had their power set to 0 instead of 1.

Fix wrong move power

---

src/data/pokemon/level_up_learnsets.h
src/data/pokemon/species_info.h

Both Alolan Rattata and Alolan Raticate have "#if P_ALOLAN_FORMS" before their level up learnsets even though all other Alolan forms (including Rattata/Raticate in other files) only have the if statement once per line. This PR removes that and also standarizes the spacing in Veluza's stats
Frankfurter0

Removed redundant '#if P_ALOLAN_FORMS' for Raticate and fixed Veluza's stat spacing

---

include/config/pokemon.h
src/battle_script_commands.c

Since Gen 6, the capture rate curve was changed to make pokeballs more effective on lower level pokemon
It's by 65536 divided by 255 to the power of (1/5.33) and I did the work of translating that so a rough approximation can be done in integers, and so far, it seems to work close enough. I use this in my romhack for months now and it works fine.
roseareazero

Update catch curve for pokeballs

---

src/data/pokemon/species_info.h

Adds the missing Pokédex descriptions and updates the base form's if necessary. Everything should fit (the same script was used for the descriptions of the Gen9 mons, and I don't remember any inaccuracies there), but double checking would be appreciated.
Fixes #3650 
bassoonian

Add missing Pokédex texts for forms

---

include/config/battle.h

Fix a copypaste error and a typo in config.

---

include/config/item.h

Fix Vs Seeker description.

---

include/battle.h

Compare against https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/battle_main.c#L135.
graiondilach

Use the same relative gBattleTextBuff3 declaration in both definitions.

---

src/evolution_scene.c

Prevent unused variable error with Gen3 Shedinja config.

---

include/battle.h
src/battle_script_commands.c
src/battle_util.c
test/battle/ability/magician.c

Fix Magician Life orb recoil when stealing

---

data/battle_scripts_1.s
src/battle_main.c
test/battle/ability/innards_out.c

Fixes #3658 
Tests included.
Note: For Innards Out on Magic Guard I used Showdown's behavior. If someone wants to, they could check if it's the same in the games, but imo it's fine the way it is.

Fix Innards Out doing dmg after Gastro Acid / vs Magic Guard

---

README.md

The update message in the readme said to pull expansion/1.6.2 instead of expansion/1.7.0

Fix Update Message Saying 1.6.2

---

src/battle_script_commands.c
src/battle_util.c
test/battle/move_effect/ion_deluge.c

Fix Ion Deluge interaction with VoltAbsorb/LightRod

---

src/battle_script_commands.c
src/battle_util.c
test/battle/ability/prankster.c

Fixes #3660 
Replaces #3680
@AlexOn1ine 
I modified some of your tests, as sometimes there was a slight mistake which made them fail. I also took care of the Magic Coat edge case.
As for Obstruct test, I verified the behavior on Showdown instead of going with what was written on Bulbapedia.

Prankster tests + fixes

---

include/test/battle.h

Makes the EXPECT_MUL_EQ threshold always ±1 no matter how small it is. This leaves room for any rounding errors at smaller multiples.
kittenchilly

EXPECT_MUL_EQ thresholds are always at least ±1

---

data/battle_anim_scripts.s

Regression caused by #3727, it missed out padding the battleanim array, breaking all Z and max moves in the process.
Custom moves added after the padded moves can also be affected.
graiondilach

Realign battleanim array with battlemove array.

---

include/constants/battle_script_commands.h
src/battle_script_commands.c
test/battle/hold_effect/metronome.c

Fixes  #3251
Fixes #3250
I split up the logic so it is checked when a move ends. Checking it in ppreduce didn't cover everything.

Fixes Item Metronome damage

---

src/battle_main.c

This could cause issues in the test system, but also in the game if one battle would start right after the other. For example using Sticky Web in one battle would cause Defiant to not activate in the second battle(same with 2 tests). This should fix it once and for all.

Clear BattleScripting struct at the battle start

---

Makefile
include/test/test.h
ld_script_test.ld
test/species.c
test/test_runner.c

- Supports `u16` `PARAMETRIZE`s in the non-battle tests.
- Speeds up `CB2_TestRunner` with a `goto` (saves several frames per skipped test which is valuable when using `TESTS=`).
- Uses DACS to set the test state to `CRASH` if an illegal instruction is encountered. This greatly speeds up test failures when branching into memory that does not contain code. Previously we'd have to wait ~60s (headless!) for `mgba-rom-test` to report a `TIMEOUT`. mgba's 0.10.2 release does not support DACS in its HLE BIOS, but it's on `master` and hopefully the next release will support it. When unsupported, DACS is harmless.
[merrp uses DACS in her crash handler](<https://discord.com/channels/442462691542695948/442465020291317760/1179672160088883280>) (with a different ROM offset).

Small test runner improvements

---

include/battle_ai_util.h
src/battle_ai_main.c
src/battle_ai_util.c
src/battle_dome.c
src/battle_main.c

Fixes #2445
There is now `healBlockBanned` flag which covers all cases mentioned in the original issue.

same lists for healing moves

---

src/battle_util.c

Overworld weather-based terrain setting effects were previously using hard-coded numbers for their intro text, which is causing incorrect text to display for electric terrain created by thunderstorms. I changed them to instead reference their respective B_MSG_TERRAIN_SET constants.
I made the change for both electric and misty terrain, though the constant has been unchanged so far for misty terrain, so the text wasn't bugged.
Gif of the issue before being fixed:
User: ravepossum

Make overworld weather-based terrain setting effects use B_MSG_TERRAIN_SET constants for intro text

---

src/data/items.h

The Charizardites and Mewtwonites had identical item descriptions, but both as separate compound strings. This fixes that oversight.
bassoonian

Fix Mega Stone descriptions

---

src/battle_util.c

When defeating two opponents simultaneously, the second exp gain wasn't occurring until the subsequent action was performed
This was due to a premature `return FALSE;` in `HandleFaintedMonActions`. The fix:

Fix exp gain when defeating two opponents at once

---

src/battle_script_commands.c
test/battle/move_effect/doodle.c

Follow up on PR #2498
According to a [smogon forum post](https://www.smogon.com/forums/threads/incorrect-sv-smogon-pokedex-doodle-ability-description.3711874/) the move fails if either user or target have a banned ability.

Adds missing Doodle tests and fix

---

src/battle_controller_player.c

Fixes a buffer overread in `GetNextBall`.
When `i` is indexing the last item in the bag pocket reading `i+1` overflowed into the next pocket (TMs), this fixes the issue.
resolves #3790
karathan

[battle_controller_player.c] refactor  and fix buffer overread

---

include/config/item.h
test/battle/hold_effect/gems.c

Fixes the description of the gem boost config to refer to Gen6 rather to Gen5. Also fixes an assume in a test.
Fixes #3813 
bassoonian

Fix gem boost description + test

---

src/data/pokemon_graphics/front_pic_anims.h

I spotted that the first #if block for `P_FAMILY_REGIGIGAS` in `front_pic_anims.h` covers the AnimCmd array declarations for both Regigigas and Giratina.
`gamebriel#4784`

Fix P_FAMILY #if blocks for Regigigas and Giratina in front_pic_anims.h

---

src/pokedex_plus_hgss.c

If the HGSS Dex is enabled, all Pokemon sprites will be the shiny sprites due to the way shininess was refactored in #3438. This fixes that
Frankfurter0

Changed SHINY_ODDS to FALSE in pokedex_plus_hgss.c

---

src/data/items.h

These were left out by mistake, but now should be correct.

Add Treasure Factor to Nugget and Tiny Mushroom

---

data/battle_anim_scripts.s

Some pointless move animation defines were left in `battle_anim_scripts.s`. This removes them. No more, no less.
bassoonian

Remove leftover TID placeholder move defines

---

include/test/test.h
src/main.c

#3866, but targeting `master` since it has the same bug (it's just that I don't think we've run into it due to sheer luck).

Consistent BENCHMARK timing (master)

---

include/test/test.h
src/main.c

Waits for a v-blank to start so that `BENCHMARK`s have a (hopefully!) consistent number of IRQs when compared.
Also disables `AdvanceRandom` in the test runner. This shouldn't be necessary, and is probably masking a different problem... but it seems to work for `-j4` and `-j8` and I'd like to get `upcoming`'s CI running again ^^"

Consistent BENCHMARK timing

---

src/pokemon.c

`IsSpeciesEnabled` wasn't accounting for Eggs, since they don't have they HP stat set.
#3775 

Fixed Egg graphical data not being properly read

---

src/battle_z_move.c

In the issue linked below, it was reported that Z-Moves are broken in the Battle Frontier, and this appears to be the reason for why they were disabled. However, after performing some testing in different scenarios I have been unable to reproduce any errors which occur from using Z-Moves in the battle frontier. Please see below for a video demonstration of this feature working.
I'd imagine whatever was causing crashes with Z-Moves in the Battle Frontier may have inadvertently been fixed by another change, and it has not been tested since then until now. Please let me know if there are any concerns or questions ^
No images, however youtube demonstration of Z-Moves working can be seen [here](https://youtu.be/ubI8Q0PFoq0)
Fixed [#3334](https://github.com/rh-hideout/pokeemerald-expansion/issue …

Re-Enabled Z-Move Usage in Battle Frontier

---

include/battle_util.h
include/config/battle.h
include/pokemon.h
src/battle_ai_main.c
src/battle_script_commands.c
src/battle_util.c
src/data/abilities.h
test/battle/move_effect/doodle.c

Replaced cumbersome hardcoded arrays in battle_util.c with flags applied directly to abilities to mark what can be suppressed, copied, swapped etc.
As the title suggests, created the following flags for abilities:
```
u8 cantBeCopied:1; // cannot be copied by Role Play or Doodle
u8 cantBeSwapped:1; // cannot be swapped with Skill Swap or Wandering Spirit
u8 cantBeTraced:1; // cannot be copied by Trace - same as cantBeCopied except for Wonder Guard
u8 cantBeSuppressed:1; // cannot be negated by Gastro Acid or Neutralizing Gas
u8 cantBeOverwritten:1; // cannot be overwritten by Entrainment, Worry Seed or Simple Beam (but can be by Mummy) - same as cantBeSuppressed except for Truant
u8 breakable:1; // can be bypassed by Mold Breaker and clones
u8 failsOnImposter:1; // doesn't work on an …
```

Ability flags update

---

src/battle_script_commands.c

Forgot to update Receiver/Power of Alchemy to use flags
A follow-up to #3886 because I realised I forgot to update Receiver/Power of Alchemy to use flags instead of a hardcoded switch statement.
Cancer Fairy/thechurchofcage

Ability flags update (Receiver/Power of Alchemy)

---

src/battle_script_commands.c

This fixes an issue where changing `B_WAIT_TIME_MULTIPLIER` to a value other than 16 (we tried 8) would break the inner focus case of SetMoveEffect. The default value of 16 "magically" ends up in the right string to print (use gdb debugger), as `gBattlescriptCurrInstr++` ends up using (16 * 2 = 0x20) as the mapped function from `gBattleScriptingCommandsTable`.
poetahto
me: accelgor

Refactored SetMoveEffect Inner Focus Case

---

Makefile
include/crt0.h
include/gba/defines.h
ld_script.ld
ld_script_modern.ld
ld_script_test.ld
src/crt0.s
src/main.c
src/reload_save.c

I understand there is occasionally a need to allocate data or code within EWRAM or IWRAM sections that are initialized when the crt0.s codepath starts the game.
I have implemented LD script and assembly changes that create (currently unused) sections for EWRAM and IWRAM data that will be initialized from LMA areas towards the end of the ROM. These LMA areas will not be created if the sections are unused.
I also renamed the existing IWRAM and EWRAM sections to have names more appropriate for their purpose.
`luigi___`

Allocate initialized sections for EWRAM and IWRAM

---

data/battle_anim_scripts.s
include/battle_anim.h
src/battle_anim_flying.c
src/battle_anim_new.c
src/battle_anim_normal.c
src/battle_anim_rock.c

Fixes animations for Wildbolt Storm, Sandsear Storm, Springtide Storm, and Bleakwind Storm to handle multiple targets. Requires updating `UnpackSelectedBattlePalettes`, `AnimParticleInVortex`, and adding `HurricaneGustCentered` animation sub routines.
Old Animation:
New Animation:
Fixes #3887

Fix genie storm move anims

---

src/pokedex_plus_hgss.c

With all the pokemon refactoring in 1.7 there were a couple bugs introduced while searching pokemon pre-evolutions in the HGSS pokedex.
When printing a pokemon's pre-evolutions there is a loop that goes through all the species to look for the pre-evos. Because of an error the loop was checking the evolution array of the species selected in the pokedex, instead of the species being looped. 
Also, since now mega-evolutions are no longer stored as an evolution but as a form, the previous logic used to find a megaevolution base species was wrong. I changed the code so it now checks the form change array.
mauro58

Fix HGSS pokedex preevolutions

---

include/config/pokemon.h
src/data/graphics/pokemon.h
src/data/pokemon/species_info.h
src/data/pokemon/species_info/gen_1.h
src/data/pokemon/species_info/gen_2.h
src/data/pokemon/species_info/gen_3.h
src/data/pokemon/species_info/gen_4.h
src/data/pokemon/species_info/gen_5.h
src/data/pokemon/species_info/gen_6.h
src/data/pokemon/species_info/gen_7.h
src/data/pokemon/species_info/gen_8.h
src/data/pokemon/species_info/gen_9.h
src/pokedex.c
src/pokedex_plus_hgss.c
src/pokemon_debug.c

Adds a config to disable Pokémon footprints. Saves 29kb (0.09% of totally allowed rom size) if enabled
Fixes #3636 
bassoonian

Footprint config

---

src/debug.c

After PR 3796 was merged, now the flag toggles in the debug menu now no longer reflect the current state of the flag when you toggle them. Basically when you toggle a flag on, it doesn't update the color to reflect it and it ends up "flipped" from what it really should be, because it's getting redrawn before the function runs to toggle the flag.
This PR changes when the redraw happens relative to the function itself depending on which option is selected. This way the menu renders properly both when toggling a flag and viewing all the flags/vars in the debug menu.
This is kind of a silly fix, but it's the best way I could think of. Let me know if y'all have a better way to write this in mind.
No gif included because without inputs visible it doesn't make sense.
Discord user: ravepossum

Fix debug menu flags not redrawing correctly after PR 3796

---

include/pokedex.h
include/pokemon.h
src/data/pokemon/species_info.h
src/data/pokemon/species_info/gen_1.h
src/data/pokemon/species_info/gen_2.h
src/data/pokemon/species_info/gen_3.h
src/data/pokemon/species_info/gen_4.h
src/data/pokemon/species_info/gen_5.h
src/data/pokemon/species_info/gen_6.h
src/data/pokemon/species_info/gen_7.h
src/data/pokemon/species_info/gen_8.h
src/data/pokemon/species_info/gen_9.h
src/pokedex.c
src/pokedex_plus_hgss.c
src/pokemon_debug.c

Saves an additional 6376 bytes on top of the other 29096 bytes that the original change did.
Also, unified Footprint functions into a single one.

Removed footprint field when P_FOOTPRINTS is FALSE

---

include/birch_pc.h
src/birch_pc.c
src/match_call.c

This PR completely overhauls the regional dex rating. Features:
- There no longer is a hardcoded limit of 200 in the rating. Instead, it dynamically adapts to the amount of species in the regional dex and the amount of quotes Birch has, evenly distributing them across the size of the regional dex.
- The two different functions in Match Call and actually talking to Birch have been condensed into a single function.
- Rather than hardcoding Jirachi and Deoxys (and how they affect what counts as a complete dex), there is now a static array that consists of species that are ignored for regional dex rating purposes. They are taken into account for the formulas mentioned above.
- This also saves a whopping 496 bytes!
This is currently based on master since it's a bugfix (imo), but can be rebased …

Dynamic regional dex rating

---

src/debug.c

#3566 introduced a bug to `upcoming` where you can't toggle the "Shiny" value when using the "Give Pokemon (Complex)" action in the debug menu.
The code assumes that the value of `JOY_NEW(DPAD_UP | DPAD_DOWN)` will be 1 or 0.
`gamebriel#4784`

Fix debug action SelectShiny tInput value toggle

---

src/party_menu.c

Issue: After adding a new field move, no field moves will be displayed in the party menu screen at all. This fixes this issue.
When adding a new field move to the party menu options (e.g. adding FIELD_MOVE_HEADBUTT in the appropriate spots in party_menu.c and party_menu.h), no field moves will be displayed in the party menu screen at all for any Pokémon.
This one-line change fixes that.
jojoo0

Fix to issue with party menu field moves

---

src/berry.c

As found by @fdeblasio, YIELD_RATE was an oversight because of laziness. This PR fixes that
bassoonian

Fix YIELD_RATE (berryexpansion fix)

---

src/battle_main.c
src/battle_util.c

Minor pledge combo fixes
- Sea Of Fire damage checks battler is alive
- Reset pledgeMove field at end of turn in case a canceller stops the combo'ed move

Some pledge combo fixes

---

src/battle_util.c
test/battle/move_effect/stuff_cheeks.c
test/battle/move_effect/teatime.c

- Adds tests for Stuff Cheeks.
- Cleans up `CheckMoveLimitations` to use less horizontal space..
- Fixed harcoded uses of `MOVE_STUFF_CHEEKS` and `MOVE_ME_FIRST`.
- Fixed Teatime test checking for Wonder Room instead of Magic Room.

Stuff Cheeks cleanup

---

include/battle.h
src/battle_main.c
src/battle_script_commands.c
test/battle/move_effect/syrup_bomb.c

As mentioned by Skeli in PR #3402, Syrup Bomb / Sticky Syrup need to be cleared once the user leaves the field.

Syrup Bomb / Sticky Syrup addition

---

include/config/pokemon.h
src/battle_script_commands.c

People were reporting 100% catch rates with pokeballs with the new change.

Revert "Update catch curve for pokeballs (#3685)"

---

data/battle_scripts_1.s

Very simple change to stop Clangorous Soulblaze boosting itself twice (once after each hit) in doubles
Target still needs to be selected in doubles, which is redundant but I assume part of how Z-Moves are implemented
SirScrubbington#0322

Fix clangorous soulblaze boosting itself twice in doubles

---

include/config/item.h
src/data/items.h

Free dopamine!
Fixes #3911 
bassoonian

Add power item config

---

include/pokemon.h
src/battle_ai_util.c
src/battle_util.c
src/data/battle_moves.h

Renames healBlockBanned flag to healingMove, since its used for more than just heal block.
Also made it so Bitter Blade and Matcha Gotcha only have the flag if B_HEAL_BLOCKING is GEN_6 or greater.
kittenchilly

healBlockBanned -> healingMove

---

src/rom_header_rhh.c

RHH rom header was not in the correct section
(Compare https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/rom_header_gf.c#L98 / https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/rom_header_rhh.c#L26 )
Old:
New:
ninjdai

 Fix RHH rom header section

---

INSTALL.md

At a high level, I've made the following changes to INSTALL.MD:
- I've integrated the instructions for installing devkitARM with all of the OS setup sections, instead of being in its own section at the bottom. This way people should naturally follow the instructions before they attempt to install and make the expansion.
- Inspired by [Lunos's installation guide](https://www.pokecommunity.com/threads/tutorial-how-to-build-the-pok%C3%A9mon-gba-decomps-using-wsl-win10.432351/) that I've been providing to folks since 1.7.0, I've updated the devkitARM installation instructions based on newer installation instructions from [the devkitPro github](https://github.com/devkitPro/pacman/releases) and [the devkitPro wiki](https://devkitpro.org/wiki/Getting_Started).
- I've replaced "pokeemerald" with …

Updates to INSTALL.MD for 1.7.0+ and misc clarifications

---

src/battle_script_commands.c

Reworks the way a player loss is checked in multi battles to prevent false loss positives.
Fixes #3966
There is a deeper issue at hand, where losing a multi battle causes the player to have to pay prize money, even in the Battle Tower. This PR does not address said issue (for which a new official issue should be opened), but at least it doesn't prevent people from winning battles anymore.
bassoonian

Fix battle frontier random loss

---

include/config/overworld.h
src/pokemon.c

By default, you can be seen by two different trainers at the same time and engage in a 1v2 multi battle with them on the condition you have at least two eligible Pokémon in your party. The added config allows you to override said check and get spotted by two trainers at the same time, even if you only have one eligible Pokémon.
Fixes #3951
bassoonian

Allow being spotted by two trainers with one mon in party

---

src/battle_gfx_sfx_util.c

Source: https://www.youtube.com/watch?v=Y4kB7_nbu0s
Before vs After:

Added Calyrex's blue Dynamax aura

---

src/data/items.h

Fixes Reins of Unity being erroneously refered to as "Reins of Unities" in plural contexts
bassoonian

Fixed plural item names

---

src/script_pokemon_util.c

Melmetal is the only Mythical with a GMax form and also the only one whose GMax form can't be toggled with Max Soup.
Therefore, it's safe to assume that for the sake of extrapolation, Mythicals are excluded from the Max Soup effect.

Removed sGigantaxFactorLockedSpecies to instead check for mythicals

---

data/maps/DesertUnderpass/scripts.inc
data/maps/MirageTower_4F/scripts.inc

If bag is full and expansion configs are set as default, the chosen fossil will be lost upon selecting it, as there is no check to ensure it went into your regular items pocket.
Zatsoo

fixed oversight causing chosen fossil to be lost if bag is full

---

include/item.h
src/berry.c
src/item.c

Deprecate GetBerryCountString

---

include/battle.h
src/battle_script_commands.c
src/battle_util.c
test/battle/hold_effect/eject_pack.c
test/battle/hold_effect/red_card.c

Fixes Life Orb + Eject Pack / Red Card interaction

---

src/battle_util.c
test/battle/ability/emergency_exit.c

Fixes Emergency Exit when hp is restored over tag out range

---

src/data/pokemon/level_up_learnsets.h

In level_up_learnsets.h, Kingdra's learnset was inside a check for P_GEN_4_CROSS_EVOS. As a Gen 2 Pokemon, this has been updated to check for P_GEN_2_CROSS_EVOS instead.
.skyeward

Fixed Kingra's learnset gen

---

src/pokemon_storage_system.c

Incase someone still assume them being disabled (like I did earlier today on Team Aqua discord).
graiondilach

Tag previously-unused icon pals as such in code.

---

data/maps/DewfordTown/scripts.inc
data/maps/MauvilleCity/scripts.inc
data/maps/MauvilleCity_BikeShop/scripts.inc
data/maps/MauvilleCity_House2/scripts.inc
data/maps/MossdeepCity_House3/scripts.inc
data/maps/MtChimney/scripts.inc
data/maps/Route104_PrettyPetalFlowerShop/scripts.inc
data/maps/Route113_GlassWorkshop/scripts.inc
data/maps/Route118/scripts.inc
data/scripts/contest_hall.inc

Adds additional bag checks for key items not obtained as part of the main storyline.
Fixes #4019
Any key items that are obtained as part of the story (i.e. directly after a battle, or as part of some sort of event) are not included as having a full bag there would prevent the script from running until the end.
bassoonian

Add extra key item bag space checks

---

src/battle_controller_player_partner.c

Fixed a bug that caused the wrong palette to be used during Steven's ball throw animation in the Mossdeep Space Center fight.
Fixed a bug that caused the wrong palette to be used during Steven's ball throw animation in the Mossdeep Space Center fight.
I'm not sure if it is a known bug.
Issue that has been fixed:
jojoo0

Fixed graphics bug with Steven double battle

---

data/battle_scripts_1.s
test/battle/move_effect/pursuit.c

Fixes #3819
Credits to @ZnogyroP

Fixes Pursuit, Tangling Hair interaction

---

ld_script_modern.ld

Backported @SBird1337's [fix to pret's pokeemerald](https://github.com/pret/pokeemerald/pull/1976/files).
Normally, this would wait until next pret merge, but it fixes an ugly bug that manifests in 1.7.0-1.7.2, so it takes priority.
Fixes #4077.

[Critical fix] Backported gHeap alignment fix from upstream pret

---

test/test_runner.c
tools/mgba-rom-test-hydra/main.c

Passing `KNOWN_FAILING` were being grouped with `PASSED`
I wanted to take the chance to have the errors in the summary as well, but it was too much for me :(

Added passing "KNOWN_FAILING" to test summary

---

asm/macros/battle_script.inc
data/battle_scripts_1.s
src/battle_script_commands.c

All credit goes to @Pokabbie.
G-Max moves were working due to `GetTypeBasedMaxMove` looking up what the move would be if they Gigantamaxed.
The sign toggles Gmax factor
Fixes #4048.
Fixes #3936 

Fixed Gigantamax Factor not changing form

---

data/battle_scripts_1.s
include/battle.h
include/battle_scripts.h
include/constants/battle_string_ids.h
src/battle_message.c
src/battle_util.c

- Adds supersweet syrup effect, which is basically intimidate for evasiveness.
- Unifies dauntless shield, intrepid sword, supersweet syrup single-activation fields to single "abilityActivated" field (since can only have one ability)

Add supersweet syrup

---

include/global.h
src/battle_anim_ghost.c
src/battle_anim_mons.c

Fixes #4120
Flip Turn, Anchor Shot, and Snipe Shot were caused by the same division.
Incinerate was another one.
Note: I had to modify `SAFE_DIV` macro to bypass the compiler error. I've also submitted this as an additional PR for pret [here ](https://github.com/pret/pokeemerald/pull/1979)

Fix move animation crashing on some emulators because of division by zero

---

include/config/battle.h
src/battle_script_commands.c
src/battle_util.c
src/overworld.c

So, `VAR_TERRAIN` *(which I renamed to `B_VAR_TERRAIN` for consistency reasons)* allows to set up a "permanent" field terrain.
"Permanent" in the sense that it's not permanent at all because it can be overwritten just like the weathers can in Gen. 5 for example.
What I'm adding with this PR is a variable that can be used to set up a number of turns to keep field terrains active, which might be useful for ROM Hacking projects.
I decided to PR it because I think it's a good addition, feel free to shut it down if you disagree.
I also took the chance to fix syntax and alignment issues with Sky Battle configs and the function that resets a bunch of battle variables at the end of each battle.
lunos4026

Renamed VAR_TERRAIN to B_VAR_TERRAIN and added a var-based field terrain timer 

---

src/pokemon.c

In Scarlet and Violet, some previously tutor-exclusive moves became TMs which had the added effect of Mew being able to learn them. To reflect this, they've been removed from the Mew switch statement in CanLearnTeachableMove
Frankfurter0

Removed previously untutorable moves from Mew's unteachable moves

---

asm/macros/battle_script.inc
data/battle_scripts_1.s
src/battle_script_commands.c

Minor adjustments that do ~~two~~ three things:
- fix a bug caused by a comment (of all things) in `battle_scripts_1.s` causing the attackstring/charge animation/charge string sequence of two-turn moves to fall out of order (thanks to Alex for discovering that)
- made a separate, more easily modifiable function for checking conditions for a charge move to fire in one turn (thanks to Jasper/Bassoonian's comments)
- make macros/commands a little easier to understand
That's all, folks
The Cancer Fairy/thechurchofcage

Two turn moves tweaks

---

asm/macros/battle_script.inc
data/battle_scripts_2.s
src/battle_script_commands.c
src/item.c
test/battle/item_effect/cure_status.c
test/battle/item_effect/heal_and_cure_status.c

Fixes #4099
With tests.
Also, I modified the Full Restore's battlescript so it only prints 'healed HP' / 'healed Status' messages if they're actually cleared and not always(this was bugged before anyway, because it was printing the HP message twice).

Fix Full Restore / Antidote not reseting Toxic Counter

---

src/battle_util.c
test/battle/ability/stench.c

Pokemon would still be able to proc Stench even if they were flinched with Fake Out and their move didn't damage the opponent. Changed Stench to check if the target was damaged, instead of checking if a non-status move was used.
Broken Stench: 
#4158 
Fixed Stench:
https://github.com/rh-hideout/pokeemerald-expansion/assets/81360291/4c490027-2a35-4208-ae62-a2bde4871ee4
Fixes #4158 
hungry_pickle

Fixes Stench ability triggering on non-damaging attacks

---

src/battle_ai_util.c

as the title says. Replace unnecessary extra calls to AI_GetTypeEffectiveness so should save a few frames. Eventually can also replace all of the `move` args with AI_THINKING_STRUCT->moveConsidered

AI_CanStatus functions replace AI_GetMoveEffectiveness with AI_DATA->effectiveness

---

src/battle_script_commands.c
src/battle_util.c

Disguise wasn't registering `changedSpecies` for the original form, causing issues when the battle ended.
Before
After
Fixes #4131.
- Minior scenario described in the issue is vanilla behavior. While you catch Minior in its Meteor form, it stays in Core form outside of battle, becoming Meteor form once a new battle starts.
- Other non form change table form changes may be affected by this situation as well. For now, this PR only fixes Disguise, but I added comments to convert the form changes to the new table.

Fixed Disguise not ending the battle in the correct form

---

data/battle_anim_scripts.s
data/battle_scripts_1.s
data/battle_scripts_2.s

For whatever obscure reason, `battle_scripts_2.s` switched to using spaces rather than tabs at some point, unlike `battle_scripts_1.s` and the counterpart of both files in pret. This PR switches it back to tabs and also cleans up some whitespace issues in other files to be consistent.
bassoonian

Clean up space/tabs difference

---

src/battle_script_commands.c
src/battle_util.c

Applies the changes from #4091 to Supersweet Syrup, which was unaffected due to it not yet being on master.
Fixes #4162 
bassoonian

Analogously fix Supersweet Syrup interaction

---

include/constants/pokemon.h
src/script_pokemon_util.c

Closes #4186.
`ScriptGiveMonParameterized`, `ScriptGiveMon` and `ScrCmd_givemon` will now generate an ability for a Pokémon in the vanilla way when `NUM_ABILITY_VANILLA` is passed through their `abilityNum` parameter, that is, by defaulting to the 1st ability and then tweaking it based on the least relevant bit of the personality of the Pokémon they generate.
I also wrote the `if` statement that tries to generate a valid random ability at `ScriptGiveMonParameterized` differently due to popular demand.
lunos4026

Updated the way in which ScriptGiveMonParameterized and ScrCmd_givemon chooe a default ability

---

asm/macros/event.inc

Inspired by [this Discord message](https://discord.com/channels/419213663107416084/774393519569502268/1207220602029744138).
Lets us do things like:
```
@ VAR_RESULT is one of Treecko, Torchic, or Mudkip
randomelement SPECIES_TREECKO, SPECIES_TORCHIC, SPECIES_MUDKIP
@ Gives a random one of Treecko, Torchic, or Mudkip.
givemon VAR_RESULT, 5
```
```
@ VAR_RESULT is TRUE 25% of the time, and FALSE 75% of the time.
randompercentage 25
@ Gives a Wobbuffet that is shiny 25% of the time.
givemon SPECIES_WOBBUFFET, 20, isShiny=VAR_RESULT
```
The implementations of these could be improved if there was some way to do indirection, but they're not any worse than what a user would roll by hand.
I think `randomelement` in particular is something that gets asked for relatively often.

randompercentage and randomelement Script Commands

---

data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.inc
include/pokedex.h
src/pokedex.c
src/pokemon_size_record.c

Solves https://github.com/rh-hideout/pokeemerald-expansion/issues/4188
- Fixes Seedot and Lotad House to give measurements based on the unit system and decimal seperator chosen by the developer.
- Created `ConvertMonHeightToString` and `ConvertMonWeightToString` for developers to use
The scripts in the Lotad and Seedot house used to seperately convert a Seedot or Lotad's calculated size into inches (or presumably centimeters in non-imperial versions of the game.)
This logic has been removed and replaced with `ConvertMonHeightToString`, which was partially introduced in https://github.com/rh-hideout/pokeemerald-expansion/pull/4183. This means the NPCs will now output the same measurements as the Pokédex.
You can recreate this branch by applying a patch or pulling the repo. From a clean …

Fixes Seedot and Lotad House

---

src/pokemon_size_record.c

A typo that slipped in during Species Refactor work meant that GetMonSize was using weight rather than height.
bassoonian

Fix height call

---

src/battle_ai_main.c
src/battle_ai_util.c
src/data/moves_info.h

In PR #4036 ghoul recommended to use `GetBattlerSecondaryDamage` instead of `BattlerWillFaintFromWeather` in the function `IncreaseStatUpScore` which makes sense since the checks cover much more then just weather.
Also some minor corrections. First Impression needs an argument because checking for priority made no sense since both `first turn only moves` are priority moves. Also defense boosts are useless a lot of times, especially if they increase the stat only by one so I included a `AI_FLAG_STALL` check.

AI PR 4036 follow up

---

src/battle_interface.c
src/battle_main.c

In #4168 b7d7709 a memset was added but this causes the issue #4200. The sizeof was done on the variable instead of the struct. This caused other variables in EWRAM to loose their value. I have no idea if this fix breaks what was intented to do in #4168.
Also fixed the issue reported in my comment. When you run out of balls gLastThrownBall has a value, but you enter the if statement because you have no more balls. There the next in line ball is set to display but if there are non there is nothing to display. Afterwards when you get a new ball, you do not enter the if statement to update the gBallToDisplay because the ball is in the bag and gLastThrownBall is still set to not 0. Then it's checked if the bag has gBallToDisplay which does not point to a ball and therefor nothing is shown. …

Fixed LastUsedBall not being saved and DisplayBall not being shown

---

include/config/battle.h
include/data.h
src/battle_main.c
src/data/partner_parties.h
test/battle/trainer_control.c

Fixes #4123
Fixes #3641
Since the hardy nature is the default now the macro for natures is not needed anymore.

Sets neutral nature and ability 0 as default in trainer control

---

include/config/save.h
include/global.h

Also added new section to save config since the config now affect both SaveBlocks
Fixes #4177 

Added FREE_EXTRA_SEEN_FLAGS to Pokedex struct

---

src/main.c
src/random.c

Also adjust some comments.
Use timer 1 and timer 2 together for seeding during new games if `HQ_RANDOM` is enabled.
tertu

Use a 32 bit seed for new game seeding in HQ mode.

---

asm/macros/event.inc
data/scripts/debug.inc
src/debug.c
src/script_pokemon_util.c

So, earlier, we were kinda talking inside RHH's Discord server about how it'd be cool to provide examples of how to use the dynamic multichoice feature designed by @SBird1337 which was merged in #3826.
Josh asked why didn't we feature one such example as a part of the debug menu.
As soon as they said that, a light bulb went on in my head.
We have this not-very-convenient option to poison all the Pokémon in the party, yeah?
Why not turn it into something more useful with the power of ~~science~~ the dynamic multichoices?
Thus, I wrote a debug overworld script to inflict a non-volatile status ailment aka status1 at will.
I also added a choice for the scope of the feature while I was at it, which means you can now burn to a crisp that detestable Pikachu in your party without ever damaging …

Upgrading the debug menu's 'Poison Party'

---

src/script_pokemon_util.c

Fixes an oversight of mine from #3924.
The new `givemon` wasn't properly respecting the value of the `P_FLAG_FORCE_SHINY`, causing certain Pokémon such as the starters not to be generated as shinies even if said flag was set.
lunos4026

Made ScriptGiveMonParameterized recognize the state of P_FLAG_FORCE_SHINY and P_FLAG_FORCE_NO_SHINY

---

data/scripts/debug.inc
data/specials.inc
include/config/decap.h
include/config/level_caps.h
include/config/overworld.h
include/constants/global.h
include/level_caps.h
include/script_pokemon_util.h
src/berry.c
src/debug.c
src/pokemon.c
src/script_pokemon_util.c

#4274 #4230 already handle the rest of the things that I wanted to do.

Pre-1.8 tweaks

---

src/pokedex.c
src/pokedex_plus_hgss.c
src/pokemon.c

Fixed graphical issue when displaying a newly caught species different from the base form using the vanilla Pokédex.
Also corrects the cry played.
Fixes #4270 
It does not show other non-base form data besides footprint, sprite and cry, and that will require a bigger refactoring of the vanilla pokedex code.
This PR is meant to be just a temporary fix to the issue.

Fixed DisplayCaughtMonDexPage graphical issue + cry

---

include/battle_util.h
include/pokemon.h
src/battle_ai_main.c
src/battle_ai_util.c
src/battle_script_commands.c
src/battle_util.c

Reverted macros from PR #4096 
I think those specific macros made the code hard to read and we shouldn't make a simple loop more complicated then it should even if it's duplicating code.

Reverts additional move effect macros

---

src/script_pokemon_util.c

Fixes an issue where the nature of a Deoxys would be randomized even if one was set at the time of calling givemon or the functions related to it.
This was happening because when the code executed `ScriptGiveMonParameterized`, the conditions of the `if (OW_SYNCHRONIZE_NATURE >= GEN_6 && (gSpeciesInfo[species].eggGroups[0] == EGG_GROUP_NO_EGGS_DISCOVERED || OW_SYNCHRONIZE_NATURE == GEN_7))` statement were met, prompting the function to set a random nature.
#4263 
lunos4026

Updated OW_SYNCHRONIZE_NATURE statement in ScriptGiveMonParameterized

---

include/random.h
src/random.c

Adds a function `rng_value_t LocalRandomSeed(u32)` that returns a properly seeded `rng_value_t` regardless of `HQ_RANDOM` status. I realized this was missing. In LCG mode, it simply returns its argument, and in SFC32 mode it calls the internal SFC32 seed function and returns that.
tertu

Add LocalRandomSeed

---

include/config/overworld.h
src/pokemon.c
src/wild_encounter.c

Felt that these settings are a bit meaningless when we're applying them in a game that doesn't have Symbol encounters as the only way of encountering mon.

Removed Gen 9 settings for out-of-battle abilities

---

include/config/pokemon.h

Something we forgot to do on 1.8 release, as Terastalization is not done.

Disable Tera Type on summary screen by default

---

include/constants/battle.h
src/battle_script_commands.c

#3377 mentioned that the status was removed when it wasn't. This PR fixes that.

Actually remove unused STATUS3_CANT_SCORE_A_CRIT

---

CHANGELOG.md
docs/changelogs/0.9.0.md
docs/changelogs/1.0.0.md
docs/changelogs/1.1.0.md
docs/changelogs/1.1.1.md
docs/changelogs/1.2.0.md
docs/changelogs/1.3.0.md
docs/changelogs/1.4.0.md
docs/changelogs/1.4.1.md
docs/changelogs/1.4.2.md
docs/changelogs/1.4.3.md
docs/changelogs/1.5.0.md
docs/changelogs/1.5.1.md
docs/changelogs/1.5.2.md
docs/changelogs/1.5.3.md
docs/changelogs/1.6.0.md
docs/changelogs/1.6.1.md
docs/changelogs/1.7.0.md

Added all missing changelogs from pre-1.6.2 versions.
Also updated 1.7.0's changelog to better specify what tables were converted to what fields in `gSpeciesInfo`
Besides 1.7.0's changelog, I only updated the header to use the current instructions for pulling new versions.
If anyone wants to reorganize the changelogs to use the current categories, be my guest xD (though make sure to also update the GitHub releases pages.

Added pre-1.6.2 changelogs

---

src/pokemon.c

When implemented form tables were implemented, I had assumed that by changing the order of the forms in them (and therefore the "base form"), it would've been reflected in the Pokédex.
However, that was not the case, instead it was returning the first species that had the specific National Dex number (which was always the base form). This PR fixes that, so that you can do this to set the default species shown in the Pokédex:
```diff
static const u16 sRattataFormSpeciesIdTable[] = {
-   SPECIES_RATTATA,
SPECIES_RATTATA_ALOLAN,
+   SPECIES_RATTATA,
FORM_SPECIES_END,
};
```
Spirits Undead on Discord for letting me know about the issue.
I don't currently have thought on what to do about cases like Giratina, where `HOLD_EFFECT_GRISEOUS_ORB` checks for `SPECIES_GIRATINA` which is defined as …

Fixed unintended Pokédex form behavior

---

gflib/string_util.c

A loop in `ConvertInternationalString` after an intentional underflow by GF caused it to loop until the end of time. This affected Pokémon with Japanese language and Eggs, which have their language set to Japanese until they hatch.
Fixes #4300 
@DizzyEggg, who recommended to remove the casting entirely instead of upgrading it to `u32`.

Fixed Egg's summary screen softlock

---

src/level_caps.c

This fixes the logic in `GetSoftLevelCapExpValue()` so that it properly calculates the exp you should receive when you are below the level cap. Previously it would always calculate to zero if you:
- Had a soft or hard level cap configured
- And were below the level cap 
- And left `B_LEVEL_CAP_EXP_UP = FALSE`
- Receving zero exp when below the level cap when a level cap is configured with `B_LEVEL_CAP_EXP_UP = FALSE`
ravepossum

Fix Receiving Zero Exp When Below Level Cap

---

include/data.h
include/pokemon.h

A few structs surrounded used `field : bits;` rather than `field:bits;`. This PR brings them in line with the rest of the repo
bassoonian

Fix style of some bit definitions

---

src/battle_script_commands.c

The target's No Guard is handled from L1556.
N/A

Check for the correct battler's No Guard.

---

src/battle_pyramid.c

Fixes #4325
Fixes #3791
Credits:
Jasper for the base species check idea
ghoulslash for fixing the freeze

Random Pyramid Encounter fixes

---

include/config/battle.h
src/battle_script_commands.c
test/battle/move_effect/knock_off.c

In Gen 5+, Knock Off removes the item from the target altogether, as opposed to making it unusable. This updated behavior allows for Knocked Off targets to gain another item later in the battle. Otherwise, it is almost entirely aesthetic as other edge cases seem unaffected: Unburden seems to trigger from Knock Off in Gen 4 and Symbiosis never triggers after Knock Off.
This PR adds more tests for Knock Off's basic interactions, this updated behavior, and some other small edge cases.
**Gen 3 and 4:**
https://github.com/rh-hideout/pokeemerald-expansion/assets/103095241/02afedb3-6c3a-4694-ac75-9ad16b905769
**Gen 5+:**
https://github.com/rh-hideout/pokeemerald-expansion/assets/103095241/787e48ae-305b-4efe-a380-83ece229565e
Fixes #1903 (wow that's old)
Thanks @AlexOn1ine and @Bassoonian for …

Updated Knock Off

---

include/config/battle.h
src/battle_interface.c

In `MoveBattlerBar`, when `B_FAST_HP_DRAIN` is enabled, `hpFraction` gets the maximum amount of the relevant mon's HP and divides it by `B_HEALTHBAR_PIXELS`. After some [manual testing](https://docs.google.com/spreadsheets/d/1aIt5ybfxz-9kTux6mF178sr7KT7wHIgKq5am_wg8cNo/edit?usp=sharing) and conversations with @SonikkuA-DatH (who helped with the original implementation, [7ca07527faeb5d8f3c5aae355ecfd33a554acca6](https://github.com/PokemonSanFran/pokeemerald-expansion/commit/7ca07527faeb5d8f3c5aae355ecfd33a554acca6)), I've realized:
* `B_HEALTHBAR_PIXELS` should actually be divided by 2 here to provide a greater benefit to Pokémon of varying HP.
* The current implementation is slightly _slower_ for Pokémon with less HP, while the newly proposed one benefits all to a greater extent.
* Using …

Added B_FAST_EXP_GROW / Updated MoveBattleBar to use a more applicable denominator

---

src/pokemon.c

Original discussion: https://discord.com/channels/419213663107416084/774393519569502268/1220032007225217046
I don't feel strongly about how this is worded, but I think an explanation is a good idea. If this turns out to be a common / bigger issue, we can circle back.

Add explanation of STATIC_ASSERTS in pokemon.c

---

src/battle_util.c
test/battle/hold_effect/protective_pads.c

Fixes  #4034
This also probably fixes a couple other protective pad issues. (unseen fist + tough claws)

Fixes Protective Pads Fluffy interaction

---

data/battle_scripts_1.s

Fixes ability pop up config

---

src/battle_ai_switch_items.c
test/battle/ai.c

Bug discussed on discord.
Found by @Skolgrahd
Fix provided by @Pawkkie

Fixes switch in AI bug

---

src/battle_util.c

Tiny bugfix, removed leftover burn status code to prevent this interaction from happening.
duke5614 on discord

Fixes Guts countering frostbite's special move damage reduction

---

include/battle.h
include/metaprogram.h
include/test/battle.h
src/battle_dynamax.c
src/battle_script_commands.c

As the title suggests. Reopened because I closed the other one by mistake.
Took Monsieur Griffin's fancy recursive (or should I really say iterative) macro and replaced instances of `VARARG_8` with it. This allows for those macros to have an unlimited number of arguments rather than just 8. Also moved `CMD_ARGS` definition to `include/battle.h` as it was doubly-defined (I don't think the `battle_dynamax.c` version having `unused` should matter).
The Cancer Fairy/thechurchofcage

Replaces VARARG_8 uses with recursive macros

---

src/battle_ai_main.c
src/battle_ai_switch_items.c
src/battle_ai_util.c

Add Earth Eater AI code

---

src/battle_message.c

Fixes #3239 
Fix is courtesy of @MelonSpeedruns
bassoonian

Fix Trainer Slide message misbehaving

---

data/battle_scripts_1.s
include/battle_script_commands.h
include/config/battle.h
src/battle_script_commands.c
src/data/moves_info.h
test/battle/ability/disguise.c

Fixes #4032
Almost fixes 2966. A couple things are left to do (mainly things that should not overwrite disguise)

Disguise fixes + gen8 hp loss config

---

include/gba/types.h

If `gba/types.h` is included before `gba/defines.h`, it ends up declaring a variable named `PACKED` rather than specifying that `BgCnt` should be packed.
This occurs in `src/mini_printf.c`, and also apparently in a feature branch which is how this situation was detected (a multiple definition error at link time).
Erroneously raised as pret#1988.

Include gba/defines.h in gba/types.h

---

tools/trainerproc/main.c

Porygon2 was being interpreted as just Porygon, for example.
Fixes #4365 
Credit to @agsmgmaster64 for finding the issue and to @mrgriffin for the fix itself.

Fixed trainerproc skipping numbers when writing species IDs

---

Makefile
check_history.sh

Requires active confirmation to build the repository without a valid `git` repository or installed `git` software.
Prints a scary error when someone tries to build without a git repository in order to avoid a potential footgun of not being able to merge release updates or use feature branches.
@SBird1337 
karathan

feat: check if inside of git repository before building

---

include/config/overworld.h
src/overworld.c

Implements https://www.pokecommunity.com/threads/simple-modifications-directory.416647/page-17#post-10449889 with permission from Anon822.
| `TRUE` | `FALSE`|
| --- | --- |
| ![K5LJmti](https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/948761f1-22b1-4ffa-be2a-9b01cf699c8d) | ![Baj4HwZ](https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/68b8afd4-2cca-40f0-9bd0-d1396a42c3a6) |
Anon822
I am pkmnsnfrn.

Add OW_HIDE_REPEAT_MAP_POPUP config

---

src/script_pokemon_util.c
test/pokemon.c

Fixes #4262
With the PR moves are now filled with level up learnsets only if none are given at all.

Fixes givemon moves not defaulting to none

---

src/battle_util.c
test/battle/ability/forecast.c

**Before**: At end-of-turn, if a Pokémon with a weather-triggered form change is on the field, and the weather effects are suppressed by Cloud Nine or Air Lock, an infinite loop ensues in which the Pokémon continually swaps between its weather-specific form and its base form. This may depend on specifically which slots the battlers with weather suppression and form changes occupy. In my case, Cloud Nine Golduck was in slot `B_POSITION_PLAYER_LEFT` and Flower Gift Cherrim was in `B_POSITION_OPPONENT_RIGHT` during a Double Battle.
**After**: A simple check of `WEATHER_HAS_EFFECT` to prevent execution of the change back to the weather-specific form prevents the loop and resolves the issue.
Skolgrahd#6928

Fixed softlock w/ weather-triggered form changes & Cloud Nine

---

src/pokemon.c

The GiveBoxMonInitialMoveset_Fast function can generate pokemon that know the same move twice, if a pokemon has that move twice in its last 4 learnset slots.
It also produces different results from GiveBoxMonInitialMoveset in some niche cases and reverses the order of known moves.
Currently only used to fill the PC storage system with pokemon by the  debug menu.
duke5614

Rewrite GiveBoxMonInitialMoveset_Fast to match GiveBoxMonInitialMoveset results (but still faster)

---

src/battle_ai_util.c

Memento's effect was missing in `IsStatLoweringEffect` as pointed out by @AsparagusEduardo. So I added it here.

Include Memento effect in `IsStatLoweringEffect`

---

include/battle_util.h
src/battle_util.c
test/battle/hold_effect/ability_shield.c

Ability Shield should protect holder from Neutralizing Gas.
Bug found by @skolgrahd and fix provided by @AsparagusEduardo.

Fixes Ability Shield, Neutralizing Gas interaction

---

include/config/species_enabled.h
sound/cry_tables.inc

Fixes regression from #3562.
It also adds a warning to `include/config/species_enabled.h`, since for some reason using `1` and `0` instead of `TRUE` and `FALSE` causes cry ID's enum to not be properly updated.
https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/484fe57c-d891-408c-89e1-9d50006e4264
Fixes #4388 
Tried to update `include\constants\cries.h` to use `== TRUE`, but didn't work.

Fixed silent Klefki cry

---

src/pokedex_plus_hgss.c

Pokemon front pics and icons in Pokedex Plus display using a personality of 0, which is female for most species.
This PR changes it to use a male personality.
Also makes icons use the saved Unown/Spinda personalities.
Before: 
After:
Frillish and Jellicent icons using the wrong pallete
Unown Icon not matching its front pic
duke5614

Pokedex plus defaults to male icons and front pics

---

data/event_scripts.s
data/scripts/config.inc
data/scripts/debug.inc

Previous Pull Request:
https://github.com/rh-hideout/pokeemerald-expansion/pull/4286
This has been rebased for the master branch, and updated as per feedback
Tested and working on my system
Reordered Debug_EventScript_InflictStatus1 to within the 'DEBUG_OVERWORLD_MENU == TRUE' .if block, as it relies on 'Debug_NoPokemon' which is not defined outside of it.
[Discord Message](https://discord.com/channels/419213663107416084/1077168246555430962/1219230896075309097)
[MrGriffin, for suggesting the fix](https://discord.com/channels/419213663107416084/1077168246555430962/1219233509567365140)
AsparagusEduardo, for suggesting the second refractor to remove unused functions in release builds
sirscrubbington

[Rebase of #4286] Reordered Debug_EventScript_InflictStatus1 

---

tools/learnset_helpers/teachable.py

In some environments (not actually Windows as previously thought), or alternatively in some versions of Python, the teachable learnset helper would fail to work. This PR changes all regex strings to be considered raw by Python, so this should fix it (it fixed it for psf). Confirmed to work on my OSX environment, preferably tested by the reviewer also.
Fixes #4321 
Fixed thanks to a suggestion by @mrgriffin 
bassoonian

Fix teachable learnsets crashing in some environments

---

Makefile

I'm PR'ing this on behalf of @mrgriffin.
Me and RavePossum noticed that while trying to build a ROM or tests using the upcoming branch, the contents of our Windows installations' PATH variable were being printed on the terminal.
This PR fixes that.
lunos4026

Made competitive party syntax no longer print the contents of PATH

---

include/config/battle.h
src/battle_main.c
src/battle_util.c

A very meaningful PR which corrects the comment description of B_RESTORE_HELD_BATTLE_ITEMS and also updates it to remain consistent with the rest of the configs which all use a comma inbetween the origin game and the explanation.
As a result of reviews and conversations, this has now been turned into a non-boolean config. Can't say I'm on board, but I also don't care enough.
lunos4026

Turned B_RESTORE_HELD_BATTLE_ITEMS into a non-boolean config

---

test/test_runner_battle.c

[See Discord for context](<https://discord.com/channels/419213663107416084/1077009799293710357/1230460946476957737>). The error messages for `EXPECT_MOVE` and `EXPECT_SWITCH` are backwards, saying, e.g. `Expected MOVE, got SWITCH` when it should say `Expected SWITCH, got MOVE`.

Fix AI test error messages

---

include/constants/battle_ai.h
src/battle_ai_main.c
src/battle_ai_switch_items.c

AI_FLAG_SMART_SWITCHING also sets AI_FLAG_SMART_MON_CHOICES automatically for greatly improved switching behavior.
Through doing this I accidentally discovered that AI_FLAG_SMART_MON_CHOICES may cause softlocks in double battles thus this PR disables it for double battles for now.
When used on its own AI_FLAG_SMART_SWITCHING causes the AI to perform extremely questionable switches as it doesn't know which Pokemon effectively counters the enemy, arguably making it dumber instead of smarter.
Combined with AI_FLAG_SMART_MON_CHOICES it produces very satisfying and logical results, but simply merging them into one is not necessarily desirable as AI_FLAG_SMART_MON_CHOICES works perfectly on its own to make enemies switch into favorable matchups after a faint.
Smart mon choices cause the AI to …

Combine AI smart switching with smart mon choices automatically and disable smart mon choices in double battles.

---

INSTALL.md

`pkg-config` has recently become a dependency in order to build on macOS (not sure when this started or if this is only with modern, but installing it resolves issues with `libpng` not being found during the build process).
zsh has also been the default shell since macOS 10.15, so I updated the instructions to use that, with an additional note for users who might still be using bash.
te_on

Update outdated macOS instructions in INSTALL.md

---

include/battle.h
src/battle_script_commands.c
src/battle_util.c
test/battle/ability/poison_puppeteer.c

Adds Ability Poison Puppeteer

---

data/battle_scripts_1.s
test/battle/ability/intimidate.c
test/battle/ability/supersweet_syrup.c

When attack or evasion can't be further reduced by these abilities, it now prints "Pokemon's stat won't go lower!"
Tests by @AlexOn1ine 
Fixes #4401
duke5614

Intimidate and Super Sweet Sugar prints the right message and doesn't play animation when already at -6

---

src/pokedex_plus_hgss.c

Changed PokemonStats.expYield to u16 so that pokedex plus works with the expansion's updated experience yield feature.
Wrong display of experience yield in pokedex plus due to overflow
duke5614

Pokedex plus expYield matches SpeciesInfo type

---

test/battle/trainer_control.h

This gets added whenever `trainerproc` runs, due to #4431, so I'm committing it to stop it showing up in some random PR in the future.

Add missing shouldDynamax

---

src/pokedex_plus_hgss.c

The u8 to u16 change misaligned the struct members. This fixes that

Realign struct in HGSS Pokedex

---

include/battle_gfx_sfx_util.h
src/battle_anim_effects_1.c
src/battle_gfx_sfx_util.c

- Ally Switch handles elevation shadows
- Ally switch fix direction of animation for opponents
- Also add some safety checks into shadow sprite id
Before:
After:

Ally Switch Handle Shadows, Fix Opponent Anim

---

src/battle_interface.c

Hard to describe, if two ability popus happen on the same battle step and the second one has a short ability name the popup displays some leftover text.
Before:
https://github.com/rh-hideout/pokeemerald-expansion/assets/56992013/d67c0325-acd8-41dc-844f-d7c630e7cb3a
After:
https://github.com/rh-hideout/pokeemerald-expansion/assets/56992013/a16e90c0-3747-4322-9c3a-a7e7a5f105aa
duke5614

Fix lingering long ability popup names

---

data/battle_scripts_1.s
include/battle_scripts.h
src/battle_script_commands.c
test/battle/move_effect/stealth_rock.c

Fixes Eject Items causing gBattlerFainted to take entry hazard damage instead of the pokemon switching in, since SetDmgHazardsBattlescript did not account for calls with BS_SCRIPTING. This PR handles that.
Fixes #4457
PhallenTree

Fixes Eject Items causing wrong pokemon to take damage from entry hazards

---

src/battle_main.c

Fix HANDLE_EXPANDED_TYPE_NAMES producing errors when setting B_EXPANDED_TYPE_NAMES to FALSE
Modified the macro arguments
MGriffin on discord
Nopinou#8678

fix non expanded types names macro

---

data/battle_scripts_1.s
test/battle/ability/color_change.c

Fixed an issue where Color Change wouldn't trigger on foreseen attacks (Future Sight, Doom Desire) and wrote tests for Color Change.
Added `moveendcase MOVEEND_ABILITIES` to the foreseen move script.
Wrote tests for most things that can be relevant for how Color Change works.
Fixes #3523 
Fix provided by [AlexOn1ine](https://github.com/AlexOn1ine)
hedara#5073

Color change fixes

---

src/battle_ai_util.c

Added a case in `IsDamageMoveUsable` to see if any terrain is up. If not, the function returns `TRUE`, so the AI should realize that Steel Roller (and moves with the same effect) will not succeed.
Additionally, `IsDamageMoveUsable` was renamed to `IsDamageMoveUnusable` to better reflect the returned boolean value.
Alex, for pointing out where the missing check was.
Special K#8400

Update IsDamageMoveUsable to check for Steel Roller viability

---

src/battle_terastal.c

The default behavior on `upcoming` allows for Terastallization from the get-go, which is hopefully the last slip-up as that wasn't intended behavior. The expansion user should be required to set `B_FLAG_TERA_ORB_CHARGED` so that the player requires not just the Tera Orb item but a "charged" Tera Orb.

CanTerastallize Adjustments

---

src/data/moves_info.h

Fixes a typo in the description of Mortal Spin and Diamond Storm having no effect.
PhallenTree

Fixes Diamond Storm and Mortal Spin's description

---

src/data/moves_info.h

Fixes Assist calling MOVE_NONE. This would happen if there is a pokemon on the party that doesn't have a full moveset.
The original result of calling MOVE_NONE is shown in the video below (note that Phantom Force is banned by Assist).
https://github.com/rh-hideout/pokeemerald-expansion/assets/168426989/849618c5-7d48-4ff0-b37a-20278acd0a94
PhallenTree

Fixes Assist calling MOVE_NONE

---

src/battle_main.c
test/battle/hold_effect/red_card.c

Fixes bug where Red Card would trigger on the newly switched in mon if an endured and damaged mon was forced to switch out.

Fix Red Card, Endured Damage interaction

---

src/battle_script_commands.c

Issue: 
In case of EVO_LEVEL_MOVE_TWENTY_TIMES, the evolution tracker currently gets updated regardless of which move is used.
In case of EVO_LEVEL_RECOIL_DAMAGE_MALE/EVO_LEVEL_RECOIL_DAMAGE_FEMALE, the tracker gets updated with twice the amount intended, if a mon has both evolution methods (which Basculin does) due to calling the function twice.
Fix:
EVO_LEVEL_MOVE_TWENTY_TIMES evolution tracker only gets updated if param contains the used move.
EVO_LEVEL_RECOIL_DAMAGE_MALE/EVO_LEVEL_RECOIL_DAMAGE_FEMALE gets called only once depending on the mons gender
.cawt

Fixed evolution tracker updates

---

README.md

This allows programs like emacs to open the proper file when clicking them.  Previously doing so would lead to a different (probably nonexistant) file because they would be interpreted as relative to the filesystem root instead of being relative to the current directory.
Absolute filepaths only work on GitHub because GitHub-flavored markdown does some non-standard magic with them specifically, instead of following the relative URL specification.
Comb through any other markdown files in the repo to update them accordingly.

Make filepath links in readme relative

---

test/battle/ability/beads_of_ruin.c
test/battle/ability/costar.c
test/battle/ability/supreme_overlord.c
test/battle/ability/sword_of_ruin.c
test/battle/ability/tablets_of_ruin.c
test/battle/ability/vessel_of_ruin.c
test/battle/ability/zero_to_hero.c

#4500 fixed messaging certain abilities, but tests weren't added to complement this.
Confirmed that the test fails without the fix for the Ruin abilities and Zero to Hero, but I couldn't make Supreme Overlord trigger when using explosion, so I marked them as `KNOWN_FAILING`.
Costar didn't have a test, so for now I decided to leave it as a TODO test.

Add tests to complement PR 4500

---

src/pokedex.c
src/pokedex_plus_hgss.c

Undoes the accidental removal of the fairy type as a Pokedex search option caused by #4513
duke5614

Restore Pokedex Fairy type search option

---

src/battle_script_commands.c
src/level_caps.c
src/pokemon.c

Fixed an absurd amount of experience points being gained.
Changed the checks order in GetSoftLevelCapExpValue for better clarity.
Fixed parts where EXP_CAP_HARD settings were not properly checked (should have been B_EXP_CAP_TYPE == EXP_CAP_HARD).
Fixed wrong assignment of gBattleMoveDamage to a gExperienceTables value (see picture below).
None opened
Duke on discord
Nopinou#8678

fix and tweak level cap code

---

src/battle_ai_main.c

AI was discouraged from using fixed damage, ohko, counter and other similar move effects based on the type effectiveness table.
For example, it didn't want to use seismic toss on Crobat.
duke5614

AI ignores resistances that don't actually apply when checking for bad moves

---

src/script_menu.c

Dynamic Multichoice no longer plays SE_SELECT right after being created, matching the behavior of `multichoice` .
duke5416

Dynamic Multichoice no longer plays sound on init

---

src/battle_script_commands.c

Removes duplicate outdated checks that didn't account for B_TRAINER_KNOCK_OFF_ITEMS for Thief and Covet that made it so these couldn't steal items if used by an opposing Trainer.
Fixes #4469 
PhallenTree

Fixes Thief and Covet used by an opponent not stealing items

---

src/battle_terastal.c

Checks if the Safari Zone flag is set to avoid making part of the battle UI invisible.
Before fix:
After fix:
This is Jasper's fix, I'm just making the PR.
Special K#8400

Prevents Terastallization UI from making part of the Safari Zone battle UI invisible

---

src/pokemon.c

Issue: If compiled with agbcc ```evoTracker.asField.unused``` is not initialized(?) and ``` evoTracker.value ``` reads 7 bits of garbage.
Solution: Initialize ``` evoTracker.asField.unused``` with 0
before-after comparison:
asField.a (5 bit) -> 0 or 00000 in binary
asField.b (4 bit) -> 0 or 0000 in binary
asField.unused -> 41 or 101001
value -> 20992 or   101001 | 0000 | 00000 (unused | b | a) in binary
.cawt

Fix GetBoxMonData for evolution tracker if compiled with agbcc

---

data/battle_scripts_1.s
test/battle/move_effect/belly_drum.c
test/battle/move_effect/fillet_away.c
test/battle/move_effect/shed_tail.c
test/battle/move_effect/substitute.c

Marked the damage taken from using those moves as "passive damage" so that they don't trigger on-hit effects.
Added `HITMARKER_PASSIVE_DAMAGE` to moves that costs HP to use and erroneously triggered on-hit effects. Substitute, Belly Drum, Fillet Away and Shed Tail were the moves exhibited this behavior.
Wrote tests to check if said moves trigger on-hit effects.
Fixes #4527 
hedara

Fixed moves with HP cost triggering effects where they shouldn't

---

src/berry.c

Applies the fix from #4510 to tree mutations, which work the same way
bassoonian

Fix possible agbcc corruption for tree mutations

---

src/battle_main.c

specialTrainerBattleType gets reset in ClearSetBScriptingStruct, which is needed for DoSpecialTrainerBattle/HandleSpecialTrainerBattleEnd

fix battle script clearing specialBattleType

---

src/battle_util.c
test/battle/move_effect/future_sight.c

Fixes #4542
Fixes freeze/weird behavior if a mon was killed by residual damage while a future sight attack attempted to strike.

Fixes Future Sight freeze/weird behavior

---

src/data/items.h

The first line of the Dubious Disc description was too long. A few letters would escape the box in the Bag and in Marts. This brings them in line.
Additionally, when the Freeze Status is replaced with Frostbite, the descriptions of the Ice Beam and Blizzard TMs are too long, so I altered those as well.
Dubious Disc Post-fix:
Should've taken a screenshot before the fix, but with "transparent" instead of "clear," the last "e" in "device" was well into the scroll menu.
Blizzard TM Pre-fix:
Blizzard TM Post-fix:
Special K#8400

Changed item descriptions to prevent text overflowing into scroll menus

---

src/data/pokemon/species_info/gen_1_families.h

Since Gen 6, Mr. Mime has been a Psychic/Fairy type. Mime Jr already has the correct typing so it's probably an oversight.
PhallenTree

Fix Mr. Mime's typing

---

data/battle_scripts_1.s
src/battle_script_commands.c

Fixes Copycat being able to call Z-Moves (should fail) and fixes Copycat-called 2 turn moves (like Fly, Ice Burn, ...) having the second turn's animation play on both turns.
Fixes #4490 
PhallenTree

Fixes Copycat issues with Z-Moves and 2 turn moves

---

sound/cry_tables.inc

This PR fixes Oricorio Pom-Pom silent cry.
It does the same thing as https://github.com/rh-hideout/pokeemerald-expansion/pull/4392 but with this guy.
https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/75f63388-236b-490c-9fb1-91dd24395647
https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/8c673577-1450-4f48-94a4-561c69779a6b

Fix silent Oricorio Pom-Pom cry

---

data/battle_scripts_1.s
src/battle_script_commands.c
src/battle_util.c
test/battle/ability/shield_dust.c
test/battle/item_effect/covert_cloak.c
test/battle/move_effect/knock_off.c
test/battle/move_effect/salt_cure.c
test/battle/move_effect/smack_down.c
test/battle/move_effect/smelling_salts.c
test/battle/move_effect/sparkling_aria.c
test/battle/move_effect/thousand_arrows.c
test/battle/move_effect/wake_up_slap.c

Fixed the effect of Knock Off, Salt Cure, Smack Down, Thousand Arrows, Wake-Up Slap and Smelling Salts not getting blocked by Substitutes where they should.
Fixed Sparkling Aria interaction with Shield Dust in Singles vs Doubles.
Fixed Wake-Up Slap and Smelling Salts getting boosted damage where they shouldn't vs Substitutes.
Encapsulated the calls to the effects of Knock Off, Salt Cure, Smack Down, Thousand Arrows, Wake-Up Slap and Smelling Salts in  `if (!DoesSubstituteBlockMove(...))` to check if they hit a Substitute or not.
Wrote a check for Sparkling Aria vs Shield Dust/Covert Cloak to implement the interaction where in doubles it can cure burns of supposedly protected Pokemon if Sparkling Aria hits more targets than the Shield Dust user. The check counts the number of Pokemon with …

Fixed some moves' on-hit effects bypassing Substitutes where they shouldn't and some other things discovered along the way

---

src/battle_ai_switch_items.c

Fixed various AI calculations where:
- Weather based healing was treated as damage
- Damage and healing from multiple sources overwrote each other
- Utility umbrella and magic guard were ignored.
- Max G-Steelsurge was ignored.
- Sitrus berry's Gen 4+ effect was ignored.
Replaced some checks where an item was used directly instead of its hold effect.
duke5614

Various AI switching logic fixes

---

src/battle_script_commands.c

The ability Parental Bond should not affect multi-hit moves in any way. To give an example (in fact, the only example that exists under normal conditions), Mega-Kangaskhan can have the move Comet Punch. Comet Punch has `.effect = EFFECT_MULTI_HIT` and can hit from 2-5 times. Mega-Kangaskhan's ability, Parental Bond, should be ignored for this move, but it currently is not. 
So let's say Parental Bond is configured to have the 2nd hit do 25% damage. The behavior that is currently seen is that Comet Punch will hit once for normal damage, then a 2nd time 25 % damage as Parental Bond's 2nd hit, then Comet Punch will end. It can only hit a maximum of twice, with the 2nd hit only hitting for 25% (or 50% depending on configuration) damage. 
While this is the only interaction that occurs in the …

Adds a check for EFFECT_MULTI_HIT moves in IsMoveAffectedByParentalBond

---

src/battle_anim_sound_tasks.c

Currently if a Pokemon is disguised by Illusion and uses a move that plays a cry, it will always play the cry of the Pokemon with the ability instead of using the Pokemon it appears as (this makes it a lot more obvious that it's an Illusion).
I also made the method of obtaining the species to use for the cry consistent.
Before the fix:
https://github.com/rh-hideout/pokeemerald-expansion/assets/168426989/c36e0b50-4f75-4c52-bf69-bcf63a75e693
After the fix:
https://github.com/rh-hideout/pokeemerald-expansion/assets/168426989/b1bd8ef6-9eea-4669-b967-7afdcb02319a
PhallenTree

Fixes cries in move animations ignoring Illusion

---

data/battle_anim_scripts.s

Fixes incorrect usage of `ANIM_PLAYER_LEFT` and `ANIM_PLAYER_RIGHT` in some places.
Fixes `AnimTask_HorizontalShake` visual task being used with too many arguments.
Made sunsteel strike shake the attacker's partner for a slightly shorter time.
https://github.com/rh-hideout/pokeemerald-expansion/assets/56992013/b29498e0-7b74-41f4-b712-435e5d5c6d41
duke5614

Fix a few move animations

---

data/battle_scripts_1.s
test/battle/ability/magic_guard.c
test/battle/move_effect/max_hp_50_recoil.c
test/battle/move_effect/mind_blown.c

Pokemon with Magic Guard shouldn't take damage from recoil from moves like Double-edge. I think the only normal in game situation where this can occur is Clefable with Magic Guard getting access to the move Double-edge. In that case, Clefable should not take damage from recoil. 
I didn't see a set of tests that exists where something like this should be added. Didn't see any tests for Rock Head or Magic Guard, and the tests in the recoil.c file don't look to account for abilities such as these.
Before fix:
After fix:
^ sorry it's not Clefable but this Delphox has magic guard and I gave it double-edge so i think it will do
iriv24

Add check for Magic Guard to avoid taking recoil damage
