src/battle_ai_switch_items.c
AI now calculates damage from the badly poisoned status.
AI now removes weather damage from current AI instead of adding it.
Removed some unnecessary calculations added in #4571 that reduced weather damage to 0.
duke5614
=>  Various AI switching logic fixes Part 2

test/battle/move_effect/absorb.c, test/battle/move_effect/accuracy_down.c, test/battle/move_effect/accuracy_down_2.c, test/battle/move_effect/accuracy_up.c, test/battle/move_effect/accuracy_up_2.c, test/battle/move_effect/acrobatics.c, test/battle/move_effect/acupressure.c, test/battle/move_effect/after_you.c, test/battle/move_effect/ally_switch.c, test/battle/move_effect/aqua_ring.c, test/battle/move_effect/aromatic_mist.c, test/battle/move_effect/assist.c, test/battle/move_effect/assurance.c, test/battle/move_effect/attack_accuracy_up.c, test/battle/move_effect/attack_down_2.c, test/battle/move_effect/attack_spatk_up.c, test/battle/move_effect/attack_up_2.c, test/battle/move_effect/attack_up_user_ally.c, test/battle/move_effect/attract.c, test/battle/move_effect/aura_wheel.c, test/battle/move_effect/autotomize.c
First part of a long-term goal of adding all missing TODO tests to the repository.
Also:
- Split Acupressure + Ally Switch test into 2 separate tests to account for #4565.
- Added tests for: `EFFECT_ATTACK_DOWN_2`, `EFFECT_ATTACK_SPATK_UP` and `EFFECT_ATTACK_UP_2` based on existing tests.
- Adjsuted test names for `EFFECT_ACCURACY_DOWN`, `EFFECT_ATTACK_DOWN`, `EFFECT_ATTACK_UP` and `EFFECT_ATTACK_UP_USER_ALLY`.
The plan is just to mainly just add TODO tests, so that they can eventually be filled properly.
=> Added missing Move Effect TODO tests - Volume A

include/config/overworld.h, src/pokemon_storage_system.c
Adds a config that makes released mons put their held item in the bag first, as is the case in Gen8+
Fixes #3703 
If the bag is full, the item is still lost. Need to check in Gen8+ what happens if you eg release a mon holding a Poké Ball with maxed out Poké Balls in the bag
bassoonian
=> Add on release item config

src/battle_ai_util.c
Fixes call to SetBattlerData in `AI_CalcPartyMonDamage` needing the `saved` flag set. Temporarily set and then cleared afterwards
=> AI_CalcPartyMonDamage set saved flag for SetBattlerData

src/pokemon_storage_system.c
I noticed the name of some held items on pokemon in the PC switched to using the shorter font, when the item name is the same as vanilla (not expanded). This fixes that by making the width it checks the same as the pokemon species name, as its more than enough to fit within the box, and it was really limiting before.
(Mystic Water is a vanilla name and is not expanded)
Before:
After:
kittenchilly
=> Fix held item names in the PC sometimes using the shorter font when unnecessary

include/config.h, src/pokedex_plus_hgss.c
#4512
https://github.com/rh-hideout/pokeemerald-expansion/assets/56992013/043fab55-b268-4bd8-9fab-5eb390225ba4
duke5614
=> Pokedex Plus fixes

include/config/save.h
I've disabled the Pokenav / match call behaviour because I use psf's Jaizu's VS Seeker, so when I got the save control defines merged I figured awesome more save space I can turn this off, I'm not using match call. This is the description next to that define:
```
#define FREE_MATCH_CALL                     FALSE   // Frees up match call and rematch data
```
It became apparent after the VS Seeker broke that this is needed for that also. I brought this up in Discord and psf suggested I PR a clarification to the comment. I've changed it to:
```
#define FREE_MATCH_CALL                     FALSE   // Frees up match call and rematch data. Still needed to use the VS Seeker even if the Pokénav's "Match Call" isn't being used (104 bytes).
```
I'm a fan of detailed clarity above brevity where …
=> Adjust description of FREE_MATCH_CALL

data/battle_scripts_1.s, test/battle/move_effect/explosion.c
Fixes #4599
I couldn't find the PR that added `trytofaintmon` to all absorbing ability scripts (vanilla emerald doesn't have those) but judging by the comments in #1961 it was added to fix an explosion interaction. With #4516 this is not needed anymore and causes a bug instead.
=> Fixes freeze on Galvanize Explosion against Volt Absorb

include/config/battle.h, src/battle_util.c
In Generation 5 onward, Thief and Covet no longer _permanently_ steal items from trainers. From Bulbapedia:
> Covet no longer steals a Trainer's Pokémon's items permanently; however, a wild Pokémon's item is still permanently stolen by the player. 
> Thief no longer steals a Trainer's Pokémon's items permanently; however, a wild Pokémon's item is still permanently stolen by the player. 
However, as it currently stands, this updated behavior was not implemented. As such, this PR implements the following:
- The addition of a variable `B_RETURN_STOLEN_NPC_ITEMS` in `battle.h` that rudimentarily handles generation-based logic for Thief/Covet against NPCs;
- A refactor of the `TryRestoreHeldItem` function that includes the above variable. Individuals can now choose whether or not trainer NPCs …
=> Add configuration to prevent permanent item theft (Covet / Thief) from NPCs

src/battle_util.c
No change in logic, just allows users to create quadruple kick or something without having to add a new effect.
duke5614
=> EFFECT_TRIPLE_KICK calcs uses the move's strikeCount instead of a constant

docs/changelogs/1.8.x/1.8.0.md, docs/changelogs/1.8.x/1.8.3.md, include/constants/pokemon.h, src/battle_script_commands.c, src/data/pokemon/species_info/gen_1_families.h, src/data/pokemon/species_info/gen_2_families.h, src/data/pokemon/species_info/gen_5_families.h, src/data/pokemon/species_info/gen_9_families.h, src/pokedex_plus_hgss.c, src/pokemon.c
The reason for this change is that we usually don't name evolution methods with a `LEVEL` prefix unless it evolves with an explicit level.
Renames:
```
EVO_LEVEL_MOVE_TWENTY_TIMES -> EVO_USE_MOVE_TWENTY_TIMES
EVO_USE_MOVE_TWENTY_TIMES -> EVO_RECOIL_DAMAGE_MALE
EVO_RECOIL_DAMAGE_MALE -> EVO_RECOIL_DAMAGE_FEMALE
```
=> Renames evolution methods the were labeled as evo level

data/battle_scripts_1.s, src/battle_script_commands.c, test/battle/ability/own_tempo.c
This was caused due to those checks being done when canceling stat drops.
Inner Focus, Scrappy, Own Tempo, and Oblivious specifically only target the Intimidate ability itself and not the attack stat drop.
Because of that, I thought it'd make sense to fix this by moving the checks to Intimidate's script, much like how Guard Dog is done since that also specifically targets the Intimidate ability.
Fixes #4602
kittenchilly
=> Fix Inner Focus, Scrappy, etc granting immunity to all stat drops if the attacker has Intimidate

src/data/moves_info.h
Fixes the descriptions for Feint and Feint Attack.
Feint utilized a custom description, despite intention to share a description with Mighty Cleave. Feint Attack also had the wrong description. The description in this PR is taken from [`pokeemerald`](https://github.com/pret/pokeemerald/blob/18f84b78f2d1a8669753fa586836fca06036c790/src/data/text/move_descriptions.h#L740).
@lhea
=> Fix move descriptions for Feint and Feint Attack

src/battle_main.c, test/battle/ability/mycelium_might.c, test/battle/hold_effect/quick_claw.c
Fixed Quick Draw always outspeeding Quick Claw and Custap Berry.
Fixed Myceleum Might always outspeeding Stall.
Also corrected the name of a test.
duke5614
=> Speed Ignoring effect fixes

src/pokedex_plus_hgss.c
Previously it read garbage. This also covers for `EGG_GROUP_NONE`/unset Egg Groups.
Also, did some alignment cleanup
Before vs after:
(*juuust* enough space to have the 2 longest egg group names)
=> Added failsafe in HGSS dex for Egg Groups without text defined

include/battle_util.h, src/battle_ai_util.c, src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/belch.c, test/battle/move_effect/stuff_cheeks.c
@Kasen discovered today that Belch was being considered an invalid option (score and damage of 0) by the AI even after it had eaten a berry. While exploring the issue I discovered that the check used to determine whether a berry has been eaten was completely different in `IsDamageMoveUnusable` and `IsBelchPreventingMove`, with the latter implementation being significantly older. I updated it to match the newer implementation, and it fixed the issue.
I wrote a test that builds a situation in which the AI should use Belch, which fails on current master but passes with this PR. I also moved the only other Belch test I could find into its own file with this one as there are now two Belch tests, though one relates to the AI and the other was in with Stuff Cheeks so if you'd like a different …
=> Belch AI Scoring Fix

data/battle_scripts_1.s, include/battle_scripts.h, src/battle_script_commands.c, test/battle/ability/shield_dust.c, test/battle/item_effect/covert_cloak.c
#4558 introduced a rough version of Sparkling Aria + Shield Dust edge case, but it was just preventing messages and icons from playing and updating, meaning that tests were being masked into passing.
Reverting this change showed that Covert Cloak/Shield Dust also wasn't protecting from Sparkling Aria even in singles, so all of them have been marked as `KNOWN_FAILING`.
Also, added failsafes in case `MOVE_EFFECT_REMOVE_STATUS` is used with other Status1
=> Reverted bad implementation of Sparkling Aria+Covert Cloak/Shield Dust

src/battle_script_commands.c, src/battle_util.c, test/battle/ability/dancer.c
Fixes Dancer triggering if the original user of the move flinched, was paralyzed or frozen. Added tests for this and for checking if the order of Dancer triggering is correct (slowest to fastest).
Fixes #4495 
I'm not sure if Dancer still triggers every time it should, specifically if there are cases where it should trigger but gHitmarker doesn't include HITMARKER_ATTACKSTRING_PRINTED
PhallenTree
=> Fixes Dancer triggering if the move's user didn't act

docs/changelogs/1.8.x/1.8.0.md, docs/changelogs/1.8.x/1.8.3.md
#4607 accidentally modified the changelogs upon renaming the evolution methods. This PR fixes it
=> Restore changelog search-replace

test/battle/ability/armor_tail.c, test/battle/ability/queenly_majesty.c
PR #4635 combined Dazzling type tests. This PR adds empty test files with a comment referring to the `dazzling.c` file.
=> #4635 follow up. Missing test comments

include/battle_ai_main.h, include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_util.c, src/battle_main.c, test/battle/ai_flag_risky.c
#4615 added the ability to choose what damage rolls the AI uses when scoring its moves, which introduced the concept of having the pre-existing AI_FLAG_RISKY assume it gets high rolls and score accordingly. This prompted discussing a minor overhaul to AI_FLAG_RISKY, which is otherwise just a simple list of effects that the AI will score more highly. 
After that initial discussion, we decided that a fun risky AI would:
- **Prioritize maximizing damage from moves at the cost of accuracy** (I'm interpreting this as "When comparing damaging moves, the AI only considers accuracy if expected damage is the same (ie. multiple neutral attacks with the same power), even if hits to KO are the same (if the player switches the AI still wants to do the biggest chunk of damage it can)")
- **Prioritize …
=> AI_FLAG_RISKY Improvements

include/battle_ai_main.h, src/battle_ai_main.c
I've added Temporarily scores in #3984 but since then I've realized that they are convoluted for no reason. This PR reverts that part and adjusts the scores accordingly.
=> Remove temp scores in AI_CalcMoveEffectScores

src/battle_util.c
Moved this label to prevent `IsBattlerWeatherAffected(battler, B_WEATHER_SUN)` from being checked twice in a row by Dry Skin code.
duke5614
=> Move SOLAR_POWER_HP_DROP label

include/battle_ai_util.h, include/battle_util.h, src/battle_ai_util.c, src/battle_util.c
=> Add global constants for damage roll related code and make AverageRollDmg faster

gflib/malloc.c, include/test/test.h, src/battle_ai_main.c, test/test_runner.c, test/test_runner_battle.c
See title
Fixes #4222 
bassoonian
=> Rename MgbaPrintf_ to Test_MgbaPrintf

src/battle_main.c
Updates `FaintClearSetData` in `battle_main.c` to clear Dynamax data when a battler faints.
Fixes #4484 
Special K#8400
=> Clear Dynamax data when a battler faints 

src/battle_dynamax.c, src/battle_main.c
In `FaintClearSetData` in `battle_main.c`, calls `UndoDynamax` whenever a mon faints to ensure that its HP is reverted and the relevant data is cleared. Updates `UndoDynamax` in `battle_dynamax.c` to `CalculateMonStats` after applying the HP reversion to prevent fainted mons from retaining their boosted Max HP until the end of the battle.
Fixes #4484 
Special K#8400
=> Revert Dynamax HP on fainting

src/battle_ai_util.c
Add a check for held item before using poltergeist and a check that it is actually the first turn for moves that are first turn only
@AlexOn1ine 
iriv24
=> Add Checks for Poltergeist and FirstTurnOnly Moves to IsDamageMoveUnusable

data/battle_scripts_1.s
Removes an incorrect check for Guard Dog when using U-Turn, Volt Switch. Adds the intended check to Dragon Tail, Circle Throw.
PhallenTree
=> Moves activation of Guard Dog from HitEscape to HitSwitchTarget

src/daycare.c, src/egg_hatch.c
Regional variants according to https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_breeding#Regional_forms and https://bulbapedia.bulbagarden.net/wiki/Everstone#Regional_forms
Pokeball inheritance was mostly implemented, but never set for the hatched mon.
.cawt
=> Fixed regional variant inheritance and pokeball inheritance

include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c
changes `AverageDmg` to see the 9th roll by default
=> Use 9th roll instead of average in AI calcs

src/battle_script_commands.c, src/battle_util.c
Fixes Hyper cutter stopping MOVE_EFFECT_ATK_MINUS_1 and MOVE_EFFECT_ATK_MINUS_2.
Fixes Big Pecks stopping MOVE_EFFECT_DEF_MINUS_1 and MOVE_EFFECT_DEF_MINUS_2.
Fixes Keen Eye and Illuminate stopping MOVE_EFFECT_ACC_MINUS_1 and MOVE_EFFECT_ACC_MINUS_2.
Note that none of these effects are currently used with `.self = TRUE`.
duke5614
=> Fix some abilities preventing stat dropping move effects when used on self

src/item_use.c
Using honey corrupted(?) some tiles at the top of the screen.
Before:  
After:  
.cawt
=> Fixed honey use altering tiles

src/item_use.c
Same issue as in #4703. Using RemovedUsedItem with a field effect item potentially leads to undefined behaviour. This does seem to be the case in vanilla Emerald/FRLG, so maybe there is some background magic that I'm not aware of. From what I can see though this should also be an issue with escape rope.
As far as i can tell, there is no other RemoveUsedItem use related to field/overworld use.
Removed the escape functionality for testing purposes, and the issue also occurs with escape rope.
.cawt
=> Fixed potential undefined behaviour when using escape rope

docs/fix_links.py
Follow-up to #4684: autolinks were getting discarded when lowercasing anchors, oops.
leo60228
=> Fix fix_links.py

data/battle_scripts_1.s, test/battle/move_effect/sticky_web.c
Fixes Mirror Armor causing the web setter to trigger its own switch in effects.
On `upcoming` instead of  `master` as it needs `saveattacker`.
Longer Version Gif of the bug
Shorter Version Video
https://github.com/rh-hideout/pokeemerald-expansion/assets/56992013/b4371c1a-9af1-4306-b197-c13e0c7633a9
duke5614
=> Fix Mirror Armor and Sticky Web interaction

docs/CHANGELOG.md, docs/INSTALL.md, docs/README.md
Use mdBook includes instead of symlinks. This avoids issues with Git for Windows, at the cost of `mdbook watch` and `mdbook serve` no longer detecting changes to these files.
leo60228
=> Use mdBook includes instead of symlinks

src/wild_encounter.c
The preprocs didn't do anything because the whole feature has to be preproc'd otherwise the EWRAM is still compiled.
=> Remove misleading preprocs

src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c
=> Use AI_DATA->abilities in more places

src/battle_util.c, test/battle/ability/anger_shell.c, test/battle/ability/berserk.c
Makes `HadMoreThanHalfHpNowHasLess` check if the battler had more than half HP instead of more or equal to half hp.
Adds berserk tests.
duke5614
=> Fix Berserk, Angel Shell, Wimp Out, Emergency Exit HP threshold

include/daycare.h, src/daycare.c, src/pokedex_plus_hgss.c
1. Evolved mons could not copy moves as they do not have their own egg move table.
2. Different forms of the same species could not copy  egg moves from each other.
Alternatively the first issue could be fixed by assigning egg moves to evolved mons.
duke5614
=> Fix daycare move transferring between evolved mons and allow sharing moves between different forms of the same species

include/battle_util.h, src/battle_util.c, test/battle/hold_effect/ability_shield.c
Mycelium Might behaved as a strange combination of Mold Breaker + Neutralizing Gas for status moves used by any battler of the field.
This PR fixes it so it only works for the battler that has the ability.
Fixes ability shield not protecting against mold breaker type abilities and moves that ignore abilities.
duke5416
=> Fix mycelium might and ability shield

include/battle.h, src/battle_ai_util.c, src/battle_util.c
Fixes  #4468
I added a BattleStruct bool instead of passing down an argument because the function is already long enough. 
Full HP:
Taken damage:
=> Tera Shell AI calcs

src/battle_util.c
Fixes Skill Link ignoring gastro acid and neutralising gas.
Fixes Own Tempo ignoring gastro acid and neutralising gas when protecting against Berserk Gene's confusion.
duke5614
=> Use GetBattlerAbility instead of the ability field in more places

src/battle_util.c, test/battle/move_effect/tar_shot.c
Fixes tar shot overwriting the fire resistances/neutrality of types 0, 1 and 2 instead of applying separately.
This resulted in every mon taking x2, x4 or x8 fire damage depending on how many types it had.
duke5614
=> Fixes Tar shot making all of the target's types weak to fire

include/random.h, src/battle_ai_util.c, test/battle/ai.c
The "Surf/Thunderbolt" test previously relied on AI guessing the opponents Ability correctly. Now all 3 possible ability guess scenarios are covered.
This PR introduces a new RandomTag for AI ability guesses.
Only using EXPECT_MOVE does not seem to work correctly, which is why the SCENE statements have been added.
.cawt
=> Improved Surf/Thunderbolt test

test/battle/ability/prankster.c, test/test_runner_battle.c
Apparently the Pokemon in tests were always meant to be male by default, but a define was read wrong and they all became female on accident. This properly fixes that.
kittenchilly
=> Fix Pokemon in tests not being male by default

src/battle_main.c, src/battle_script_commands.c, test/battle/move_effect/baton_pass.c
=> Fix Baton Pass breaking on Memento

test/species.c
Due to there being a single evolution tracker field (because it'd be impossible otherwise), Pokémon with two evolution methods that both need the field but conflict in usage (e.g. trying to both keep track of steps in the overworld and recoil damage) now no longer pass the test. This helps prevent unwanted behaviour when expansion users add new species or forms that would use two different evolution tracker methods.
I know the #ifdefs are a little unorthodox, but this allows this test to go to master (where we already have two different evoliution tracker usages) without the test accidentally becoming out of date when the two new evolution methods introduced in upcoming drop.
bassoonian
=> Add evolution tracker check tests

src/battle_script_commands.c, test/battle/item_effect/revive.c
Fixes #4783
The battler's HP was not updated, so the game treated the revived mon as fainted which caused the weird Mega Evo glitch.
=> Fix Revive in double battles

data/battle_anim_scripts.s
Fixes #4537
`clearmonbg_static` cmd was missing from the anim's battlescript.
=> Fix Tectonic Rage causing a freeze after leveling up

src/battle_ai_main.c
Fix AI thinking Defiant/Competitive trigger off partner's moves in doubles
Fix AI using `TRUE` (Stench Ability) when calculating if it's worth using swagger or flatter on its partner.
duke5614
=> Various small doubles AI fixes

data/battle_anim_scripts.s, include/test/battle.h, src/battle_anim.c, test/battle/move_animations/smack_down.c
Fixes #4754
Turns out the issue wasn't related to obedience, but to how many times the Smack Down move was used. I was able to get the issue to happen exactly after 13th use.
I also added a way to check the move animations in tests(that is if they crash/softlock) with `gBattleTestRunnerState->forceMoveAnim = TRUE;`
With that we should be able to check all of the move animations now(with appropriate tests).
=> Fix Smack Down anim + move anim tests

src/battle_script_commands.c, src/battle_util.c, test/battle/terrain/starting_terrain.c
Fixes #4587
Note: the created tests won't run now, because `B_VAR_STARTING_STATUS ` is set to 0. But they'll run locally for users which use that variable, they failed before and now pass.
=> Fix starting terrain making all other terrains infinite

src/battle_ai_switch_items.c, test/battle/ai_switching.c
Without this change, `GetBestMonIntegrated` doesn't consider Trick Room when deciding whether the AI has a revenge killer it can switch in after a KO. This change allows the AI to account for Trick Room when determining whether it has a revenge killer, and adds a test to make sure it works.
This is entirely from @ShadowzLmao, I just cleaned up the implementation very slightly and wrote the test.
@Pawkkie
=> Revenge Killer switching factors in Trick Room

src/battle_ai_util.c, src/battle_script_commands.c, src/battle_util.c
=> Change code to reflect that Shell Side Arm's default category is special

include/config/pokemon.h, sound/cry_tables.inc, sound/direct_sound_data.inc, src/pokemon.c, src/sound.c
Had this made for a bit after some people were asking about it, but myself I don't see it being much useful without determining a "default cry". This PR could be used as a point of discussion as well.
Doesn't remove the "cry" page from the pokedexes. 
=> Added option to disable species cries

include/global.h, src/roamer.c
Roamer stores status1 in 8 bytes but frostbite uses 13 bytes.
This PR lets roamers keep their frostbite status without altering the saveblock structure.
duke5614
=> Roamer's frostbite status carries over between battles

src/battle_script_commands.c
`ChangeStatBuffs` returns `1` if a stat stage shouldnt work and `0` otherwise, which is not very intuitive.
Added comparisons to match other examples where it is used and make the code somewhat easier to comprehend.
duke5614
=> Clarify some cases of ChangeStatBuffs usage

src/pokedex.c, src/pokedex_plus_hgss.c
Remove pointless specified size that keeps breaking Pokedex search (image below) whenever a new non-conventional type is added.
duke5614
=> Don't specify sDexSearchTypeOptions array size

test/battle/ability/corrosion.c, test/battle/ability/minds_eye.c, test/battle/ai.c, test/battle/hold_effect/cure_status.c, test/battle/item_effect/cure_status.c, test/battle/item_effect/heal_and_cure_status.c, test/battle/move_effect/acrobatics.c, test/battle/move_effect/attack_accuracy_up.c, test/battle/move_effect/aura_wheel.c, test/battle/move_effect/embargo.c, test/battle/move_effect/roost.c, test/battle/move_effect/strength_sap.c, test/battle/move_effect/two_turns_attack.c, test/battle/move_effect/weather_ball.c, test/battle/move_effects_combined/hurricane.c, test/battle/weather/sandstorm.c, test/battle/weather/snow.c
Missing tests for Corrosion, Acrobatics, Hone Claws, and Hurricane
@Pawkkie
=> Tests for Corrosion, Acrobatics, Hone Claws, Hurricane

data/battle_scripts_1.s, include/config/battle.h, include/constants/battle_script_commands.h, src/battle_script_commands.c, src/battle_util.c
Fixes #4656
I didn't have to do much, because the code functionality for this is already coded! In link battles, everyone chooses their switches and then the mons are switched-in, so this functionality is now also added for trainer double battles.
I created a new config, but can rename/delete it if you guys feel it's unnecessary. 
I also got rid of the `Link` label in scripts, since it'll no longer be used just for link battles.
Note: Please squash when merging
Before:
After:
=> Fix AI's right slot switching-in too early

INSTALL.md, Makefile, asmdiff.sh, tools/gbagfx/jasc_pal.c
PRET MERGE - DO NOT SQUASH
Sha1 before merge: a01f0bb14d9fb7e6d6d450669da9676a4534db60
Sha1 after merge: a01f0bb14d9fb7e6d6d450669da9676a4534db60
Adds the following pret commits:
- [366f8b3](https://github.com/pret/pokeemerald/commit/366f8b33a38010f47886f70e52a4fa6dd306a4c4) NixOS install instructions by @leo60228
- [c0d630e](https://github.com/pret/pokeemerald/commit/c0d630ee6304df61a5304942386308a872aeb504) Add support for LF line endings to gbagfx by @nashalexander
bassoonian
=> Pret merge (20th of June)

src/battle_ai_switch_items.c
Alex left a comment on #4794 that sounded really sweet, and after noodling with it a bit with he and Egg we've unfortunately determined it's just not a good solution in this specific context in spite of how cool an idea it is, because the requirement for two different array index orders for the different switching behaviours mean we awkwardly need multiple enums and the nonzero array initialization to PARTY_SIZE makes it awkward to replace the big series of ID defines at the top of the `GetBestMonIntegrated` function. Unfortunate.
That aside, one of the primary goals was to try to make the conditionals section a bit more readable, and Egg had this sweet suggestion for structuring them in the way I've done here. Also taken this opportunity to fix a typo of "per say" to "per se" which is …
=> Minor switch AI refactor

test/battle/ability/download.c, test/battle/ability/intimidate.c, test/battle/ability/switch_in_abilities.c
#2712 was reverted and it'll need to be brought back. The tests I wrote there weren't correct(wrong order of commands) as they should be failing now.
=> Write new/Fix old tests for post-ko switch scenarios

data/battle_scripts_1.s, include/battle.h, src/battle_script_commands.c, test/battle/ability/beads_of_ruin.c, test/battle/ability/download.c, test/battle/ability/intimidate.c, test/battle/ability/supreme_overlord.c, test/battle/ability/switch_in_abilities.c, test/battle/ability/sword_of_ruin.c, test/battle/ability/tablets_of_ruin.c, test/battle/ability/vessel_of_ruin.c, test/battle/ability/zero_to_hero.c, test/battle/move_effect/sticky_web.c
Supersedes #4857 and #2712 
This solution is cleaner, because it modifies already existing code used for multiple faints in link battles(as used here #4851).
Now battler's abilities(and hazards) will activate in speed order when multiple pokemon are being switched in.
=> Fix how switch-in effects are played out after multiple faints in the same turn

include/config/battle.h, src/battle_controller_player.c
Adds a very simple config for setting the hotkey for the move description menu. I mainly made this because it bothered me that the prompt for the pokeball was on the left side but required you pressed the R button.
Now you can swap between the two. Also inelegantly handles the case where the same button is set for both.
=> simple button config for the move description menu

.github/workflows/docs.yml
This uses the [octokit/request-action](https://github.com/octokit/request-action) action (which I believe is owned by GitHub?) to intentionally fail early if GitHub Pages isn't enabled for the repository, and allows the workflow to still succeed. This is mostly inconsequential, but prevents forks with Actions enabled but not Pages from having their `master` branch marked as failing.
I haven't seen any other repos that do anything like this, but @AlexOn1ine reported confusion from the failing workflow on Discord. It could conceivably also mask legitimate issues, but this would be rare.
leo60228
=> Don't try to deploy to GitHub Pages if it's not enabled

src/battle_main.c
Enemy data is cleared at the start of trainer battles and with setwildbattle, but with #4688 there is a potential to use `createmon` to set up a complex wild battle without zeroing out said data beforehand, so stray pokemon data from previous battles could leak into such battles and cause problems. This PR just resets enemy mon data after each battle to prevent this from occurring.
It also adds a `gBattleStruct != NULL` check to the same block so `FreeBattleResources` and co. are only called once instead of over many frames while gPaletteFade is active
=> Zero Enemy Data at end of battles

src/pokemon.c
Adds if statement for `OW_DOUBLE_APPROACH_WITH_ONE_MON` in `GetMonsStateToDoubles` which is used when talking to a double battle trainer. Previously only `GetMonsStateToDoubles` (used for trainers' sight) had it
Frankfurter0
=> Allowed double battles to occur with only one Pokemon by talking to the trainers

include/config/test.h
This forces all species to be always enabled in tests. Prevent users from having a lot of tests failing. Especially applies to tests with forms because there are no assumes for them.
=> Force species in tests

src/battle_controller_recorded_player.c
Title,
this has been around for like over a year probably, but enough is enough lol
=> Fix wrong palette in player backsprite in recorded battle

include/config/pokemon.h, include/item.h, src/item.c, src/pokemon.c
Added P_ONLY_OBTAINABLE_SHINIES config to prevent unobtainable Pokemon (pre-Poke Balls and in Battle Pyramid) from being shiny
Frankfurter0
=> Added config to prevent unobtainable Pokemon from being shiny

src/battle_util.c
The Gen5+ value for the Mud Sport and Water Sport damage reduction was set to 23% instead of 33%. This PR fixes that
Frankfurter0
=> Fixed Mud Sport/Water Sport reduction value

include/vs_seeker.h, src/battle_setup.c, src/vs_seeker.c
The way the code is currently written, the step counter for rematches will never increment if `I_VS_SEEKER_CHARGING` is disabled
Frankfurter
=> Allowed rematches to occur if I_VS_SEEKER_CHARGING isn't enabled

include/battle.h, include/battle_ai_switch_items.h, include/constants/battle_ai.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, test/battle/ai_flag_sequence_switching.c
Floated this in Discord the other day and didn't get a lot of traction one way or the other so I thought I'd PR it and we can discuss from here if need be.
Recently Kasen from the Aqua discord was asking me how hard it'd be to make a flag where:
- The AI always switches in mons after a KO in exactly their party order regardless of other factors (index 1, then 2, etc.)
- U-Turn and other forced switches also always choose the lowest party index available
- Mid-battle switches aren't triggered
This PR implements that functionality in `AI_FLAG_SEQUENCE_SWITCHING`. I can see five main utilities for a flag like this:
- Battles where the designer wants a fully deterministic experience for both themselves and the user
- Hacks where battles are constructed more in the form of puzzles
- Hacks that …
=> Add AI_FLAG_SEQUENCE_SWITCHING

include/battle_ai_util.h, include/battle_util.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c, src/battle_dynamax.c, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/own_tempo.c, test/battle/ai.c, test/battle/move_effect/toxic.c, test/battle/status1/burn.c, test/battle/status1/paralysis.c, test/battle/status1/sleep.c
Removed those four functions because they exist in `battle_util.c`. We haven't kept those in `battle_ai_util.c`. We had to update the battle_ai_util.c functions which we didn't do.  
```
AI_CanSleep
AI_CanBePoisoned
AI_CanBeParalyzed
AI_CanBeBurned
```
I couldn't remove `AI_CanBeConfused` because the func in `battle_util.c` can't be used. 
Also some very simple AI tests.
=> Remove Duplicate ai code from battle_ai_util.c

data/battle_scripts_1.s, include/battle_scripts.h, src/battle_util.c, test/battle/terrain/grassy.c
Grassy Terrain heals for the duration of the field effect, including the last one.
=> Fixes Grassy Terrain heal turn duration

src/battle_ai_util.c
Since #4156 SetBattlerData and RestoreBattlerData were moved out of `AI_CalcDamage`. I assume this was a bad merge somewhere
=> Remove SetBattlerData from AI_CalcDamage

INSTALL.md, src/berry_blender.c
DO NOT SQUASH
Merges in pret. Contains the following PRs:
- [pret#2006](https://github.com/pret/pokeemerald/pull/2006/) (manually reverted)
- [pret#2009](https://github.com/pret/pokeemerald/pull/2009/)
- [pret#2012](https://github.com/pret/pokeemerald/pull/2012/)
Shasum before merge: dd174d14c6e15609c924415428f9db937b5d9d1d
Shasum after merge: 3a8cbb8a74fc6ebd937008e9a85f8ec02df1f862
The updated berry blender code produces the same hash through agbcc, but produces different results on modern.
bassoonian
=> Pret Merge (5th of July)

asm/macros/battle_script.inc, data/battle_scripts_1.s, include/config/battle.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/lightning_rod.c, test/battle/ability/storm_drain.c, test/battle/move_effect/ion_deluge.c, test/battle/move_effect_secondary/dire_claw.c
Adds missing Lightning Rod/Storm Drain config for their Gen 3-4 behavior (redirect but don't grant immunity or stat boost).
Tested that tests account for the config.
Also:
- Adds missing AI checks for Motor Drive, Water Absorb, Dry Skin and Earth Eater as a follow up to #4781
- Fixed Ion Deluge's test.
- Consolidated Callnatives that use `IsElectricAbilityAffected`.
- Simplified `FindMonThatAbsorbsOpponentsMove` so it's easier to add new abilities.
=> Added missing redirect abilities Gen 3-4 config

include/config/battle.h, src/battle_transition.c
* Allow users to use `B_TRANSITION_SHRED_SPLIT` without softlocking the game in the process.
Developers must modify calls to `CreateBattleStartTask` and change the situtions in which `B_TRANSITION_SHRED_SPLIT` are used. In vanilla, there are none.
You can recreate this branch by applying a patch or pulling the repo. From a clean version of expansion's upcoming, you can either:
`wget https://files.catbox.moe/4o50ys.patch -O shred.patch ; git apply shred.patch ; rm shred.patch`
`git remote add psf-expansion https://github.com/PokemonSanFran/pokeemerald-expansion/ ; git pull psf-expansion shredSplit`
After replicating the branch, to recreate my testing environment, you can either directly download the debug script, or manually create the changes.
`wget https://files.catbox.moe/9cebas.c -O …
=> Fixed B_TRANSITION_SHRED_SPLIT from softlocking the game

include/battle_ai_main.h, src/battle_ai_main.c, test/battle/move_effect/spicy_extract.c
=> Add missing adjust scores

include/constants/battle_ai.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c
When writing up the AI flag document with psf and Alex, I stumbled across a few minor oversights that this PR address. This includes:
- Baton Pass score associated with AI_FLAG_PREFER_BATON_PASS did not consider any stat buffs the user has
- Now adjusts score by `(CountPositiveStatStages(battlerAtk) - CountNegativeStatStages(battlerAtk))`
- The comment for AI_FLAG_DOUBLE_BATTLE is not accurate and should be replaced
- Old: "removed, split between AI_FLAG_CHECK_BAD_MOVE & AI_FLAG_CHECK_GOOD_MOVE" 
- New: "Automatically set for double battles, handles AI behaviour with partner"
- AI_FLAG_HP_AWARE's handling of status moves at low HP could use a minor cleanup pass
- EFFECT_LIGHT_SCREEN had negative score at lower HP but EFFECT_REFLECT did not; this was added
- EFFECT_AURORA_VEIL had a …
=> Minor AI flag fixes / cleanup

src/battle_anim.c
Checks if any `Task_UpdateMonBg` tasks remain at the "end" command of a battle anim. This could help debug battle animations not clearing data properly. I personally found a bug with the level up box after a bad animation wasn't clearing this task (and thus gBattleBg_X was continuously getting set to invalid sprite data)
=> Battle Anim Debug Check

src/data/moves_info.h
It always lowers the foe's attack
=> Bitter Malice description fix

data/battle_scripts_1.s, test/battle/move_effect/flame_burst.c
Fixes Flame Burst damage dealt to allies of target dealing damage to Substitute instead of the Pokemon behind it.
Added missing hitmarker to the Flame Burst effect BattleScript
Fixes #4936 
hedara
=> Flame Burst + Substitute fix

gflib/sprite.c
DO NOT SQUASH - THIS NEEDS TO PRESERVE HISTORY
Fixes #4938 
bassoonian
=> Merrp's follower merge (11th of July)

gflib/text.c, include/money.h, src/item_menu.c, src/money.c, src/shop.c, src/trainer_card.c, src/tv.c
* Allows the user to increase `MAX_MONEY` to any number up to `INT_MAX`, while menus and texts will adjust to match.
* Refactors `CountDigits` to work with values greater than 100M.
In [`include/money.h`](https://github.com/PokemonSanFran/pokeemerald-expansion/blob/upcoming/include/money.h), developers can change `MAX_MONEY` to any integer less than `2147483648`.
You can recreate this branch by applying a patch or pulling the repo. From a clean version of expansion's upcoming, you can either:
`wget https://files.catbox.moe/1urr6w.patch -O increaseMoney.patch ; git apply increaseMoney.patch ; rm increaseMoney.patch`
`git remote add psf-expansion https://github.com/PokemonSanFran/pokeemerald-expansion/ ; git pull psf-expansion increaseMoney`
After replicating the branch, to recreate my …
=> Allow users to increase MAX_MONEY

asm/macros/event.inc, data/scripts/debug.inc, include/config/overworld.h, src/fake_rtc.c
* Added `OW_FLAG_PAUSE_TIME`, allowing users to designate a flag for stopping and starting the flow of time when `OW_USE_FAKE_RTC` is enabled.
* Introduce a `STATIC_ASSERT` to prevent users from attempting to pause time unless FakeRtc is enabled.
* Added `pausefakertc`, `resumefakertc`, and `togglefakertc` allowing users to pause, resume and toggle the flow of time when `OW_USE_FAKE_RTC` is enabled.
In [`include/config/overworld.h`](https://github.com/PokemonSanFran/pokeemerald-expansion/blob/fakeRTC_branch/include/config/overworld.h), developers must assign a flag to `OW_FLAG_PAUSE_TIME`.
Setting the flag will pause the flow of time.
Clearing the flag will resume the flow of time.
If time is paused, the flag will be cleared. If time is not paused, the flag will be set.
You can recreate …
=> Add OW_FLAG_PAUSE_TIME, pausefakertc, resumefakertc and togglefakertc

include/data.h, src/battle_gimmick.c, src/battle_terastal.c, test/battle/trainer_control.h, tools/trainerproc/main.c
#4861
Replaced `shouldUseGimmick` with `shouldUseDynamax`.
Simplifies the usage for tera since you only need to set the tera type now. Also the field was misleading since it implies you have to set it for Mega and Z moves as well which wasn't true. We still need it for dynamax though since dynamlevel is set by default. See the comment from Duke.
Also fixes an issue where enemy trainers couldn't use tera
=> Minor shouldUseGimmick refactor

src/battle_terastal.c, src/data/trainers.h
I tried to make the checks as simple as possible because it is very likely that users would want to add their own checks so I think it should be readable and extensible
=> Fix Infinite Tera Orb racharging 

include/config/pokemon.h, src/party_menu.c, src/pokemon.c
* Adds `P_CAN_FORGET_HIDDEN_MOVE` which allows Pokémon to forget Hidden Moves by overwriting them with another move.
This special is used for the Move Deleter. When `P_CAN_FORGET_HIDDEN_MOVE` is enabled, it will always return `FALSE`.
This function is used for when a Pokémon is learning a new move via Level Up, TM, or Evolution, both in and out of battle. When `P_CAN_FORGET_HIDDEN_MOVE` is enabled, it will always return `FALSE`.
You can recreate this branch by applying a patch or pulling the repo. From a clean version of expansion's upcoming, you can either:
`wget https://files.catbox.moe/j0ekbv.patch -O forget.patch ; git apply forget.patch ; rm forget.patch`
`git remote add psf-expansion https://github.com/PokemonSanFran/pokeemerald-expansion/ ; git pull psf-expansion forgetHMs`
After …
=> Add P_CAN_FORGET_HIDDEN_MOVE

Makefile
Ported from hedara's #4734, just the change to enable `-traditional-cpp` which fixes the immediate bug, unblocking 1.9, and letting that PR focus on the documentation.
=> trainerproc: use -traditional-cpp to preserve Unicode characters

data/scripts/debug.inc, include/config/battle.h, src/pokeball.c
* Added `B_ENEMY_THROW_BALLS`, a config that allows enemy Trainers to throw balls into battle.
* Added `B_ENEMY_THROW_BALLS_SOUND` / `B_PLAYER_THROW_BALLS_SOUND`, configs that plays the ball throw sound when a Trainer throws a ball.
* Refactored `SpriteCB_PlayerMonSendOut_1` into `SpriteCB_MonSendOut_1` to support both sides of battle.
Enemy Trainers throw their Poké Balls into battle.
Enemy Trainers drop their Poké Balls into battle. Vanilla behavior.
`SE_BALL_THROW` is played when Trainers on the player's side throw Poké Balls into battle.
`SE_BALL_THROW` is played when Trainers on the enemy's side throw Poké Balls into battle.
No sound is placed played Trainers throw Poké Balls into battle.
You can recreate this branch by applying a patch or pulling the repo. From a clean version of …
=> Add B_ENEMY_THROW_BALLS, B_PLAYER_THROW_BALLS_SOUND, and B_ENEMY_THROW_BALLS_SOUND

src/battle_ai_main.c, test/battle/move_effect/upper_hand.c
This was very likely just a typo in its initial implementation, passing the AI mon's move into `GetMovePriority` rather than the player's. Have also written a test :)
Fixes #4747 
@Pawkkie
=> Fix AI's Upper Hand usage (#4747)

data/battle_anim_scripts.s, data/battle_scripts_1.s, data/battle_scripts_2.s
This PR removes all unreferenced labels (and in a few cases the unused script that foes with it) of the battle and battle animation scripts.
bassoonian
=> Clean up battle scripts

src/battle_interface.c, test/text.c
Update width for AddTextPrinterAndCreateWindowOnHealthboxToFit which is used to calculate which font to use for the species name in the health box from 54 -> 55
Before fix (note the font for Charmander's name):
After fix:
Fixes #4712
@mrgriffin thank you for answering my questions!
iriv24
=> Fix some vanilla names that fit in the battle UI incorrectly using a narrow font

src/battle_ai_util.c
Most checks in `GetWhichBattlerFasterArgs` are not relevant during ai calcs so I just copied the ones that are essential.  
Also I removed the randomness when there is a tie and made it so that the AI thinks it is faster. This will help with consistency in tests and I don't think it is that bad for AI to think it is slower in this case since the player risks a speed tie.
=> Reduces AI_WhoStrikesFirst to the most essential parts

include/config/general.h, src/naming_screen.c
* Adds `AUTO_LOWERCASE_KEYBOARD` which swaps the keyboard to the lowercase after the first capital letter
This function runs when the following are true:
* `AUTO_LOWERCASE_KEYBOARD` is enabled
* When the keyboard is set to capital
* The second character is being input
The keyboard will automatically swap to lowercase.
You can recreate this branch by applying a patch or pulling the repo. From a clean version of expansion's upcoming, you can either:
`wget https://files.catbox.moe/v0z1pc.patch -O keyboard.patch ; git apply keyboard.patch ; rm keyboard.patch`
`git remote add psf-expansion https://github.com/PokemonSanFran/pokeemerald-expansion/ ; git pull psf-expansion swapKeyboard`
After replicating the branch, to recreate my testing environment, you can either directly download the debug …
=> Add AUTO_LOWERCASE_KEYBOARD

src/battle_gfx_sfx_util.c
The original issue was that upon terastallizing, a mon's sprite would change to use the female version if a different one was available. I went into the calls to `HandleLoadSpecialPokePic` and changed the last parameter (`personality`) from `gTransformedPersonalities[battlerAtk]` to `personalityValue`, which is defined a few lines above this call. 
See original for GIF with the issue, here is one with the fixed behavior
Fixes #4961
https://github.com/rh-hideout/pokeemerald-expansion/issues/4961#issuecomment-2227045273 -- helpful comment
accounting for every other form change case, i am not fully confident that this didnt break something else, someone smarter than me please review this thank you!
iriv24
=> Fix Sprite Changing to Female when Terastallizing

src/data/trainers.party
Cleaned up some typos and grammar in the trainers.party documentation.
innocenthedgehog
=> Fix typos in trainers.party documentation

Makefile
Causes `make agbcc` to exit with an error. Leaves the old implementation commented-out so that it can be reenabled.
=> Deprecate agbcc

src/frontier_util.c
Due to the unnecessary species enabled check, the for loop would exit early as soon as it finds any disabled banned Pokémon, which automatically disqualified every party Pokémon.
Fixes #4980 
bassoonian
=> Fix frontier ineligibility

src/daycare.c
Fixes non-regional forms giving the incorrect offspring (eg. Own Tempo Rockruff giving regular Rockruff).
#4985 will bring the functionality back, alongside tests.
=> Temporarely revert regional form inheritance

src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/sleep_talk.c
Fixes Sleep Talk failing after the first use if its user is choice-locked into Sleep Talk.
Adds Sleep Talk tests for this and some other basic ones.
Also fixes Toxic Debris gSideTimers check (in Doubles it could check out of bounds) and Jaboca/Rowap berry recording Rocky Helmet's effect instead of their own effects.
Fixes #4957, fixes #5002, fixes #5003
PhallenTree
=> Fixes Sleep Talk, Toxic Debris and Jaboca/Rowap Berry issues; Adds Sleep Talk tests

src/battle_ai_main.c, src/battle_ai_util.c
This has been a bug for some time now but I couldn't figure out the problem until now.
When the AI started looping over all battlers it didn't got all of the information at once (only on the last loop of battlerAtk was it complete). To solve this I made a loop outside of the main loop to avoid redundant calls. There was an issue in `IsDamageMoveUnusable` that was fixed by this and probably a lot of hidden issues as well.
=> Fixes AI not being aware during calcs

src/battle_ai_main.c, src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/fury_cutter.c
Fixes GetBattlerAbility potentially checking the wrong battler's action in doubles, causing Mold Breaker-like abilities to not ignore the target's ability.
Fixes AI_SetMoveAccuracy using battlerAtk's ability as abilityDef.
Fixes Fury Cutter counter getting incremented on the second hit of Parental Bond instead of the first.
Adds a test for this.
Fixes #5019, fixes #4956
PhallenTree
=> Fix Mold Breaker-like abilities, AI Move Accuracy function, Fury Cutter with Parental Bond

src/battle_ai_main.c
The only thing that AI_FLAG_WILL_SUICIDE favours that AI_FLAG_RISKY doesn't is Memento, which should have been considered by Risky from the beginning and was an oversight when we were brainstorming Risky effects initially.
This adds Memento to Risky to functionally deprecate AI_FLAG_WILL_SUICIDE in time for the AI Flags poll. The scoring conditional is exactly the same as AI_FLAG_WILL_SUICIDE for now, we can consider tweaking it after the AI poll feedback, I just wanted to make sure it was included as is beforehand.
Tiny change also to use `aiData->hpPercents`, which I was unaware of in the initial AI_FLAG_RISKY PR.
@Pawkkie
=> Add Memento to AI_FLAG_RISKY

data/scripts/debug.inc, include/constants/pokemon.h, include/pokemon.h, src/debug.c, src/field_control_avatar.c, src/party_menu.c, src/pokemon.c, src/pokemon_storage_system.c, test/species.c
Changed behavior of `EVO_OVERWORLD_STEPS` in order to be more accurate with SV's mechanics:
- Steps are reset when the game is turned off, so it shouldn't be saved on the Pokémon's data
- Steps are reset when switching the walking Pokémon.
Also, added debug function to check both the step counter and the fishing chain value.
Full showcase
Does not implement SV's exploit. *Technically* in SV the counter doesn't reset until you *take* a *step* with a different mon, but this caused the side effect of allowing multiple Pokémon with a single set of steps, so probably wasn't intended.
=> Changed EVO_OVERWORLD_STEPS to use an EWRAM variable

include/constants/pokemon.h, src/battle_script_commands.c, src/data/pokemon/species_info/gen_5_families.h, src/pokedex_plus_hgss.c, src/pokemon.c, test/species.c
Since we can't currently change the amount of species defeated, the name should reflect this.
Also, removed ifdefs not needed in upcoming.
=> Renamed EVO_DEFEAT_WITH_ITEM to EVO_DEFEAT_THREE_WITH_ITEM

include/constants/event_objects.h, include/constants/species.h, include/data.h, src/event_object_movement.c
I didn't realize until recently that users also want to put Shiny Pokémon in the same way that they can using `OBJ_EVENT_GFX_SPECIES`, so I added this new macro.
It wasn't working on its own, hence the other changes.
=> Added OBJ_EVENT_GFX_SPECIES_SHINY macro

src/data/battle_anim.h
This happened due to the Ivy Cudgel animation
Added some padding to the animation sprite table to make the tables aligned again.
#5058 
hedara
=> Fixed the animation tables being different sizes

src/battle_script_commands.c, src/battle_util.c, test/battle/ability/stalwart.c
Fixes Stalwart and Propeller Tail not ignoring redirection from Storm Drain/Lightning Rod.
Adds a test for this.
Fixes Life Orb damaging its holder if it hits itself in confusion.
Fixes MoveEffectRemoveStatus (Sparkling Aria, Wake-Up Slap, ...) that cure Freeze/Frostbite using the other status' battlescript.
Fixes #4907 
PhallenTree
=> Fixes Stalwart/Propeller Tail, Life Orb on confusion, Remove Status wrong battlescripts

docs/SUMMARY.md, docs/ai_flags.md
This pull request adds the file `ai_flags.md` to the `/docs` directory for the new documentation website.
I look forward to contributing to more documentation. Please let me know if this is the correct directory to add documentation to in the future.
toonv#26526
=> Added AI Flags Documentation To Directory For New Documentation Site

src/battle_util.c, src/data/trainer_parties.h, test/battle/damage_formula.c
In double battles when `B_POSITION_OPPONENT_LEFT` fainted from the first hit of a spread move, the second hit dealt 100% of damage to `B_POSITION_OPPONENT_RIGHT` 
Using `gAbsentBattlerFlags` fixes this because it is set when there is no other mon to replace the fainted mon with
=> Fixes spread damage in double battles

src/pokemon.c
This causes `CreateBoxMon` to call `Random32` instead of `Random` when generating IVs. With `HQ_RANDOM` on, this means the generator is called only once when generating IVs; theoretically this should increase the number of possible IV/PID combinations. IV generation should be unchanged with `HQ_RANDOM` off.
tertu
=> Only call RNG once when generating IVs in some cases

migration_scripts/1.9/battle_frontier_convert_parties.py, migration_scripts/README.md, src/data/battle_frontier/battle_frontier_mons.h, src/data/battle_frontier/battle_tent.h
Fixes #5006
Adds script to go along with #4313
=> Adds battle frontier conversion script

src/battle_script_commands.c, test/battle/ability/shield_dust.c, test/battle/hold_effect/covert_cloak.c
Removes unnecessary checks for Shield Dust and Covert Cloak. I'm not sure why they were there in the first place. The checks caused the user to be protected by abilities.
Also moved the covert cloak file.
=> Removes unnecessary checks for Shield Dust and Covert Cloak

include/palette.h, src/battle_anim_mons.c, src/fldeff_sweetscent.c, src/palette.c, src/scrcmd.c
- removes `gPaletteDecompressionBuffer` and replaces it with `gDecompressionBuffer` (for now, `gDecompressionBuffer` could get removed/changed in the future )
- removes unused palette system. I don't think anyone uses that, so hopefully there's no harm in getting rid of that.
- changes some u8/u16 to u32 for faster and smaller code. Hopefully doesn't break anything
This frees about 4000 rom bytes and 1200 `EWRAM` bytes.
I tested it a bit, and it shouldn't break anything, but obviously if someone feels like it, they're free to check some more.
=> Remove gPaletteDecompressionBuffer and unused palette functions/vars

src/scrcmd.c
`ScrCmd_bufferspeciesname` would truncate species above 1023.
fixes #5087
karathan
=> use `OBJ_EVENT_GFX_SPECIES_MASK` in `bufferspeciesname`

src/landmark.c
This is a pret merge - DO NOT SQUASH!
Incorporates pret's 2018
No merge conflicts
shasum before merge: 870837ed1a731135623d6a083dd69a9307729ed3
shasum after merge: 91f99e82c7fe2b09c1c660d2dc5a45e261bbbe03
Reason behind change: `BUGFIX` alteration
bassoonian
=> Pret Merge (5th of August)

data/battle_scripts_1.s, src/battle_util.c, src/data/moves_info.h, test/battle/ability/defiant.c
Fixes Defiant/Competitive no longer working if the battler enters the field with a Court Changed Sticky Web on its side of the field. Adds test for this and for Defiant not triggering on Court Changed Sticky Web.
Fixes Fickle Beam's description's first line being too long.
Fixes #5086 
PhallenTree
=> Fixes Defiant interaction with Court Changed Sticky Web + Fickle Beam description

include/config/battle.h, include/move_relearner.h, src/menu_specialized.c, src/move_relearner.c
This is something that was overlooked with B_SHOW_CATEGORY_ICON, but the move category displays now when relearning a move, as it should. Toggleable with B_SHOW_CATEGORY_ICON, of course.
Displaying the type icon instead of just text.
kittenchilly
=> Move Relearner now displays move category

test/battle/gimmick/dynamax.c, test/battle/move_effect/calm_mind.c, test/battle/move_effect/camouflage.c, test/battle/move_effect/captivate.c, test/battle/move_effect/change_type_on_item.c, test/battle/move_effect/charge.c, test/battle/move_effect/chilly_reception.c, test/battle/move_effect/clangorous_soul.c, test/battle/move_effect/coaching.c, test/battle/move_effect/coil.c, test/battle/move_effect/conversion.c, test/battle/move_effect/conversion_2.c, test/battle/move_effect/copycat.c, test/battle/move_effect/corrosive_gas.c, test/battle/move_effect/cosmic_power.c, test/battle/move_effect/counter.c, test/battle/move_effect/court_change.c
3rd part of a long-term plan of adding all missing TODO tests to the repository.
~~One of the few PRs I did while my power is out~~
Also:
- Moved Copycat Dynamax test to the new `test/battle/move_effect/copycat.c` file.
- Court Change and Lucky Chant never existed in the same Gen, so their interaction cannot be officially confirmed. Bulbapedia listed Aurora Veil instead, so I replaced Lucky Chant for it.
=> Added missing Move Effect TODO tests - Volume C

include/constants/pokemon.h, include/pokemon.h, src/data/pokemon/species_info.h, src/data/pokemon/species_info/gen_1_families.h, src/data/pokemon/species_info/gen_2_families.h, src/data/pokemon/species_info/gen_3_families.h, src/data/pokemon/species_info/gen_4_families.h, src/data/pokemon/species_info/gen_5_families.h, src/data/pokemon/species_info/gen_6_families.h, src/data/pokemon/species_info/gen_7_families.h, src/data/pokemon/species_info/gen_8_families.h, src/data/pokemon/species_info/gen_9_families.h, src/pokemon.c
Decoupled perfect IV generation from the `isLegendary`, `isMythical`, `isUltraBeast` and `isTotem` flags by expanding `allPerfectIVs` into `perfectIVCount`.
This allows for users to customize their perfect IV counts without needing to remove other flags that may be used by them (eg, `isUltraBeast` is also used to determine Beast Ball/regular ball multipliers.
`LEGENDARY_PERFECT_IV_COUNT` is used for all Legendaries, Mythicals, Ultra Beasts and Totem Pokémon, instead of having their own defines.
=> Made perfect IV count into a granular setting

src/battle_dynamax.c, src/battle_terastal.c
Fixes Zigzaggon being able to Dynamax and Terastal on the first battle.
=> Fixes Zigzgoon battle being able to use a Gimmick

src/battle_ai_util.c, src/battle_util.c
Updates AI calcs for the Triple Kick Effect to match it closer to actual damage
=> Adjusted AI calcs for Triple Kick Effect

src/battle_util.c
#4928 follow up. 
Based on the review comments I made a function to avoid duplicating code and an array to account for speed being last to check the animation.
=> Clean up for #4928

src/battle_main.c, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/dancer.c, test/battle/gimmick/zmove.c, test/battle/move_effect/revelation_dance.c
Adds Tests for Revelation Dance.
The following Revelation Dance interactions were added:
- If a Pokémon is Typeless, Revelation Dance will have no type (in which case Revelation Dance will not receive STAB). If a Pokémon has lost its primary Flying type due to having used Roost earlier this turn and uses Revelation Dance due to Dancer, Revelation Dance's type will match its current type: its secondary type if it has any, or else be Normal-type (regardless of type additions by Forest's Curse or Trick-or-Treat).
- Typeless Revelation Dance does not activate Color Change and is blocked by Wonder Guard. Conversion 2 will fail if the last move used by the target was typeless Revelation Dance.
- Regardless of the user's types, Revelation Dance is always treated as Normal-type for Z-Move …
=> Fixes Dancer, adds Revelation Dance interactions with Z-Move, Roost and typeless mons

include/pokemon.h
Fixes wrong padding in struct SpeciesInfo that is if I counted correctly.
After I opened #5138 I realized it might be an issue on master as well.
Feel free to close one of those but I think it should be solved on master for sure as well
=> Fixes wrong padding in struct SpeciesInfo

include/tilesets.h, src/field_specials.c
Some tiles can change to PC tiles when using boxlink or the debug menu PC access.
.cawt
=> Fix specific tiles changing to pc tiles when using boxlink/debug pc

src/battle_util.c, test/battle/ability/purifying_salt.c
Fixes Purifying Salt not halving dmg for dynamic move types and replaced some hardcoded moves types with `GET_MOVE_TYPE`.
=> Fixes Purifying Salt not halving dmg for dynamic move types

src/frontier_util.c
Consolidates most of the Frontier Brain values into gFrontierBrainInfo to make adding/editing easier
sFrontierBrainsMons and sBattlePointAwards were left alone. sBattlePointAwards seemed best to leave as a sort of table the way it is now
Frankfurter0
=> Refactor Frontier Brains

include/test/battle.h, test/battle/move.c, test/test_runner_battle.c
Made the speed ties test utilize `PASSES_RANDOMLY` instead of a large `PARAMETRIZE`.
This method utilizes the properties of the moves Endeavor, Super Fang, Crush Grip and Life Dew along with chosen max/starting HP value of the player Pokemon and chosen Atk/Def values to make calculation easier.
Final HP values of Mon1 and Mon2 were calculated manually then verified in the test runner after a setup had been finalized.
hedara
=> Made the speed tie test use PASSES_RANDOMLY

src/type_icons.c
Added `FreeAllTypeIconResources` which fixed an issue with https://github.com/rh-hideout/pokeemerald-expansion/pull/5131 where the type icon sprite was not being properly handled when hidden.
```diff
Debug_EventScript_Script_1::
+    setflag FLAG_BADGE01_GET
+    setflag FLAG_BADGE02_GET
+    setflag FLAG_BADGE03_GET
+    setflag FLAG_BADGE04_GET
+    setflag FLAG_BADGE05_GET
+    setflag FLAG_BADGE06_GET
+    setflag FLAG_BADGE07_GET
+    setflag FLAG_BADGE08_GET
+    givemon SPECIES_WOBBUFFET,100,ITEM_LEPPA_BERRY
+    givemon SPECIES_GYARADOS,100,ITEM_GYARADOSITE
+    additem ITEM_MEGA_RING,1
+    setwildbattle SPECIES_WOBBUFFET,100,ITEM_LEPPA_BERRY
+    dowildbattle
release
end
```
https://github.com/user-attachments/assets/075483c1-715a-4194-8ccb-0252cf98ec99
[Reported on …
=> Fix a sprite issue with B_SHOW_TYPES

include/global.fieldmap.h, src/fieldmap.c, src/item_use.c
This is a pret merge - DO NOT SQUASH!
- pret#2011
No merge conflicts.
`5e5cde9220ed708b418f9f428c920fe0bd5d0ea7`
`cbcd1790a3967e70e40516e683e7d893895a511a`
Almost undoubtedly the result of modern dealing with the rewritten block of code in `item_use.c` differently.
bassoonian
=> Pret merge (14th of August)

include/config/battle.h
Set new anim particles by default to off
=> Set new anim particles by default to off

include/config/battle.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_script_commands.c, src/battle_util.c, src/pokemon.c, test/battle/move_effect/defog.c
Removed some hardcoded move IDs.
Also added Defog's Gen 4/5's setting by updating `B_DEFOG_CLEARS_TERRAIN` into `B_DEFOG_EFFECT_CLEARING` and updating the tests to pass instead of using an `ASSUME`
=> Removed some hardcoding of move IDs + Gen4/5 Defog

data/battle_scripts_1.s
They were the last animations that needed the use of `B_WAIT_TIME` constants.
=> Teatime animations use B_WAIT_TIME_LONG

include/battle.h, src/battle_main.c, src/battle_util.c, test/battle/ability/ice_face.c
Fixed Ice Face not transforming Eiscue back into Ice Face form when it should.
Redid the `ShouldChangeFormInWeather` function to reset the ability for Ice Face to proc when opponents set up weather.
Added Ice Face to the abilities that trigger on switch in.
Implemented all the TO_DO tests for Ice Face.
#5150 
hedara
=> Fixed Ice Face, implemented tests

include/constants/event_objects.h
Followers were breaking the game in different ways when trying to spawn a follower with species ID above 1535.
This is fixed by increasing `OBJ_EVENT_GFX_SPECIES_BITS` from 11 to 12, which should last us for quite a while.
Before:
https://github.com/user-attachments/assets/7807bb38-dcde-4762-8633-df9c705f164a
After:
https://github.com/user-attachments/assets/eb035b8e-7608-4a9f-a642-1c71112d82e9
#5105 
@mrgriffin 
@SarnPoke
hedara
=> Fixed followers breaking for species IDs above 1535

src/battle_main.c, src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/retaliate.c
If a pokemon fainted from damage at the end of turn, (e.g. Poison, Burn, Leech Seed, Bind effects), Retaliate did not get the boosted base power the next turn. Instead Retaliate was boosted on the turn after it was supposed to.
Flame Burst was also bugged, fixed it in order to make the tests work.
Moved the decrement of `retaliateTimer` to the start of turn instead of end of turn so that it doesn't matter at what point in time during the turn a pokemon faints.
Wrote tests for Retaliate interactions I could think of.
Fixed a bug with Flame Burst where current HP was used to calculate damage from Flame Burst AoE effect.
#5153 
hedara
=> Fixed Retaliate not working correctly with passive damage

src/battle_ai_switch_items.c, src/battle_ai_util.c, src/battle_util.c, test/battle/ability/ice_body.c, test/battle/ability/rain_dish.c, test/battle/weather/hail.c, test/battle/weather/sandstorm.c
Added code to make `maxHP / 16` round to 1 if 0 in several cases.
Weather damage, Ice Body healing and some AI calculations adjusted.
Wrote tests for weather damage.
Wrote 2 "TO_DO" tests found along the way.
#5180 
hedara
=> Fixed incorrect rounding when maxHP <16

src/battle_util.c
Self explanatory, the "Hit (num) time(s)" text was printing garbage if you used population bomb while holding loaded dice, as the string wasn't initialized properly. This fixes that by moving a line.
kittenchilly
=> Fix using Population Dice with Loaded Dice printing garbage text

src/battle_util.c, test/battle/ability/wind_rider.c
Adds a missing activation of Wind Rider (when switched in while Tailwind is active on the user's side of the field).
> When Tailwind takes effect on its side **or when the Pokémon with Wind Rider is sent into battle while Tailwind is in effect on its side, its Attack is increased by one stage in addition to receiving the speed boosting effect of Tailwind.**
Also adds tests for Wind Rider.
PhallenTree
=> Adds missing Wind Rider activation and tests

test/battle/move_effect/round.c
Tests for the move Round.
Tests that other battlers that selected Round moves immediately after the first user of Round, both allies and foes.
Tests that the turn order doesn't change otherwise (no exhaustive)
Tests that the other usages of Round has doubled Base Power.
Tests that #5148 hasn't been fixed.
This PR does not fix #5148, it simply implements tests for the move and the bugged behavior.
hedara
=> Round Tests

src/data/moves_info.h
Kasen just posted these in the Aqua server earlier today. Fixing them now so they don't get lost to time. They all still fit within the description box with the extra character, as seen below.
https://github.com/user-attachments/assets/39bc176e-8a31-4495-8ed5-e4de61ba4500
Kasen found the typos
@Pawkkie
=> Fix 3 move description typos

src/battle_main.c
Fixes Wild Battles using the last trainer fought's Starting Status.
Current interaction:
https://github.com/user-attachments/assets/e693dc0a-e309-47ac-87af-c2bcf9d8b2d1
Fixed interaction:
https://github.com/user-attachments/assets/165f5da7-2497-4156-bc49-2de1176d7033
PhallenTree
=> Fix Starting Status being used on Wild Battles

src/battle_main.c, test/battle/ability/adaptability.c, test/battle/ability/aerilate.c, test/battle/ability/aftermath.c
Just a few tests, also found Aerilate working incorrectly
kittenchilly
=> Adaptability, Aerilate, Aftermath tests

include/battle.h, include/random.h, src/battle_main.c, src/main.c, src/random.c, test/random.c, test/test_runner_battle.c
Removes support for the original LCG random number generator. It has been disabled since 1.8 and there is no evidence that anybody on current expansion is using it. This also removes the `HQ_RANDOM` config (it is effectively always enabled now).
tertu
=> Remove support for the original LCG random number generator

test/battle/ability/disguise.c
Adds the missing tests for the old Disguise issue.
- Type Change: If Mimikyu's type had been changed beforehand, it is restored to Ghost/Fairy when it changes to its Busted Form.
- Baton Pass: If a Pokémon that has its Ability suppressed passes that effect to a Pokémon with this Ability via Baton Pass, that effect fades.
hedara
=> Disguise tests

src/data/graphics/pokemon.h
This fixes a compilation error that occurs if OW_POKEMON_OBJECT_EVENTS is true but P_HISUIAN_FORMS is false.
The overworld graphics for red/blue striped basculin was incorrectly put within directives for the white striped basculin, so the graphics end up missing if the hisuian forms are disabled. This separates the logic out to prevent a compilation error.
hjk321
=> Basculin graphics config fix

include/battle.h, include/battle_util.h, src/battle_script_commands.c, src/battle_util.c
Made it so that the Z-Move animation doesn't play when the battler doesn't obey, and doesn't "waste" the Z-Move activation.
Used 3 bits in the `BattleStruct` to store the obedience result.
The obedience check is then moved to before the battler has done anything in the turn and the Z-Move activation can then check for obedience.
Z-Move flags for the battler are then cleared in order to not interfere with the next turn.
https://github.com/user-attachments/assets/8dfc7308-c71c-42fa-bbde-85ba254ee84c
Fixes #3333 
hedara
=> Fixed Z-Moves+Obedience bugged behavior

include/battle_scripts.h
removes an unused battlescript signature. the battlescript doesnt exist and is not referenced anywhere.
likely leftover from initial implementation. 
u8-Salem
=> remove unused bs signature

src/battle_ai_main.c
Encourages the AI to use an "always crit" move on its partner, if that partner has the Anger Point ability.
sarnnn
=> Add Anger Point/Crit Moves Doubles AI Interaction

include/battle_controllers.h, src/battle_controller_player.c, src/type_icons.c
Improved `ShouldHideTypeIcon` to fix https://github.com/rh-hideout/pokeemerald-expansion/pull/5200.
```diff
Debug_EventScript_Script_1::
+	setflag FLAG_BADGE01_GET
+	setflag FLAG_BADGE02_GET
+	setflag FLAG_BADGE03_GET
+	setflag FLAG_BADGE04_GET
+	setflag FLAG_BADGE05_GET
+	setflag FLAG_BADGE06_GET
+	setflag FLAG_BADGE07_GET
+	setflag FLAG_BADGE08_GET
+	givemon SPECIES_TEDDIURSA, 100,0,move1=MOVE_EARTHQUAKE, move2=MOVE_WICKED_BLOW
+	givemon SPECIES_WATTREL,100,0,move1=MOVE_CELEBRATE, move2=MOVE_THUNDERBOLT
+	setwildbattle SPECIES_ELECTABUZZ,50,0,SPECIES_MAGMAR,50,0
+	dowildbattle
release
end
```
https://github.com/user-attachments/assets/ed92c2b0-d54f-4f97-b9bb-fb2539eac8ff
https://github.com/rh-hideout/pokeemerald-expansion/pull/5200
@iriv24
I am pkmnsnfrn and there is a [discussion …
=> Fix a display issue with B_SHOW_TYPES

src/battle_script_commands.c, test/battle/ability/parental_bond.c
Added an exception to `MOVEEND_MULTIHIT_MOVE` so that the multi-hit doesn't get canceled if the current move is Snore and the user is asleep.
Fixes #5029 
hedara
=> Fixed Snore not hitting twice with Parental Bond

src/data/moves_info.h
The descriptions for frostbite and freeze for Ice Fang were in the wrong order.
As far as I could see Ice Fang was the only mix up for freeze/ frostbite move descriptions.
The descriptions for frostbite and freeze for Ice Fang were in the wrong order, I swapped them to the correct order.
laserxdolphin
=> Fixed swapped frostbite and freeze descriptions for Ice Fang

include/battle.h, include/config/battle.h, src/battle_script_commands.c, src/battle_tv.c, src/battle_util.c, test/battle/move_effect/charge.c
The status expiring is based on the move used next turn and not a timer.
=> Fixes Charged up status

include/global.h
Adds a way to measure cycle counts.
`CycleCountStart` starts the counter.
`CycleCountEnd` stops the counter and returns the number of CPU cycles since start. (Should be accurate within tens of cycles)
This is locked behind commenting out `#define NDEBUG` in `include/config/general.h`.
@SBird1337 , provided the actual code.
hedara
=> Added performance counter

src/battle_script_commands.c, test/battle/move_effect/multi_hit.c, test/battle/move_effect/round.c
Fixes #5148
Also fixes Scale Shot not activating when `gMultiHitCounter` was not decreased to zero while opposing mon fainted.
=> Fixes Scale Shot not activating + Known Failing Round test

include/constants/battle_ai.h, src/data/trainers.h, src/data/trainers.party
Consolidates some flags into Basic and Smart trainer
=> Adds basic trainer and smart trainer flags

src/battle_util.c
=> Fixes dmax move base power not seen by ai

include/frontier_util.h, src/battle_arena.c, src/battle_dome.c, src/battle_factory.c, src/battle_main.c, src/battle_palace.c, src/battle_pike.c, src/battle_pyramid.c, src/battle_tent.c, src/battle_tower.c, src/frontier_util.c
Fixes the Battle Factory and Slateport Battle Tent returning no Pokémon when the player wants to swap their Pokémon with one of the Pokémon from the last opponent.
Fix for #5082
https://github.com/user-attachments/assets/af9ef3c1-41be-48f6-81b5-9dd106ebd8ee
Fix for #5280
https://github.com/user-attachments/assets/ac853b13-a689-4878-844d-d9733cb7198d
Fixes #5082 
Fixes #5280
sarnnn
=> Fix Slateport Battle Tent/Battle Factory

src/battle_ai_main.c
Wiz pinged me this afternoon having encountered weird behaviour while developing one of their escape rooms. In this scenario, the player's Porygon has Wonder Guard, and the AI has no moves that can affect it (Astonish, Rest, Rock Slide). The AI uses Rest until it runs out of PP, and then the game hangs, because all 3 moves have an AI score of 0, but 2 of the moves still have PP so it can't use struggle.
On investigation, this seems to be related to the way Check Bad Move handles Wonder Guard. Currently, it just returns a score of 0 if the move can't damage the Wonder Guard mon.
This PR changes this line to return a 1 instead, which should be lower than virtually all other legal move options, but is still nonzero so the AI can select it in battle if required.
Open to criticism or …
=> Wonder Guard AI Fix

docs/ai_flags.md, include/constants/battle_ai.h, src/battle_ai_main.c, src/data/trainers.h, src/data/trainers.party
Addresses the concerns outlined in #5303 explicitly
Fixes #5303 
Alex, psf
Pawkkie
=> AI_FLAG_SETUP_FIRST_TURN Rename and Clarifications

src/battle_util.c
In Gen 3 and 4, Future Sight, Beat Up and Doom Desire deals typeless damage.
#3522 
hedara
=> Fix Gen 3 foreseen and Beat Up damage type

src/battle_script_commands.c
Uses `GetBattlerForBattleScript` instead of `GetBattlerAtPosition`
=> Fix Cmd_trainerslidein/out

src/wild_encounter.c
During my review of #5313 I overlooked that the function vars used a u8 instead of u32. This follow up fixes it
=> RTC-based wild encounters follow up

src/battle_ai_util.c
Fixes minor wrong order in `AI_CalcDamage` and adds Tera Blast/Tera Storm
Nature Power should always be decided before the Z move because the outcome influences the z move chosen.
Also Tera Blast/Storm were missing and for better readability I changed it to a switch.
=> Fixes minor wrong order in AI_CalcDamage and adds Tera Blast/Tera Storm

include/config/overworld.h, include/wild_encounter.h, src/data/wild_encounters.json.txt, src/wild_encounter.c, tools/jsonproc/jsonproc.cpp
As pointed out by Jasper this implementation has flaws.
=> Revert rtc based encounters

src/battle_script_commands.c, test/battle/move_effect/pledge.c
Fixes Pledge move combos attempting to be executed multiple times in a turn, causing mons to decrement sleep timer multiple times during the turn or causing infinite loops.
Fixes Pledge move combos sometimes being executed despite one of the mons being unable to act.
Adds tests for most cases presented in #5041, but I wasn't able to replicate all situations described, so I'm not sure if all were fixed.
Partially? fixes    #5041
#5329
PhallenTree
=> Fix some Pledge move combo issues

src/battle_script_commands.c, test/battle/move_effect/pledge.c
If a called pledge execution failed due to the 'mon being incapacitated, the pledge status was still `TRUE` in `gBattleStruct` which messed up the execution flow if the opponent was also using a pledge move.
Setting the pledge status to `FALSE` if the 'mon fails to move solves this.
Fixes #5329 
@PhallenTree found the issue, wrote the test and pointed in the right direction with the other pledge fix
hedara
=> Pledge fail into opponent pledge loop fix

src/battle_util.c, test/battle/move_effect/pledge.c
Fixes the looping/timeout from #5329 happening with Freeze instead of sleep. Happened since Freeze never sets `HITMARKER_UNABLE_TO_USE_MOVE` (which was required by #5339 's fix)
PhallenTree
=> Fixes Pledge move combo timeout if frozen

src/battle_util.c, test/battle/move_effect/pledge.c
Powder was missing a `gHitMarker |= HITMARKER_UNABLE_TO_USE_MOVE` which could cause an infinite loop.
hedara
=> Another Pledge fix, Powder this time

docs/ai_flags.md
Adds `AI_FLAG_BASIC_TRAINER` and `AI_FLAG_SMART_TRAINER` to the AI flags documentation. Forgot about this document when they were introduced in #5298.
Targeting upcoming because those flags are only in upcoming :)
@Pawkkie
=> Add Composite AI Flags to Docs

src/overworld.c
When loading the map from the save, it didn't actually read `gSaveBlock1Ptr->mapLayoutId` anywhere, so the "default" layout was always loaded, and no transition script could actually run to change it on a save load.
This change makes the map you load into match the one saved in.
It was not extensively tested, just in shoal cave, that it works and in other maps that nothing is immediately broken.
https://github.com/user-attachments/assets/440a1009-ed5f-4e8d-a410-2b14f03dc582
Fixes #5343 
hedara
=> Fixed loading into the wrong version of a map after saving in areas with multiple layouts

include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_util.c, src/battle_util.c
`AI_GetBattlerMoveTargetType`was redundant because `GetBattlerMoveTargetType` does the same thing and was updated.
=> Removes redundant moveTargetType ai function

src/battle_ai_util.c
Addresses issues brought up in #5272. The ties were the result of a flat +1 score increase to any burning move as long as the AI was able to burn the target, in all cases. This increase has now been gated behind checks for the player mon having a physical attacking move that the AI knows about, or guessing that it might be a physical attacker based on its base stats. The stronger stat increase in the case of very high incoming damage was also improved to ensure as best we can that the incoming damage is physical nature before applying the score increase.
Scoring after fix
Fixes #5272 
@iriv24 and @AlexOn1ine
@Pawkkie @iriv24
=> AI burn score fixes and improvements

src/new_game.c
#4767 missed resetting item flags when a new game was started. This handles that
=> Reset item flags on new game

src/battle_ai_util.c
This is *exactly* the same changes made in #5356 and fixes the same issue, they're just applied to Frostbite instead of Burn. Shoutout to @kittenchilly for the suggestion.
While we don't have a Frostbite copy of Will-O-Wisp, `IncreaseFrostbiteScore` is still used in the existing codebase when handling Psycho Shift, and as such I don't see a reason that its AI shouldn't be kept at parity with Burn's in the same scenarios. The real reason behind supporting parity in my opinion is because of how commonly users make frostbite equivalents for burning moves like Scald and Will-O-Wisp, and while I understand that supporting that as the only reason may be out of scope, we *do* use identical handling for Psycho Shift anyways, so I don't see this as being a problem.
@kittenchilly for the …
=> AI frostbite score fixes and improvements

src/battle_ai_util.c
Full credit to @ghoulslash for this I'm just PRing it.
In `AI_IsMoveEffectInPlus`, the check for move effects that lower stats by 2 stages uses the incorrect effect Id. When `ShouldLowerStat` is called, it knows what stat to reference by offsetting the move effect such that it relates to the 0 - 6 scale of Pokemon stats.
This works as intended for the cases where single stage effects are offset by `MOVE_EFFECT_ATK_MINUS_1`, but two stage effects are also offset by `MOVE_EFFECT_ATK_MINUS_1` when they should be offset by `MOVE_EFFECT_ATK_MINUS_2`. This PR just corrects that offset.
Fixes #5197 
@ghoulslash for identifying / fixing, I'm just PRing it and explaining it for posterity.
@Pawkkie
=> IsMoveEffectInPlus stat Id fix

src/battle_util.c, test/battle/move_effect/pledge.c
Using a Pledge combo into a matching absorption ability was bugged.
Resets the `gBattleStruct->pledgeMove` to `FALSE` is it's `TRUE` and the pledge is attacking into a matching absorption ability.
Wrote tests for these cases.
hedara
=> Fixes with Pledge combos and absorption abilities

src/battle_ai_switch_items.c
Addresses #5218 by adding a check for Focus Sash and Sturdy to the hitsToKO calculation that the smart switching AI flags use. Other cases are already handled in the damage calc and I didn't realize it at the time of suggestion :)
Closes #5218 
@Pawkkie
=> Switch AI hitsToKO considers one shot prevention

src/battle_ai_switch_items.c
Cleanup / addition to #5371 that I was reminded about with #5373. Lets the smart switch AI's hitsToKO calculation consider Disguise, and also checks the player's mon for mold breaker abilities.
Extends #5371 
@Pawkkie
=> Switch AI hitsToKO considers Disguise

include/event_object_movement.h, src/data/object_events/object_event_anims.h, src/data/pokemon/species_info.h, src/data/pokemon/species_info/gen_1_families.h
Introduces the `OVERWORLD_SET_ANIM` macro which works like the regular `OVERWORLD` macro, except that it takes a fifth required argument which is a `sAnimTable`.
Partially #5135 
Asymmetric sprites other than Farfetch'd
hedara
=> Custom anim table follower macro & Farfetch'd example

data/battle_scripts_1.s, include/battle_scripts.h, include/config/battle.h, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/dancer.c, test/battle/gimmick/zmove.c, test/battle/move_effect/pledge.c, test/battle/move_effect/powder.c
Simplified the fix from #4638 to use a more suitable HitMarker.
Other fixed interactions:
> - If a Pokémon with Magic Guard affected by Powder attempts to use a Fire-type move, it will fail to execute the move but take no damage.
> **Generation VII**
> - Powder will no longer damage the Pokémon during heavy rain.
> - If a Pokémon affected by Powder uses Fire Pledge after an ally uses Water Pledge, such that the Pokémon ends up using Water Pledge as a combination move, Powder will not affect that move. If a Pokémon affected by Powder uses Fire Pledge otherwise (including as the first move of a combination move, or when using Grass Pledge as a combination move after an ally's Fire Pledge), Fire Pledge will be prevented by Powder like any other Fire-type move.
Currently it stopped all first …
=> Fixes Powder (status) interactions + tests

src/battle_script_commands.c, test/battle/move_effect/after_you.c, test/battle/move_effect/shell_trap.c
Fixes `ChangeOrderTargetAfterAttacker` (used by both moves) not changing battlers' actions to reflect the new turn order. (`gActionsByTurnOrder`)
In the test presented in the issue, it saw the After You target having the action "NothingFainted" (since the battler which originally would move after the user of After You was the fainted Pidgeot) which made it not act. I presume similar effects may happen with other actions that don't happen before After You can be used.
Current interaction:
https://github.com/user-attachments/assets/8c9f0d70-329a-4e33-8cbc-648e224130be
Confirmed that the same issue occurred with Shell Trap.
Added the test from #5316 and a similar one for Shell Trap.
Fixes #5316 
PhallenTree
=> Fixes After You/Shell Trap not updating battlers' actions correctly

src/battle_script_commands.c, test/battle/move_effect/defog.c
=> Fixes Defog used by the wrong side when there is a Substitue and Screen

include/battle.h, src/battle_anim_mons.c, src/battle_debug.c, src/battle_message.c, src/battle_script_commands.c, src/battle_tv.c, src/pokeball.c, src/type_icons.c
Closes #2656
The function was already present. I just renamed it to represent more what it does and cleaned up the code I could
=> Cleaned up a bit of code with GetBattlerPartyData

src/battle_script_commands.c
`MAX_BATTLERS_COUNT` can be used here because we iterate over max battlers in the first place.
=> Remove potential uninitialized behavior

src/map_name_popup.c
This is a minor tweak to fallback to the default BW map pop-up theme if the current map section isn't in the theme array (`sRegionMapSectionId_To_PopUpThemeIdMapping_BW[]`), so that users won't encounter issues if they forget to include their new map section in it.
This doesn't actually address the potential UB of accessing the `sRegionMapSectionId_To_PopUpThemeIdMapping_BW[]` array out of bounds. This could mask errors, but it's my impression that this is not really likely to happen. Please let me know if that's a bad assumption.
An example of the behavior before the fix if you don't include the new map section in the theme array:
Common source of error when adding new map sections while using BW map pop-ups.
ravepossum
=> Fallback on default BW map pop-up theme to reduce potential for error

data/battle_scripts_1.s, include/battle_scripts.h, src/battle_script_commands.c, test/battle/move_effect/multi_hit.c
When Scale shot was used the previous turn it caused a multi target hit move not to hit all targets. I don't really have an explanation to why it happened but this fixes it.
I also cleaned up some leftover caused by the multi hit refactor
=> Fixed corruption of the next turn used move caused by Scale Shot

include/config/battle.h, src/battle_script_commands.c, test/battle/move_effect/after_you.c, test/battle/move_effect/quash.c
Quash's current implementation has a fair amount of problems (in `BS_TryQuash`), which have been fixed.
- First, it changes `gBattlersByTurnOrder` but not `gActionsByTurnOrder` which causes the same issue described in #5384.
- Due to `if (!gProtectStructs[i].quash && !gProtectStructs[j].quash && GetWhichBattlerFaster(gBattlerByTurnOrder[i], gBattlerByTurnOrder[j], FALSE) == -1)`, anyone affected by Quash will move in that order (player's Left mon would move first, opponent's Left mon would move second, etc.)
- Also after executing some swaps, it checks the wrong battler's Quash bit.
- It also doesn't properly follow either of the turn order interactions (Gen5-7 or Gen8+).
If you don't want spend a lot of time analyzing the current implementation's code, here's a rundown:
- Turn order is …
=> Fix Quash implementation, adds After You and Quash missing configs + tests

src/pokemon.c
Fun fact: By setting maxHP for Shedinja earlier in the code, we do not need to worry about it for calculating HP later down the line.
What only matters is: currentHP only increases if the maxHP is greater than previous maxHP (currentHP can never go down), and currentHP is always at most maxHP.
currentHP cannot be more than newMaxHP anyway unless it already was prior.
RSilicon
=> Simplify HP Logic

data/battle_scripts_1.s, src/battle_util.c
Anger Shell uses `saveattacker` instead of overwriting gBattlerAttacker (could be relevant in double battles)
=> anger shell use saveattacker

src/battle_ai_main.c
Simply checks if the AI knows the opponent has a held item before running the code that gives score depending on what hold effect it is. Before it always gave a weak score to the move even if the opponent had no held item.
Fixes #5411
kittenchilly
=> Fix Trick/Switcheroo giving AI score even if the opponent has no held item

data/battle_anim_scripts.s, src/battle_anim_effects_3.c
Get rid of the transform/mozaic animation that serves no purpose
Applied it for primal reversions and ultra burst as well.
The function can be partly imitated to hide the sprite during the animation of other gimmicks so that it doesn't flicker/appear too early
See the difference here : https://discord.com/channels/419213663107416084/774393519569502268/1251840634264748074
=> Mega evolution animation is a little smoother

src/battle_util.c
The function IsMoveMakingContanct does not have the protective pads check anymore which means the comment wasn't accurate and the function can be used.
Also reordered the checks to have the most cost heavy happen at the end.
=> Clean up Unseen Fist Check

test/battle/ability/tangling_hair.c
Adds rocky helmet dmg element to last tangling hair + defiant test to make sure that the chained effects do not overwrite relevant battler Ids.
=> Tangling Hair Test Additional Check

data/battle_scripts_1.s, include/battle.h, include/battle_scripts.h, include/battle_util.h, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/dancer.c, test/battle/ability/trace.c, test/battle/form_change/primal_reversion.c, test/battle/move_effect/dragon_darts.c
- Adds Snatch interactions with Swallow and Dancer:
> Dancer will not activate if the move is stolen by Snatch.
> If Swallow is stolen and the user of Snatch is not under the effects of Stockpile, it will nonetheless recover 25% of its max HP.
- Fixes Electrified Dragon Darts sometimes not correctly avoiding targets with ability immunity (Volt Absorb, Motor Drive)
- Fixes Trace not activating a switch-in ability it traces, removes unused `RESOURCE_FLAG_TRACED`.
- Fixes multiple Primal Reversions not occurring after multiple battlers fainted.
- Fixes the wrong battler's ability pop up occuring from #5427 (doesn't fix other battlers' Booster Energy not activating)
- Simplified Quash code (assumes the turn order is correct when using the move)
Added tests for Dancer; also for the Dragon …
=> Adds some Snatch interactions, fixes for Dragon Darts, Trace, Primal Reversion, Protosynthesis/Quark Drive

src/battle_main.c
Note: The messages will be wrong if someone uses those effects on other moves so maybe hard-coding is better in this case to keep the accuracy
=> Use move effect for some moves instead of ids

include/battle.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c, src/battle_main.c
Addresses #5380, reducing the number of `ShouldSwitch` function calls by doing it once at the start of the turn and using that result everywhere else `ShouldSwitch` is used where `emitResult` is set to false. 
I chose to do this in `HandleTurnActionSelectionState` because as we continue to expand the AI logic into player prediction in particular this result is likely to be referenced in progressively broader contexts, and initializing it here ensures it's ready to go before any of the scoring happens, which is similar logic to why `mostSuitableMonId` is initialized here after it was refactored in the same way.
I also renamed `shouldSwitchMon` in the same struct to `shouldSwitchIfBadMoves` to be more explicit about what it's used for but mostly to avoid confusion by having both …
=> Add ShouldSwitch result to AiLogicData

tools/mgba-rom-test-hydra/main.c
Probably this was a case of bad copy-paste.
=> Fixed test assumption fail summary fields using more memory than needed

src/battle_script_commands.c
Happened to be scrolling the branches on TAAR today, realized some of mine were outdated, got to this one and thought "hang on this is totally in scope for expansion isn't it"
This is basically an exact update of my branch to current expansion, that implementation has been working (or at least no one has ever told me it's not working lol) since 1.7.X and I know at least a handful of folks have used it, so I didn't want to do any unnecessary overhauls unless it was determined to be a good idea in review.
I've left in the more liberal comments I included in the branch as it was originally requested by someone who wasn't a programmer, though in this case I think they help guide customization as gen 1 crit mechanics behave so radically differently from the rest of the series. Feel free to …
=> Add Gen 1 Crit Chance

src/data/items.h, test/battle/item_effect/cure_status.c
Fixes Jubilife Muffin not actually working, due to a missing effect.
Also adds Jubilife Muffin to local specialty and full heal tests, as well as adding frostbite to the test which was missing.
kittenchilly
=> Fix Jubilife Muffin full heal effect + better full heal tests

test/battle/ability/commander.c
Fixes the fact that two Commander tests shared a name, even if it was unrelated to the actual contents of one of the tests
bassoonian
=> Fix Commander test name

include/party_menu.h, src/battle_controller_player.c, src/party_menu.c
In doubles, if you choose to use a flute item on battler 0 and then cancel, you end up with 2 flutes
=> Fix duplicating flute bug

src/battle_main.c, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/protosynthesis.c, test/battle/ability/quark_drive.c
- Fixes Protosynthesis and Quark Drive sometimes not activating ability popup but gaining the boost. (example: Iron Jugulis would not display the ability popup but gain the boost if Quark Drive was activated by Electric Terrain)
> Protosynthesis will activate in harsh sunlight even if the Pokémon is holding a Utility Umbrella, but not if a Pokémon with Air Lock or Cloud Nine is on the field.
> Quark Drive will activate even if the Pokémon is not grounded.
Also adds interaction with Transform.
> If a Pokémon obtains Protosynthesis/Quark Drive with Imposter or Transform, the Ability will not activate regardless of if the Pokémon is affected by harsh sunlight/on Electric Terrain or holding a Booster Energy.
- Fixes Protosynthesis and Orichalcum Pulse granting the boost despite Air Lock/Cloud …
=> Fixes to Protosynthesis, Quark Drive, Beast Boost, Orichalcum Pulse, Hadron Engine

include/test/battle.h, test/battle/ai/ai_switching.c, test/test_runner_battle.c
The AI tests weren't having their state reset between PASSES_RANDOMLY runs, which meant that every run but the first one was checking the wrong information. This PR fixes that behaviour, and fixes the one AI test that used PASSES_RANDOMLY while it was broken. This is all mgriffin not me :)
@mrgriffin Did the whole thing :D
@Pawkkie
=> Fix AI tests using PASSES_RANDOMLY

src/battle_util.c
`gLastLandedMoves` and `gLastHitByType` aren't used very often, but they are used for both Conversion 2's functionality and by the switch AI to determine whether the AI can switch in a mon that absorbs the last move they were hit by.
Now that we can write PASSES_RANDOMLY tests and I'm refactoring `ShouldSwitch` ahead of switch prediction, I discovered that both of these terms were being reset at the end of the turn, which means no continuity across turns, breaking both of these functions.
Alex helped brainstorm solutions and identified exactly where this needed to be removed from. Not including tests for the absorb switching as they'll be coming with the refactor instead, as the `RandomPercentage` changes are more invasive than what I typically PR to master.
@AlexOn1ine 
@Pawkkie
=> Fix certain move data being cleared on turn end

src/battle_main.c
This is already run at the end of `TryDoEventsBeforeFirstTurn` which makes the first calc redundant.
I've had this removed in my project for a while and didn't notice any problems
=> Remove one redundant call of SetAiLogicDataForTurn in DoBattleIntro

include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_util.c, src/battle_main.c, src/battle_util.c
As far as I can see `AI_IsBattlerGrounded` and `AI_IsTerrainAffected` are the last remaining functions that were duplicates in `battle_ai_util.c`
Also supersedes a little bit #5489. It applies the same concept but does it inside `IsBattlerGrounded` instead of `GetBattlerAbility` since `GetBattlerAbility` isn't used anywhere else in AI functions. 
And renames `GetBattlerAbility2` to `IsBattlerGroundedInverseCheck`
=> Unify GetBattlerAbility/TerrainAffected to remove duplicate ai function

src/pokemon.c
The P_FRIENDSHIP_EVO_THRESHOLD config accidentally checked for Gen 9 for if the new threshold should be applied and not Gen 8 (which is how it should be), so I fixed that. Don't know how this slipped past.
kittenchilly
=> Fix P_FRIENDSHIP_EVO_THRESHOLD not checking for Gen 8

include/battle_anim.h
Removed `sub_810E2C8` from `include/battle_anim.h` which was renamed to `DestroyAnimSpriteAfterTimer` but was still present in Expansion.
sha1sum before removal: `26b50cc7ebc7be904aea2d21a12306504927aaa3  pokeemerald.gba `
sha1sum after removal: `26b50cc7ebc7be904aea2d21a12306504927aaa3  pokeemerald.gba`
hedara
=> Cleanup extraneous function in battle_anim.h

src/berry.c
Fixes an issue with the mutation reading code that would attempt to look up spot `-1` in a table, resulting in it reading garbage and returning `Persim Berry` through sheer coincidence.
Fixes #5432
bassoonian
=> Fix negative mutation value

include/config/battle.h, src/battle_main.c, src/battle_script_commands.c, src/battle_util.c, src/overworld.c
Adds `B_FLAG_NO_RUNNING` that when set, prevents the player from being able to run from wild battles. This also prevents Roar/Whirlwind from working. One possible application for this is preventing the player from running during scripted wild totem battles or other perceived "important" story battles with wild Pokémon.
sarnnn
=> Add battle flag that prevents running from wild Pokémon

include/field_specials.h, src/field_specials.c, src/scrcmd.c
#5177 added a lot of nice scripting macros, but a few oversights went unnoticed. This PR fixes these.
bassoonian
=> Clean up scrcmd PR

src/data/abilities.h, src/data/items.h, src/data/moves_info.h, src/data/pokemon/species_info/gen_2_families.h, src/data/pokemon/species_info/gen_3_families.h, src/data/pokemon/species_info/gen_4_families.h, src/data/pokemon/species_info/gen_5_families.h, src/data/pokemon/species_info/gen_6_families.h, src/data/pokemon/species_info/gen_7_families.h, src/data/pokemon/species_info/gen_8_families.h, src/data/pokemon/species_info/gen_9_families.h, src/data/pokemon/species_info/shared_dex_text.h, test/text.c
And fixes any that failed those tests.
Width to check against was taken from vanilla description sizes and the boxes any text was contained in.
kittenchilly
=> Add text width tests for move, ability, item, and pokedex descriptions

ld_script.ld, ld_script_modern.ld
I opened a PR a while back to add EWRAM_INIT support to the project. The linker script modifications I made didn't take into account that users may define data sections that are not a multiple of 4 bytes in size. This leads the DMA transfer at init to copy garbage into the wrong sections, resulting in subtle errors at runtime when the feature is used. I've also aligned IWRAM_DATA to prevent the same error.
This is a one-line change, allow me to explain what's happening:
```diff
.ewram ORIGIN(EWRAM) : AT (__ewram_lma)
ALIGN(4)
{
__ewram_start = .;
*(.ewram*);
+        . = ALIGN(4);
__ewram_end = .;
} > EWRAM
```
The `.` represents an address marching ahead in memory in ld scripts as each section is defined/filled. If we added a `EWRAM_INIT u8 foo = 1;` then this section would resolve …
=> Fix alignment errors in EWRAM_INIT and friends when using u8, u16, etc.

src/battle_script_commands.c, test/battle/ability/emergency_exit.c, test/battle/crit_chance.c
Introduces the function `GetCritHitOdds` to switch between generational critical hits. 
Also I turned the macro `BENEFITS_FROM_LEEK` into an inline function for better readability and removed `ASSUME(B_CRIT_CHANCE >= GEN_7);` from `crit_chance.c`. Correct me if I'm wrong but it seems to me that it isn't needed by any current tests. If I'm wrong I can add it back to the specific tests which would need it.
=> Removes Crit Chance preproc

data/battle_scripts_1.s
Originally from #5253, separated this into its own PR.
> From [Pokémon Brilliant Diamond and Shining Pearl](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Brilliant_Diamond_and_Shining_Pearl) onwards, Follow Me fails in Single Battles.
=> Fix Follow Me failing in Single Battles for Gen 6/7 config

include/test/battle.h, test/battle/ai/ai_flag_sequence_switching.c, test/battle/ai/ai_switching.c
If you rename Leaf (or do decap or anything else), the AI tests have their message fail because the trainer name no longer matches. This PR centralises the AI trainer name and uses it in the message checks so that downstream users can simply change the define and they won't run into new expansion AI tests failing because they didn't update their messages.
bassoonian
=> Centralise AI Tests trainer name

src/battle_ai_util.c
In `AI_CalcDamage` a global was used for the Terastorm check instead of passed var
=> Global is used instead of passed var

src/battle_main.c
I don't think this fixes anything but better to pass a normal var instead of a global if possible. I used i because it's free.
=> Remove unnecessary gBattlerAttacker usage

include/sound.h, src/battle_main.c, src/sound.c, test/test_runner.c, tools/mgba-rom-test-hydra/elf.h, tools/mgba-rom-test-hydra/main.c
Extends `mgba-rom-test-hydra` to look up the symbols associated with pointers printed via `%p` and extends the test runner to detect any leaking tasks and print them.
For example:
```c
static void Task_LeakingTask(u8)
{
}
TEST("Task Leak")
{
CreateTask(Task_LeakingTask, 0);
}
```
Produces this output:
```
[0] Task Leak: FAIL
<Task_LeakingTask>: task not freed
```
And for `%p`:
```c
TEST("Addresses")
{
Test_MgbaPrintf("%p %p", &gPlayerParty[3], VarGet);
EXPECT(FALSE);
}
```
```
[0] Addresses: FAIL
<gPlayerParty+0x12c> <VarGet>
```
=> Tests: detect task leaks

src/pokedex_plus_hgss.c
After searching, selecting an evo from the evos page, and then backing out to the list again, the HGSS dex would display the wrong name and sprite. This is because the `sPokedexListItem->dexNum` field is overwritten by the evos page and never restored.
This is not an issue for the regular dex list because it always rebuilds the whole dex list. The search list does not, so the field needs to be restored manually. We could potentially re-run the search instead to match the normal dex list, but this seemed more efficient to me.
Fixes #3960 
ravepossum
=> Fix HGSS dex search printing wrong mon after selecting evos

include/event_object_movement.h, include/global.fieldmap.h, src/event_object_movement.c, src/pokemon_sprite_visualizer.c
Fixes followers breaking for females with high species numbers.
Removed vestigial shiny handler not present in the expansion version of the followers branch since it's handled with a bitfield instead.
Updated a `graphicsId` comment to represent current expansion status.
Fixed this fix breaking followers in the sprite visualizer.
Changed a follower form extraction to use updated expansion values (maybe, I don't know if that function actually does that, hopefully someone who knows more can verify)
https://github.com/user-attachments/assets/04f66642-2eae-479a-85e2-37c667b99b96
Fixes #5470 
Hisuan Sneasel brokeness in sprite visualizer
hedara
=> Follower female fix

include/random.h, src/battle_util.c, test/battle/ability/healer.c
Adds tests for Healer ~~because I need to reference RNG_HEALER for sleep clause tests~~
I'm not entirely sure how to handle the test for curing Freeze, as the Wobbuffet thaws before Healer can cure it based on `RNG_FROZEN`, and I'm not sure how to (or if we even can?) nest `PASSES_RANDOMLY` statements. Hardcoding the 20% chance reduction and using `PASSES_RANDOMLY(24, 100, RNG_HEALER)` for Freeze didn't work unfortunately.
Note that one of these that should pass according to Bulbapedia fails, I've marked it as `KNOWN_FAILING`.
Pawkkie
=> Healer ability tests

src/mini_printf.c
`mini_printf.c` does not build due to `#include "string_util.h"` being lost during a pret merge. The exact error is about `StringLength` not being defined.
=> Missing string_util.h include in mini_printf.c

src/battle_util.c, test/battle/ability/shed_skin.c
This is maybe the pettiest looking PR I've ever made, but I realized this was "broken" while writing tests for the sleep clause branch iriv and I are working on.
Shed Skin triggers 30% of the time in Gen 4, and 1/3 of the time otherwise, according to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Shed_Skin_(Ability)#Effect). As is, it triggers 30% of the time with configs set to Gen 4 or higher.
Gotta get that sweet sweet 3% proc chance ~~and fix my sleep clause test~~
Pawkkie
=> Shed Skin chance fix

include/test/battle.h, include/test/test.h
`__attribute__((used))` to future-proof against disabling `-fno-toplevel-reorder` (e.g. a future iteration on #5515, see https://github.com/rh-hideout/pokeemerald-expansion/pull/5515#issuecomment-2408648464)
=> Mark all tests as used

tools/mgba-rom-test-hydra/Makefile, tools/mgba-rom-test-hydra/main.c
Zatsu noticed that CI doesn't declare `memmem` (but I suppose it must be available because we don't get a linker error... Meaning that the implicit definition casts a `void *` to `int` and causes hell to break loose). To support systems which don't provide `memmem` at all, I've added a very naive implementation for when `_GNU_SOURCE` isn't set (see [`memmem(3)`](https://www.man7.org/linux/man-pages/man3/memmem.3.html)).
EDIT: Please double-check my logic in `memmem`. I implemented it very quickly and carelessly.
=> Fallback memmem implementation

src/battle_util.c, test/battle/move_effect/salt_cure.c
Fixes Salt Cure damaging Magic Guard users and changed the Magic Guard macro to a static inline
=> Fixes Magic Guard not preventing Salt Cure

test/battle/terrain/starting_terrain.c
Starting terrain tests weren't run if `B_VAR_STARTING_STATUS` wasn't set, so errors in the test didn't show up when running `make check`.
This fixes the illegal ability for the Grassy Terrain setter and the short-form Grassy Terrain text.
This does not cause the test to run if `B_VAR_STARTING_STATUS` isn't set.
hedara
=> Fixed broken Starting Terrain test

Makefile
This fixes unnecessary extra dependency scanning currently being performed by the Makefile that's slowing down builds quite a bit. It occurs on every build, not just test ones.
The changes are based on the ones in [this pret PR from pfero](https://github.com/pret/pokeemerald/pull/2046).
It also fixes the test ROM names erroneously including "agbcc" (which was causing them to not get caught by `make clean`).
- Builds being slow after the recent makefile merged (notable by multiple people in discord)
ravepossum
=> Fix unnecessary dependency scanning for test build and test rom names

src/data/object_events/object_event_pic_tables_followers.h
Some 64px followers had their tile size set to 4 by 4 instead of the correct 8 by 8.
This only became a problem for uncompressed follower for some reason?
Test by setting `OW_GFX_COMPRESS` to `FALSE` and use, for example, Groudon as a follower.
Fixes #5592 
hedara
=> Fixed 64px uncompressed followers

docs/tutorials/ai_flags.md, include/constants/battle_ai.h, src/battle_ai_switch_items.c, src/battle_controller_opponent.c, test/battle/ai/ai_double_ace.c
This flag allows trainers to avoid switching in their last two Pokémon at all costs, unless there's no other option. It is intended for double battles because it symbolizes that two trainers that act as one still have their own Ace Pokémon. It still works as well with single battles.
* As the flag logic ended up being identical to `AI_FLAG_ACE_POKEMON` I didn't make tests for single battles.
* Thought about it but I have no idea about how to make `AI_FLAG_ACE_POKEMON` extensible so you can choose how many Aces the trainer has. Maybe by adding it as a member in `struct Trainer` instead of making it a flag.
* There's no order for these Ace Pokémon. Both sides will switchin them if there's no other option left.
@ghoulmage
=> New AI flag for marking the two last Pokémon as Ace Pokémon.

src/battle_util.c, test/battle/ability/transistor.c
* The following abilities modify the attack stat, not move base power. Source Showdown and Bulbapedia
* ABILITY_TRANSISTOR
* ABILITY_DRAGONS_MAW
* ABILITY_GORILLA_TACTICS
* ABILITY_ROCKY_PAYLOAD
* ABILITY_PROTOSYNTHESIS
* ABILITY_QUARK_DRIVE
* ABILITY_ORICHALCUM_PULSE
* ABILITY_HADRON_ENGINE
Also Tranistor was broken for gen9+. It didn't apply any modifier. 
Lastly I improved the readability of Protosynthesis and Quark Drive checks
=> Fix damage calc modifiers

docs/tutorials/ai_flags.md, include/pokemon.h, src/battle_ai_switch_items.c, src/battle_controller_opponent.c, src/pokemon.c
The behaviour for the `AI_FLAG_ACE_POKEMON` didn't take into account two separate trainers in double battles.
When `AI_FLAG_ACE_POKEMON` was relevant for choosing a mon, it compared the current selection to the total amount of mons of the trainer, but there was no differentiation between mons in the left side vs the right side for two completely separate trainers that merged due to seeing the trainer at the same time (which was already able to be checked with `BATTLE_TYPE_TWO_OPPONENTS`/`GetAIPartyIndexes`).
* @/uvula on Discord noted the weird behaviour.
* Testing for double (separate) trainers as that is still not possible. I had to create custom trainers and test all possible cases (like one with aces and the other without, both with and without).
Fix for the AI not considering both …
=> `AI_FLAG_ACE_POKEMON` takes into account separate trainers

src/battle_ai_main.c
`EFFECT_POWER_BASED_ON_USER_HP` does not need any AI handling because it will be chosen based on damage it will deal to the player.
=> Moves that deal a Fixed amount don't need AI handling

Makefile
This restores the missing rules for test file dependencies that were removed by #5594 (while still taking advantage of the new build system's speed).
This can by tested by compiling and running a test such as `"Poke Toy lets the player escape from a wild battle"`, swapping the item ID constant for `ITEM_POKE_TOY` with another item that doesn't have `EFFECT_ITEM_ESCAPE`, and then re-running the test. Before these changes the assumptions would fail, but afterwards they succeed. You should also be able to observe that `.d` files are successfully generated in `build/modern-test/test`, whereas they were not beforehand.
- Regression caused by #5594 where test files were not getting rebuilt properly when their dependencies were updated
ravepossum
=> Restore test file dependencies so they're rebuilt properly

src/battle_ai_util.c
`gBattleStruct->dynamicMoveType` was not properly reset during AI calcs. Also it is set to 0 at the start of the `SetTypeBeforeUsingMove` function so I just moved it to the end of `AI_CalcDamage`
=> Fixes dynamicMoveType global not being reset during AI calcs

include/test/battle.h, test/battle/ability/sap_sipper.c, test/battle/weather/hail.c, test/battle/weather/sandstorm.c, test/test_runner_battle.c
- `SEND_OUT` gives a better error message if added to a `TURN` where it is not needed.
- `Speed` is now required for all battlers if it is set for any (there was a bug where it could be missing from one side).
@AlexOn1ine, @ghoulslash
=> Improve SEND_OUT error message; require Speed for all battlers

include/config/battle.h
Set the default shadow setting to `GEN_3` and added a warning about trainerslides.
- Note: Trainerslides don't work properly with Gen4 shadows.
hedara
=> Set default battle shadow to Gen3

src/battle_message.c
The current implementation adds only scrolls when there is more than 1 line. With these changes scroll and new line alternate.
old:
new:
.cawt
=> Improve line breaks/scrolls

map_data_rules.mk
The Makefile only specified `headers.inc` as a dependency without any build steps. This does not work if `headers.inc` exists, but e.g. `map_group_count.h` gets deleted while `src/debug.c` gets updated. I tested the following scenario:
```bash
make clean && make
rm src/data/maps/map_group_count.h
touch src/debug.c
make
```
which fails without the fix.
resolves #5647
Fixes an issue that caused the build to fail on updates to `src/debug.c` due to mismatched dependency.
karathan
=> fix(makefile): dependencies for map_group_count.h

include/test/battle.h, test/test_runner_battle.c
Checks that the tag specified in `PASSES_RANDOMLY` was the argument to a structured RNG call. This catches errors that look like "expected _, got 0.0" and "expected _, got 1.0" that are the result of there not actually being any randomness.
@Pawkkie
=> Check that PASSES_RANDOMLY affected a Random call

data/battle_scripts_1.s, test/battle/move_effect/curse.c
Fixed incorrect Curse effect when used by Protean mons.
Added tests for Curse+Protean and Trick-or-Treat+Curse
Fixes #5662 
hedara
=> Fixed curse + Protean interaction

include/battle.h
The following issues occur if the Dondozo is on the right slot (player or opponent) only:
- Order Up loses or changes its effect upon using a Stellar Boosted move.
- Some types start out with the Stellar Boost consumed.
These happen because `gBattleStruct` doesn't have enough space to store `commanderActive` for all battlers, so, as shown in the example program below, it instead stores on the next one (`stellarBoostFlags`).
In a situation where both would be in use at the same time (example, Tera Stellar Dondozo affected by Commander on the right slot), both would modify the value stored, breaking the other's functionality.
This PR fixes these issues by giving proper space to store `commanderActive` for all battlers.
PhallenTree
=> Fix Order Up + Tera Stellar breaking each other with Commander

include/battle_util.h, src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/hit_set_remove_terrain.c
`TryToRevertMimicryAndFlags()` only triggers when the terrain counter/timer turns 0.
If you use `Steel Roller`, Mimicry doesn't revert to the original typing since `RemoveAllTerrains()` never calls `TryToRevertMimicryAndFlags()`. This PR just adds `TryToRevertMimicryAndFlags()` to the end of `RemoveAllTerrains()`
Originally wasn't sure if this was vanilla behavior, at least simulating it on showdown shows that `Steel Roller` should revert typing. (Unless I overlooked something)
47929991024
=> Mimicry updates typing with RemoveAllTerrains()

src/battle_controller_opponent.c
Fixes regression caused by #5435. A wrong id was assigned to `gBattleStruct->monToSwitchIntoId` in `OpponentHandleChoosePokemon` which didn't manifest in expansion but for iriv a bad egg switched in.
=> Fixes wrong Id when AI chooses mon to switch in

data/battle_scripts_1.s, src/battle_script_commands.c, test/battle/move_effect/absorb.c
Fixes #5687
I forgot that `tryfaintmon BS_TARGET` was already handled in `EffectHit`. Also was unable to write a test. For some reason a mon during the test always switched in.
=> Fixes Absorb regression caused by #5670

src/battle_util.c, test/battle/move_effect/protect.c
Cleans up redundant Decorate check and adds parametrized tests to avoid regression
=> Removes redundant Decorate check

include/constants/battle.h, src/data/moves_info.h, test/battle/move_effect/flower_shield.c, test/battle/move_effect/protect.c
`MOVE_TARGET_ALL_BATTLERS` can't be applied to status moves since they handle the targeting through their own script. This is not ideal because it isn't trivial to make status moves that apply to all battlers but would need a refactor first. 
This PR replaces the target bit with `MOVE_TARGET_USER`. It didn't manifest in expansion but caused a bug in the simultaneous hp reduction branch.
=> Changes taget bit of Flower Shield

tools/trainerproc/main.c
Copy pasting Farfetch'd or Sirfetch'd from showndown generates an invalid species (e.g. `SPECIES_SIRFETCH_D` instead of `SPECIES_SIRFETCHD`). With this the showdown apostrophe is handled the same way the ascii one is.
.cawt
=> Handle showdowns apostrophe the same way as ASCII apostrophe

src/data/moves_info.h
Adds `.minimizeDoubleDamage = TRUE` to Supercell Slam which is should have according to the [Smogon research thread](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-55#post-10346635)
hedara
=> Added Minimize interaction to Supercell Slam

README.md
Same as my feedback on #5640 that's now on ice until Edu gets back, functionally reopening #5643 but that has commit history tied to the wrong GitHub account, my bad lol
Adds a link to INSTALL.md near the top of README.md, and gives the section a new header. Doesn't do anything else that's already included in #5640 
@Pawkkie
=> Update README.md to link to INSTALL.md

include/battle.h, src/battle_util.c, test/battle/hold_effect/enigma_berry.c, test/battle/hold_effect/kee_berry.c, test/battle/hold_effect/maranga_berry.c
Fixes #5674
The berries checked for `TARGET_TURN_DAMAGED` which is a global battler check which caused a partner of a damaged mon to trigger a berry. Ideally we replace  all `TARGET_TURN_DAMAGED` battler checks with a function `BattlerTurnDamaged` and deprecate both macros to prevent us and users from potential bugs. Should be done in upcoming though.
=> Fixes Kee Maranga and Enigma Berry

src/battle_util.c, test/battle/move_effect/knock_off.c
As it currently stands, you can Knock Off the Rusted Shield from Zamazenta and the Rusted Sword from Zacian. According to bulbapedia: 
I didn't take a GIF of the behavior before the fix because i forgot :(
I also added several tests that i didn't see existing versions of, but maybe they do exist somewhere in which case ill delete them. Also they are kind of redundant with each other but hey can never have too many tests ya know.
iriv24
=> Don't Allow Rusted Shield/Sword to be Knocked Off Zamazenta/Zacian

src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
AI will treat Soundproof the same way it treats absorbing abilities like Sap Sipper when considering switching decisions.
Closes #5702 
@Robdeezy for the idea!
@Pawkkie
=> Smart Switching handles Soundproof

src/battle_ai_main.c
Basic handling for Revival Blessing score increases attached to Check Viability.
Score is only increased if the AI has a fainted mon in its party. Score is further increased if the mon considering Revival Blessing has a bad matchup, and if the AI has another mon that has a favourable matchup against the player's current mon.
This felt like competent handling without being over the top to me.
Closes #5487 
Cybeast for the idea!
@Pawkkie
=> Add Revival Blessing AI

src/battle_ai_util.c
Before this fix, the AI only considered its partner triggering sleep clause with moves that use EFFECT_SLEEP and EFFECT_YAWN.
This fix introduces `IsMoveSleepClauseTrigger` to be referenced instead, a one-stop shop for these moves to be referenced anywhere else, and also a single place to add any new move effects in the future. This means the AI now handles all sleep clause triggering moves (I checked on [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_can_inflict_sleep)), including Dark Void, G-Max Befuddle, and G-Max Snooze.
@Pawkkie
=> Fix Sleep Clause AI handling of partner sleeping moves

include/battle_util.h, include/config/battle.h, src/battle_ai_util.c, src/battle_main.c, src/battle_script_commands.c, src/battle_util.c
@AlexOn1ine suggested adding a global overriding config to enable or disable Sleep Clause at the project level for convenience, and that's what this PR adds.
Frankly I think it also cleans up a lot of the conditionals super nicely, `IsSleepClauseActive` reads like `IsDoubleBattle` and I like that a lot for some reason lol
@Pawkkie
=> Sleep Clause global config

test/test_runner.c
Timeouts in tests weren't properly shown in the summary, making it harder to properly know why a test failed. This PR fixes that.
Before vs After
=> Fix test TIMEOUT messaging in summary

src/move_relearner.c
Took a look at the move relearner under the following conditions:
**BEFORE THE FIX:**
1) Increased `MAX_LEVEL_UP_MOVES` from 20 -> 25 (note, `MAX_RELEARNER_MOVES`  is defined as `max(MAX_LEVEL_UP_MOVES, 25)`)
2) Increased Venusaur's level up learnset to contain 25 moves
3) Taught Venusaur 4 moves that were not in its learnset
and saw the following:
**AFTER FIX:**
Works as intended under the same conditions after adding 1 to `MAX_RELEARNER_MOVES` to `menuItems` in `sMoveRelearnerStruct`. 
Not sure if this is something that tests can be written for, please let me know if further testing is required.
#5768
issue reported by @luckytyphlosion
iriv24
=> Fix Off-by-One Error in Move Relearner

data/battle_scripts_1.s, src/battle_util.c, test/battle/move_effect/octolock.c
Octolock stat drops are not triggering defiant. This fixes that and adds a test
=> Fix octolock + defiant

data/battle_scripts_1.s, test/battle/move_effect/gravity.c
Minor fix to gravity not running through all moveend cases at end of turn (mostly concerned about MOVEEND_CLEAR_BITS not getting executed). Add test with gravity + fly/sky drop.
=> Gravity fix + Sky Drop Test

data/battle_scripts_1.s, test/battle/move_effect/ohko.c
Issue is described in the linked issue: mon with ability no guard tries to use an OHKO move on a mon that is semi-invulernable (flying, underground, diving, etc) but the move fails, which is incorrect. Normal moves hit under these circumstances, and so should OHKO moves according to bulbapedia.
Made `BattleScript_EffectOHKO` call `accuracycheck` with `ACC_CURR_MOVE` instead of `NO_ACC_CALC_CHECK_LOCK_ON`.
I couldn't figure out why it was using `NO_ACC_CALC_CHECK_LOCK_ON` in the first place, so if there was a specific reason for that that I am missing and this is the incorrect fix, please let me know. 
Wrote accompanying test and tested the scenario in game.
#5745
Issue reported by @Cafeei
iriv24
=> Fix Pokemon with No Guard failing OHKO Moves into Semi-Invulnerable Pokemon

src/battle_controller_player.c, src/battle_util.c
There's currently an issue with `GetBattleMoveCategory()` where it looks at `gCurrentMove` instead of the local variable `moveId` so the wrong category is retrieved when PSS is turned off. This fixes that as well as a bug with the category icon in battle move info where it wasn't accounting for PSS being turned off.
ravepossum
=> Fix move category and category icon when PSS is off

include/config/pokemon.h, src/pokemon.c
Added config option to change move learning behavior for pokemon evolved at level 1.
In gen 7 and before, pokemon would try to learn all moves that could be learned at level 1, in gen 8+ pokemon will only learn moves larned upon evolution, not level 1 moves.
Config option: `P_EVOLUTION_LEVEL_1_LEARN`, default set to `GEN_LATEST`, changes when set to `GEN_7` or earlier.
Fixes #5787 
If the move is present as both the evolution move and the level 1 move, the player will be prompted to learn the move twice if they decline the first.
hedara
=> Evolution level 1 learn

include/config/battle.h, src/battle_script_commands.c
- Added missing Friend Ball effect:
> When used from the Bag in a wild encounter, it attempts to catch the wild Pokémon with a catch rate modifier of 1×. **If caught, the Pokémon's friendship is set to 200 in Generations II through VII, or 150 in Generation VIII onwards**. It has no effect on the friendship of Pokémon hatched in a Friend Ball.
- Added config `B_FRIEND_BALL_MODIFIER` to reflect Gen2-7 and Gen8+ effects.
- Fixed a small oversight from #5770 that caused an Eiscue with Ice Face to not play the effectiveness sound when hit by a Special move instead of a Physical move.
To test if the friendship was assigned correctly, the following change was made in `PrintMonOTID` to display a mon's friendship in the summary screen (not available in this PR, only for the videos presented …
=> Adds missing Friend Ball friendship bonus upon catching

src/pokedex_plus_hgss.c
Fixes the HGSS dex orders not working correctly when Hoenn dex mode is on.
Fixes #5693 
ravepossum
=> Fix HGSS dex sort orders working incorrectly

src/item_use.c
The 4 Key Items that use `ItemUseOutOfBattle_Fusion` (DNA Splicers, Solarizer, Lunarizer, Reins of Unity) can cause a crash if they are registered and used.
Steps to reproduce:
1) register one of the above key items
2) use the registered key item by pressing select in the overworld
3) close whatever menu gets opened, save your game, close your emulator
4) reopen your game, use the registered key item by pressing select in the overworld
5) crash
The following behavior is **before** this fix. Had to capture it with 2 videos and a screenshot.
Registering the DNA Splicers and using them, then saving and closing the game
https://github.com/user-attachments/assets/a1c43224-f627-40e5-a51f-783534e00a67
Loading back up, pressing select to use my registered DNA Splicers …
=> Prevent Key Items that open other menus from causing a crash if registered and used from the field

src/battle_anim_effects_1.c, test/battle/move_effect/ally_switch.c, test/battle/move_effect/sticky_web.c
See original PR here #5804 
Fixes and adds tests for:
Sky Drop + Ally Switch as the target
Sky Drop + Ally Switch as the attacker
Sticky web on opposing side
All side timer battlerIds. These are not necessary, but makes ally switch robust to any future effects that might care about who sets reflect, for example
Future Sight. If it's been set up against a side that uses ally switch, need to swap the tracked battler/party IDs
Wish. If we use wish and then ally switch, need to update party ID
=> Ally Switch extra battlerId tracking

src/battle_script_commands.c
Doesn't impact the functionality of Dragon Darts itself, but users that create moves with `EFFECT_DRAGON_DARTS` may run into this issue. The previous check only impacted whenever Dragon Darts missed a target, therefore this should not create other issues.
PhallenTree
=> Fixes moves based on Dragon Darts with strikeCount > 2 always hitting the same battler from the second hit onwards

include/config/battle.h, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/pickup.c, test/battle/move_effect_secondary/steal_item.c
Adds Thief/Covet config to send wild mon's stolen item to bag. Also adds a test for this, despite not being able to test if the item gets sent to bag.
Adds Pickup config to allow user to restore its own item in a wild battle at the end of the turn. Adds a test for this.
- Added missing `MOVE_EFFECT_STEAL_ITEM` tests.
Fixes #2459 
PhallenTree
=> Adds Thief/Covet config to send stolen item to bag and Pickup config to pickup user's item in wild battles

src/battle_util.c
Using `B_LAST_USED_BALL` does not take importance into consideration.
This patch fixes it and will not run `RemoveBagItem` if it sees the item (probably a ball) has `.importance = 1`.
Useful for projects that have some sort of infinite pokeball item.
If something like "last healing item" exists, this does not cover it.
- prevents `B_LAST_USED_BALL` from removing balls with `.importance = 1`
47929991024
=> B_LAST_USED_BALL and .importance

src/battle_anim_effects_1.c, src/battle_util.c
Similar to how the previous implementation of Quash set the quash affected battler's act order equal to its position and how it didn't swap any battlers' actions, this caused quash affected battlers to have their end of turn effects happen in an order equal to their positions (playerLeft would always be first, playerRight would always be third, etc.) and if users decide to have certain effects not trigger due to having performed a certain action during a turn, these also took into account the wrong battler's action.
See #5400 for more information on these issues and about the previous implementation of Quash.
Also fixes Ally Switch not swapping battlers actions (likely irrelevant since either partner already acted if its action does not match)
PhallenTree
=> Fixes Quash-affected battlers having the wrong order for End Turn effects

data/battle_scripts_1.s, test/battle/ability/cotton_down.c, test/battle/ability/gulp_missile.c
Adds missing `STAT_CHANGE_ALLOW_PTR` for Cotton Down and Gulp Missile, making them interact correctly with Mirror Armor, Clear Body, Clear Amulet and others.
Added tests for both of these.
PhallenTree
=> Fixes Cotton Down and Gulp Missile not interacting correctly with stat reduction prevention effects

data/battle_scripts_1.s
When a hit escape move (like u-turn) faints a mon, it gave exp to the mon that switched in when it shouldn't have.
This fixes it simply, similar to how hazard fainting works with exp.
#5843
kittenchilly
=> Fix Hit Escape moves giving Exp to the mon that switches in

Makefile
Weirdly enough... it works for me. 
If CI passes, I'd appreciate others to pull and build it locally to see if it works for them too.
=> remove fno-toplevel-reorder

src/battle_script_commands.c, test/battle/ability/regenerator.c
Fixes Regenerator healing past maxHP due to checking the wrong value when trying to ensure it doesn't put the mon at more hp than maxHP. Also added back the Regenerator fix from #5694 since that got accidentally reverted.
Added basic Regenerator tests.
PhallenTree
=> Fixes Regenerator healing past maxHP

src/battle_main.c, test/battle/move_effect/pursuit.c
Oversight from #5707.
Fixes Pursuit into Emergency Exit mon causing a switch but not stopping the Pursuit cycle, causing a second switch at the end of the Pursuit cycle. (likely also happens with Eject Button/Pack)
Also fixes Pursuit user fainting causing Pursuit Cycle to end. (stopping other Pursuiters from attacking and stopping the target from finishing their switch)
https://github.com/user-attachments/assets/d61eaa61-67e5-478e-ae30-bdab3cce065b
PhallenTree
=> Fixes Pursuit + Emergency Exit causing double switches and Pursuit user fainting causing target to not finish switch

src/caps.c
Fixes #5682
There is technically a 2nd part to the issue but I'm not sure if we should be concerned about it.
=> Fixes UB in caps.c

INSTALL.md
Does what it says on the tin - changes INSTALL.MD to reference expansion's `debug` target instead of using `DINFO=1`, and also mentions the change to optimization level that it makes.
ravepossum
=> Change install.md to mention make debug instead of DINFO=1

src/battle_anim_effects_1.c, test/battle/move_effect/ally_switch.c
=> Fixed Ally Switch breaking Illusion

include/pokemon.h, src/daycare.c, src/pokemon.c, src/script_pokemon_util.c, test/pokemon.c
Includes test.
Fixes #5372.
- Also removed redundant `RemoveIVIndexFromList` function in `src/daycare.c`, so it uses `src/pokemon.c`'s instead
=> Fixed givemon not respecting perfect IVs for species

data/battle_scripts_1.s, test/battle/move_effect/salt_cure.c
Fixes Salt Cure battle script order of operations. `tryfaintmon` was running before `printstring`, so "x fainted!" would print before "x was hurt by Salt Cure!"
Also simplifies BattleScript_AbilityPopUpScripting to jump to BattleScript_AbilityPopUp to remove duplicate code
=> Fix Salt Cure script

include/config/battle.h, src/battle_util.c, test/battle/ability/magic_guard.c
=> Adds Generational config for Magic Guard (Fix for Gen4+)

include/battle_transition.h, include/data.h, src/data/trainers.h, tools/trainerproc/main.c
Removes `mugshotEnabled` by adding `MUGSHOT_COLOR_NONE` instead.
=> Clean up redundancy for mugshots

include/battle_gfx_sfx_util.h, include/config/battle.h, src/battle_controllers.c, src/battle_gfx_sfx_util.c, src/battle_intro.c, src/battle_main.c, src/battle_script_commands.c, src/pokemon.c, src/pokemon_animation.c, test/test_runner.c
As tests keep increasing in quantity, we will require new ways of optimizing testing times. This PR is meant to look into finding multiple ways of speeding them up.
So far, the following has been implemented:
- Using @SBird1337's fast battle intro during headless mode.
- Added config to use fast battle intro regularly.
- Reducing wait time for the `waitmessage` command to 0.
- Reducing wait time for the `pause` command to 0.
- Silencing cries (this is to fix an issue where cries would not finish playing before tests were over, causing a "leaking task" error)
- Skipping mon animations.
Any other suggestions are open! :)
- Before vs after. `Switch-in abilities trigger in Speed Order after post-KO switch - Double Battle`, is able to run 2 iterations in the time that it would've originally …
=> Speed up tests in headless mode

test/battle/ability/shield_dust.c
Adds the last Sparkling Aria + Shield Dust test, currently failing.
Fixing the bug, #4636 
hedara
=> Added final Sparkling Aria+Shield Dust interaction test

src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
There's a section of code in `ShoudSwitch` that's decently old and has been refactored out of relevance that was allowing correct switching behaviour with hit escape moves (ie. U-Turn) and is no longer necessary, and in the current setup is actively allowing switching into illegal mons. This was removed, which fixed #5919. Turns out that *is* a duplicate of #5697, which fixes that also.
I noticed we didn't have a switching test for the #2591, which the code I was removing was initially intended to fix, and discovered that it wasn't working correctly anymore anyways, even with the code lol. For both smart switching and regular switching. I fixed this also and added a generic case for both switching behaviours to make sure we don't regress this again.
Fixes #5919 
Fixes #5697 
@iriv24 for …
=> Fixed ace switching bugs

src/trainer_hill.c
Fixes an out of bounds array access in `trainer_hill.c`'s `SetUpDataStruct` which caused map generation to break without `-fno-toplevel-reorder`.
After this PR:
Before this PR:
/
karathan
=> Fix Trainer Hill OOB array access

include/main.h, ld_script_test.ld, src/crt0.s, src/m4a.c, src/m4a_1.s, src/main.c
moves `SoundMainRAM` and `IntrMain` to a loaded section in `.iwram.code` instead of manually loading them. Saves around 2kb of memory.
This also fixes an issue where you were unable to have loaded data in the test binary, because the `.persistent` section would overflow.
karathan
=> Initialize m4a and IRQ handler in a loaded section

include/battle.h, src/battle_ai_util.c, src/battle_controllers.c, src/battle_main.c, src/battle_script_commands.c, src/battle_util.c
Moving overwritten abilities field to disable struct so it is automatically cleared on switchout/faint. In addition, the field will get properly swapped during Ally switch.
=> move overwrittenAbilities field to DisableStruct

docs/tutorials/how_to_new_move.md
The macro was deleted by 1.10, so it only makes sense to remove it from the docs too.
Closes #5756
=> Removed references to HANDLE_EXPANDED_MOVE_NAME in docs

include/battle.h, include/battle_dynamax.h, include/battle_util.h, include/pokemon.h, src/battle_controller_player.c, src/battle_dynamax.c, src/battle_script_commands.c, src/battle_util.c, src/pokemon.c, test/battle/gimmick/dynamax.c
- Fixes Dynamaxed mons having the Dynamax HP multiplier applied again when changing form while Dynamaxed, causing HP to be restored when changing forms and potential overflow;
- Fixes Dynamaxed mons not properly following the interaction described below when changing form: (from Power Construct on Bulbapedia)
> Since Zygarde Complete Forme has a higher base HP stat, Zygarde's maximum HP will increase and its current HP will be revised to its new maximum HP minus the amount of HP it had lost before changing form.
- Fixes Dynamaxed mons gaining HP when leveling up based on the amount of HP gained on the previous level up;
- Fixes Dynamaxed mons gaining too much HP when leveling up after a Dynamaxed mon was the last to level up (caused an HP overflow);
Fixed level up interaction (tested with …
=> Fixes various Dynamax HP conversions/calculations

src/script.c
Revert #5033 change to `MapHeaderRunScriptType`.
Reported by AGSMGMaster64, some vanilla scripts are broken by my change. I think I should be able to restore the feature, but this quickly turns it off to prevent `upcoming` from being totally broken in the meantime.
=> Revert #5033 change to MapHeaderRunScriptType

src/battle_tower.c
This error showed up for me when compiler knew the contents of `GeneratePersonalityForGender`.
=> CreateFacilityMon error: 'personality' may be used uninitialized

src/dexnav.c
Compiler may decide to crash the game if it knows `stepPtr` is `NULL`.
=> Don't write to NULL in TryFindHiddenPokemon

src/move_relearner.c
`error: array subscript 255 is above array bounds of 'struct Sprite[65]' [-Werror=array-bounds=]`
=> Remove out of bounds gSprites access in move relearner

asm/macros/event.inc, include/constants/weather.h, src/debug.c, src/script_pokemon_util.c, test/pokemon.c
Closes #5653 
I was thinking of doing more cleanup on the debug menu, but probably should be done on a separate PR.
- Added Tera Type, Dynamax Level, and Gigantamax Factor to the "Give Pokémon (complex)" debug menu option.
- Added `dmaxLevel` option to `givemon` and `createmon`.
- Added `WEATHER_COUNT`.
- Cleaned up repeated code instances in debug menu.
- Fixed mislabel of `ggMaxFactor` in `givemon` and `createmon`. Now it's `gmaxFactor`.
=> Debug menu and `createmon` additions/cleanup

test/battle/gimmick/dynamax.c, test/test_runner_battle.c
An issue that has persisted for a bit was that gimmick tests failed when running first and the more than 1 battler used a gimmick.
Turns out, `GetBattlerSide` in `MoveGetIdAndSlot` was always returning 0 on the first test.
This PR changes the use of the function to `battlerId & BIT_SIDE` like other test code.
=> Fixed Gimmick tests failing when running first

src/battle_util.c
This can potentially lead to a bug if the current move isn't a future sight move
=> Use gCurrentMove instead of checking FF move

asm/macros/battle_script.inc, data/battle_scripts_1.s, data/battle_scripts_2.s, include/battle_controllers.h, include/battle_gfx_sfx_util.h, include/pokemon.h, src/battle_anim_mons.c, src/battle_controllers.c, src/battle_gfx_sfx_util.c, src/battle_script_commands.c, src/pokemon.c
Form changes while Dynamaxed
Venusaur has G-Max factor, Ditto doesn't.
Ditto has G-Max factor, Venusaur doesn't.
Closes #4651
Right now, there's some duplicity between `HandleSpeciesGfxDataChange` and `BattleLoadMonSpriteGfx`. I wanted to handle this in this PR, but I'll have to do it in a future one.
- Dynamax and Tera color tinting now stays during Transform/Form Change animations.
- Dynamax no longer resets Transformed mon sprites.
- Transform no longer transforms into a Gigantamax Pokémon unless the transformee has Gigantamax Factor and transforms into a base form with a Gigantamax Form.
=> Fixed multiple transform/form change graphical issues

data/battle_anim_scripts.s, src/battle_anim_dark.c, src/battle_anim_electric.c, src/battle_anim_mon_movement.c
Move animations there were improperly implemented.
Moves were found by luckytyphlosion
MOVE_LUCKY_CHANT, done
MOVE_PUNISHMENT, doneish
MOVE_LAST_RESORT, done
MOVE_SUCKER_PUNCH, done
MOVE_AQUA_RING, done
MOVE_MAGNET_RISE, maybe done
MOVE_FLARE_BLITZ, maybe done
MOVE_FORCE_PALM, done
MOVE_AQUA_TAIL, done
MOVE_DRAGON_PULSE, done
MOVE_DRAGON_RUSH, maybe done
MOVE_EARTH_POWER, done
MOVE_SWITCHEROO, done
MOVE_GIGA_IMPACT, done
MOVE_NASTY_PLOT, done
MOVE_AVALANCHE, done
MOVE_PSYCHO_CUT, maybe done
MOVE_ZEN_HEADBUTT, done
MOVE_MIRROR_SHOT, done
MOVE_ROCK_CLIMB, done
MOVE_DRACO_METEOR, done
MOVE_LAVA_PLUME, done
MOVE_ROCK_WRECKER, done
MOVE_GUNK_SHOT, done
MOVE_MAGNET_BOMB, done
MOVE_STONE_EDGE, done
MOVE_CAPTIVATE, done
MOVE_GRASS_KNOT, done
MOVE_AQUA_JET, done
MOVE_ATTACK_ORDER, done …
=> Fixed a bunch of move anims

Makefile
Currently the teachable learnset helper depends on the event scripts file, which (as notated by the repo itself :) ) is hacky and produces misleading error messages like below any time there's an error in a scripts file:
```bash
make: *** No rule to make target 'build/modern/data/event_scripts.o', needed by 'src/data/pokemon/teachable_learnsets.h'.  Stop.
```
To address this, I've changed it so the learnset helper instead explicitly depends on all .inc files and the two other relevant files that affect it (`include/constants/tms_hms.h` and `src/pokemon.c`).
Now only the relevant error message is included in the output:
```bash
data/maps/LittlerootTown/scripts.inc: Assembler messages:
data/maps/LittlerootTown/scripts.inc:70: Error: bad instruction `foo'
make: *** [Makefile:411: …
```
=> Explicitly specify dependencies for teachable learnset helper

docs/tutorials/ai_flags.md, include/constants/battle_ai.h, src/battle_ai_main.c, test/battle/ai/ai_flag_risky.c
Adds flag that prioritizes using the highest damage move regardless of accuracy or secondary effects. Replacing what would have been the theoretical behaviour of `AI_PREFER_STRONGEST_MOVE`, under a new name for clarity and to avoid shadow-changing the behaviour of that flag for existing users.
Closes #5969 
@Pawkkie
=> Add AI_FLAG_PREFER_HIGHEST_DAMAGE_MOVE

include/script.h, src/scrcmd.c
#5033 caused some weirdness with `lock*` and `release*` commands in triggers. This PR _should_ restore the behavior, but it needs some testing :)
Reported by AGSMGMaster64. Testing by HunarPG.
=> Restore lock/lockall/locktrainer/release/releaseall in triggers

include/config/battle.h, src/battle_util.c, test/battle/ability/lightning_rod.c, test/battle/move_effect/pledge.c
[Since Gen 4, redirection abilities, e.g. Lightning Rod, are redirected from ally attacks as well](https://bulbapedia.bulbagarden.net/wiki/Lightning_Rod_(Ability)#Generation_IV)
This PR fixes this with a config and adds a basic test
TODOs:
=> Fix Redirection Abilities Not Drawing in Ally Moves

include/battle_util.h, src/battle_ai_switch_items.c, src/battle_util.c
`gBattleStruct->moveResultFlags` is accessed with species instead of battler.
Fixes #6021
.cawt
=> Fix UB when accessing move result flags

src/battle_setup.c
Match Call now attempts to rematch NPC trainers _within_ the current map, rather than outside of it. This is a straight-up bugfix and returning to original Emerald behavior.
This change cannot affect Vs Seeker functionality in any way.
Fixes #5931.
You can find me on Discord at `mercycle`. I am in the RH Hideout Discord.
=> Fix Match Call Behavior (#5931)

include/config/battle.h, src/battle_controller_player.c
Added config to set if move slot can be rearranged in battle.
Before Gen 4 move slots could be freely rearranged in battle, but Gen 4+ it can only be done in the summary screen out of battle.
Fixes #5943 
@ghoulslash for pointing out the exact point in the code where move slot rearrangement is handled.
- Move slot rearrangement is disabled by default in battle, set `B_MOVE_REARRANGEMENT_IN_BATTLE` to `GEN_3` to enable rearrangement again.
hedara
=> Config for move slot rearrangement in battle

include/constants/pokemon.h, src/move_relearner.c, test/pokemon.c
Adds a known failing test that proves #5633 and moves `MAX_RELEARNER_MOVES` for that purpose outside of the move relearner file.
#5633 refers to `MAX_LEVEL_UP_MOVES` and `MAX_RELEARNER_MOVES` being too low for the level up learnsets that come preshipped with expansion, leading to unexpected behaviour. Both defines are actively used in EWRAM context (`MAX_RELEARNER_MOVES` natively, which is why it's capped, and `MAX_LEVEL_UP_MOVES` in the HGSS dex), so enlarging them comes with memory consequences that need to be carefully reviewed. This PR does not include a fix, only a test that will prove that a hypothetical fix is correct.
bassoonian
=> Add known failing learnset cap test

include/config/dexnav.h, src/dexnav.c, src/field_control_avatar.c, src/field_player_avatar.c, src/start_menu.c
DexNav config flags and vars differed from other configable flags and vars by not having a clear prefix, which meant confusion with actual flags and vars was possible. This PR adds prefixes to bring them in line with the other configable flags and vars.
bassoonian
=> Rename DexNav flags and vars

include/config/battle.h, src/battle_util.c, test/battle/ability/magic_guard.c
This should fix a bug reproducible by setting `B_MAGIC_GUARD` to `GEN_3` or lower.
My approach isn't ideal as `RNG_PARALYSIS` will now needlessly roll, but I wrote this fix for personal use and figured it couldn't hurt.
Feel free to test.
47929991024
=> fixed bug giving immunity to full-paralysis when B_MAGIC_GUARD is >= GEN_4

src/pokedex_plus_hgss.c
`sPokedexView->categoryIconSpriteId` is set to `0xFF` in the previous line, so `gSprites[sPokedexView->categoryIconSpriteId].invisible = TRUE;` can't do anything and should be removed if I understand the code correctly.
Fixes #6050 
hedara
=> Fixes HGSS dex not compiling currently

src/data/trainers.h
Trailing whitespace in src/data/trainers.h was added back in https://github.com/rh-hideout/pokeemerald-expansion/commit/cacd07db9acdfce61a89a341f5405fb7c3f1d41f. This PR removes it again
Frankfurter0
=> Re-removed trainers.h trailing whitespace

src/battle_message.c
Fixes battle messages' line breaks/scroll prompts being generated with the wrong amount of `maxLines`/`screenLines`, causing large messages to be cut off instead of prompting the user to scroll the message.
Current behavior:
https://github.com/user-attachments/assets/0c59877a-1aa3-4978-a250-4368891dda5d
With the fix:
https://github.com/user-attachments/assets/e7e50837-4010-4d52-944d-57ed0e4f0bc2
PhallenTree
=> Fixes large battle messages being cut off instead of being prompted to advance

src/battle_ai_main.c, test/battle/move_effect/entrainment.c
The bug was occuring because the AI was adding significant score to any target who's ability had an aiRating above 5, and this was more significant than the score bonus for targeting a partner with a poor ability. There was no safety valve conditional to ensure that the AI's own ability was less than 5 before switching, so in the case provided, a higher aiRating could also be given to the opponent as long as their ability was at least of rating 5.
This fix cleans up Entrainment's scoring in both doubles and singles to be more granular and effective. Also adds a test for the reported situation.
#6055 
@Pawkkie
=> Fix Entrainment AI scoring bug

include/battle.h
When I documented the other battle structs I forgot to document `DisableStruct`
=> Documentation for DisableStruct

include/battle_ai_util.h, src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
If the player's active mon has a trapping ability, the switch AI will now consider Trace mons in the party as though they have that ability.
#4838 
@ShadowzLmao2
@Pawkkie
=> Switch trapping AI will consider Trace

include/constants/map_types.h, include/overworld.h, src/dexnav.c, src/field_screen_effect.c, src/fldeff_flash.c, src/item_use.c, src/overworld.c
Current version of Porymap doesn't support `enum` variables. This reverts a change of some map variables to `enum`s while leaving the `enum` implementation commented out.
hedara
=> Revert map related enum conversion

Makefile
Adds a dependency on the porymoves json files to the teachable learnset helper. This means that the learnset herlper we will re-run as expected if its json files are updated.
Fixes #5208 
ravepossum
=> Add dependency on json files to learnset helper

src/battle_main.c, test/battle/ability/liquid_voice.c
Reordered some steps in `GetDynamicMoveType` so that Normal-type sound moves would show the correct dynamic type outside of battle if affected by Liquid Voice
Fixes #6091 
Frankfurter0
=> Fixed Liquid Voice's dynamic type for normal moves 

src/battle_controller_player.c, src/battle_main.c
Adds WEATHER_DOWNPOUR to the list of weather types that allow Weather Ball to display as a Water-type in the overworld if dynamic types are enabled
Also uses speciesId more often in MoveSelectionDisplayMoveType
Frankfurter
=>  Added WEATHER_DOWNPOUR to Weather Ball's dynamic type

src/battle_script_commands.c, test/battle/move_effect/charge.c
Fixes #6101
The tests for charge didn't work so they didn't catch the bug. They didn't work because no damage was stored in the variables (See: #5977). Using an array fixes it.
=> Fixes Charge effect not boosting and tests

src/battle_ai_switch_items.c, src/battle_util.c, test/battle/ai/ai_switching.c
When the AI is using the ace flag with only the ace mon left and has a forced switch from Eject Button / Eject Pack, they would send the forced-out mon back in again rather than the ace mon.
This PR fixes this bug and adds corresponding tests.
It's to upcoming rather than master because of the use of `AI_GetBattlerAbility`, which is only on upcoming.
@wiz1989 for reporting the bug
@Pawkkie
=> Eject item ace flag switch AI fixes

src/battle_ai_util.c, src/battle_main.c, src/battle_util.c
There were two instances of checking the terrain and if the battler was grounded that I converted to using IsBattlerTerrainAffected to make them more consistent with the rest of the code
In addition, I switched Psyblade to just check the terrain, since according to Bulbapedia, the power boost doesn't depend on the user being grounded
Frankfurter
=> Terrain function standarization

src/battle_script_commands.c, test/battle/hold_effect/seeds.c
Fixes seeds softlocking the game when activating after Terrain gets changed on switchin.
Updated seeds tests to have more scenarios where they can activate.
PhallenTree
=> Fix seeds softlocking the game when a battler with a Surge ability enters the field

docs/tutorials/how_to_new_trainer_slide.md, include/battle.h, include/trainer_slide.h, src/battle_main.c, src/battle_script_commands.c, src/battle_util.c, src/trainer_slide.c
- Fixes `B_POWDER_RAIN` not working properly after the `AtkCanceller` got reordered. (#5885)
- Fixes some terrain timers not using `gBattleTurnCounter`, causing setup terrains staying on the field for less turns or to last much longer than they should.
- Fixes `gBattleTurnCounter` being reset at the end of first turn events instead of at the start of it (caused timers to be set using the previous battle's `gBattleTurnCounter`).
- Fixes a typo on `unburdenActive`.
- Fixes typos on `TryInitializeTrainerSlide` functions.
PhallenTree
=> Fix Powder (status) config and some terrain timers not using gBattleTurnCounter

src/battle_util.c
Fixes Powder config causing Fire moves not being sizzled out in Primal Rain when `B_PRIMAL_RAIN < GEN_7` due to missing a Powder status check. Made it so `TryActivatePowderStatus` checks for the Powder Status and simplified the code of `CancellerPowderStatus`.
Cleanup of #6109
PhallenTree
=> Fix Powder config not checking for Powder status

src/battle_bg.c
Compiler can complain about it if built with `-fno-toplevel-reorder`
=> Remove UnusedBattleInit from battle_bg.c

include/config/item.h, src/battle_setup.c
This adds a config I_FISHING_ENVIRONMENT to match current gen behavior in regards to the battle environment after hooking a wild pokemon from fishing.
In Gen 3, it used the battle environment of the current tile you were standing on (usually resulting in a grassy environment), while in Gen 4 onwards it matches the environment for the tile that is being fished into (almost always being a water environment).
kittenchilly
=> Match current gen behavior for battle environment after fishing

src/pokedex.c
Changed two for loops to end at `HOENN_DEX_COUNT - 1` instead of `HOENN_DEX_COUNT`
One of these fixes the Hoenn Dex's owned off by 1 error, the other allows HasAllHoennMons to work correctly
Fixes #6103 
Frankfurter
=> Fixed Hoenn dex off by 1 issues

src/battle_ai_main.c
Removed stray semi-colon in `src/battle_ai_main.c` `AI_CalcMoveEffectScore` for hazards.
hedara
=> Removed stray semi-colon in AI code

src/scrcmd.c
Naively applying the same logic for follower mons to also ow mons as well was what fixed it. For talking directly, it doesn't seem to cause an issue, so I think this PR is really just a bandaid fix. I'm not so sure though.
https://github.com/user-attachments/assets/b7eecf3f-5823-4851-97a6-10754451f284
Fixes #5824 
me
accelgor
=> Implemented clear animation for also overworld pokemon

include/battle.h, src/battle_main.c
BattleStruct members quickClawRandom and quickDrawRandom were set in the same function `TryChangingTurnOrderEffects` was invoked so they could be passed as arguments as well.
=> Replace BattleStruct members quickClawRandom/quickDrawRandom with locals

include/battle.h, src/battle_script_commands.c, src/battle_tv.c, src/battle_util.c
I've made the abstraction `MoveResultHasEffect` when I made Simultaneous Reduction HP but in hindsight it is not intuitive to use because when searching for moveResult flags, the abstracted ones don't come up so it makes it harder to find specific places.   Additionally the negation is important information that is abstracted
=> Clean up follow up for Simultaneous Reduction HP 

src/battle_script_commands.c
The MOVEEND_SAME_MOVE_TURNS case did not take into account Pokemon being unable to use their move (sleep, flinch, etc.) when checking to increment the `sameMoveTurns` counter. This resulted in a disparity in damage when, e.g., an Amaura was flinched when selecting Echoed Voice. Selecting it again next turn would have the counter be higher than it should be. This is unintended behavior and as such, a bug; confirmed by testing it against Smogon's engine.
Adds a hitmarker check for `HITMARKER_UNABLE_TO_USE_MOVE` in the `MOVEEND_SAME_MOVE_TURNS` case in `Cmd_moveend`.
#6165 
viridian.
=> Prevent sameMoveTurns from incrementing when unable to use move

src/battle_ai_util.c, test/battle/ai/ai_check_viability.c
This was talked about on Discord this morning, that the AI should associate a positive effect with using Pursuit if it OHKOs the player so they can't switch to get out of it. Also fixes Fell Stinger not looking for a OHKO before getting a bonus.
@Pawkkie
=> AI adds score to Pursuit if it OHKOs

data/battle_scripts_1.s, src/battle_script_commands.c, test/battle/hold_effect/red_card.c, test/battle/move_effect/hit_switch_target.c, test/battle/move_effect/roar.c
Fixes Suction Cups displaying an incorrect ability popup.
Added Roar tests for Guard Dog and Suction Cups interactions.
Fixes Guard Dog preventing Red Cards from activating instead of allowing them to be consumed but not switching out the attacker. ([Source](https://www.youtube.com/watch?v=rggthHKGgTM))
Added Red Card test for Guard Dog interaction.
Fixes #6153 
PhallenTree
=> Fixes Suction Cups ability popup and Red Card + Guard Dog interaction

src/battle_ai_util.c, src/battle_anim.c, src/battle_anim_dark.c, src/battle_anim_effects_3.c, src/battle_anim_mons.c, src/battle_anim_throw.c, src/battle_anim_utility_funcs.c, src/battle_anim_water.c, src/battle_dynamax.c, src/battle_script_commands.c, src/pokeball.c
Used `GetPartyBattlerData` to clean up code that relied on checking the player's side to obtain party data.
- Uses of checking battler's side to show front or back sprite. These will be handled in a future PR.
- Found some battle controller code that uses `gPlayerParty` and `gEnemyParty` directly, but decided to not handle those as they probably should be handled separately and with caution.
=> Cleaned up party data access GetPartyBattlerData

include/battle_ai_switch_items.h, src/battle_ai_switch_items.c, src/battle_controller_opponent.c, src/battle_controller_player_partner.c, src/battle_main.c
I've meant to do this during some of the recent switching refactors and kept forgetting. Alex accidentally reminded me about this today.
For the last while, `GetMostSuitableMonToSwitchInto` takes a TRUE or FALSE to handle whether a switch is after a KO or not. In the spirit of getting rid of passing in booleans that are less readable where it makes sense, this PR refactors the affected functions to use an enum instead.
@Pawkkie
=> SwitchType enum to clean up GetMostSuitableMonToSwitchInto

src/battle_message.c, src/battle_util.c, test/battle/ability/unnerve.c
Unnerve would print "Your team is too nervous to eat Berries!" regardless of what side the user was on.
Couldn't fix As One which is also affected by this bug.
hedara
=> Fixed Unnerve message and wrote tests

test/battle/ability/sheer_force.c
Fixes wrong move ID or name in a few sheer force tests
=> Sheer Force Test Fixes

include/constants/event_objects.h, include/event_object_movement.h, src/event_object_movement.c, src/load_save.c, src/pokemon_sprite_visualizer.c, src/scrcmd.c, src/shop.c
Supersedes #6117 
Fixes shiny pokemon object events and adds the possibility to female forms if they exist, also with shiny.
Also fixes the Swinub OW palette tag collision with the weather.
Refactored how follower `graphicsId`s are calculated.
Now they are calculated by taking the species number and adding`1 << 13` to signify that it is an OW follower/object event.
Furthermore the bits `1 << 14` and `1 << 15` are used to signify if is shiny and female.
Fixes #5683 , fixes #5147 
@AsparagusEduardo 
- Fixes `OBJ_EVENT_GFX_SPECIES_SHINY`
- Adds `OBJ_EVENT_GFX_SPECIES_FEMALE` and `OBJ_EVENT_GFX_SPECIES_SHINY_FEMALE`
hedara
=> Follower Object Event refactor

src/battle_ai_switch_items.c, test/battle/ai/ai_choice.c
One of @iriv24's players sent a recording of some weird switching behaviour which lead to this discovery. Turns out `ShouldSwitchIfBadChoiceLock` was checking if the last move used _globally_ was a status move, not the last move the choice'd mon had used was. Whoops!
This is to upcoming because `GetMoveCategory` isn't in master.
@/capncrunch
@Pawkkie
=> Fix Choice'd mons referring to incorrect move when switching

data/battle_scripts_1.s, test/battle/ability/liquid_ooze.c
This test was not testing the correct scenario. The liquid ooze battle script of leech seed also needed to set the attacker to the target (seeder) for the liquid ooze message to print properly. This should be safe since the BS_ATTACKER sequence had already been run at this point.
=> Fix Liquid Ooze + Leech Seed Test

src/sound.c
Similar to https://github.com/rh-hideout/pokeemerald-expansion/pull/5889, this prevents Fanfares from running in headless mode. This will have small speed gains and prevents tests that end before the fanfares are finished from failing.
@hedara90, @AsparagusEduardo
No other features are removed from headless mode.
pkmnsnfrn
This spawned from a [Senate discussion](https://discord.com/channels/419213663107416084/1077009799293710357/1337906390949298237).
=> Prevented fanfares from playing in headless mode

src/battle_main.c
Fix [Using a Safari Ball crashes the game (#6206)](https://github.com/rh-hideout/pokeemerald-expansion/issues/6206)
=> Fix Using a Safari Ball crashes the game #6206

include/battle.h, include/battle_util.h, src/battle_util.c
`IsBattlerAlive` is a really common check that I think it is worth to inline it. Especially because it is used in big loops like moveend. It might not be much of a speed improvement but it is also free to do.
=> Redefine IsBattlerAlive in battle.h as a static inline

asm/macros/event.inc, include/script.h
`requests_effects` was misspelled in macros.
Test before and after by adding these commands to any script.
```
getobjectxy 0, CURRENT_POSITION, VAR_0x8000, VAR_0x8001                                                                                                                 
getobjecttemplatexy 0, CURRENT_POSITION, VAR_0x8000, VAR_0x8001                                                                                                         
getobjectcurrentxy 0, CURRENT_POSITION, VAR_0x8000, VAR_0x8001                                                                                                          
checkobjectat 10, 10                                                                                                                                                    
getseenmon …
```
=> Fixed typo in requests_effects

include/battle.h, src/battle_script_commands.c
Fixes macro `BATTLER_TURN_DAMAGED`. It used the wrong battler id for the endure check.
=> Fixes BATTLER_TURN_DAMAGED battler id 

src/battle_script_commands.c
The fix from upstream was not applicable to the expansion codebase, so I had to redo it from scratch.
The issue laid in `SwitchPartyOrderInGameMulti` using `i` instead of the actual value from `gBattleStruct->monToSwitchIntoId` like it was supposed to.
Also moved the declaration of `i` to the loop where it's used.
Fixes #5842 
hedara
=> Fixed multi battle forced switches

include/reshow_battle_screen.h, src/battle_script_commands.c, src/party_menu.c, src/reshow_battle_screen.c
Fixes the dodgy battle UI sprites when returning to the battle for the "add to party?" prompt.
https://github.com/user-attachments/assets/5873e8f8-56a6-49bb-8c16-71f73e7fc363
This fix is likely how the original feature should have worked anyways. Rather than sending you back to the battle, it puts you in the post battle UI that would usually appear after registering a mon in the dex, with the mon you just caught in center screen.
Does not resolve whatever was going on with the register UI that causes the corrupted sprites in the first place.
=> fix for battle ui for add to party menu (#6229)

src/data/moves_info.h, test/battle/move_effect/dream_eater.c, test/battle/move_effect/reflect_type.c
Also fixed Dream Eater not ignoring Substitutes in Gen 5+.
There's no current way of changing move flags during a test, so the Dream Eater tests use preproc instead.
=> Added missing Dream Eater and Reflect Type tests

src/overworld.c
A wrong static assertion was made in pr #6174
=> Fixes Static Assert from pr #6174

src/data/moves_info.h
Not a bug but I think it makes more sense to use the define that includes all moves.
=> Use more accurate count in MovesInfo

src/field_message_box.c
Whoever ported this made a mistake and left two duplicate lines of code past case 0's break statement in `Task_DrawFieldMessage`.
Whoever ported this FRLG's walking into signpost functionality made a mistake and left two duplicate lines of code past `case 0`'s break statement in `Task_DrawFieldMessage`. This PR removes them.
Mistakenly leftover code.
deokishisu
=> Fix Extra `task->tState++` and `break` in `Task_DrawFieldMessageBox`

data/battle_scripts_1.s, include/battle_util.h, src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/follow_me.c, test/battle/move_effect/instruct.c, test/battle/move_effect/sleep_talk.c, test/battle/move_effect/snore.c
- Fixes called moves ignoring redirection (Follow Me, Storm Drain, etc.);
- Consolidated various called move related functions into `ResetValuesForCalledMove`;
- Fixes Stance Change + Sleep Talk test;
- Added tests for Sleep Talk and Instruct to test redirection interactions;
- Added a test for Follow Me and one for Spotlight;
- Added basic tests for Snore;
PhallenTree
=> Fixes Called moves ignoring redirection

src/battle_ai_util.c, test/battle/ai/ai.c
In the previous iteration of `AI_WhoStrikesFirst`, the code performed a check like this:
```c
if (GetMovePriority(battlerAI, moveConsidered) > 0)
return AI_IS_FASTER;
```
This incorrectly assumes that the AI is always faster if the battle move's priority is above `0`. This did not take into account whether the player's predicted move was a priority move, and as such, would faultily use moves like `Sucker Punch` even if it the enemy has `Aqua Jet` with a higher speed stat.
The updated code now checks the player's predicted move through `AI_DATA->lastUsedMove[battler]` to see if the predicted move's priority is higher or lower than the AI's considered move. The rest of the checks stay the same, as this code simply fixes the faulty check.
Fixes #6255 
viridian.
=> Fix AI wrongly thinking it strikes first with priority even if player is using priority themselves

src/pokemon.c
removes a now obsolete check when retrieving partners name in multi battles. `GetFrontierTrainerName` handles this correctly so the extra check for steven is not needed anymore. Also fixes a bug related to incorrect name being loaded
Fixes #6282 
@hedara90 
u8.salem
=> remove obsolete check for steven when retrieving partner name

src/debug.c
moveId 255 is getting skipped, which is Spit up. Didn't find any reason why 0xFF was skipped specifically.
.cawt
=> fix spit up getting skipped

src/data/object_events/object_event_pic_tables_followers.h, src/data/pokemon/species_info.h, src/data/pokemon/species_info/gen_1_families.h, src/data/pokemon/species_info/gen_2_families.h, src/data/pokemon/species_info/gen_3_families.h, src/data/pokemon/species_info/gen_4_families.h, src/data/pokemon/species_info/gen_5_families.h, src/data/pokemon/species_info/gen_6_families.h, src/data/pokemon/species_info/gen_7_families.h, src/data/pokemon/species_info/gen_8_families.h, src/data/pokemon/species_info/gen_9_families.h, src/pokemon.c
edit by psf:
https://github.com/rh-hideout/pokeemerald-expansion/pull/5597 introduced a regression detailed in #6141. This PR reverts #6141.
~~NOTE: Only merge in case #6141 is not solved by the time of 1.11's release.~~
=> Reverted compound literal OW mon pic tables

src/battle_util.c
moveDamage had the wrong argument but you also don't need it. Same with resultFlags. `IsBattlerTurnDamaged` covers both already
=> Fixes inconsistency for Kings rock.

include/battle_ai_util.h, include/config/ai.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c
I went through everything in #6126 and added what I thought made sense.
Fixes:
- check all moves that can make hazards properly
- check all moves that can remove hazards properly
- `IsBattlerIncapacitated` considers Sleep Talk
Tweaks:
- Additional items added to `sRecycleEncouragedItems`
- Check for low accuracy move added when considering copying stat changes
This is to upcoming so I can rename `BLUNDER_POLICY_ACCURACY_THRESHOLD` to `LOW_ACCURACY_THRESHOLD` and reuse it.
Closes #6126 
Closes #5763 
@ShadowzLmao2
Things I didn't think were good to add include:
- refactoring `IsSemiInvulnerable` (seems like unnecessary conflicts)
- Changing the ShouldSet[weather] functions to also check if a different weather is up and the opponent is using it (I don't fully understand what this means, we …
=> Fix AI hazard move handling, minor AI tweaks

src/battle_ai_main.c
Big Root was being scored incorrectly for several moves, and not considered at all for other applicable ones.
I've double checked the full list from Bulbapedia, and this cleans it up entirely.
Closes #6168 
@Pawkkie
=> Big Root AI Fix

include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c, src/battle_util.c
This started as adding Magic Room to `IsMonGrounded`, but I did a search for `ABILITY_KLUTZ` and found a bunch of cases where a quick boolean function would shorten up conditionals. This PR addresses that initial mishandling, while also applying the same thorough item checks everywhere it's applicable and introducing `IsBattlerItemEnabled` for use in the future.
Closes #6122 
@Pawkkie
=> Fix AI hold effect considerations

include/config/ai.h, include/config/general.h, src/battle_ai_switch_items.c
Got some fabulous data from @iriv24 indicating just how overeager this switching is, makes for some truly embarrassing behaviour.
This PR adds clauses to check that the AI's current mon can't OHKO the player and also doesn't have any stats raised before it switches out for an absorber to fix the issue. I've also pulled the number for "how many stats raised do you want to stay in for" into a config as it's been hardcoded to 3 up to this point which I hadn't realized, and definitely shouldn't be.
To upcoming because this code has seen significant refactoring.
I should note I'm intending to do a major overhaul to how `ShouldSwitch` is structured in the not-too-distant future so these kinds of checks can be applied more universally without rerunning them for every sub function, but that's way …
=> Fix Overzealous Absorber Switching

include/battle.h, src/battle_script_commands.c, src/battle_util.c
Removes `pursuitSwitchByMove`, instead using `pursuitStoredSwitch` to determine if the party screen should come up at the end of the Pursuit cycle.
Removes extra instruction left by master->upcoming merge
PhallenTree
=> Remove pursuitSwitchByMove and additional if statement

data/battle_scripts_1.s, include/battle.h, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/own_tempo.c, test/battle/ability/pastel_veil.c, test/battle/hold_effect/air_balloon.c, test/battle/hold_effect/jaboca_berry.c, test/battle/move_effect/coaching.c, test/battle/move_effect/two_turns_attack.c
- Fixes Coaching succeeding if ally is in a semi-invulnerable state.
- Fixes Air Balloon being stolen before being consumed.
- Fixes Immunity abilities failing to heal a user's status if the original attacker has a Mold Breaker-like Ability.
- Fixes Razor Wind not playing its second turn animation if holding a Power Herb.
- Fixes Burning Bulwark not being removed correctly after being hit by Feint.
Fixes 6 Known Failing tests.
The first Own Tempo test failed because the slower Slowpoke's move would activate Own Tempo to cure its confusion.
PhallenTree
=> Fixes Coaching on semi-invulnerable ally, Air Balloon being stolen, Immunity abilities being ignored by Mold Breaker

include/constants/event_objects.h
`1 << 15` is used to define a palTag that isn't blended with DNS, this shifts the tags used for followers away from that bit.
hedara
=> Shifted the follower graphicsIds

include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c, test/battle/move_effect/shed_tail.c
There's been a bug for a while where, after the switch AI got pretty good at identifying when to switch out, it'd prefer to switch out in cases where it should instead use Substitute, largely because cases where Substitute is good and cases where switching are good have significant overlap.
Been going through the `battle-ai` issues the last bit during merge freeze to try to get what I can cleaned up, and I'm pretty happy with this implementation. It reuses the move scoring function for Substitute effects to identify if Substitute is good, and if so it'll prioritize that instead of switching. This lets users actually have effective Substitute behaviour while using the smart switching AI, particularly with Shed Tail.
I'll think about a follow-up that uses the same approach for pivot moves …
=> Fix Substitute / Shed Tail Switch AI

src/battle_util.c
This catches an edge case in multi 2 vs 1 battles where if both opposing mons get knocked out on the same turn and there is only one mon left for the opponent to send out, that last mon won't be erroneously sent out twice.
Fixes #5136.
bivurnum
=> fix for multi 2vs1 opponent sends out too many mons bug

include/constants/battle.h, src/battle_controller_opponent.c, src/battle_controller_player.c, src/battle_controller_player_partner.c, src/battle_gfx_sfx_util.c, src/battle_util.c, src/contest.c, src/data/moves_info.h, test/test_runner_battle.c
Removed `MOVE_TARGET_USER_OR_SELECTED` and replaced the target bit with `MOVE_TARGET_OPPONENT` for use with moves that are like `MOVE_TARGET_SELECTED` but can't target allies in double battles.
Added `MOVE_TARGET_OPPONENT` to Me First since it's not supposed to be able to target allies and it behaves strangely when done.
Fixes #2522 
hedara
=> Added MOVE_TARGET_OPPONENT and added it to Me First,

data/battle_anim_scripts.s
Fixes Nature's Madness trying to allocate too much VRAM in Singles.
Fixes Parabolic Charge trying to allocate too much VRAM in Doubles.
Fixes Frost Breath trying to allocate too much VRAM in Doubles.
Fixes Stuff Cheeks trying to allocate too much VRAM in Doubles.
(I am aware that this should target master, but the testing system for this was written for upcoming)
Fixing Nature's Madness in Doubles
hedara
=> Made some move animations fit in VRAM

src/battle_script_commands.c
When settings `B_ALLY_SWITCH_FAIL_CHANCE` to anything except `GEN_9` `protectUses` wouldn't reset when using a non-protect move.
This adds a case to the `if` statement to catch that config setting.
Discovered by @wiz1989
hedara
=> Fixed protect not resetting the counter in earlier gens

src/battle_main.c
Fixes fainted battlers on the right slot being given the option to select an action. This happened because `battlerState.absentBattlerFlags` was not being set correctly.
Fixed interaction:
https://github.com/user-attachments/assets/fdc914b8-86f9-43f6-9807-04482d63f730
Fixes #6294
PhallenTree
=> Fixes fainted battler being able to select an action

src/battle_ai_main.c
We must've missed this when the function was repurposed. To upcoming because the repurposing was in upcoming.
Don't make an exception to the freeze for this, it can just go in the post-1.11 pile.
@Pawkkie
=> Update AI_TryTo2HKO comment

src/berry.c
When a Berry Tree is growing, all of the strings expect a singular berry. Previously, it had taken the number of berries from the final berry tree, so every in-progress string was grammatically wrong unless it was going to result only in one Berry.
This checks the status of the berry tree it's grabbing the item string for.  If it is not at the final Berry stage, it will return the singular form of the item, which is what all the calls in `data/scripts/berry_tree.inc` actually wanted.
Before:
After:
Berry trees berries are no longer erroneously plural.
wildvenonat
=> Fixing grammar of Berry Tree strings

include/config/battle.h, src/battle_script_commands.c
If you are disabling a wide variety of species across generations, it is likely that most pokemon in the National Pokedex will be unobtainable, which means that it's undesirable behavior to scale the % chance that a Critical Capture will happen based off of the number of Pokemon in the national dex assuming all Pok&eacute;mon were obtainable within that generation.  This instead adds a configuration setting to change it to go by the number of Pokemon in the Hoenn Pokedex instead, as it's far easier to adjust what's in the Hoenn Pokedex than to account for disabled species in the National Pokedex.
wildvenonat
=> Configuration to scale Critical Capture odds based on local Pokedex or estimated National Pokedex

src/pokemon.c
Currently, if Zacian or Zamazenta Crowned would learn Iron Head while in battle and already knowing Iron Head in the form of Behemoth Blade/Bash, it would still be able to learn Iron Head despite already "knowing" the move.
This adds a check to prevent them from learning Iron Head if they already know Behemoth Blade/Bash.
@wiz1989 reported the issue
hedara
=> Fixed Zacian/Zamazenta learning Iron head while already knowing

src/battle_controller_player.c, src/battle_main.c
Ivy Cudgel was checking the second type of the mon using it to determine move type, this means that it wouldn't work properly if Ogerpon would've had it's type changed by for example Soak.
By hard-coding the types depending on the mon/form it works in all cases.
hedara
=> Fixed Ivy Cudgel types with type changes

include/constants/battle_script_commands.h, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/dancer.c
Postpones Dancer activations to be more in line with the timing used in the games (see https://bulbapedia.bulbagarden.net/wiki/User:FIQ/Turn_sequence) and removes issues due to `gBattlerAttacker` and `gBattlerTarget` being overwritten for the Dancer move.
Also removed some duplicate `ClearDamageCalcResults()` calls as it's already called when the action finishes.
Added a `ClearDamageCalcResults()` for called moves.
Moved clearing of snatched and bounced move bits to `HandleAction_ActionFinished`.
Added a test to check if the original targets are correctly restored after Dancer activates.
Cleaned up other Dancer tests.
Fixes #6377
PhallenTree
=> Reorder Dancer activation

src/battle_main.c
Fixes https://github.com/rh-hideout/pokeemerald-expansion/issues/5805, which is consistently reproducible by:
1. Encountering a roamer;
2. Letting it flee;
3. Encountering a roamer of the same species again.
The fix is to ensure that `ZeroEnemyPartyMons` is called after `UpdateRoamerHPStatus`.
Demonstration of the bug (mGBA 10.4, expansion 1.10):
https://private-user-images.githubusercontent.com/105816064/418068804-a0471103-355d-4b15-a6a7-14579691207a.webm?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5MTU5NzksIm5iZiI6MTc0MDkxNTY3OSwicGF0aCI6Ii8xMDU4MTYwNjQvNDE4MDY4ODA0LWEwNDcxMTAzLTM1NWQtNGIxNS1hNmE3LTE0NTc5NjkxMjA3YS53ZWJtP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QU …
=> Fix roamers having 0 hp on repeat encounters

src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
Both parts of the switching code have sections that run a calc to figure out how many hits the AI can take from the player before being KO'd. I got asked a question in iriv's hack's Discord about whether this consideration factors in occasions that the player is choice locked into a particular move, which it doesn't.
It does now lol
@Pawkkie
=> Switch AI will factor in player's choice lock when determining hits to KO

include/battle.h, include/battle_ai_util.h, include/battle_script_commands.h, include/battle_util.h, include/config/ai.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c, src/battle_debug.c, src/battle_script_commands.c
The AI is intended to use different rolls for damage calcs depending on its flags, specifically with Risky and Conservative leading to different behaviour. With Risky the AI is meant to assume it gets highrolls when attacking and is only hit by lowrolls, and Conservative is the opposite. Other combinations use the median damage roll.
This hasn't been working as intended likely since the introduction of the `SimulatedDamage` struct at least.
This PR aims to both fix the damage rolls issue, cleanup the damage calc (within reason) and its crit handling to manage the rolls internally, and make an easy access function `AI_GetDamage` that will do all of the handling for the unique flag-roll correspondence and can be expanded in the future to handle more if needed.
To upcoming because it relies …
=> Fix roll handling in AI damage calcs

src/battle_main.c
The battle intro was incorrectly entering the trainer battle path in wild battles if `B_FAST_INTRO_PKMN_TEXT` was set to false.
This removed that possibility.
Fixes #6394 
hedara
=> B_FAST_INTRO_PKMN_TEXT fix

include/battle_util.h, src/battle_util.c
`B_REDIRECT_ABILITY_ALLIES  <= GEN_3` does not compile
.cawt
=> remove/replace IsAlly leftovers

src/battle_gimmick.c
Fixes gimmick icon flying off the screen if selecting a move (and target if applicable) and the next mon's action quickly.
This happened because the `x` value was not correctly updated in these cases, causing the x value from the previous mon's gimmick icon to be used (which was not on its "Optimal" position (`gSprites[gHealthboxSpriteIds[sprite->tBattler]].x - xOptimal`), so it tried reducing `x` until it was correct).
Also limited the movement of the gimmick icons to only happen within their normal bounds (between its "Optimal" position and its "Slide" position (`gSprites[gHealthboxSpriteIds[sprite->tBattler]].x - xSlide`)).
Haven't tested with other gimmicks but I presume this fix works since they use the same functions.
Fixed interaction: …
=> Fixes gimmick icon flying off the screen

data/battle_scripts_1.s, include/config/battle.h, src/battle_script_commands.c, src/data/items.h, src/data/moves_info.h, test/battle/move_effect/chilly_reception.c, test/battle/weather/hail.c
This adds a configuration setting to homogenize Ice weather effects if so desired, making all Hail or Snow summoning moves summon the same weather type.
By default, both Ice weathers are available and moves work the way they do in vanilla games.
I moved battle configurations focusing on weather effects into their own section of `include/config/battle.h`, then added configuration settings to either: make Hail and Max Hailstorm summon Snow, make Snowscape and Chilly Reception summon Hail, or have both Ice-type weathers.  I also adjusted the descriptions of the Hail TM, the Icy Rock, and the move Aurora Veil to reflect which Ice weathers are desired.
#6147 is myself requesting this exact feature.
- Added a config to homogenize Ice weathers between Hail, Snow, or both.
wildvenonat
=> Configuration to make all Hail moves summon Snow or vis versa, to have only one ice weather

src/battle_script_commands.c
I can't think of a problem right now this might cause but it was possible that in some situation the wrong battler would cause an issue.
=> Wrong argumet usage in `CalcCritChanceStage`

src/field_control_avatar.c
Currently, the player cannot bring up the Pokemon Mart and Center sign scripts by pressing A on the metatile. Whoever added the metatile behaviors for these tiles forgot to add them to `GetInteractedMetatileScript`. This PR fixes that.
~~It would also be really cool if maintainers would check to make sure that super basic functionality like the original commit that added these sign metatile behaviors is working properly before merging.~~
deokishisu
=> Include Missed `GetInteractedMetatileScript` Entries for Mart & Center Signs

test/battle/sleep_clause.c
Fixes Known Failing Sleep Clause test. The interaction was already fixed in #6327.
Fixes #5578 
PhallenTree
=> Fixes Known Failing Mold Breaker Sleep Clause test

src/battle_util.c
The function was inefficient because the `IsAbilityOnField` was called for each ability meaning that it needed double the amount of `GetBattlerAbility` calls. Did the same for `IsUnnerveAbilityOnOpposingSide`. This one needed 3 times as many GetBattlerAbility calls.
=> Refactor HasWeatherEffect and IsUnnerveAbilityOnOpposingSide

include/config/battle.h, src/battle_util.c
The function `IsAbilityPreventingEscape` was very inefficient. With every `IsAbilityOnOpposingSide` call it recalculated the abilities. I reworked it so that each each ability is checked within one `GetBattlerAbility` call
=> Refactor the function IsAbilityPreventingEscape

asm/macros/battle_script.inc, data/battle_scripts_1.s, include/battle_scripts.h, include/battle_util.h, src/battle_ai_util.c, src/battle_script_commands.c, src/battle_util.c, src/data/battle_move_effects.h, src/move_relearner.c, src/pokedex_plus_hgss.c, src/pokemon_summary_screen.c
The unification ensures that when users add a new move with a dynamic move category, it will work correctly in battle and for the ai.
We have a lot of tests for these moves so I don't think there will be any regression.
=> Unifies dynamic move category checks 

include/config/ai.h, src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
Some context, because the problem this is solving is pretty specific:
`ShouldSwitchIfAllMovesBad` prompts switches when the AI's mon has no moves that affect the target. It prompts a generic switch, which means it relies on `GetMostSuitableMonToSwitchInto` and subsequently `GetBestMonIntegrated` (assuming smart switching) to find a good candidate mon. `GetBestMonIntegrated` has pretty high standards for what constitutes a good mon when considering mid-battle switches, as it both helps the AI make good switches and also keeps several `ShouldSwitch` functions in check by first ensuring a *good* candidate exists by checking `GetBestMonIntegrated`'s result.
In cases where `GetMostSuitableMonToSwitchInto` does not find a mon it's happy with, and no mon has been specified by `ShouldSwitch`, …
=> Improve "all moves bad" switching

data/battle_anim_scripts.s
Fixes Jet Punch not destroying a task it creates.
This caused issues when the move was ran in isolation in tests with animations on.
hedara
=> Fix Jet Punch in isolated tests

include/config/test.h, test/battle/move_animations/all_anims.c
Updates the "All move animations" test with self-targeting tests and options to choose the start and end moves to test.
Note that the self-targeting tests are currently commented out due to them not working properly right now, the `SCENE` blocks aren't set up for the sometimes lack of animation for same-side targeting.
hedara
=> Update the All Move Animations test

src/berry_blender.c
Removed unused debug EWRAM variables for the berry blender.
Note that the compiled EWRAM size didn't change compared to without this removal. So the variables were probably optimized out during compilation, the sha1sum does change though.
hedara
=> Removed unused debug EWRAM variables

src/battle_script_commands.c, test/battle/move_effect/sucker_punch.c
Sucker Punch wasn't working properly vs. Struggle.
Fixed by adding a check for if the target has valid moves, which is the same check as for executing Struggle.
This can't be tested with the automated system, test vs. a trainer with a mon with only one move with 1 PP (Sketch, Revival Blessing).
Added tests for regular Sucker Punch behavior.
Attempts were made at handling Struggle vs. Sucker Punch in tests, but the bugged behavior couldn't be replicated in tests.
Fixes #6472 
hedara
=> Sucker punch vs struggle

include/battle.h, src/battle_gimmick.c, src/battle_main.c
With the introduction of Trainer Party Pools the party in battle is decoupled from the underlying Trainer struct. This caused issues with Terastalization and Dynamax usage for the AI.
The AI was checking the original index for if a mon could use Terastalization or Dynamax, instead of the actual post-TPP index.
This changes how the AI check if a mon can use those gimmicks by introducing fields in `struct BattleStruct` to store that data.
hedara
=> AI gimmick check changed from checking trainer data to a BattleStruct field

src/battle_script_commands.c
Since damage is now recorded for all battlers we can remove this potential pitfall in case something wrong was saved.
=> Remove potential pitfall with saved damage for recoil moves

test/battle/move_effect/toxic_spikes.c
Test was set as `KNOWN_FAILING` but behaviour is actually correct for at least Gen 7.
hedara
=> Changed KNOWN_FAILING test

include/metaprogram.h
Allows `metaprogram.h` to be included without having included `global.h`. (Useful for testing preprocessor things locally by manually invoking `cpp`)
Also fixes a small typo.
=> metaprogram.h without global.h

include/test_runner.h, test/test_runner.c, test/test_runner_battle.c, tools/mgba-rom-test-hydra/main.c
Also fixes a bug in the `memmem` implementation.
@mrgriffin 
hedara
=> Made memory integrity checks run betweeen PARAMETRIZE runs

data/battle_scripts_1.s, src/battle_util.c, test/battle/ability/aftermath.c
When Aftermath was triggered the wrong message was displayed. For some reason it only happened when the aftermath user was the opponent so I added two tests to make sure there is no regression
=> Fixs Aftermath ability popup message

src/data/union_room.h
The Union Room tries to load an array of types to select from that contains uninitialized members, so it crashes when prompting the user to choose one of the types.
Now restored interface:
`luigi___`
=> Hide in-battle types from Union Room trade request

src/siirtc.c
The RTC hint string gets optimized out these days. Marking it with `USED` puts it back in the ROM. This fixes some emulators out of the box.
```bash
~ # arm-none-eabi-nm -a pokeemerald.elf | grep AgbLibRtcVersion
0833b594 r AgbLibRtcVersion
```
[mGBA](https://github.com/mgba-emu/mgba/blob/10eb794cfd602eac6f70f01838a420eebd9b8267/src/gba/overrides.c#L388) and [other emulators](https://github.com/SourMesen/Mesen2/blob/02180abed132599f3f1e4b769a16eac808fd862c/Core/GBA/GbaConsole.cpp#L160) sometimes fail to detect the game as using Flash saves because it's (partially) tied to searching for the RTC hint string for whatever reason and not the save hint string. This should fix auto-detection on emulator platforms where it was once broken.
SBird -- pointed out the USED attribute to avoid a worse …
=> Mark RTC/Flash save hint string as used

data/battle_scripts_1.s
Fixes Hone Claws checking if the user's Sp.Atk/Sp.Def can be boosted instead of Atk/Acc when choosing whether to play a stat change animation (If Sp.Atk and Sp.Def were at the maximum stage, the stat change animation wouldn't play, despite being able to boost Atk/Acc)
Fixes Stockpile stat drops (when using Spit Up or Swallow) being prevented by Clear Body and other stat reduction prevention effects.
From Bulbapedia:
> Generation V onwards
> The Stockpile removal is now shown as a stat change. For each Stockpile that successfully changed a defensive stat, that stat will drop by two stages if the Pokémon has Simple at the time of using Swallow, rise by one stage if the Pokémon has Contrary at that time, **or drop by one stage with any other Ability.**
PhallenTree
=> Fixes Hone Claws checking the wrong stats for its stat change animation and Stockpile drops being stopped by stat reduction prevention effects

include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_util.c, test/battle/ai/ai.c
Adds a few basic cases where the AI should score a move negatively if the opponent has Unaware. I'm sure there are more cases, but this is a simple start that'll cover most of them.
@Pawkkie
=> Add basic Unaware check bad move scoring

data/battle_scripts_1.s
This was missing in the Will-O-Wisp script
=> Fixes Will-O-Wisp not being blocked by Thermal Exchange

test/battle/ability/thermal_exchange.c
Thermal Exchange tests.
One test is added as `KNOWN_FAILING`, #6535 
Fixing the found incorrect behaviour.
hedara
=> Thermal exchange tests

include/config/test.h, test/battle/move_animations/all_anims.c
Improves the move animation test.
Moves the settings for start/end move to the test file to reduce recompilations.
Removed a function causing the compilation of these tests to fail.
Added tests for Z-moves.
Max Moves, since they're not implemented as their own move animations right now.
hedara
=> Updated move animation tests

src/wild_encounter.c
just adds a missing break statement that causes compiler errors in older versions of gcc. i went through the other switch cases added and didn't see anything else i missed.
@khbsd
=> fix: missing break statement

include/config/battle.h, include/type_icons.h, src/battle_main.c, src/type_icons.c
adds the option to show the type indicators only when a mon has been seen before by:
- adding `SHOW_TYPES_SEEN` as a `#define` option
- when `SHOW_TYPES_SEEN` is selected, mons will be marked as seen once a battle finishes, not as soon as it starts, so the type indicators wont read the mon as seen (they load after that flag is set).
- adding a little logic to handle when a mon has been seen but not caught
- this slightly alters how the flag `FLAG_GET_SEEN` is set, so keep that in mind if you have any functionality that relies on it being at the start of the battle.
@khbsd
=> Adds SHOW_TYPES_SEEN to the B_SHOW_TYPES option

data/battle_scripts_1.s, test/battle/gimmick/dynamax.c
Fixes Dynamax reversion animation when fainting. This happened since for some animations, the battler's sprite is not considered to exist if fainted, unless `gBattleStruct->spriteIgnore0Hp` is set.
Fixed animation:
https://github.com/user-attachments/assets/4ed150cd-2fbf-467e-ae74-be52cc36cdcd
PhallenTree
=> Fixes Dynamax reversion animation when fainting

include/battle_ai_main.h
Since the idea is that users can make adjustments to the score increases it might be better to just assign those now even if they are in consecutive order.
=> Adjust enum AIScore

src/overworld.c
The old setting to turn off DNS could break palettes on map transitions when `FALSE`.
This should be a more reliable way to turn off DNS.
hedara
=> Fixed DNS off config sometimes breaking palettes on map change

src/daycare.c
Adds a check to make sure level caps aren't being surpassed when taking a mon out of the daycare.
Fixes #6620 
hedara
=> Capped Exp from Daycare to level cap

data/battle_anim_scripts.s
Black Hole Eclipse was trying to load too much stuff into VRAM in doubles, this fixes that by unloading stuff that's not used any more and rearranging some other unloads.
hedara
=> Fix VRAM load for Black Hole Eclipse

src/battle_script_commands.c, src/battle_util.c, test/battle/ability/gulp_missile.c
=> Fixes Gulp Missile freezing the game if when attacker fainted

data/battle_anim_scripts.s
I could not figure out what `ANIM_TAG_CIRCLE_OF_LIGHT` and `ANIM_TAG_TEAL_ALERT` was used for in the Nature's Madness animation.
I could not figure out what `ANIM_TAG_SPARKLE_2` used in in the Lunar Blessing animation.
With these changes all normal moves pass the "All Animations don't leak" on `upcoming`.
Fixes #6290 
hedara
=> Fixes some moves trying to load too much VRAM

src/battle_script_commands.c
Currently, the default B_MULTI_BATTLE_WHITEOUT config makes it so in multi battles the battle can still be won even if the player's 3 mons were all knocked out. However, if the player only has 3 or less eligible mons in their total party, they end up returning to the OW with no viable mons after battle. This adds a check that makes the player white out if they wouldn't have any battle-viable mons in their party after the battle. While this is tied to an open issue, it should not be treated as a long-term fix for it.
Partially fixes #6625
bivurnum
=> Fix no eligible mons when only the partner wins in multi battle

src/battle_anim_effects_1.c, src/battle_util.c, test/battle/move_effect/acupressure.c, test/battle/move_effect/ally_switch.c
- Fixes moves failing after Ally Switch if the Attacker is the ally of the battler that used Ally Switch and if they target a battler on the same side of the field (changed so that only moves that did not originally target the user, but target the user after Ally Switch fail).
- Fixes Acupressure failing regardless of target if Ally Switch was used by their partner.
- Fixes Snipe Shot, Propeller Tail and Stalwart redirecting moves for some battlers when they shouldn't (after Ally Switch).
Fixes #6646
@hedara90 made the Ally Switch test in #6646
PhallenTree
=> Fixes Ally Switch cancelling partner's moves targeting that side of the field

include/move.h, src/apprentice.c, src/battle_ai_util.c, src/battle_script_commands.c, test/battle/ability/color_change.c, test/battle/ability/intimidate.c, test/battle/ability/neutralizing_gas.c, test/battle/ability/thermal_exchange.c, test/battle/ai/ai.c, test/battle/hold_effect/shell_bell.c, test/battle/move_effect/dream_eater.c, test/battle/move_effect/follow_me.c, test/battle/move_effect/instruct.c, test/battle/move_effect/laser_focus.c, test/battle/move_effect/recoil_if_miss.c, test/battle/move_effect/rototiller.c, test/battle/move_effect/sleep_talk.c, test/battle/move_effect/snore.c, test/battle/move_effect/spectral_thief.c, test/battle/move_flags/recoil.c, test/test_runner_battle.c
IMO, this should be standard for new code ever since 1.11, otherwise doing stuff like #6652 would be impossible.
=> Added missing `gMovesInfo` encapsulation

src/pokemon.c
Fixes the `HasTwoFramesAnimation` to take into account species that only has 1 animation frame.
This was causing issues with the post-KO animations.
Issue discovered by PCG on Discord.
Test to see the behaviour.
```C
SINGLE_BATTLE_TEST("blergh")
{
GIVEN {
PLAYER(SPECIES_SHEDINJA);
OPPONENT(SPECIES_ABSOL) { Item(ITEM_ABSOLITE); }
} WHEN {
TURN { MOVE(opponent, MOVE_CRUNCH, gimmick: GIMMICK_MEGA); }
}
}
```
Bugged behaviour
hedara
=> Change HasTwoFramesAnimation to take into account species with 1 frame

data/battle_scripts_1.s
Fixes #6036
When Gravity / Perish Song were looping through battlers it increased `gBattlerTarget` till it was able to break out when it reach 4. This fixes it by storing and restoring the target/
=> Fix gBattlerTarget OOB for Gravity and Perish Song

test/battle/move_effect_secondary/haze.c, test/battle/move_effect_secondary/leech_seed.c, test/battle/move_effect_secondary/light_screen.c, test/battle/move_effect_secondary/reflect.c
The tests relied on Gen 8 versions that had 95% accuracy, unlike the Gen 7 version with 100% accuracy.
=> Fixed LGPE move test fail with `B_UPDATED_MOVE_DATA` to `GEN_7`

src/fake_rtc.c
Removes a vestigial function (presumably from testing) inside fake_rtc.c, brought in from the merge of #5695 `FakeRtc datetime and ResetRtcScreen day increments`.
ruby
ruby.raven
=> Remove vestigial AdvanceScript function used for testing

src/battle_script_commands.c, test/battle/ability/teraform_zero.c
Fixes Teraform Zero + Neutralizing Gas known failing test. (Neutralizing Gas doesn't activate for `battler` if `gDisableStructs[battler].neutralizingGas` is set to true)
Reminder to keep Known Failing tests "passable" so that when the problem is solved the test actually passes.
Fixes #5010
PhallenTree
=> Fixes Neutralizing Gas activating again after switch-in

data/battle_scripts_1.s, test/battle/ability/mirror_armor.c
From Sword/Shield Research thread: (at the end of https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8330904)
> Pokemon A with Substitute uses Screech into Pokemon B with Mirror Armor. Mirror Armor activates, but Pokemon A's Defense does not drop ("it doesn't affect <Pokemon>..."). Pokemon B's Defense doesn't drop either, as expected. On an unrelated note, though I would have expected this, you can miss Screech on a Pokemon with Mirror Armor.
The previous check was incorrect since `jumpifsubstituteblocks` checks if `gBattlerAttacker`'s move is blocked by `gBattlerTarget`'s Substitute, when Mirror Armor is `gBattlerTarget` inflicting a debuff on `gBattlerAttacker`.
According to the research, this seems to ignore the `.ignoresSubstitute` attribute of …
=> Fixes Mirror Armor stat drops not being stopped by Substitute

src/event_object_movement.c
Fixes broken palettes for shiny followers in the sprite visualizer.
Followers and OW object events works after this change, in combinations of shiny and female and not.
The problem was probably a vestigial handling for the old graphics ID handling.
hedara
=> Fixed broken palette load for shiny followers in the sprite visualizer

src/debug.c
There was an EWRAM variable I declared in my first attempts to clean up and refactor my own code for the Time Menu, and realized it was still there after it was merged
ruby
ruby.raven
=> Removes vestigial EWRAM variable from debug menu.

src/battle_main.c, test/battle/ability/unburden.c
Fixes Unburden doubling speed when Neutralizing Gas is on the field.
Added a few basic Unburden tests and some to verify #6673.
Fixes #6673
PhallenTree
=> Fixes Unburden doubling speed when affected by Neutralizing Gas

include/config/pokemon.h
This was a leftover I forgot to disable.
- `P_TUTOR_MOVES_ARRAY` set to `FALSE` by default.
pcg06
=> Disable `P_TUTOR_MOVES_ARRAY` config

src/event_object_movement.c
The check for preventing follower NPCs from being removed out of bounds was erroneously checking the objectId instead of the localId. This caused some other objects to not be removed properly even if their event flag was set. This commit fixes that issue.
Fixes #6714
bivurnum
=> Fixed objects not getting unloaded properly when event flags are set

src/battle_ai_switch_items.c
Made this change to `ShouldSwitchIfAllMovesBad` some time ago, never ported it to Wonder Guard handling.
All this does is prioritize sending in what the AI considers a good switchin, before defaulting to "any mon that has a SE move".
Without this, if the call from this function finds a *bad* matchup mon that just has a SE move, there's a chance it'll immediately switch it out for the good candidate mon identified by `GetBestMonIntegrated`. This change sends that mon out first if it exists, so this awkward potential double switching can't happen.
@Pawkkie
=> Fix Wonder Guard potential double switching

include/battle_ai_util.h, src/battle_ai_switch_items.c, src/battle_ai_util.c
Follow-up to the final part listed in #6396, I'd largely forgotten about this until that PR came up in conversation today and I though it'd be good to finish getting the system cleaned up before the next release.
This incorporates an extremely similar refactor to that PR; use the new enum instead of passing booleans, and handle all of the roll determinations right at the point of returning a damage value to keep everything tidy.
In a similar vein to the previous PR, this "adds" behaviour back in that has been broken since the `SimulatedDamage` refactor, but I'm considering it a bugfix rather than a new feature.
@Pawkkie
=> Fix roll handling in AI party damage calcs

asm/macros/event.inc, include/constants/follower_npc.h
Changed the names of the follower npc script macros to specify that they are for the npc followers. This change also makes the names line up with the documentation in #6704.
bivurnum
=> Rename follower npc macros for better specificity and to match documentation

src/battle_util.c, test/battle/hold_effect/life_orb.c
Fixes issue #6767 
Add a test for Life Orb for the case of using status moves
spindrift64
=> Fix Life Orb inflicting self damage when using status moves (#6767)

src/pokemon.c
When calling `CreateMon`/`CreateBoxMon` with a fixed personality, any attempt to reroll the personality (i.e. Shiny Charm) will overwrite the fixed personality. This mainly effects eggs received from the Daycare. The egg's personality is set when the Daycare Man has an egg and includes the nature if it were to inherit one. Overwriting the personality means the nature is no longer inherited, leaving the Everstone effect useless if the player has a Shiny Charm.
My fix lets the code reroll as normal to get whether or not the Pokemon is shiny, but uses the fixed personality in the Pokemon's data instead. This makes gender, nature, and ability preserved when rerolling. Includes when the OT ID is fixed, whether or not the personality is fixed.
Fixes #4981, fixes #2803 
i0brendan0
=> Fix rerolls overwriting Fixed Personality

src/battle_main.c, src/battle_script_commands.c, test/battle/hold_effect/gems.c
Gems do not activate for no type damage moves such as Counter/Psywave/Super Fang.
Check for base power of the move used. Moves that would trigger the bug have 1 base power.
Fixes #6785
spindrift64
=> Fix gems activating for moves that don't deal type damage

data/battle_scripts_1.s, include/battle_scripts.h, include/constants/battle_string_ids.h, src/battle_message.c, src/battle_script_commands.c, test/battle/move_effect/toxic_spikes.c
Toxic Spikes print whether the target gets poisoned or badly poisoned.
Fixes #6809
spindrift64
=> Toxic Spikes print whether the target is poisoned or badly poisoned

include/config/battle.h, src/battle_main.c, src/battle_util.c
Not every game that decides to use badge boosts will use the same badge flags as vanilla emerald. This PR changes it so you change which flag you can use.
Also, changed the description of the flag configs to hopefully make it easier to understand for newbies
@ghoulslash, @klemniops, whose' code I was using for comparison when I found these
=> Allow different flags for Badge boost

asm/macros/event.inc, src/scrcmd.c
Created several macros to manipulate the Fake RTC in scripts.
These are as follows:
- **addtime**: Adds a specified amount of time in the format of `(days, hours, minutes)`
- **adddays**: Adds a specified amount of days
- **addhours**: Adds a specified amount of hours
- **addminutes**: Adds a specified amount of minutes
- **fwdtime**: Forwards the time to a specified time in a 24h format
- i.e., given `fwdtime 15, 0`, it forwards the time to 3 PM.
- **fwdweekday**: Forwards the time to a specified weekday, with the week as a 0 index starting on Sunday.
For the purposes of this demonstration, the function `FakeRtc_ForwardTimeTo` called by the `fwdtime` macros have had their RTC pausing and resuming sections commented out.
https://github.com/user-attachments/assets/0df6761d-4f67-4291-b219-05 …
=> Timemacros

data/battle_scripts_1.s
`MOVE_EFFECT_GRAVITY` (used by G-Max Gravitas) calls `BattleScript_EffectGravitySuccess` which is after `savetarget`, but `restoretarget` is still called.
This also fixes other MoveEnd effects potentially using the wrong target for G-Max Gravitas.
PhallenTree
=> Fixes restoretarget on empty stack when using G-Max Gravitas

src/battle_script_commands.c
Sendout breaks in doubles, if multiple mons fainted and both sides have 1 empty spot, while the player has no mons left to send out. 
Note: `NoAliveMonsForBattlerSide` is a function that already exists in upcoming, so this will result in merge conflicts. `NoAliveMonsForBattlerSide` makes use of `CountAliveMonsForBattlerSide` to deduplicate code.
.cawt
=> Fixed double battles send out breaking

include/battle_scripts.h
Removes a duplicate script declaration from the file.
@i0brendan0
bassoonian
=> Remove redundant script declaration in `battle_scripts.h`

Makefile
This won't affect most devs who has an average or just better PC in general, but it is nice-to-have for devs who only has more low-end PC.
Below are the results with `make tidy -j1 -O` before and `make -j1 -O` after.
Before the scaninc fix:
```sh
Executed in  514.76 secs    fish           external
usr time  346.42 secs  998.00 micros  346.42 secs
sys time   31.28 secs  390.00 micros   31.28 secs
```
After the scaninc fix:
```sh
Executed in  506.27 secs    fish           external
usr time  328.54 secs  848.00 micros  328.54 secs
sys time   27.90 secs  509.00 micros   27.90 secs
```
mudskipper13
=> Prevent scaninc touching tests when `make`-ing non-test builds

Makefile
Fixes the `make clean && make` not regenerating `src/data/trainers.h` and `src/data/battle_partners.h`.
A future change should try to make these files be generated properly, but this is a stopgap solution.
Fixes #6833 
hedara
=> Make make clean work again

src/data/moves_info.h, test/text.c
This was requested on the discord. Now every move has a description that the game can use.
Also fixes some z-move names that were different from how they actually are on cart.
It doesn't actually make these descriptions display anywhere, this PR just adds the data so someone else can make them display properly.
kittenchilly
=> Add move description data for Z-Moves and Max/G-Max moves

data/battle_scripts_1.s
`tryfriskmsg` overwrites `gBattlerTarget` and depneding on when it activates it might cause a bug.
=> Fix potential bug in BattleScript_FriskActivates

src/battle_ai_switch_items.c
AI currently doesn't consider the player's Mold Breaker ability when sending in a mon with an absorbing ability. This is rather exploitable.
While fixing this, noticed that it also ran a damage calc without considering choice locked items. This has already been addressed in the other switching functions, must forgotten this one had one.
This PR fixes both of these issues.
#6854 
@Pawkkie
=> Fix FindMonThatAbsorbsOpponentsMove not seeing Mold Breaker or choice items

include/config/battle.h, src/battle_script_commands.c, src/data/moves_info.h
re-PRing #6853 using upcoming as a base
Implements the gen1 no recharge on KO mechanic on a toggleable flag. This applies to all recharge moves such as Hyper Beam, Blast Burn, etc.
As such:
If the B_SKIP_RECHARGE flag is set to GEN_1, if the user of Hyper Beam (or any other move with the MOVE_EFFECT_RECHARGE effect) KOes its target, it skips the recharge turn.
fixes #6142
No tests yet. The changes were tested directly in-game, both for GEN_LATEST and GEN_1 settings. I had problems during my tests, where in the following case:
```
{
ASSUME(MoveHasAdditionalEffect(MOVE_HYPER_BEAM, MOVE_EFFECT_RECHARGE) == TRUE);
ASSUME(MoveHasAdditionalEffect(MOVE_DIRE_CLAW, MOVE_EFFECT_DIRE_CLAW) == TRUE);
}
```
The first assume would fail, and the second assume would work, which I think is not normal …
=> Gen 1 no recharge on KO

src/battle_end_turn.c
If the battler had Magic Guard and Wrap active, it would reach the "else" code, causing wrap to end at the end of the turn that Magic Guard was obtained or at the end of the turn that Wrap was applied.
PhallenTree
=> Fixes Magic Guard causing Wrap to end immediately

include/data.h, migration_scripts/1.12/convert_trainer_battle_types.py, src/battle_main.c, src/battle_setup.c, src/data/trainers.h, src/data/trainers.party, test/battle/trainer_control.c, test/battle/trainer_control.h, test/battle/trainer_control.party, tools/trainerproc/main.c
Changes `Double Battle` to `Battle Type`, in order to support future battle types with trainerproc.
Includes migration script.
Doesn't add any additional battle types.
=> Expand trainerproc to support additional battle types

src/debug.c
Follow up to #4025.
Changes:
- Moved SaveBlock, ROM Space and Expansion Version to new "ROM Info" menu.
- Moved Player Name, ID and Gender options to new "Player" menu.
- Moved Check/Set Clock options to Time Menu, which was moved up.
- Cleaned repeated submenu display code into functions
=> Debug menu cleanup

README.md
The URL previously pointed to `upcoming`, but the most recent version of `CREDITS.md` will be on `master`.
pkmnsnfrn
=> Fixed URL for contributors badge on README.md

.all-contributorsrc
CI doesn't need to run when bot is adding new contributors. This enables the setting to skip the CI. Other settings: https://allcontributors.org/docs/en/bot/configuration#docsNav
pkmnsnfrn
=> Update .all-contributorsrc to skip CI

src/battle_transition.c
Add checks to skip OpponentB and Partner functions when OpponentB or Partner are not present
Issue present where 2v1 mugshot transitions led to unwanted overworld sprite and camera effects due to OpponentB not being present but some of the mugshot transition functions for OpponentB not being appropriately skipped. Change adds if checks to skip these functions. Checks also added to equivalent Partner functions for when partner is not present.
@AlexOn1ine for troubleshooting support and code recommendations
grintoul
=> Mugshot Transitions 2v1 fix

test/battle/ai/ai_switching.c
All explicit references to Leaf were meant to be replaced by `AI_TRAINER_NAME` to make it easier for downstream to maintain their tests.
This test was either added after that without remembering it existed, or was missed in the initial replacement.
This PR updates the test to the new standard.
@Pawkkie
=> Fix test not referencing AI_TRAINER_NAME

tools/trainerproc/main.c
Allows moves like King's Shield and abilities like Mind's Eye to be parsed correctly. 
Fixes #6483
jfb1337
=> Fix trainers.party parser failing on apostrophes

include/config/battle.h, include/config/overworld.h
Users ought to be warned of the footguns involved with both gen 5 map popups and B_VAR_WILD_AI_FLAGS.
Ideally, B_VAR_WILD_AI_FLAGS would be deprecated completely, but in the meantime, explaining how to avoid using it is sufficient.
wildvenonat
=> Commenting in config files to explain limits of map popups and wild AI flags

src/battle_util.c
If used on a spread move the damage from first battler was otherwise applied
=> Fixes global usage in super fang effect.

include/battle_main.h, include/constants/battle.h, include/pokemon.h, src/battle_controller_player.c, src/battle_main.c, src/pokemon.c, src/pokemon_summary_screen.c
Fixes #6875
I found an other bug but since it is just a visual issue I'm not really keen on fixing it. 
> // Bug: in battle, this only shows the dynamic type of battler in position 0
=> Fixes ate type being ignored after checking summary screen

data/battle_scripts_1.s, src/battle_script_commands.c, src/overworld.c
Both settings are now handled in `getmoneyreward` to make it cleaner.
To keep parity with the regular lose condition, the money displayed is not shown upon forfeit.
Fixes #6817 
=> Fixed forfeit money for `B_WHITEOUT_MONEY <= GEN_3`

test/test_runner.c, test/text.c
While I was doing something, I accidentally had a string without a string assigned, which caused a segmentation fault during the test. This should prevent those situations.
=> Added check for gBattleStringsTable

src/battle_ai_switch_items.c, test/battle/ai/ai_choice.c
This is (I think) the last case (at least in the switch AI) where the AI considers all of its moves when choiced.
This one is used when evaluating whether the current mon has a super effective move or not, which I'd entirely missed until it messed up a line I was planning in a nuzlocke recently lol. Short fix.
Getting rid of the rng reference in this function as it's no longer needed and hasn't been in some time.
@Pawkkie
=> Fix switch AI considering non-choiced SE moves when choiced

src/pokemon_summary_screen.c
Cleanup of #6888.
It would check the "new move" 's type (which most likely was `MOVE_NONE`) instead of the move displayed.
PhallenTree
=> Fixes checking wrong move's Dynamic Move Type in Summary Screen

src/map_name_popup.c
Removes the update to the popup window every frame that queries the RTC chip. This burns a lot of cycles due to the siirtc being slow and the code accounting for it in a busy wait.
- Fixed an issue that causes the game to lag in some configurations that involve `OW_POPUP_BW_TIME_MODE`.
karathan
=> Fix OW_POPUP_BW_TIME_MODE burning a lot of cycles due to RTC queries.

src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
This was a two-pronged switching bug reported in Emerald Imperium that took a bit to track down as a result. Firstly, the "defensive switchin" switchin candidates weren't checking whether they could win a 1v1, and are the only such label not to do so; this meant the AI could see mons that would lose (but lose over 3+ hits) as good switchin candidates.
The second part is kind of the reverse, the second clause that can trigger bad odds switching checks for bad type matchup and lack of a super effective move and high HP, but doesn't actually compare KO thresholds between the involved battlers.
These two features combined could lead to not only double switching as soon as a new mon has been sent out, but the AI also sending in a mon that would lose the 1v1 when it did so. Very bad.
Both …
=> Fix bad odds / defensive switchin double switch cases

src/battle_script_commands.c
This PR fixes an issue where Eiscue would stay in Noice Face form after battle. Instead, Eiscue now behaves correctly and resets back to Ice Face outside of combat, similar to Mimikyu.
Fixes #6264.
vexedon
=> Fix Eiscue not resetting back to Ice Face form after battle.

test/battle/move_effect/heal_bell.c
`i`, which refers to the current PARAMETERIZE and of which there are 14, was used as the index into `gPlayerParty`, of which there are 6, instead of the intended "check each player party mon" loop index variable, which is `j`
yoshord
=> Fix out-of-bounds in Heal Bell Cures Entire Party test

src/follower_npc.c
Added logic to the `FollowerNPC_WarpSetEnd` function that makes sure the follower will have the same state as the player after a warp. For example, when surfing into a warp that leads to a non-surfing destination the follower would erroneously retain the surf blob on land. This fixes that issue.
Here is a video showcasing the bug:  
https://discord.com/channels/419213663107416084/1357388177161326834/1377337293433471148
bivurnum
=> Fixes follower NPC not changing state with player after warp

data/scripts/field_move_scripts.inc
Selecting "No" when asked if you want to surface from underwater will no longer change the follower NPC to the regular surf sprite.
A video showcasing the bug:  
https://discord.com/channels/419213663107416084/1357388177161326834/1376995585411907724
bivurnum
=> Fixed follower NPC changing to surf sprite when choosing not to surface from dive

src/field_screen_effect.c
Mossdeep gym warps now set the follower NPC to reappear.
A video showcasing the issue:  
https://discord.com/channels/419213663107416084/1357388177161326834/1376678372498870412
bivurnum
=> Fix follower NPC not reappearing after Mossdeep gym warp

src/follower_npc.c
The surf blob would get created for the follower NPC on map reload even if they were invisible, causing a second surf blob to be created when the follower is revealed. This fixes that issue.
Video showcasing the bug:  
https://discord.com/channels/419213663107416084/1357388177161326834/1377337293433471148
bivurnum
=> Fixed surf blob binding to invisible follower NPC on map reload

Makefile, tools/wild_encounters/wild_encounters_to_header.py
@/spargel on discord brought this up:
https://discord.com/channels/419213663107416084/1077168246555430962/1374503502243696650
this handles the fields better and checks for duplicate entries, as well as reading from `dexnav.h` to determine whether hidden mon macros should be generated.
@/spargel on discord for alerting me to the problem
=> fix: better area mons handling, no longer duplicates `hiddenMons` field

src/debug.c
`Debug_DestroyMenu_Full` is called twice in a row, when `FAKE_RTC` is disabled, causing free to be called twice on the same pointer.
.cawt
=> Fix UB when using time menu

src/battle_message.c
Two trainer battle intro text doesn't always display second trainer name. PR fixes this issue.
Adds defined line breaks into sText_TwoTrainersWantToBattle so both trainer names are always displayed
Before fix
https://github.com/user-attachments/assets/39ed6539-1bd1-48aa-b19a-1490f3326646
After fix
https://github.com/user-attachments/assets/a0a85ee2-670f-49ac-bef5-917101f504ab
Fixes #6816
grintoul
=> Added line break between Trainer 1 name and Trainer 2 name in sText_TwoTrainersWantToBattle

data/battle_anim_scripts.s, src/battle_anim_effects_2.c, src/battle_anim_electric.c, src/battle_anim_flying.c, src/battle_anim_new.c, src/battle_anim_rock.c
This pull request adds 18 new move animations, few of which were edited while the rest are completely new.
Added/edited are the following moves:
* Dynamax Cannon
* Behemoth Blade
* Behemoth Bash
* Eternabeam
* Glaive Rush
* Triple Dive
* Doodle
* Ruination
* Collision Course
* Electro Drift
* Blazing Torque
* Wicked Torque
* Noxious Torque
* Combat Torque
* Magical Torque
* Psyblade
* Mighty Cleave
* Supercell Slam
See #5192 for missing move animations.
[Video Showcase](https://youtu.be/8Qwoac0FfTE?si=WY4jcvgO9ZMbGya0)
Fixes #5192
* Added move animations for multiple moves by @LinathanZel
- Dynamax Cannon, Behemoth Blade, Behemoth Bash, Eternabeam, Glaive Rush, Triple Dive, Doodle, Ruination, Collision Course, Electro Drift, Blazing Torque, Wicked Torque, Noxious Torque, Combat Torque, …
=> New Attack Animations: 25w20a

src/battle_message.c
#6052
Probably fixes #6816 without manual line breaks (haven't tested, but the situation in the videos of #6052 happened again and was fixed again by this)
PhallenTree
=> Fixes large battle messages being cut off instead of being prompted to advance 2

src/pokedex_plus_hgss.c
Every species between `SPECIES_ALCREMIE_STRAWBERRY_VANILLA_CREAM` (869) and `SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL` (1288) was being treated as Alcremie, causing their font widths to be forced into `FONT_NARROWER`.
Also, changed the use of `FONT_NARROWER` to `FONT_SMALL_NARROWER`, to match the use of `FONT_SMALL` on the evolution descriptions.
=> Fixed text width for a lot of forms in HGSS Dex

include/decompress.h, src/decompress.c
Followers weren't being properly identified as being compressed when using `.smol` compression due to detection being handled by the `IsLZ77Data` function.
Implemented a new function for detecting LZ77 and smol compressed data and used that instead.
hedara
=> Fix follower compression

docs/tutorials/how_to_trainer_pic.md
Tutorial was referencing `u32` `.gbapal.lz` palettes, but that's been changed to `u16` `.gbapal`.
hedara
=> Changed trainer tutorial to take into account removed palette compression

src/battle_util.c
Small change that prevents a regression in case new protect types are released.
=> Change GetZMaxMoveAgainstProtectionModifier to prevent regressions

src/battle_main.c
Stat changes are always calculated first. Tested in-game
Pawmot should always be faster (101 speed) then Basculegion (100 speed) but due to the wrong order the calculation for Basc ended in a speed tie with Pawmot   
```
=== DEBUG_TRAINER_PLAYER ===
Name: Player
Class: Pkmn Trainer 1
Pic: Brendan
Gender: Male
Music: Male
Pawmot
Serious Nature
Level: 40
IVs: 31 HP / 31 Atk / 31 Def / 31 SpA / 31 SpD / 31 Spe
- Icy Wind
- Splash
=== DEBUG_TRAINER_AI ===
Name: Debugger
AI: Basic Trainer
Class: Rival
Battle Type: Singles
Pic: Steven
Gender: Male
Music: Male
Basculegion F
Serious Nature
Level: 38
IVs: 31 HP / 31 Atk / 31 Def / 31 SpA / 31 SpD / 31 Spe
- Rain Dance
```
=> Fixes speed calculation order

asm/macros/battle_script.inc, data/battle_scripts_1.s, src/battle_script_commands.c, src/data/debug_trainers.h
`sStatusFlagsForMoveEffects` was a relic from GF that isn't needed anymore. In addition to being mostly redundant there was a bug with rage because the status wasn't in the table there.  
There was extra handling done for non volatile statuses but I think it is much more readable because you don't need to check a table anymore and the if-else branches are gone.
=> Deprecate sStatusFlagsForMoveEffects

src/battle_end_turn.c
Title. Grassy Terrain heals non-grounded Pokemon when it shouldn't. This PR fixes #7057.
In `battle_end_turn.c`, the `FIRST_EVENT_BLOCK_GRASSY_TERRAIN_HEAL` needs `IsBattlerGrounded(battler)` in its activation conditional.
linathan
=> Bug fix for Grassy Terrain incorrectly healing non-grounded Pokemon

src/field_screen_effect.c
If a dive warp is used while a follower NPC is still set to come out of a doorway, the follower erroneously performs the exit door behavior after the dive warp. This fixes that issue.
Here's a video showcasing the issue:  
https://cdn.discordapp.com/attachments/1357388177161326834/1379916880671670292/follower_dive_surface.mp4?ex=6841fb3d&is=6840a9bd&hm=07063cd9dfd0971b0923bf0b3519df44d32f8818fb3562dafa07a74be0f60a26&
bivurnum
=> Bug fix: clear saved follower NPC door warp when doing dive warp

src/contest_painting.c
Contest Painting try load palette with LZSS compressed, but all palette are not compressed.
=> Fix Contest Painting load palette error

src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/pursuit.c
Fixes Pursuit user switching out due to Red Card/Eject Pack and partner switching into the same mon, causing both of the player's (or the opponent's) battlers being the same mon. Source of the fix is Showdown since I couldn't find information on what should happen in this case (in Showdown, the partner's switch is cancelled).
Also moves timing of Tera Stellar boost being used up to `MOVEEND_CLEAR_BITS` since the previous code didn't expend the boost sometimes when Dancer was activated or when the Pursuit cycle ended.
Fixes #6699
PhallenTree
=> Fixes Pursuit potentially causing both battlers to switch into the same mon

include/malloc.h
The new `.smol` compression scheme makes it so that some decompressions in battle would overflow the heap.
Increasing the heap by 592 bytes would be enough, but increasing by 768 makes the declaration a bit more even and leaves a buffer.
hedara
=> Increased heap by 768 bytes

include/test/battle.h, include/test/test.h, test/battle/ai/ai_switching.c, test/test_runner.c, test/test_runner_battle.c
Fixes battle tests not being torn down properly after a `KNOWN_FAILING` test.
Fixes `PASSES_RANDOMLY` tests not being marked as `KNOWN_FAILING_PASS` when they should.
hedara
=> Test runner fixes

src/battle_ai_util.c
Was writing another text for a different bug and fell into this rabbit hole when it wouldn't pass.
After one of the recent damage calc refactors, function parameters were put in the wrong order, with ability and hold effect swapped. This was only the case for the AI's calc.
This PR fixes this appropriately.
Relatedly I thought this kind of error would be caught by the compiler now, given that hold effects are an enum. Is that now how type checking works?
There's a test for this included in #7131, which is the bug I was initially fixing when I discovered this. Can't use the test without also fixing that bug. Perhaps we can consider that test load bearing lol. That PR will also not pass without this one.
@Pawkkie
=> Fix incorrect function parameters used in AI damage calc

src/follower_npc.c, src/overworld.c
If the player whites out while surfing, the follower NPC will now have their surf blob cleared upon map reload.
bivurnum
=> Bug fix: clear follower npc surf blob on white out

asm/macros/battle_script.inc, data/battle_scripts_1.s, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/neutralizing_gas.c
- Fixes `cantBeSuppressed` abilities activating again when Neutralizing Gas leaves.
- Fixes Imposter activating after switch-in (apparently this is the only timing when Imposter can activate, Skill Swapping, Wandering Spirit or obtaining the Ability via Receiver/Power of Alchemy do not allow Imposter to activate according to Bulbapedia).
Fixes #6668
PhallenTree
=> Fixes Neutralizing Gas leaving the field activating unsuppressable abilities again

src/battle_ai_main.c, src/battle_script_commands.c, src/data/moves_info.h, test/battle/move_effect/soak.c
Before, it used the move's actual type.
Also fixed inconsistency in the data itself.
=> Use `argument.type` for `EFFECT_SOAK`

src/data/moves_info.h
Fixes Rapid Spin description which contained incorrect grammar. Previously said "Spins attack that removes certain effects / Spins attack that removes some effects and ups speed"
Fixes #7178
grintoul
=> Fixes Rapid Spin description (#7178)

src/battle_util.c
Those berries activate when they are hit by a move which means on a gen3 or lower setting they would miss timing.
=> Fixes Enigma, Kee and Maranga Berry activation timing

src/battle_util.c
`CalcTypeEffectivenessMultiplierHelper` was taking `moveType` as input, but didn't use it and used the actual type of the input move instead.
hedara
=> Fix incorrect type input

src/overworld.c
Closes #6991
We broke the code once because the feature was pre-proc'd. Saveblock stuff has been kept behind a pre-proc.
=> Changes pre-proc to a normal if for Item Desc Header

src/battle_script_commands.c, test/battle/hold_effect/jaboca_berry.c
Jaboca berry not stolen by bug bite so it can trigger at end of move (more efficient than adding entirely new ITEMEFFECT just for jaboca)
Re: https://bulbapedia.bulbagarden.net/wiki/Bug_Bite_(move)#Generation_V_onwards
didn't think it was worth an entire gen 4 vs. 5 config to avoid config bloat wherever possible
=> Jaboca berry triggers instead of being stolen by bug bite

src/battle_script_commands.c
Fixes a bug where Pokémon caught during follower NPC partner battles would disappear instead of being added to the party or PC. The issue occurred because the temporary battle party would overwrite captures before the player's original party was restored.
Changes:
- Restores the player's real party before adding caught Pokémon
- Saves the party again after capture to prevent overwrites
- Maintains vanilla behavior for non-follower battles
[(link to Discord discussion)](https://discord.com/channels/419213663107416084/419214240277200898/1385935682886963310)
- Does not modify behavior for regular partner battles (e.g., Steven double battles)
- Does not affect PC storage logic beyond this specific case
juanjo4540
@all-contributors please add @J2M2 for code, bug, and test
=> [FIX]  Prevent caught Pokémon loss in NPC partner battles

data/battle_scripts_1.s
Fixes Emergency Exit sometimes causing a battler to become invisible due to the argument for `returntoball` being different.
The battler would be invisible until reloaded (example, opening the Pokémon menu and backing out)
PhallenTree
=> Fixes Emergency Exit sometimes causing an unrelated battler to become invisible

data/battle_scripts_1.s
A graphical fix. Truant loafing around script needs to flush the textbox before the popup otherwise the popop will occur while player moves are still displaying
=> Flush textbox for Truant Popup

src/follower_npc.c
Removed an unnecessary extra call to `TryUpdateFollowerNPCSpriteUnderwater` that was causing the normal bobbing behavior of follower NPCs to happen twice.
Here's a video demonstrating the bugged behavior:  
https://cdn.discordapp.com/attachments/1357388177161326834/1387899299995848734/fnpcunderwater.mp4?ex=685f0573&is=685db3f3&hm=ddab8cf6dbb8cb3bf5cb17eb61284a3a0e97471d57881e1d968c6e51490b63f0&
bivurnum
=> Bug Fix: Follower NPCs no longer have glitchy bobbing while underwater

include/gba/defines.h, ld_script_modern.ld, ld_script_test.ld, src/agb_flash_1m.c, src/rom_header.s, src/rom_header_gf.c, src/rom_header_rhh.c, src/siirtc.c
`--gc-sections` removes unused headers/version identifiers even with `USED`. This PR keeps them even with this flag enabled.
credits to @Gudf for the `KEEP` suggestion
.cawt
=> Keep removed headers

src/battle_ai_main.c
Super edge case, but if the player uses e.g. Copycat, and the opponent also knows copycat, the AI will enter an infinite recursive loop because if the predicted move is gLastMoves, it will try to run CheckBadMove on copycat endlessly.
For safety I added the same GetMoveEffect failsafe checks in all places that return an AI score function on a different move
=> Prevent AI Recursion

include/config/pokemon.h, src/pokemon.c
Previously, P_ONLY_OBTAINABLE_SHINIES was exclusively about the Battle Pyramid.  It now also checks that if B_FLAG_NO_CATCHING is assigned and set, it will not generate a shiny wild Pokemon.
wildvenonat
=> Changing P_ONLY_OBTAINABLE_SHINIES to truly be Only Obtainable Shinies

src/battle_anim_effects_1.c, test/battle/move_effect/ally_switch.c
gLastUsedMove, for example, needed to be updated with Ally Switch for proper future references. A mimic example test is added
Added a SwapBattlerMoveData function to help group swapped data a bit more
=> Ally Switch swap gLastX values

src/data/moves_info.h
Obsoleted all instances where an additional effect was defined with chance = 100 and SHEER_FORCE_NO_BOOST, since those are all by definition primary effects anyway.
thechurchofcage/Cringe Fairy
=> Removed all instances of .chance = 100, SHEER_FORCE_NO_BOOST

include/wild_encounter.h, src/dexnav.c, src/wild_encounter.c
- separated water and rock smash encounter rates so they can be adjusted independently of each other
- changed relevant `ChooseWildMonIndex()` functions to u32
- brought a couple functions up into `include/wild_encounter.h` for consistency with others (mostly dev qol)
fixes #7292- ty to @phexmiau for bringing it up!
@khbsd
=> feat: separate water and rock smash encounter rate checks

include/test/battle.h, include/test/test.h, ld_script_test.ld, test/test_runner.c, test/test_test_runner.c
`.persistent` was incorrectly positioned in the linker script which meant that the `RegisterRamReset(RESET_ALL)` in `src/crt0.s` zeroed `sCurrentTest`, causing the crashing test to re-run.
Fixes #7255
=> Fix crashing tests looping

src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
`ShouldSwitchIfAllMovesBad` is intended to trigger a switch if the AI has no moves that can affect the player.
To this point there was no handling for absorbing abilities, so something like Marowak-A with Lightning Rod can wall a TPunch Lopunny without the AI ever seeing an issue.
I'm putting this to master rather than upcoming as this was intended to already cover these cases with `AI_GetMoveEffectiveness`, and I didn't realize that had no handling for such abilities. A test is also included.
@Pawkkie
=> Fix switch AI not seeing absorbing abilities

Makefile, include/battle_util.h, src/battle_ai_main.c, src/battle_ai_switch_items.c, src/battle_ai_util.c, src/battle_script_commands.c, src/battle_util.c
`Ai_SetMoveAccuracy` returned an inaccurate result because only a few things were checked. This PR modifies the function `AccuracyCalcHelper` to work for ai and renames it to `CanMoveSkipAccuracyCalc`.
Also unified all function call enums into `FunctionCallOption`
=> Changes AccuracyCalcHelper into CanMoveSkipAccuracyCalc

data/battle_scripts_1.s
Fixes Cotton down using jumpiffainted in its loop. This doesn't work for e.g. 2v1 or 1v2 battles, when a battler is missing entirely. jumpifabsent will include the relevant checks via IsBattlerAlive
=> Cotton down use jumpifabsent

src/battle_controllers.c, src/battle_main.c
Please do a master->upcoming merge after reviewing, this was discovered while working on stuff for `upcoming` lol
`AI_DecideKnownAbilityForTurn` checks `gDisableStructs[battlerId].overwrittenAbility` before returning its own ability, which breaks in tests where that was being set for illegal abilities. This (to at least Alex) seems unnecessary and breaks the AI reading its own ability in tests for switchins, so it's being removed.
@Pawkkie
=> Fix AI seeing switchin abilities wrong in tests

src/battle_controllers.c, src/battle_gfx_sfx_util.c
Fixes shadows on Illusioned battlers using some values from the original species, causing the shadows to be placed in the wrong position and/or having the wrong size.
Fixes some animations, like the mon entry animation, using the animation from the original species instead of the one it's disguised as.
(GetBattlerVisualSpecies returns GetIllusionMonSpecies if `!= SPECIES_NONE`, otherwise `gBattleMons[battler].species`)
Does not fix 7068 but I believe it changes the shape of the shadows (but they're still not right) since it gets the species from the battler instead of from the mon.
PhallenTree
=> Fixes shadows and mon animations for Illusioned battlers

src/battle_ai_util.c, test/battle/ai/ai.c
This is 100% stealing ideas from @iriv24 after seeing their success in Emerald Imperium. Full credit to iriv for these I've just them into expansion, tweaked some formatting, and added tests.
AI will generally be smarter about when to use setup moves. It won't fall victim to "I outspeed you and you 2HKO me I'm safe (dies to priority move)", and also won't fall victim to infinitely setting up rather than hugely chunking a Sturdy mon that's forcing it to see a 2HKO instead of a OHKO.
@Pawkkie
=> Improve AI's setup logic

src/battle_ai_main.c
Fixes magnet rise timer value check in battle_ai_main
I also do not like that timer values are used inconsistently throughout expansion now... e.g. encoreTimer, disableTimer do not check gBattleTurnCounter, but magnetRiseTimer does? That is very confusing. I would suggest making it consistent
=> Fix magnet rise ai timer check

include/battle_ai_util.h, src/battle_ai_util.c, test/battle/ai/ai_switching.c
Switch AI will now pull weather effects from the switchin candidate's ability and pass that to the damage calc so it can see its own Drizzle etc.
In the pipeline to also do this for terrains, but weather handling is WAAAAAAAAAY more centralized and thus much easier / less invasive.
@Pawkkie
=> Switch AI can see weather abilities of switchin candidates during damage calcs

src/battle_controller_opponent.c
Any calls through to `GetBestMonIntegrated` from `OpponentHandleChoosePokemon` were hardcoded to use `SWITCH_AFTER_KO`, which breaks handling for hit escape effects like U-Turn that also call the switchin selection code from this function. This PR adds the exact same clause used to identify these cases in `GetBestMonIntegrated` so mon selection after hit escape effects is handled correctly instead of hardcoded.
Thanks to @iriv24 for finding this!
@Pawkkie
=> Fix hit escape switching hardcode

include/battle_util.h, src/battle_ai_util.c, src/battle_util.c, src/trainer_see.c
AI for switch in and move decisions is factoring in type effectiveness and damage rolls for fixed-damage moves. This PR fixes. 
before
https://cdn.discordapp.com/attachments/1077168246555430962/1396601926958714980/image.png?ex=687fffe6&is=687eae66&hm=585890cbcd7c41031de8a197f6d14a049eb925a3d133712d61d0db096c58f847&
after
https://cdn.discordapp.com/attachments/1077168246555430962/1396866813987655751/image.png?ex=687fa518&is=687e5398&hm=ee898cd3f53e2af3589db8f12b8eb21694ab075982e0b161a8fefe0b926f9062&
#7381
grintoul
@AlexOn1ine for advising a more intelligent solution
=> fixed-damage-move-ai-calc-fix

src/pokemon.c
Found by @AlexOn1ine, `sSubstructOffsets` are non-vanilla which breaks saves.
=> Fix substruct offsets from #7313

data/battle_scripts_1.s, test/battle/move_effect/magic_room.c, test/battle/move_effect/magnet_rise.c, test/battle/move_effect_secondary/will_o_wisp.c
Prevents Magnet Rise from working when user is Rooted or Smacked Down.
Added tests and removed extra test file for Will-o-Wisp in `test/battle/move_effect_secondary` (`test/battle/move_effect_secondary/burn.c` already exists).
Fixes #7447
PhallenTree
=> Fixes Magnet Rise when user is Rooted/Smacked Down

src/battle_script_commands.c, src/battle_util.c
- Fixes Round and Fusion Flare/Bolt doubling power from the previous turn's move, since it checked `gLastUsedMove` which isn't cleared at the end of the turn.
Clearing `gLastUsedMove` isn't an option since Copycat also uses it and it can definitely call the previous turn's moves.
- Fixes Stockpile counter removal checking if Swallow would hit twice instead of if Spit Up would hit twice.
- Fixes potential out of bounds check when updating Round turn order.
- Fixes Pledge setup move not doubling Stomping Tantrum's power. [Source](https://wiki.xn--rckteqa2e.com/wiki/%E3%81%98%E3%81%A0%E3%82%93%E3%81%A0#%E6%8A%80%E3%81%AE%E4%BB%95%E6%A7%98)
> When the power doubles
If the previous turn's action failed due to the following reasons, the effect of doubling the power will be applied.
(...)
> - …
=> Fixes Round and Fusion moves doubling power from previous turn's move

migration_scripts/1.13/convert_compressed_files.py, src/contest_painting.c
The first commit modifies the smol conversion script so that it also converts `rl` compression to `smol` compression.    
The second commit is the result of running the conversion script
Size before replacement: `74.02%`    
Size after replacement: `73.98%`
When I was checking this, I used [museum_painting.patch.gz](https://github.com/user-attachments/files/21552432/museum_painting.patch.gz) to populate the museum paintings during a new game, for the purpose of inspecting the museum paintings
yoshord
=> Replace all usages of rl compression with smol

src/battle_main.c
I was running some animation tests and the Z-move Acid Downpour will timeout/softlock if the gScanlineEffect is not cleared.
The exact process is not clear but one of the visual tasks of the animations get destroyed by an unknown process instead of clearing itself properly. When ended this way, the visual task counter is not decreased and waitforvisualfinish never ends causing the move to softlock.
This change fixes the issue.
=> Clear gScanlineEffect to fix timeout in acid downpour animation

include/follower_npc.h, include/global.h, src/field_player_avatar.c, src/follower_npc.c
Doing a forced movement before or after a ledge jump causes the follower NPC to desync or have buggy behavior. This fixes that issue.
Video showcasing the issue:  
https://discord.com/channels/419213663107416084/1357388177161326834/1379225679618510860
Gif showcasing the behavior after the fix:  
bivurnum
=> Bug fix: add handling for forced movements into/after ledge jumps with follower NPCs

include/constants/battle_ai.h
Changes AI Flag definitions to use a macro, simplifying user input. Removes the need for ((u64)1 << x) definitions at and beyond flag 32.
@hedara90 for creating the macro
grintoul
=> Macro-for-AI-Flag-definitions

test/pokemon.c
Adds a test for `struct BoxPokemon` integrity.
Most things that can be checked with `GetMonData` is checked.
This test fails on #7313, but passes after the fix.
hedara
=> Add test for BoxPokemon integrity

src/battle_ai_switch_items.c, test/battle/ai/ai_switching.c
#7364 has had a really positive reception! However, I forgot to switch out the doubles logic to also use it, as the doubles system is still much simpler than the singles system and is handled differently.
This PR updates the doubles functionality to match the new singles functionality.
@Pawkkie
=> Fix doubles switch AI to use new type matchup system

src/battle_ai_switch_items.c
Function wasn't checking `currentHP` before adding berry health.
Also a few cases of `>` that needed to be adjusted.
Borderline of bug fix and feature as is often the case for these. AI will see one shot healing items better now when doing switchin calcs.
Thanks again to @iriv24 for debugging support!
@Pawkkie
=> Fix GetSwitchinHitsToKO one shot heal calcs

src/item_use.c
- Changes it so that you can actually use the town map as a registered item. 
- Related to #7481, but I decided to make this one separate since it's not a party menu item...and it turned out to be vastly more simple than I was anticipating
https://github.com/user-attachments/assets/d8914a7f-3a3e-4140-b6ef-e5f393187d04
- Adding the fancy map opening animation from FRLG or something
ravepossum
=> Fix using town map as registered item

include/party_menu.h, src/item_use.c, src/party_menu.c
- Modifies `SetUpItemUseCallback()` to allow using items of type `ITEM_USE_PARTY_MENU` from the field as registered items. 
- This is a follow-up to #5810 that's intended as a more permanent fix. 
- `gPartyMenu`'s `data1` field is repurposed further as a way of indicating to the party menu to return to field upon exit. It isn't used for anything else during this window of time as far as I can tell. This allows us to avoid using additional EWRAM.
- I'm pretty sure this qualifies as a fix for master, but just let me know if I need to repoint this at upcoming.
https://github.com/user-attachments/assets/4d6555e5-7dba-4f88-98d3-b27ee797707b
- This PR does not address the issue of the town map not being able to be used as a registered item. It's different enough that I'm planning on submitting …
=> Implement using party menu items from field

test/test_runner_battle.c
Data in the test parties can potentially carry over between tests.
This makes it so that parties are always zeroed after a battle test.
How to test behaviour.
Run `make check TESTS="Heal Bell" with and without this PR, note that it must be single threaded.
hedara
=> Clear out parties between battle tests

include/battle_ai_util.h, src/battle_ai_main.c, src/battle_ai_util.c
Hazards moves didn't take into account that they're a mix of damaging and non-damaging.
Mycelium Might wasn't counted as a mold breaker type ability.
wildvenonat
=> Improved hazards logic and Mycelium Might ignores ability checks

include/field_effect.h, src/field_effect.c, src/field_screen_effect.c
Copied the code from the Pokecenter escalators to hide the player's overworld shadow and put follower in pokeball when going up and down sideways stair warps
=> Remove shadow and hide follower on stair warp

include/battle_ai_util.h, src/battle_ai_field_statuses.c, src/battle_ai_main.c, src/battle_ai_util.c, test/battle/ai/ai_doubles.c
The intention here is to reduce the number of places that need to be updated every time a new move effect is added.
AI Effects is a bitfield of major utility traits of a move.  Sets weather, sets terrain, removes stat changes, removes the opponent's screens, sets your own screens, that sort of thing. The goal here is that if you add a new move effect that's like if Court Change also removed items, you add it to the case statement in GetAIEffectGroup, and if you decide it should also have the Clear Smog move effect, then it won't be used at the same time as Defog, Aurora Veil, Reflect, Light Screen, Brick Break, Haze, Clear Smog, or Freezy Frost, without having to update every AI reference to any of those moves. Similarly, you shouldn't set a terrain effect the same turn you plan on using …
=> AI handling for similar utility moves

include/test/overworld_script.h, tools/preproc/asm_file.cpp
- WARNING: If an `enum` is not present in an assembled object file, it will not be available in C. This is not a problem for `OVERWORLD_SCRIPT` because you would not use an `enum` value that is not available in `data/event_scripts.s` in those scripts.
Closes #7394
=> Hacky support for enums in C asm statements

src/battle_ai_main.c, test/battle/ai/ai_check_viability.c
Refresh could only be used if the OPPONENT had a status ailment.
I also changed it so it's only score increased if it's a status that Refresh can actually cure, e.g., not frozen or asleep.
wildvenonat
=> Fixing Refresh AI scoring

src/battle_ai_main.c
This does NOT include handling for the AI to ever pick any of those three moves; two of those need to go in CheckViability and the third needs a complete rework for a number of reasons.  This is only updating the commented out segments to current standards and uncommenting them.
wildvenonat
=> Uncommenting out No Retreat, Clangorous Soul, and Extreme Evoboost from CheckBadMove

Makefile, include/test/battle.h, include/test/test.h, test/test_runner.c
`make check TESTS="test/foo.c"` to run all tests from `test/foo.c`.
`make check TESTS="*Illuminate*"` to run all tests with "Illuminate" in the name.
Closes #3485.
Thanks to @SBird1337 for the `strstr` idea.
=> make check TESTS="..." support for filenames and infix matches

include/test/battle.h, test/test_runner_battle.c
MOVE(SHELL_SIDE_ARM, target, WITH_RNG(RNG_SHELL_SIDE_ARM, fixed_rng)
will only properly fix the RNG on the very first turn on battle. This is because SHELL_SIDE_ARM damage type is determined at the beginning of combat for the first turn and at the end of the previous turn for every turn after that.
I fixed it by making sure `SetShellSideArmCategory` properly reads fixed rng even if it occurs during end of turn but it means multiple uses of shell side arm in the same turn will use the same fixed RNG. A check has been added to make sure the test will fail if someone try to fix the rng of multiple shell side arm moves in the same turn.
Move rng is decided at the beginning of the test creation before the battle start so I needed to store the information of the number of shell side arm used on …
=> Fix shell side arm rng in battle tests moves

src/item.c
Makes it so that pockets are compacted as part of the `BagPocket_RemoveItem` operation if an entire stack is thrown.
Fixes #7570 
hedara
=> Fix tossing a stack of berries hiding following berries

asm/macros/event.inc
Adds a comment in event.inc for what callback to use when no callbacks are used for dynmultichoice macro.
rubyraven
=> Added comment in event.inc for simple menus in dynmultichoice

src/item_use.c
- It appears the lines that were setting `gTasks[taskId].data[0]` for the form change item field use funcs were not used at all. I can't see anywhere they're actually used, and deleting them does not appear to alter functionality. I've deleted the lines to fix issue #4544.
- The Poke Flute field use funcs had some references to `data[3]` that were not using the `tUsingRegisteredKeyItem` alias. I've fixed these.
- The honey item field use func had a comment left in and a line setting task data that does nothing as well. I've removed those.
- Fixes #4544 
- Remaining references to `data[X]` without an alias that are from upstream pret
ravepossum
=> Fix Form Change Item Task Data and Clean Up Field Use Funcs

src/battle_tower.c, src/data/battle_partners.party
Historically Partner trainers pulled AI flags from their equivalent define value regular trainer, meaning PARTNER_STEVEN took AI from TRAINER_SAWYER_1. The Partner AI flags PR #7378 broke this link but did not add AI: Basic Trainer to PARTNER_STEVEN, resulting in random AI. PR fixes.
Added AI: Basic Trainer to PARTNER_STEVEN.
Included "constants/battle_ai.h" to "src/battle_tower.c", which was missed from the original PR.
Before:
After:
grintoul
=> Restore AI: Basic Trainer to PARTNER_STEVEN

data/battle_scripts_1.s
- Does what it says on the tin. Multi battles in the battle frontier no longer trigger a whiteout.
- Fixes #4006 
ravepossum
=> Fix in-game partner battles always causing a whiteout

data/battle_scripts_1.s, include/battle.h, src/battle_controllers.c, src/battle_script_commands.c, src/pokemon_animation.c
Animations can potentially break because the animations for `B_ANIMATE_MON_AFTER_KO` could still be running when new animations start.
https://github.com/user-attachments/assets/5966a5d3-687f-40ae-88ee-41b34ec0c7a3
This adds another counter that `waitanimation` checks before continuing.
https://github.com/user-attachments/assets/ead1989f-8b97-423e-94db-9092ac16f312
hedara
=> Fix B_ANIMATE_MON_AFTER_KO with a new counter

tools/trainerproc/main.c
Since the function can be useful but still shows up during compile time I think we should ifdef it.
=> Suppress trainerproc compile warning for unused func

test/battle/ability/bad_dreams.c, test/battle/ability/cheek_pouch.c, test/battle/ability/comatose.c, test/battle/ability/competitive.c, test/battle/ability/contrary.c, test/battle/ability/corrosion.c, test/battle/ability/costar.c, test/battle/ability/cud_chew.c, test/battle/ability/cursed_body.c, test/battle/ability/cute_charm.c, test/battle/ability/defiant.c, test/battle/ability/flower_veil.c, test/battle/ability/insomnia.c, test/battle/ability/moxie.c, test/battle/gimmick/dynamax.c, test/battle/gimmick/zmove.c, test/battle/hold_effect/cure_status.c, test/battle/move_effect/beat_up.c, test/battle/move_effect/double_power_on_arg_status.c, test/battle/move_effect/mist.c, test/battle/move_effect/nightmare.c, test/battle/move_effect/purify.c, test/battle/move_effect/strength_sap.c, test/battle/move_effect_secondary/remove_status.c
Added TODO tests for abilities that start with C.
Also, filled Competitive tests based on Defiant's.
Besides Competitive, it only writes the titles for tests.
=> Added Ability TODO tests - Volume C

src/battle_ai_switch_items.c
Fixes #7595
The issue isn't limited to Explosion. It can be triggered if player mon dies alongside AI mons (eg Life Orb). I've only fixed it for the default switch in AI. If the fix is good enough I can fix it for the smart switch in.
Trainer to repro
```
=== TRAINER_TIANA ===
Name: TIANA
Class: Lass
Pic: Lass
Gender: Female
Music: Female
Double Battle: Yes
AI: Check Bad Move
Zigzagoon
Level: 4
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe
Shroomish
Level: 4
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe
Manectric
Level: 100
- Splash
- Celebrate
Magneton
Level: 100
- Splash
- Celebrate
```
=> Fix duplicate switch in after faint

src/battle_script_commands.c
Removes `IsProtectEffectAffected` since it is unused in master and upcoming.
=> Remove unused function

src/vs_seeker.c
This PR 
* Fixes https://github.com/rh-hideout/pokeemerald-expansion/issues/6928
* Fixes https://github.com/rh-hideout/pokeemerald-expansion/issues/6919
The Vs. Seeker has been broken since #5982. This PR changes `GetTrainerFlagFromScript` by looking at the 3rd byte instead of the 2nd in the `trainerbattle` command.
You can recreate this branch by applying a patch or pulling the repo. From a clean version of expansion's `master`, you can either:
`wget https://files.catbox.moe/pi08q5.patch ; git apply pi08q5.patch ; rm pi08q5.patch`
`git remote add psf-expansion https://github.com/PokemonSanFran/pokeemerald-expansion/ ; git pull psf-expansion vsSeekerFix`
After replicating the branch, to recreate my testing environment, you can either directly download the config file and debug script, or …
=> Fix Vs Seeker Trainer Battle script issue

data/battle_scripts_1.s
When going into `moveend` the original attacker for doodle wasn't restored.
=> The original attacker wasn't restored for Doodle

include/battle_controllers.h, include/constants/item_effects.h, include/pokemon.h, src/battle_controllers.c, src/battle_util.c, src/data/pokemon/item_effects.h, src/pokemon.c, test/battle/item_effect/increase_stat.c, test/battle/move_effect/embargo.c
- Restores of the vanilla behavior of X items increasing a mon's friendship in battle. 
- With the new refactored item effects, I had to write the update into `HandleAction_UseItem()` since the stat changes are now handled in battle scripts.
- Adds a test for X item friendship increase
- Fixes #3531 
ravepossum
=> Restore X item friendship increase

data/battle_anim_scripts.s, include/battle_anim_scripts.h, include/config/battle.h, include/constants/battle_anim.h, src/battle_anim.c, src/battle_gfx_sfx_util.c, test/battle/hold_effect/cure_status.c, test/battle/move_effect_secondary/freeze.c, test/battle/move_effect_secondary/tri_attack.c, test/battle/move_effects_combined/flinch_status.c, test/battle/status1/frostbite.c
Adds a separate animation for Frostbite with a config to toggle whether to use it or the FRZ animation, defaulting to FRB for when FRB is enabled
Current setup uses FRZ animation for both FRZ and FRB. New FRB animation feels more suitable for what the status condition is and enables the two to be distinguished if users wish to use both conditions. 
Changes:
1. Added `gBattleAnimStatus_Frostbite`
2. Added `B_USE_FROSTBITE_ANIMATION` in `include/config/battle.h`, defaulting to `TRUE`.
3. Defined `B_ANIM_STATUS_FRB`, which returns `gBattleAnimStatus_Frostbite` or `gBattleAnimStatus_Freeze` depending on config
4. Separated animations launched for `STATUS1_FREEZE` and `STATUS1_FROSTBITE` in `InitAndLaunchChosenStatusAnimation`. (3) means FRZ will be used for FRB if config set to FALSE
5. …
=> Separates FRB and FRZ animations

include/window.h, src/international_string_util.c, src/text.c
Originally designed so that I could write text directly to VRAM for a specialized use-case where I couldn't afford to buffer the text to EWRAM and then copy from that buffer to VRAM during v-blank.
Should make rendering text faster if there's a lot of glyphs to render (e.g. instant text and UIs), especially if the render calls use the exact same colors many times in a row.
Instrumented `PrintPageSpecificText` to test the impact.
```diff
static void PrintPageSpecificText(u8 pageIndex)
{
+   CycleCountStart();
u16 i;
for (i = 0; i < ARRAY_COUNT(sMonSummaryScreen->windowIds); i++)
{
if (sMonSummaryScreen->windowIds[i] != WINDOW_NONE)
FillWindowPixelBuffer(sMonSummaryScreen->windowIds[i], PIXEL_FILL(0));
}
sTextPrinterFunctions[pageIndex]();
+   DebugPrintf("PrintPageSpecificText(%d): %d", …
```
=> Text rendering optimizations

src/battle_script_commands.c
The crit stage calculation was using direct boolean results as arithmetic input where a numerical value is expected.
Replaced the direct booleans with ternaries.
hedara
=> Replace boolean multiplications with ternaries

src/battle_ai_main.c, src/battle_ai_util.c, test/battle/ai/ai_check_viability.c
Moves with an additional effect stat drop did not check if the stat drop is actually possible before scoring for it, as that's normally handled within CheckBadMove so it isn't part of IncreaseStatDownScore.  The "can this stat be lowered?" check also did not take into account Shield Dust existing.
Test fails without the changes; passes with.
ETA: threw in some handling for stat-down max move effects because they're regular degular additional effects for the purposes of users.  Also corrected Shield Dust to treat actual Max Moves as penetrating it.
wildvenonat
=> Improved move additional effect handling; now accounts for Shield Dust.

src/battle_ai_main.c, test/battle/ai/ai_doubles.c, test/battle/move_effect/coaching.c
AI handling for Coaching.
The addition of Explosion to "AI will not use a status move if partner already chose Helping Hand" is because Explosion should never be chosen over Helping Hand, meaning that opponentLeft continues to behave correctly, but it is a physical move that incentivizes Coaching.
wildvenonat
=> AI handling for Coaching.

test/test_runner.c
A tests that crashes didn't get cost assigned to it, so which test gets assigned to which runner got desynched after a crash.
This was bad because we always ran a crashing test as the first test.
hedara
=> Fix crashing tests duplicating tests from another thread

include/test/battle.h, include/test_runner.h, src/battle_main.c, test/battle/ai/ai_smart_tera.c, test/battle/ai/gimmick_dynamax.c, test/battle/ai/gimmick_mega.c, test/battle/ai/gimmick_z_move.c, test/test_runner_battle.c
Sets up `chosenGimmick` as appropriate so that the AI is able to see that it can use those gimmicks.
Untested, except for the `KNOWN_FAILING` Tera test which now passes. @surskitty, can you review this?
=> AI Tests: Gimmick Support

ld_script_test.ld, test/test_runner.c
The test runner didn't have `default` case in the main loop which was causing infinite stalls if the state was ever outside of the allowed range of states. Now states outside of the allowed range causes an immediate exit.
Also changed the linker script for tests to not misbehave if less than 4 bytes of variables use `EWRAM_INIT`.
hedara
=> Fix EWRAM_INIT in tests and add a default state to test runner main loop

src/battle_script_commands.c, test/battle/move_effect/beak_blast.c
Beak Blast had an incorrect `CanBeBurned` check which resulted in fire type being burned when attacking into Beak Blast.
Discovered by Kumatora on the TAH discord.
hedara
=> Fix Beak Blast burning fire types

src/pokemon.c
The If_gender always returns TRUE because it checks if a pokemon's gender is equal to its gender. This PR fixes this
Thanks to Charlie III in TAH for noticing the issue
Before:
https://github.com/user-attachments/assets/637f84f7-ccf6-4909-bc8a-a0f974797125
After:
https://github.com/user-attachments/assets/92f8ec59-55b9-4cc8-a247-aed91833a1e5
Jamie (foster_harmony)
=> Fix bug with IF_GENDER evolution condition

test/battle/ability/overcoat.c, test/battle/ability/slush_rush.c, test/battle/ai/can_use_all_moves.c, test/battle/gimmick/dynamax.c
Setting B_PREFERRED_ICE_WEATHER config to B_ICE_WEATHER_SNOW caused the following 4 tests to fail.
Updated to assume hail because of hail damage being tested:
- Overcoat blocks damage from hail
- Slush Rush doesn't prevent non-Ice types from taking damage in Hail
Updated to check for and work with snow preferred:
- Dynamax: Max Hailstorm sets up snow/hail
- AI can use all moves, 201-300
phexi
=> Fix failing test for B_PREFERRED_ICE_WEATHER = B_ICE_WEATHER_SNOW

src/pokemon_storage_system.c
Fix transparency error for pokemon sprites in box storage when moving items
Fix issue #6426 
Jamie (foster_harmony)
=> Pokemon storage moving items bugfix

include/battle.h, src/battle_main.c, src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/helping_hand.c
Uses 3 bits, because, due to Instruct and Triple Battles, the maximum number of Helping Hand boosts you would be able to get is 5, however since Instruct and Triple Battles are not in the same game, the maximum amount of Helping Hand boosts achievable in an actual game is 3.
Also fixes Helping Hand sometimes succeeding after the ally has already moved. (Prankster-boosted moves with +4 priority)
Adds Helping Hand tests.
Early Gens Beat Up is still boosted a single time by Helping Hand.
PhallenTree
=> Fixes Helping Hand boosts not stacking with each other

include/battle.h, src/battle_script_commands.c, src/battle_util.c, test/battle/ability/lightning_rod.c
The purpose of `lightningRodRedirected` and `stormDrainRedirected` is to print the took attack message and record the ability. However the ability is recorded much earlier and the message is the same for both abilities so we can use a single flag for both.
=> Minor clean up for Lightning Rod / Storm Drain

include/battle_script_commands.h, src/battle_script_commands.c, src/battle_util.c, test/battle/move_effect/sucker_punch.c, test/battle/move_effect/upper_hand.c
Fixes Instructed moves looking at the wrong turn order number (example, Instructed Upper Hand and Sucker Punch would be successful if the user's original move was before the target's move, even if the target has now already attempted to act)
Fixes #7776
This PR may change AI calcs when it comes to calculating damage of Payback, Bolt Beak, and accuracy with Zoom Lens.
PhallenTree
=> Fixes Instructed moves looking at the wrong turn order number

data/battle_scripts_1.s, test/battle/move_effect_secondary/flame_burst.c
Fix by Alex.
Fixes #7792 
hedara
=> Fix Flame Burst timeout if primary target is fainted

src/battle_setup.c
Added a missing `LOCALID_NONE` in `SetMapVarsToTrainerA`.
estellar.cheese
=> Added missing `LOCALID_NONE`

test/battle/hold_effect/big_root.c
`Q_4_12` calls were using incorrect arguments.
Changed attacker to Xurkitree to get healing values into multi-digit ranges.
hedara
=> Fix Big Root tests

include/battle.h, src/battle_script_commands.c
Removes the unused ``roostTypes`` and ``isAtkCancelerForCalledMove`` fields from ``BattleStruct``
bassoonian
=> Remove unused gBattleStruct fields

src/battle_tower.c
Since the frontier mons didn't have Poké Ball data set, they were defaulting to Strange Balls once they were set as Ball 0.
Figured that since Strange Balls are only meant to be used to represent "invalid" Poké Balls, the Frontier data shouldn't be able to use it.
Before vs After
Fixes #6761
=> Fix Battle Frontier using Strange Balls

src/battle_script_commands.c
Knock Off correctly handled overlapping choice lock with Sage Power/Gorilla Tactics, but this was never applied to the battle scripts for thief or trick effects. I also adjusted all three to reference MOVE_NONE for the choice lock move replacement instead of 0, hopefully improving AI behavior consistency, though if that is incorrect (I'm not a C/romhack expert by any means!), feel free to revert those instances of MOVE_NONE to 0.
This issue was discovered in Pokemon Emerald Imperium v 1.3.1, link to the PR for the fix for that romhack and supporting bug documentation located [here](https://github.com/iriv24/pokeemerald-expansion/pull/94), including a save file (inside the associated Discord thread) and steps to reproduce in that romhack.
VOD link for instance of bug happening (in Pokemon …
=> fix (choice lock): Gorilla Tactics interactions with choice item removal

data/scripts/debug.inc, include/battle_controllers.h, include/battle_util.h, include/config/battle.h, src/battle_controllers.c, src/battle_main.c, src/battle_util.c, src/debug.c, src/item_use.c, src/overworld.c
No bag use flag changed to a variable:
- It only applies to player controller
- It has 3 mode, no bag, no bag against trainer and available bag
- Update debug menu to allow switching between modes if var is set
- Prevent ball to be thrown when bag is disabled for wild battles
https://github.com/user-attachments/assets/c4b12369-c95c-4dbf-bd94-f6d343b108b9
Wally Tutorial issue that has been fixed (uses early version of the PR)
Before:
https://github.com/user-attachments/assets/dfc00041-959d-49fa-a1f2-389ff218dfd7
After:
https://github.com/user-attachments/assets/51ce6157-bf44-41b4-8211-f3f295b9fc4d
Fixes #6571
- IMPORTANT: The config flag B_FLAG_NO_BAG_USE has been removed
- A config var B_VAR_NO_BAG_USE has been added to replace it. It allows you to choose between:
bag available in battle, …
=> No bag use flag changed to a varable

src/easy_chat.c
When FREE_MYSTERY_GIFT is set to TRUE, `GetQuestionnaireWordsPtr` returns NULL, and gcc decides that writing to NULL is an UB and crashes the rom. I thought it was MyBoy-only issue at first, but no, it was happening in all emulators.
Discovered thanks to PCG who brought attention to this issue.
=> Fix LTO breaking with FREE_MYSTERY_GIFT set to TRUE

src/battle_ai_util.c
In case the recorded item wasn't properly deleted add a failsafe.
This might be a potential bugfix in a few cases.
=> Add failsafe to AI_DecideHoldEffectForTurn

src/pokedex.c
Fixes #7695
The issue was that the game runs out of heap by the time the terrain's gfx are decompressed. `SetMultiuseSpriteTemplateToPokemon` requires less heap than `CreateMonPicSprite`, so it works.
Though I guess we could do something(debug printf message?) when trying to decompress .smol without necessary heap.
=> Fix for uncaught mon with terrain active

asm/macros/event.inc, include/constants/pokemon.h, src/script_pokemon_util.c, test/pokemon.c
Mons generated with `givemon` are currently forced to be either shiny or not preventing random gift shinys. (e.g. starters and castform)
.cawt
=> Fixes shininess for givemon

src/battle_interface.c
- The last used ball window and the move description window share a palette and can appear on-screen at the same time. 
- When the move description window sprite is hidden and destroyed, it frees its palette, which shares a palette tag with the last used ball window. 
- This causes the palette to incorrectly change for the last used ball window when the move description window reappears and loads the palette in a new slot.
- I've changed the functions that destroy the two windows to avoid freeing the palette if the other window's spritesheet is loaded. The palette will then be freed by the other one being destroyed later.
https://github.com/user-attachments/assets/944a144e-7da7-487d-9cf9-ed30697c620a
Fixes #6428 
- Unrelated - I noticed a small graphical glitch with type icons can occur …
=> Ensure last used ball and move description window sprites don't free palette too early

data/battle_scripts_1.s, test/battle/ability/steadfast.c
Fixes Steadfast not activating due to missing an ability check.
Added Steadfast tests.
Fixes #7858
PhallenTree
=> Fixes Steadfast not activating + tests
