- src/map_name_popup.c
Incorportate commits from that branch in other to minimize conflicts downstream.
> Fix conflicts with RavePossum's standalone BW pop up

- include/battle_script_commands.h
- src/battle_ai_util.c
- src/battle_script_commands.c
- test/battle/ai.c
Fixes AI not recording Battle/Shell Armor abilities
Fixes AI not considering guaranteed crits
Renames various variables and functions to "odds" from "chance" for clarity.
duke5614
> Fix AI crit calculations

- include/config/overworld.h
- src/data/object_events/object_event_subsprites.h
- src/event_object_movement.c
- src/field_effect_helpers.c
Also renames `LARGE_OW_SUPPORT` to `OW_LARGE_OW_SUPPORT` for consistent prefix usage.
Fixes #4698
bassoonian
> Add option to hide substitute followers

- src/battle_ai_util.c
- test/battle/ai.c
Replaces some code that attempted to do this by preferring special moves over physical ones but even then it failed because it returned the wrong values.
duke5614
> AI actually avoids contact vs rocky helmet/rough skin

- data/scripts/debug.inc
Adds release to debug scripts, preventing followers from freezing after running them.
Fixes #4777 
bassoonian
> Add release to debug scripts

- data/battle_scripts_1.s
- test/battle/hold_effect/mirror_herb.c
> Fix Soul-Heart changing stats of wrong battler

- src/battle_controllers.c
- src/battle_gfx_sfx_util.c
- src/pokemon.c
> Fix shiny value not being updated for battle mons

- src/battle_ai_main.c
> Fix passing hold effect instead of ability in one call of ShouldSetSandstorm

- src/battle_ai_main.c
Title.
Doesn't handle other cases of `score += XYZ`.
> Fixed AI_FLAG_RISKY score increase making tests with AI_LOG fail

- src/battle_util.c
- test/battle/move_effect/body_press.c
Fixes #4316
With tests.
I believe I understood well how the interaction between these two works, but if I made a mistake, please let me know.
> Fix Body press interaction with Wonder room

- src/battle_script_commands.c
- test/battle/move_effect/relic_song.c
> Fix Relic Song transforming species other than Meloetta

- include/pokemon.h
> Fixing my mess [correct hex in speciesInfo]

- data/battle_scripts_1.s
- src/battle_script_commands.c
- test/battle/move_effect/pursuit.c
> Fix Pursuit not getting Choice-locked on switch-out

- src/battle_script_commands.c
- test/battle/move_effect/encore.c
Fixes #3395
Tests written by Alex.
Hopefully it works as expected now.
> Fix Encore turn amount bug

- src/battle_ai_main.c
> Fix struct with unitialized members being used UB

- src/daycare.c
Like Sinistea always producing phony offspring, Poltchageist should produce only counterfeit offspring.
kittenchilly
> Fix Poltchageist not always producing counterfeit offspring

- test/battle/ability/anger_point.c
- test/battle/ability/moxie.c
> Tests for Anger Point and Moxie

- include/constants/global.h
- include/global.h
- include/roamer.h
- src/battle_main.c
- src/new_game.c
- src/overworld.c
- src/pokedex_area_screen.c
- src/roamer.c
- src/wild_encounter.c
Reverts rh-hideout/pokeemerald-expansion#4762
> Revert "Add support for multiple roamers"

- data/maps/MossdeepCity_SpaceCenter_2F/scripts.inc
THIS IS A PRET MERGE - DO NOT SQUASH
Adds the latest pret commit to expansion's master. The shasum will differ because of `BUGFIX`, but this is as expected. See the (three line) diff for more.
bassoonian
> Merge in pret 189d542

- src/battle_script_commands.c
Fixes #4528
Sadly no tests, because we can't check which anim played.
> Contrary stat drop anim with Spectral Thief

- data/battle_anim_scripts.s
- data/battle_scripts_1.s
- data/contest_ai_scripts.s
- data/event_scripts.s
- include/config/general.h
- include/constants/global.h
- include/global.h
- src/libisagbprn.c
- src/map_name_popup.c
- src/mini_printf.c
- src/siirtc.c
I saw a lot of users being confused on where do they enable features such as the HGSS dex.
> Move general config file to the config folder

- test/battle/ability/full_metal_body.c
- test/battle/ability/white_smoke.c
Adds commented files that point to Clear Body for similar abilities.
#4834 
@Pawkkie
> White Smoke and Full Metal Body tests point to Clear Body file

- include/battle.h
- src/battle_controller_player.c
This saves whooping 4 bytes of EWRAM
Fixes #4676
Also, I removed some `#if` since we agreed not to use them.
> Move EWRAM variables from battle controller player file to gBattleStruct

- src/battle_script_commands.c
- test/battle/move_effect/fury_cutter.c
> Fix fury cutter scaling up to 640 power

- src/battle_util.c
- test/battle/ability/comatose.c
> Fix comatose - transform - gastro acid interaction

- src/battle_util.c
- test/battle/move_flags/ignores_target_ability.c
> Moves with the ignoresTargetAbility flag do not ignore the attacker's own ability

- src/data/moves_info.h
> [Update moves_info.h] wrong move names

- test/battle/move_effect/plasma_fists.c
This test used Ember, which is not affected by Pixilate, so any conclusions drawn from its results were void.
Also replaced mega Altaria with Sylveon as the mega evolution parts of this test are irrelevant.
duke5614
> Fix plasma fists + pixilate test

- src/data/pokemon/species_info.h
- src/data/pokemon/species_info/gen_7_families.h
- src/data/pokemon/species_info/shared_dex_text.h
- test/species.c
Minior (Meteor form) pokedex description was missing.
Also added test to find species without a description.
.cawt
> added missing Minior description + test for missing descriptions

- include/battle_util.h
- src/battle_util.c
- test/battle/form_change/mega_evolution.c
> Fix Megas gaining abilities after fainting

- data/battle_scripts_1.s
- src/battle_script_commands.c
- test/battle/ability/sticky_hold.c
Also added an ability popup
Fixes #4884
duke5614
> Fix sticky hold softlock

- src/battle_script_commands.c
> Shed tail rounds up, not down

- src/battle_script_commands.c
- test/battle/ability/parental_bond.c
> IsFinalStrikeEffect uses effect instead of move

- src/data/pokemon/species_info/gen_1_families.h
- src/data/pokemon/species_info/gen_2_families.h
- src/data/pokemon/species_info/gen_3_families.h
- src/data/pokemon/species_info/gen_4_families.h
- src/data/pokemon/species_info/gen_5_families.h
> Fixed P_UPDATED_ABILITIES not reverting newly given abilities in Gens 4/6/7

- src/battle_tower.c
> Fixes wrong nature on partner

- src/shop.c
> shop menu allows for 6 digits item prices

- src/data/pokemon/species_info.h
Found by Zatsu on RHH's Discord
> Fixed SPECIES_NONE's overworld data not compiling when ObjectEventGraphicsInfo gets new fields

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- CHANGELOG.md
- docs/SUMMARY.md
- docs/changelogs/1.8.x/1.8.5.md
- docs/changelogs/template.md
- include/constants/expansion.h
Changelog in `docs/changelogs/1.8.x/1.8.5.md`.
Also:
- Some adjustments to make changelog page in the documentation site look better.
- Added refactors to version template
> Version 1.8.5

- include/battle.h
- include/battle_util.h
- src/battle_main.c
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/ability/trace.c
> Fixes Trace turn order

- src/data/pokemon/level_up_learnsets/gen_9.h
> Fix Basculegion's gen9 level up learnset

- src/data/moves_info.h
> Fix Diamond Storm's effect

- Makefile
- tools/preproc/Makefile
- tools/preproc/asm_file.cpp
- tools/preproc/asm_file.h
- tools/preproc/c_file.cpp
- tools/preproc/c_file.h
- tools/preproc/io.cpp
- tools/preproc/io.h
- tools/preproc/preproc.cpp
sha1sum both before and after: 57938974a075b09185e7ffaad2320a3529e0d648
Adds the new C-style enums in preproc commit by @SBird1337 [(550e668)](https://github.com/pret/pokeemerald/commit/550e6688aa3b511a9aa9ea851c49ba4d90c7708a)
bassoonian
> Pret Merge (13th of July)

- include/config/overworld.h
> Fix fake RTC being on by default

- src/battle_gimmick.c
- src/data/graphics/gimmicks.h
- test/battle/gimmick/terastal.c
> Fix Tera indicators

- include/test/battle.h
- test/battle/form_change/status.c
- test/battle/hold_effect/cure_status.c
- test/battle/move_effect_secondary/freeze.c
- test/battle/move_effect_secondary/tri_attack.c
- test/battle/move_effects_combined/flinch_status.c
Rebased #4984 to master instead of upcoming
> fix tests when B_USE_FROSTBITE is TRUE

- src/battle_script_commands.c
> Fix Psycho Shift Frostbite interaction

- Makefile
See title
@mrgriffin 
bassoonian
> Fix tests not compiling outside of CI

- test/battle/trainer_control.c
> Add trainer class ball test

- src/data/abilities.h
Really simple, also makes the overall wording in-line with the other weather-summoning abilities.
kittenchilly
> Make Snow Warning description respect config

- src/data/battle_partners.h
- src/data/trainers.h
- test/battle/trainer_control.h
- tools/trainerproc/main.c
Changed reference from `include/config.h` to `include/config/general.h`
hedara
> Updated reference to config location to new location

- src/script_pokemon_util.c
> Fix givemon not giving Cherish Ball

- src/field_player_avatar.c
Fishing minigame is getting skipped currently.
@pkmnsnfrn 
.cawt
> Fix fishing minigame

- include/battle_util.h
- src/battle_ai_util.c
- src/battle_util.c
- test/battle/ability/disguise.c
> Fixes cantBeSurpressed ability check for breakable abilities

- src/field_control_avatar.c
Discussed on Discord https://discord.com/channels/419213663107416084/774393519569502268/1257704663684485261
> Allow flags in trigger scripts

- INSTALL.md
- include/constants/field_weather.h
- src/field_weather_effect.c
THIS IS A PRET MERGE - DO NOT SQUASH!
No merge conflicts
Sha1sum before and after merge: bd5e84fdfee34c60d2c141edab229a655d9efdbb
Includes:
- [pret#2016](https://github.com/pret/pokeemerald/pull/2016) Fix WSL1 install instructions
- [pret#2017)(https://github.com/pret/pokeemerald/pull/2017) Added constant for NUM_SNOWFLAKE_SPRITES
bassoonian
> Pret Merge (27th of July)

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- CHANGELOG.md
- README.md
- docs/SUMMARY.md
- docs/changelogs/1.8.x/1.8.6.md
- include/constants/expansion.h
Do not merge until we're ready to merge 1.9.0 right after (it'll be its own PR)
Changelog in `docs/changelogs/1.8.x/1.8.6.md` or [here](https://github.com/rh-hideout/pokeemerald-expansion/releases/tag/untagged-2bcde9fedfcd54283f1e).
> Version 1.8.6

- src/battle_controllers.c
> IsValidForBattle function formatting

- include/constants/pokemon.h
the u8 should be brought back once we remove agbcc.
> Doesn't compile on some compilers

- include/battle.h
- include/battle_util.h
- src/battle_ai_main.c
- src/battle_ai_util.c
- src/battle_anim.c
- src/battle_main.c
- src/battle_script_commands.c
- src/battle_util.c
- src/battle_z_move.c
The macro was not very intuitive and I think a function just looks nicer.
Feel free to close the PR if this change feels redundant.
> Change GET_MOVE_TYPE to a function

- asm/macros/event.inc
Follow-up to #4841 
bassoonian
> Update event.inc to accomodate new gDecompressionBuffer name

- src/berry_blender.c
As part of the effort to turn single-use strings into COMPOUND_STRINGs, the berry blender strings were converted. Also removed unused berry blender text
Partially fixes #4959 
Frankfurter0
> Changed single-use berry blender strings to be COMPOUND_STRINGs

- src/data/items.h
This was the only item that had an expanded name that we just forgot to add.
kittenchilly
> Add Dowsing Machine expanded name

- include/pokemon.h
- src/battle_ai_switch_items.c
- src/pokemon.c
#5084 Follow up
Minor clean up of the new function DynamicMoveType.
Also fixed a bug with overworld weather out of battle.
> Dynamic move type clean up

- data/battle_scripts_1.s
Fixes Poltergeist missing accuracy check
> Fixes Poltergeist missing accuracy check

- src/battle_main.c
Fixes booster energy not increasing speed
> Fixes booster energy not increasing speed

- src/battle_util.c
#5120 Follow up.  
Consistency change.
> #5120 Follow up

- include/config/item.h
- src/data/party_menu.h
- src/party_menu.c
- Consolidated the values for Rotom's forms' special moves so that they only need to be changed in one area
- Added config for Rotom's base form learning Thunder Shock even if it already knows other moves
Frankfurter
> Consolidated the values of Rotom's moves and added Gen9 base form effect

- src/battle_ai_util.c
Adds missing AI checks for poltergeist
> Adds missing AI checks for poltergeist

- src/battle_script_commands.c
- test/battle/move_effect/guard_split.c
- test/battle/move_effect/power_split.c
Fixes #5000
Fix provided by @mrgriffin
> Fixes UB in Cmd_averagestats

- src/battle_main.c
Another `gBitTable` made its way into `upcoming`, it's been excised.
hedara
> Removed gBitTable usage again

- data/battle_scripts_1.s
Fixes #5236
it softlocked because the move effect is already present in moves info
> Fixes Hyperspace Fury softlock

- src/battle_util.c
should probably have one. doesnt cause any issues rn since last case but would in the future. 
u8-Salem
> add missing break for poison puppeteer

- src/battle_script_commands.c
- test/battle/ability/purifying_salt.c
> Fixes Purifying Salt being poisoned by Toxic Spikes

- docs/how_to_testing_system.md
- include/test/battle.h
It erroneously said that it could be done using single quotes instead of double quotes.
> Fixed test system documentation

- src/battle_ai_main.c
- src/battle_ai_switch_items.c
- src/battle_ai_util.c
- test/battle/ai/ai_flag_sequence_switching.c
Adds AI behavior for chilly reception, acting much like a combination of how the ai uses parting shot and snowscape.
kittenchilly
> Chilly Reception AI

- src/battle_ai_main.c
- src/battle_ai_switch_items.c
- src/battle_ai_util.c
- test/battle/ai/ai_flag_sequence_switching.c
Reverts rh-hideout/pokeemerald-expansion#5265
This should've been merged to upcoming rather than master, fully my fault still learning this properly. SBird said that reverting was the appropriate solution in this case :)
> Revert "Chilly Reception AI"

- src/battle_ai_main.c
- src/battle_ai_switch_items.c
Description
#5268 but targeting upcoming
Added missing ai logic for Population Bomb, Doodle, and Corrosive Gas. Also fixed some things with role play and moves that deal a set amount of hp
Discord contact info
kittenchilly
> More missing AI logic

- include/constants/species.h
Alias for Sirfetch'd is missing
.cawt
> Add Sirfetch'd alias for competitive format

- src/data/abilities.h
> Fixed Tera Shift description

- src/battle_util.c
- test/battle/hold_effect/restore_hp.c
- test/battle/hold_effect/speed_up.c
> Fixes berries missing timing

- src/battle_ai_util.c
Based on the idea of #5218 but for non switching like #5371 does it
> Adds CanEndureHit AI function

- src/battle_script_commands.c
- test/battle/move_effect/destiny_bond.c
- test/battle/move_effect/multi_hit.c
> Fixes Multi Hit moves removing destiny bond flag in the middle of attack

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- CHANGELOG.md
- README.md
- docs/SUMMARY.md
- docs/changelogs/1.9.x/1.9.0.md
- docs/changelogs/1.9.x/1.9.1.md
- docs/changelogs/1.9.x/1.9.2.md
- docs/changelogs/template.md
- include/constants/expansion.h
- Added missing 1.9.1 changelog from docs website.
- Fixed 1.9.0 changelog "full changes" calling 1.8.5 instead of 1.8.6.
- Added missing section for documentation in changelog template.
- Added Hardlocks and Compilation issues to "Softlock/Crash fixes" section.
> Version 1.9.2

- include/config/battle.h
- include/config/overworld.h
- migration_scripts/README.md
- src/data/moves_info.h
- src/party_menu.c
- src/pokemon.c
see title and commit messages.
Growth description change should probably be conditionally based but my lack of C skills prevented me from doing so :smiling_face_with_tear:
nescioquid (was Nescioquid0#3385)
> Typo fixes and Growth move description change

- include/constants/hold_effects.h
- src/battle_debug.c
- src/battle_util.c
- src/data/items.h
- test/battle/hold_effect/ogerpon_mask.c
Ogerpon Masks boost base power of moves by 20%
> Ogerpon masks were missing their hold effects

- src/battle_script_commands.c
- test/battle/move_effect/protect.c
Counter user still got damaged by Spiky Shield
> Fixes Spiky Shield Counter interaction

- src/battle_controllers.c
- src/data/graphics/trainers.h
Merrp's branch had a custom point animation, but the changes for it to actually play weren't merged properly, so this fixes that
kittenchilly
> Play point animation when sending a follower into battle

- src/item_use.c
Fixes some code ported from FRLG not using macros used in pokeemerald
bassoonian
> VS Seeker documentation fix

- asm/macros/event.inc
- data/specials.inc
- src/battle_main.c
> Convert settotemboost command to callnative

- data/battle_scripts_1.s
DO NOT SQUASH!
Merges in the history of the original item description branch, but rejects any changes (as expansion's implementation is accurate). Fixes an indentation issue because the merge commit needed content :)
Fixes #5365 
bassoonian
> Merge item description branch history

- src/evolution_scene.c
- src/pokemon.c
- test/pokemon.c
https://discord.com/channels/419213663107416084/1077168246555430962/1287553497117626380
this was breaking pokemon generation, so we're reverting for now.
> Revert 5422

- test/battle/move_effect/wake_up_slap.c
While going through the big list of fails for gen 1 crit chance I stumbled across this typo'd test name. Going to forget about it if I don't PR it but we can wait for a bigger PR if anyone prefers lol.
@Pawkkie
> Wake-Up Slap test typo

- include/constants/battle_script_commands.h
- src/battle_script_commands.c
- test/battle/hold_effect/restore_hp.c
Title
Also Changed the defines to enums
> Fixes recoil moves not triggering berries if possible

- src/battle_ai_main.c
- src/data/graphics/pokemon.h
- src/data/pokemon/species_info/gen_9_families.h
- test/battle/ai/ai_switching.c
- test/battle/gimmick/dynamax.c
- test/battle/move_effect/pledge.c
Cleans up the trailing whitespace from the repo (master)
kittenchilly
> Remove trailing whitespace pass 10-2-2024 (Master)

- src/battle_ai_switch_items.c
- src/battle_anim_rock.c
- src/battle_script_commands.c
- src/berry.c
- src/bike.c
- src/data/graphics/pokemon.h
- src/data/heal_locations_pkm_center.h
- src/data/pokemon/species_info/gen_9_families.h
- src/event_object_movement.c
- src/field_control_avatar.c
- src/field_player_avatar.c
- src/heal_location.c
- src/metatile_behavior.c
- src/overworld.c
- src/pokemon_sprite_visualizer.c
- test/battle/ai/ai_switching.c
- test/battle/gimmick/dynamax.c
- test/battle/move_effect/pledge.c
Cleans up the trailing whitespace from the repo (upcoming)
kittenchilly
> Remove trailing whitespace pass 10-2-2024 (Upcoming)

- src/battle_main.c
- src/pokemon.c
Fixes #5461 (Is not in master yet)
Also changes the if-else block to a switch
> Fixes Hidden Power dynamic type bug

- include/battle.h
`ejectButtonSwitch` and `ejectPackSwitch` only need one bit each so I added some padding
> Adds padding in AiLogicData

- src/battle_ai_main.c
Fix Mirror Move Ai_CheckViability call
Fix EFFECT_ASBORB in AI_CalcMoveEffectScore
> Various AI fixes

- src/evolution_scene.c
Cleans up stylistically outdated Shedinja code.
Fixes #5478
bassoonian
> Clean up Shedinja code

- data/scripts/field_move_scripts.inc
- include/event_scripts.h
- src/braille_puzzles.c
- src/fldeff_dig.c
This is a merrp merge - DO NOT SQUASH!
Fixes #5482 
- d80190fe105eee12bbf74ae29647ac909084d35c
bassoonian
> Merrp merge (12th of October)

- ld_script_test.ld
Test linker script was broken, apply the same changes as #5512 to that ld scipt.
See title.
We love alignment issues.
`luigi___`
> Update test LD script to respect 4 byte data section alignment

- src/battle_script_commands.c
- src/battle_util.c
- test/battle/move.c
- test/battle/move_effect/acupressure.c
Fixes #4565
Fixes #5154
It is a bit of a scary change but all tests pass and I don't know what else could break
> Fixes Partner targeting and Acupressure/Ally Switch interaction

- data/battle_scripts_1.s
- src/battle_util.c
- test/battle/ability/costar.c
- test/battle/ability/download.c
1. Double Battle Download Test
2. Costar test. I do not plan to retarget this one
> Add Costar Tests, Download Test for Doubles

- data/battle_scripts_1.s
- src/battle_util.c
- test/battle/ability/costar.c
- test/battle/ability/download.c
PR #5526 added tests and a fix for upcoming. This pr just adds those to master as well
> Adds tests and Costar fix from PR #5526

- src/data/moves_info.h
It was missing the thousands separators.
> Fixed 10,000,000 Volt Thunderbolt name

- .gitignore
Removes agbcc screenshots from gitignore
Fixes #5535
bassoonian
> Remove agbcc screenshots from gitignore

- test/battle/ability/curious_medicine.c
Adds a curious medicine test (master)
> Add curious medicine test

- .github/pull_request_template.md
> Add changelog header in PR template to aid automation

- src/battle_message.c
Somehow some line breaks managed to fall between the cracks.
Also fixed Nickname prefixes not properly wrapping.
> Removed remaining line breaks from #3240 + Prefix wrap fix

- test/battle/ability/guard_dog.c
- test/battle/ability/steam_engine.c
Adds a basic steam engine and guard dog test
> Add basic Steam Engine, Guard Dog Tests

- include/config/overworld.h
Closes #5588
Does not change the default config or how the feature works.
> Added compressed OW mon VRAM notice in config file

- src/battle_ai_util.c
`AI_CalcDamage` was very hard to read so I split it up the move effect checks from it by using inlines.
> AI_CalcDamage clean up

- data/battle_scripts_1.s
- include/battle.h
- include/battle_scripts.h
- include/config/general.h
- src/battle_script_commands.c
- test/battle/hold_effect/eject_pack.c
- test/battle/hold_effect/red_card.c
Fixes #5551
Fixes #5550
One test is removed because the interaction was wrong
> Fixes Red Card / Eject Pack interaction with Emergency Exit 

- src/battle_script_commands.c
- test/battle/ability/ice_face.c
Fixes regression caused by #5209
Fixes #5677
> Fixes Ice Face regression

- test/battle/ability/dauntless_shield.c
> Wrong assumtion in dauntless_shield.c

- include/constants/battle_script_commands.h
- test/battle/form_change/primal_reversion.c
- test/battle/hold_effect/red_card.c
> Fixes Red Card / Eject Pack interaction

- src/battle_script_commands.c
- test/battle/status2/confusion.c
> Fixes gems triggering on confusion damage

- src/battle_util.c
> Fixes Misty Terrain displaying wrong message

- data/battle_anim_scripts.s
> Changes Max Phantasm move anim script call

- Makefile
- src/contest.c
- src/mini_printf.c
- src/pokemon.c
I think the pret merge should also be in upcoming, even though we just had a master merge lol
kittenchilly
> Master to upcoming (again, for pret merge), 2024-11-30

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- CHANGELOG.md
- README.md
- docs/SUMMARY.md
- docs/changelogs/1.9.x/1.9.4.md
- include/constants/expansion.h
> Version 1.9.4

- .github/pull_request_template.md
- docs/SUMMARY.md
- docs/scope.md
Based on the conversation held by the expansion Senate, this is the scope document that was agreed upon as deciding "what is in scope". This PR adds that documents and links to it in the PR template.
@Pawkkie and arguably the entire senate
psf
thread: https://discord.com/channels/419213663107416084/1309297830648745996
> Added scope document and made changes to pull request template

- tools/trainerproc/main.c
On any error, for example a missing `-` before a move:
```diff
Geodude
Level: 21
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe
+Rock Throw
```
We currently get the correct line number, but the incorrect content for that line:
```
src/data/trainers.party:96: error: expected empty line
src/data/trainers.party:96: Class: Team Aqua
```
This PR fixes that to give:
```
src/data/trainers.party:96: error: expected empty line
src/data/trainers.party:96: Rock Throw
```
> trainerproc: Fix showing incorrect error context

- include/battle_util.h
- src/battle_ai_main.c
- src/battle_ai_switch_items.c
- src/battle_ai_util.c
- src/battle_dynamax.c
- src/battle_script_commands.c
- src/battle_util.c
Alex had the great suggestion of using an enum instead of the much more opaque looking TRUE and FALSE statements. I agreed with him, hence this PR :)
@AlexOn1ine 
@Pawkkie
> Adds SleepClauseBlock enum to CanBeSlept

- include/config/battle.h
Adds the config that controls the new terrain options introduced in #5162, which was somehow missed.
Fixes #5788 
hedara
> Added the missing config to use new terrains

- src/battle_util.c
- test/battle/ability/flower_gift.c
- test/battle/move_effect/coaching.c
- test/battle/move_effect/cosmic_power.c
- test/test_runner.c
Also fixed KNOWN_FAILING_PASS not showing the correct test's line
Before and after
> Added missing tests + Fix Coaching/Crafty Shield interaction

- INSTALL.md
- docs/install/chromeos/CHROME_OS.md
- docs/install/linux/ARCH_LINUX.md
- docs/install/linux/DEBIAN.md
- docs/install/linux/NIXOS.md
- docs/install/linux/OTHERS.md
- docs/install/linux/UBUNTU.md
- docs/install/mac/MAC_OS.md
- docs/install/windows/CYGWIN.md
- docs/install/windows/MSYS2.md
- docs/install/windows/WSL.md
Updating the install instruction to better reflect the current state of the tooling, cleaning it up and removing outdated parts.
Verification of macOS, NixOS and ChromeOS instructions.
- Install instructions have been moved into individual files under `docs/install/ `
hedara
> Updating install instructions

- src/battle_ai_util.c
> Fix IS_MOVE_STATUS regression

- data/battle_scripts_1.s
- src/battle_script_commands.c
- test/battle/ability/disguise.c
> Fixed Wish triggering Disguise

- src/field_screen_effect.c
> Removed redundant call to FillPalBufferBlack in FRLG whiteout sequence

- src/battle_script_commands.c
- test/battle/move_effect/solar_beam.c
- test/battle/move_effect/two_turns_attack.c
Fixes regression caused by #5853.
> Fixes regression caused by argument refactor

- INSTALL.md
- docs/install/chromeos/CHROME_OS.md
- docs/install/linux/ARCH_LINUX.md
- docs/install/linux/DEBIAN.md
- docs/install/linux/NIXOS.md
- docs/install/linux/OTHERS.md
- docs/install/linux/UBUNTU.md
- docs/install/mac/MAC_OS.md
- docs/install/windows/CYGWIN.md
- docs/install/windows/MSYS2.md
- docs/install/windows/WSL.md
Backported from upcoming
hedara
> Install instructions

- src/field_specials.c
Supersedes #5871 (targeting master)
> Fix Script Scrollable Multichoice Arrow Positions

- test/battle/move_effect/belch.c
> Added missing Belch tests

- src/battle_gfx_sfx_util.c
> Fixes gen3 Style Shadows out of place

- include/test/battle.h
This was my design mistake. Should now appear correctly :)
> Fixed TODO tests not showing up when filtering by name

- test/battle/move_effect/ally_switch.c
> Comment out Ally Switch Illusion test

- test/test_runner.c
> Fixed leaking tasks not showing up in summary

- src/battle_util.c
- test/battle/hold_effect/eject_pack.c
> Fixes Eject Pack / Intimidate issue

- include/constants/battle.h
`NUM_MOVE_EFFECTS` needs to be the last value + 1
Follow-up to #5812
bassoonian
> Fix wrong value for NUM_MOVE_EFFECTS

- data/battle_anim_scripts.s
- src/battle_anim_new.c
Fixes #5521 
Fixes #5469
Fixes above issues together with #5729
Credits: Skeli
> New U-turn animation to fix visibility 

- src/battle_util.c
> Fixes Round doubling it's BP if previous Round failed 

- include/battle_util.h
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/ability/shield_dust.c
- test/battle/hold_effect/covert_cloak.c
Fixes #4636
Possible only on upcoming.
> Fixes Sparkling Aria Shield Dust / Covert Cloak interaction 

- include/battle_util.h
- src/battle_util.c
- src/event_object_movement.c
Came up in discussion regarding type effectiveness functions.
- Renamed `GetTypeEffectiveness` to `GetOverworldTypeEffectiveness`.
> Renamed OW type effectiveness function for clarity

- src/battle_ai_switch_items.c
Addresses https://github.com/rh-hideout/pokeemerald-expansion/pull/5922/files#r1900375847
@Pawkkie
> Cleanup fix from 5922

- data/battle_scripts_1.s
- include/battle_scripts.h
- src/battle_script_commands.c
- test/battle/hold_effect/eject_pack.c
> Reverts wrongly done partial Eject Pack fix

- src/battle_script_commands.c
> Fixes Trainer Slide messages causing corruption for recoil damage

- src/debug.c
> Added "Game Clear" flag toggle to debug menu

- docs/install/windows/WSL.md
Removing the "a" in "3a." fixes formatting.
**Before:** 
**After:**
> Fix formatting in WSL.md

- src/battle_util.c
> Battle Weather Refactor oversight

- docs/scope.md
Got a bit more feedback after #5948 
@kithr1
@Pawkkie
> Update scope.md (again)

- include/config/overworld.h
`OW_AUTO_SIGNPOST` should have been removed when the PR was submitted - the config doesn't actually do anything. Users need to manually assign the metatile behavior.
Fixes #5968
@doejohn126 discovered the issue
pkmnsnfrn
> Removed OW_AUTO_SIGNPOST

- data/maps/Route110/scripts.inc
I'm an idiot :facepalm: 
Fixes #5986
> Fix leftover test change from #5033

- src/battle_util.c
> Dynamic move type was ignored in doubles for spread moves

- include/battle_ai_util.h
- include/battle_util.h
- include/constants/battle.h
- src/battle_ai_main.c
- src/battle_ai_switch_items.c
- src/battle_ai_util.c
- src/battle_controller_player.c
- src/battle_script_commands.c
- src/battle_util.c
Most stuff I found this time around was in mainly in AI functions.
> Multiple removals of hardcoded move IDs

- src/battle_script_commands.c
Just catching 2 missed instances of using the new hazard type enum from #5964 
@Pawkkie
> Missed two uses of new hazard type enum

- Makefile
Adds three lines to the Makefile which allows users to create an elf for a specific test, per the documentation.
Fixes #5992
@mrgriffin 
pkmnsnfrn
> Updated Makefile to allow for the creation of specific tests

- src/battle_anim_dragon.c
- src/digit_obj_util.c
- src/ereader_screen.c
- src/link.c
- src/pokedex_area_screen.c
Before: `IWRAM:       28441 B        32 KB     86.80%`
After:     `IWRAM:       28337 B        32 KB     86.48%`
> Free some IWRAM

- Makefile
> Reorder Makefile rules so that pokeemerald-test.elf builds in build/test

- Makefile
`master` is currently broken, this fixes it
@mrgriffin Wrote the fix on upcoming
hedara
> Ported Makefile fix from upcoming

- test/battle/move_effect/hidden_power.c
Hidden Power's test had no way of checking the actual resulting type, so I changed it to use type resist berries to make sure that it works.
@hedara90, who recommended this implementation.
> Improved Hidden Power test

- docs/team_procedures/scope.md
Adding this workflow as discussed on Discord to the public facing scope document for future reference
@Pawkkie
> Workflow for Scope Discussion

- src/battle_script_commands.c
the defines were not correctly undefined
> Wrong undefs

- src/pokemon.c
Use the macros we have instead of doing it manually.
> Use SET8 and SET32 consistently

- tools/trainerproc/main.c
Makes it harder to submit PRs otherwise
> Fixed whitespace issue with trainerproc

- src/battle_ai_main.c
Don't you just love brackets
(Some compilers love them so much they explode without them)
(Or so I'm told)
@Pawkkie
> Add a uniquely striking pair of brackets

- include/constants/battle_ai.h
A comment was one spacebar too far to the left in an area of the code I look at frequently and it has been driving me nuts since I noticed
Maybe the biggest fix the repo has ever seen you be the judge
@Pawkkie
> Return the universe to a state of balanced quilibrium

- include/constants/map_types.h
- include/overworld.h
- src/dexnav.c
- src/field_screen_effect.c
- src/fldeff_flash.c
- src/item_use.c
- src/overworld.c
Reverts rh-hideout/pokeemerald-expansion#6078
> Revert "Revert map related enum conversion"

- src/data/pokemon/species_info/gen_8_families.h
> Fix Enamorus not changing forms

- asm/macros/event.inc
- src/start_menu.c
adds `forcesave` which shows the save screen and saves the game without a prompt
> Add Script Cmd for Forcing Save Game

- .gitignore
no more identifiers
+ smol for easier switching between branches
> Put Identifier and smol in gitignore

- src/shop.c
This would crash on no cash and MyBoy.
@iriv24
> Fix Crash if something costs 0 in shop

- src/battle_anim_new.c
> Fix MindBlown crash on MyBoy/No Cash

- src/battle_anim_mons.c
> Fix Double Iron Bash move animation crash on MyBoy/No$

- include/contest.h
- migration_scripts/1.11/consolidate_contest_opponent_filters.py
- migration_scripts/README.md
- src/contest.c
- src/data/contest_opponents.h
- src/data/trainers.h
Consolidated contest opponent filters into gContestOpponents to reduce work for adding new contest opponents
Frankfurter0
> Consolidated contest opponent filters into gContestOpponents

- include/gba/defines.h
- src/agb_flash_1m.c
- test/battle/trainer_control.h
Squash this please, I've no idea how this `wut` commit got here lmao
> Fix upcoming not working on no cash

- src/battle_util.c
> Fix safari zone crash on No Cash

- test/battle/ability/aroma_veil.c
- test/battle/ability/chlorophyll.c
- test/battle/ability/electric_surge.c
- test/battle/ability/grassy_surge.c
- test/battle/ability/hydration.c
- test/battle/ability/misty_surge.c
- test/battle/ability/psychic_surge.c
- test/battle/ability/snow_cloak.c
- test/battle/ability/stance_change.c
- test/battle/gimmick/dynamax.c
Wrote a bunch of the `TO_DO_BATTLE_TESTS`.
Removed some `TO_DO_BATTLE_TESTS` that don't make sense.
hedara
> Added some TO_DO tests

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- CHANGELOG.md
- README.md
- docs/SUMMARY.md
- docs/changelogs/1.10.x/1.10.2.md
- include/constants/expansion.h
> Version 1.10.2

- src/battle_main.c
> Fixes Dynamic Moves types in SumScreen while in Battle

- test/battle/ability/big_pecks.c
Wrote tests for Big Pecks, largely copied from the Hyper Cutter tests and modified for Defense instead of Attack.
hedara
> Tests for Big Pecks

- test/battle/ability/water_compaction.c
Added tests for Water Compaction.
hedara
> Water Compaction tests

- src/battle_ai_util.c
Add a comment to describe interaction
#6157 
@Pawkkie
> Clarify MOVE_EFFECT_SLEEP sleep clause handling

- src/data/pokemon/form_species_tables.h
- src/data/pokemon/species_info/gen_9_families.h
Fixes #6095 
- @wiz1989
bassoonian
> Add Poltchageist family form data

- src/data.c
Apparently tags hasn't worked with pools since I put all the pool functionality in it's own files.
This fixes the project not compiling if any tag is assigned to any pokemon for any regular trainer.
hedara
> Add the header required for TPP tags to work

- src/trainer_pools.c
Changed two LocalRandom calls to new LocalRandom32 in `src/trainer_pools.c`.
hedara
> Changed two LocalRandom calls to new LocalRandom32

- src/battle_util.c
Some gbattlerAttacker values are still floating around functions with an explicit battler argument
> Cleanup some global battler ID usage

- test/battle/move_effect/electrify.c
Also discovered that Electrify is broken.
Fixing the bugs with Electrify.
> Wrote tests for Electrify

- src/battle_script_commands.c
Introduces TrySetReflect, TrySetLightScreen for cmd_setreflect/MOVE_EFFECT_REFLECT and cmd_setlightscreen/MOVE_EFFECT_LIGHT_SCREEN
> Unify setreflect/setlightscreen and MOVE_EFFECT_REFLECT/LIGHT_SCREEN

- src/battle_util.c
(Didn't mean to push to this repo, but oh well)
@Bassoonian, for doing the original merge when I couldn't
> Fixed regression from master/upcoming merge

- test/battle/hold_effect/seeds.c
Checks that the seed actually increases the desired stat stage in tests
> Minor Terrain Seed Test Improvement

- src/data/moves_info.h
> Fix typo in Nuzzle's description

- src/event_object_movement.c
> Fixed compilation error when turning P_GENDER_DIFFERENCES off

- src/battle_controllers.c
- src/battle_main.c
Set gBattlerSpriteIds after CreateSprite for gMultiuseSpriteTemplate if gBattleTypeFlag & BATTLE_TYPE_SAFARI
Fixes #6206 
@AsparagusEduardo 
@LonelyRyan 
@hedara90
> Try a new solution to Fix Safari #6206

- src/battle_util2.c
- src/data/easy_chat/easy_chat_group_actions.h
- src/data/easy_chat/easy_chat_group_adjectives.h
- src/data/easy_chat/easy_chat_group_battle.h
- src/data/easy_chat/easy_chat_group_conditions.h
- src/data/easy_chat/easy_chat_group_endings.h
- src/data/easy_chat/easy_chat_group_events.h
- src/data/easy_chat/easy_chat_group_feelings.h
- src/data/easy_chat/easy_chat_group_greetings.h
- src/data/easy_chat/easy_chat_group_hobbies.h
- src/data/easy_chat/easy_chat_group_lifestyle.h
- src/data/easy_chat/easy_chat_group_misc.h
- src/data/easy_chat/easy_chat_group_people.h
- src/data/easy_chat/easy_chat_group_speech.h
- src/data/easy_chat/easy_chat_group_status.h
- src/data/easy_chat/easy_chat_group_time.h
- src/data/easy_chat/easy_chat_group_trainer.h
- src/data/easy_chat/easy_chat_group_trendy_saying.h
- src/data/easy_chat/easy_chat_group_voices.h
This is a pret merge - DO NOT SQUASH!
- pret#2096
- pret#2099
`battle_script_commands.c`
hedara
> Pret merge (11th of February)

- src/battle_script_commands.c
> Revert unintentional change

- src/data/trainers.h
Follow up to #6042. Sorry I forgot to do this as part of it.
> Remove whitespace from trainers data file

- src/dexnav.c
- src/start_menu.c
Replaced some hardcoded values in dexnav.c with pre-existing variables of the same value in order to make editing the sprite locations easier
Frankfurter0
> Replaced hardcoded numbers in DexNav with variables

- include/battle.h
- src/battle_anim.c
- src/battle_anim_bug.c
- src/battle_anim_effects_1.c
- src/battle_anim_fire.c
- src/battle_anim_new.c
- src/battle_anim_psychic.c
- src/battle_anim_status_effects.c
- src/battle_anim_utility_funcs.c
- src/battle_anim_water.c
- src/battle_script_commands.c
- src/battle_util.c
- src/pokemon.c
Renamed and moved to `include/battle.h` to make it an inline
> Expand usage of IsBattlerAlly (rename from IsAlly)

- src/battle_ai_util.c
Please test in-game
Fixes #6279
> Fixes Protean not restoring types after ai damage calcs

- data/battle_scripts_1.s
- test/battle/move_effect/brick_break.c
- test/battle/move_effect/raging_bull.c
Fixes 2 Known Failing tests.
Added Psychic Fangs to the existing Brick Break tests.
PhallenTree
> Fixes Brick Break/Psychic Fangs/Raging Bull breaking screens if target is immune

- include/move.h
This is an upcoming only issue for some reason.
> Fix padding amount in MoveInfo

- include/battle_script_commands.h
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/ability/tera_shell.c
- test/battle/trainer_control.h
Fixes #6270
Additional removed some duplicate code and some minor calc optimization by passing an ability argument instead of calcing. Technically same should be made for attacker ability but that is for an other day.
> Fixes Tera Shell activating on moves that have no effect on target

- include/battle.h
> Clean up leftover from simu hp reduction development

- src/data/trainers.party
_Little drops of water,
Little grains of sand,
Make the mighty ocean
And the pleasant land._
— Julia Abigail F. Carney, Poet.
As individuals, we often come to wonder about our significance in the greater world around us. Because we are individually small, we come to be intimidated by the vast everythingness that we experience in our day to day lives. For some this comes as a crushing weight of existence that results in nihilism and apathy. However, true enlightenment comes when we realize the true value of our individual contributions: that is, the power collective action that we as an intelligent species can achieve when we concretely focus our efforts on what we deem the most important.
We often forget such examples in our own history as humans: the various revolutions that have come …
> Fixed a missing ) in trainers.party comment block.

- README.md
The current link is broken, changed to an appropriate archive.org link.
Readme link is broken.
lwelyk
> Update README.md for contest src link

- src/data/object_events/object_event_pic_tables_followers.h
The wrong conditional was being checked for the OW battle forms.
Fixes #6398 
hedara
> Fix compile errors with OW_BATTLE_ONLY_FORMS set to FALSE

- include/battle_util.h
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/move_effect/speed_down.c
> Fixes Cotton Spore failing if one of the targets blocks it

- src/battle_debug.c
Tons of new ai flags were added recently that the battle debug menu wasn't updated to add, so I added them.
Converting all the strings to COMPOUND_STRING, I will do that in a separate PR targeting upcoming.
kittenchilly
> Update Battle Debug menu with new AI flags

- include/dexnav.h
- src/battle_main.c
- src/dexnav.c
- src/pokemon.c
Fixes dexnav search levels.
.cawt
> Fix DexNav search level

- include/battle.h
- src/battle_script_commands.c
- test/battle/ability/cheeck_pouch.c
Fixes #6463
There might be a smarter way to solve this but I couldn't get it to work
> Fixes Cheek Pouch mutating damage

- src/battle_script_commands.c
- test/battle/hold_effect/protective_pads.c
Fixes #6471
I don't know if protective pads protect against all protect effects but I included them all for now. Probably needs testing.
> Fixes protective pads against Protects secondary effects

- Makefile
- include/battle.h
- src/battle_script_commands.c
Maybe this was deprecated at some point, maybe never used in the first place, who knows.
> Removes unused Special Status members

- data/battle_anim_scripts.s
- include/battle.h
- include/config/battle.h
- include/dexnav.h
- src/battle_controller_player.c
- src/battle_debug.c
- src/battle_gimmick.c
- src/battle_interface.c
- src/battle_main.c
- src/battle_script_commands.c
- src/dexnav.c
- src/pokemon.c
- test/battle/ability/cheeck_pouch.c
- test/battle/hold_effect/protective_pads.c
- test/battle/move_effect/sucker_punch.c
25-03-25 master to upcoming merge
Don't squash!
> 25-03-25 master to upcoming merge

- src/pokedex_plus_hgss.c
Increases number of digits from 3 to 4 in the HGSS dex's stat screen for the Pokémon NatDex number.
Before
After
Increased Dex No digit count in the HGSS dex.
pcg06
> Increase dex no digits from 3 to 4

- include/battle_util.h
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/ability/clear_body.c
- test/battle/hold_effect/clear_amulet.c
- test/battle/hold_effect/protective_pads.c
- test/battle/move_effect/counter.c
- test/battle/move_effect/protect.c
Same as #6474 but for Clear Body type abilities and Clear Amulet
> Fixes clear body type effect and clear amulet against protect effects

- .github/workflows/labels.yml
Adds a workflow to check that at least one of the labels required by the automated changelog generator exists.
hedara
> Added workflow for labels check

- src/battle_util.c
- test/battle/ability/hospitality.c
> Fixes Hospitality not being blocked by Heal Block

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- README.md
- docs/SUMMARY.md
- docs/changelogs/1.11.x/1.11.1.md
- include/constants/expansion.h
THIS IS A RELEASE, DO NOT SQUASH
Expansion 1.11.1 release.
hedara
> 1.11.1 Release

- tools/learnset_helpers/porymoves_files/b2w2.json
- tools/learnset_helpers/porymoves_files/bw.json
- tools/learnset_helpers/porymoves_files/dp.json
- tools/learnset_helpers/porymoves_files/frlg.json
- tools/learnset_helpers/porymoves_files/hgss.json
- tools/learnset_helpers/porymoves_files/oras.json
- tools/learnset_helpers/porymoves_files/pt.json
- tools/learnset_helpers/porymoves_files/rse.json
- tools/learnset_helpers/porymoves_files/sm.json
- tools/learnset_helpers/porymoves_files/sv.json
- tools/learnset_helpers/porymoves_files/usum.json
- tools/learnset_helpers/porymoves_files/xy.json
Fix move names in learnset helper
Rename:
- `MOVE_SMELLING_SALT` -> `MOVE_SMELLING_SALTS`
- `MOVE_FOREST'S_CURSE` -> `MOVE_FORESTS_CURSE`
malad1211
> Fix move names in learnset helper

- .github/workflows/labels.yml
> Add General Merge to label check

- src/battle_script_commands.c
- test/battle/item_effect/restore_hp.c
Also adds tests for this behaviour.
Fixes #6514 
hedara
> Fix using items to heal partner in battle

- CONTRIBUTING.md
> Update maintainer list

- src/battle_debug.c
What it says on the tin
hedara
> Added AI switch display to the battle debug

- src/battle_terastal.c
> Fixes transformed mon being able to use tera on Terapagos

- src/pokemon.c
Follow up to #6365.
Aimed at master because without it, custom species that use the same form change method as Zacian/Zamazenta would get the same issue that PR aimed to solve.
> Fixed Behemoth Blade/Bash handler not using form change tables

- src/battle_ai_util.c
Swapping some `GetBattlerAbility` to `AI_DATA->abilities[battler]`
@Pawkkie
> Ability access cleanup for #6550

- docs/team_procedures/merge_checklist.md
Fix four broken links in the merge checklist per [as found on Discord](https://discord.com/channels/419213663107416084/774393519569502268/1359643245818417346).
@grintoul1
pkmnsnfrn
> Fix broken links in merge_checklist.md

- include/battle_gimmick.h
- src/battle_gimmick.c
- src/battle_interface.c
- src/data/gimmicks.h
- src/data/graphics/gimmicks.h
Instead of loading all the indicator sprites into VRAM at the start of a battle, now 1 sprite is reserved per battler, and the VRAM for that sprite is overwritten with the relevant sprite when a gimmick is activated.
Before
After
Fixes #6360 
- This frees up a lot of VRAM in battles.
hedara
> Gimmick Indicator refactor

- include/global.fieldmap.h
- sound/music_player_table.inc
- src/event_object_movement.c
- src/field_player_avatar.c
- src/main.c
- src/overworld.c
- src/trainer_see.c
This is a pret merge - DO NOT SQUASH!
- pret#2115
- pret#2117
- pret#2119
- pret#2118
None
bassoonian
> Pret merge (11 of April)

- docs/tutorials/how_to_new_pokemon.md
Documentation from DNS that should be in `master`.
hedara
> Documentation

- data/battle_anim_scripts.s
- src/battle_anim_dragon.c
- src/battle_anim_effects_1.c
- src/battle_anim_effects_2.c
- src/battle_anim_electric.c
- src/battle_anim_fire.c
- src/battle_anim_flying.c
- src/battle_anim_mon_movement.c
- src/battle_anim_mons.c
- src/battle_anim_normal.c
- src/battle_anim_poison.c
- src/battle_anim_rock.c
- src/battle_anim_utility_funcs.c
- src/battle_anim_water.c
Adapted luckytyphlosions animation fixes to expansion where relevant.
Inferno and Head Smash have been changed from the base used by lucky, so couldn't see the textbox corruptions.
Phantom Force has been changed from the base used by lucky, fixes weren't relevant.
@/luckytyphlosion
hedara
> Animation fixes from lucky adapted to expansion

- data/battle_anim_scripts.s
- docs/tutorials/how_to_new_pokemon.md
- include/battle_gimmick.h
- include/global.fieldmap.h
- sound/music_player_table.inc
- src/battle_anim_dragon.c
- src/battle_anim_effects_1.c
- src/battle_anim_effects_2.c
- src/battle_anim_electric.c
- src/battle_anim_fire.c
- src/battle_anim_flying.c
- src/battle_anim_mon_movement.c
- src/battle_anim_mons.c
- src/battle_anim_normal.c
- src/battle_anim_poison.c
- src/battle_anim_rock.c
- src/battle_anim_utility_funcs.c
- src/battle_anim_water.c
- src/battle_gimmick.c
- src/battle_interface.c
- src/battle_util.c
- src/data/gimmicks.h
- src/data/graphics/gimmicks.h
- src/data/items.h
- src/event_object_movement.c
- src/field_player_avatar.c
- src/main.c
- src/overworld.c
- src/trainer_see.c
- test/battle/ability/commander.c
> master to upcoming, 2025-04-12

- src/caps.c
Fixes #5965 
@i0brendan0
bassoonian
> Add clarification for underlying math in EV caps

- include/constants/pokemon.h
> Add clarification for EVO_SCRIPT_TRIGGER_DMG

- include/constants/battle_ai.h
> Remove redundant AI defines

- include/battle_ai_main.h
- include/battle_ai_util.h
- include/dexnav.h
- include/follower_helper.h
- src/battle_ai_main.c
- src/battle_ai_util.c
- src/dexnav.c
Also cleans up some style issues in `dexnav.c`
bassoonian
> Converts some defines to enums

- src/battle_util.c
Old compilers don't like this.
hedara
> Fix declaration after label for Psywave switch

- src/data/graphics/gimmicks.h
The rom didn't compile for me and this was suggested as a fix
> Fix potential compile error caused by sTeraIndicatorDataPtrs

- test/battle/hold_effect/big_root.c
Adds Big Root tests. The Leech Seed/Ingrain/Aqua Ring tests is marked as known failing as it heals 61 from Leech Seed in both recordings.
bassoonian
> Big Root tests

- data/battle_anim_scripts.s
Magma Storm was broken.
Test with
```C
SINGLE_BATTLE_TEST("blergh")
{
FORCE_MOVE_ANIM(TRUE);
GIVEN {
PLAYER(SPECIES_WOBBUFFET);
OPPONENT(SPECIES_WOBBUFFET);
} WHEN {
TURN { MOVE(player, MOVE_MAGMA_STORM); }
} THEN {
FORCE_MOVE_ANIM(FALSE);
}
}
```
hedara
> Fix Magma Storm getting stuck

- data/battle_scripts_1.s
> Fix regression from EndTurnRefactor

- src/data/battle_partners.h
- test/battle/trainer_control.h
Removes spaces from generated files
hedara
> Make generated files match the current formatting

- test/battle/ability/color_change.c
Found by Bassforte on Discord
hedara
> Fixed Color Change test referring to the wrong mon

- src/battle_util.c
- test/battle/hold_effect/big_root.c
> Fixes Big Root Leech Seed heal amount

- test/battle/status1/freeze.c
> Test for Freeze vs Scald thaw

- src/battle_script_commands.c
- src/battle_util.c
- test/battle/ability/commander.c
> Fixes commander activation on a fainted mon

- asm/macros/battle_script.inc
- data/battle_scripts_1.s
- src/battle_script_commands.c
- test/battle/ability/oblivious.c
Fixes Test using incorrect move and Oblivious not preventing Captivate.
.cawt
> Fix captivate-oblivious interaction and related test

- asm/macros/battle_script.inc
- data/battle_scripts_1.s
- include/battle.h
- include/battle_scripts.h
- src/battle_main.c
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/ability/intimidate.c
- test/battle/hold_effect/eject_pack.c
Fixes #6641
Only the fastest Eject Pack should activate. Most code was adopted from luckytyphlosion
> Fixes Intimidate / Eject Pack interaction

- src/battle_main.c
- src/battle_util.c
- test/battle/move_effect_secondary/bug_bite.c
> Fixes Bug Bite eaten berry not ignoring Unnerve

- src/battle_script_commands.c
> Fix party access in NoAliveMonsForBattlerSide

- src/battle_script_commands.c
> Remove misleading comment

- src/battle_script_commands.c
- test/battle/ability/comatose.c
- test/battle/ability/immunity.c
- test/battle/ability/purifying_salt.c
Toxic Spikes handling wasn't taking into account Comatose.
Added tests for Mold Breaker + Phazing interactions with Toxic Spikes and immunity Abilities.
Fixes #6682 
Pastel Veil interactions not handled, needs investigation.
hedara
> Fix various Toxic Spikes interactions

- test/battle/ability/analytic.c
- test/battle/move_effect/aqua_ring.c
- test/battle/move_effect/attract.c
- test/battle/move_effect/bestow.c
- test/battle/move_effect/captivate.c
- test/battle/move_effect/entrainment.c
Title. Bestow has a few `KNOWN_FAILING` tests that will require a bugfix down the road
bassoonian
> Adds a whole bunch of new tests

- src/battle_ai_main.c
My bad, @iriv24 and @hedara90 have better eyesight than I do
@Pawkkie
> Fix bracket typo in AI_CheckBadMove conditional

- src/battle_util.c
- test/battle/move_effect/protect.c
Same as  #6697 but to upcoming
> Fixes Z and Max moves dmg reduction against side protection - upcoming

- asm/macros/battle_script.inc
- data/battle_scripts_1.s
- include/battle.h
- include/battle_scripts.h
- include/battle_util.h
- src/battle_end_turn.c
- src/battle_main.c
- src/battle_script_commands.c
- src/battle_util.c
- src/event_object_movement.c
- test/battle/ability/analytic.c
- test/battle/ability/comatose.c
- test/battle/ability/immunity.c
- test/battle/ability/intimidate.c
- test/battle/ability/magician.c
- test/battle/ability/mirror_armor.c
- test/battle/ability/purifying_salt.c
- test/battle/ability/teraform_zero.c
- test/battle/ability/unburden.c
- test/battle/hold_effect/eject_pack.c
- test/battle/move_effect/aqua_ring.c
- test/battle/move_effect/attract.c
- test/battle/move_effect/bestow.c
- test/battle/move_effect/captivate.c
- test/battle/move_effect/entrainment.c
- test/battle/move_effect_secondary/bug_bite.c
> 27/04/25 Master to upcoming merge

- src/pokemon_storage_system.c
A line was accidentally deleted, which made mon sprites not display in the PC.
hedara
> Fix pc mon pic

- test/test_runner_battle.c
Causes compile issues when trying to increase `MAX_BATTLERS_COUNT`
> Use correct define for moves in test runner

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- README.md
- docs/SUMMARY.md
- docs/changelogs/1.11.x/1.11.2.md
- include/constants/expansion.h
This is a release - **DO NOT SQUASH**
Expansion release 1.11.2
hedara
> Release 1.11.2

- .github/workflows/labels.yml
The label check workflow is not not skipped if new commits are pushed to PRs
hedara
> Updated label workflow

- tools/mapjson/json11.cpp
- pret#2131
No conflicts
hedara
> Pret merge (2nd of May 2025)

- docs/tutorials/ai_flags.md
Title, short description from hedara's new flag.
@Pawkkie
> Add AI_FLAG_PP_STALL_PREVENTION to `ai_flags.md`

- src/data/pokemon/egg_moves.h
- src/data/pokemon/species_info/gen_5_families.h
Basculin White Striped was missing its egg moves.
Added Egg Moves for Basculin White Striped.
pcg06
> Added Egg Moves for Basculin White Striped

- src/battle_ai_switch_items.c
- src/battle_anim.c
- src/battle_anim_new.c
- src/battle_controller_link_opponent.c
- src/battle_controller_link_partner.c
- src/battle_controller_opponent.c
- src/battle_controller_player.c
- src/battle_controller_player_partner.c
- src/battle_controller_recorded_opponent.c
- src/battle_controller_recorded_player.c
- src/battle_controller_safari.c
- src/battle_controller_wally.c
- src/battle_controllers.c
- src/battle_debug.c
- src/battle_gfx_sfx_util.c
- src/battle_interface.c
- src/battle_main.c
- src/battle_message.c
- src/battle_script_commands.c
- src/battle_terastal.c
- src/battle_tower.c
- src/battle_tv.c
- src/battle_util.c
- src/battle_util2.c
- src/pokemon_animation.c
- src/recorded_battle.c
- src/reshow_battle_screen.c
Despite being introduced a long while ago, `GetPartyBattlerData` wasn't being used much when it would've made things more readable. This PR fixes that.
> Use `GetPartyBattlerData` where appropiate

- src/battle_anim_electric.c
- src/battle_anim_mons.c
- src/battle_anim_new.c
- src/battle_anim_psychic.c
- src/battle_anim_water.c
While there were some cases found in pret, most of these are expansion-exclusive.
Pret PR: https://github.com/pret/pokeemerald/pull/2132
> `InitSpritePosToAnimAttacker` documentation

- include/battle_interface.h
- src/battle_anim_mons.c
- src/battle_controller_player.c
- src/battle_gfx_sfx_util.c
- src/battle_interface.c
Added enum to identify different battle coordinates.
@ghoulslash, @klemniops for the original code.
> Better handling of battle coords

- src/battle_ai_switch_items.c
- src/battle_anim.c
- src/battle_main.c
- src/battle_script_commands.c
- src/battle_util.c
> Add missing uses of  `IsBattlerAlly`

- docs/STYLEGUIDE.md
Added JSON as the preferred data format to `STYLEGUIDE.md`.
hedara
> Added JSON as the preferred data format

- Makefile
- map_data_rules.mk
Supersedes #6823 
@mrgriffin 
hedara
> Add AUTO_GEN_TARGETS for .party files and map_groups_count, but on master

- .github/workflows/build.yml
> Changed github CI to use arm-none-eabi-gcc

- src/battle_ai_switch_items.c
- src/battle_anim_effects_1.c
- src/battle_anim_rock.c
- src/battle_script_commands.c
- src/battle_util.c
- src/battle_z_move.c
> Removed multiple instances of hardcoded move IDs

- src/event_object_movement.c
Added npc followers to the existing elevation handling for mon followers.
bivurnum
> Bug fix: add proper elevation handling for npc followers

- test/battle/ability/beast_boost.c
- test/battle/ability/protosynthesis.c
- test/battle/ability/quark_drive.c
Combined Protosynthesis/Quark Drive stat priority tests into a single parametrized test each.
Also added Beast Boost since they use the same priority system.
> Consolidated stat-priority ability tests

- src/data/abilities.h
- src/data/moves_info.h
Updates move descriptions to increase clarity (and a couple abilities)
Moves with secondary effects should now always be mentioned.
Moves with a duration are mentioned when possible.
Some spread moves (MOVE_TARGET_BOTH) update foe -> foes where gramatically convenient. (Not updated: foe's -> foes', or when 'its' is also used in the singular)
Night Slash is still potentially unclear - the wording "Hits as soon as possible" may imply that it's a priority move. But i'm not sure how to better incorporate that flavour text that all official descriptions of the move do.
Wanted to include the gen8+ behaviour that inner focus, own tempo, and scrappy prevent intimidate, but not enough room. "Prevents flinch/Intimidate" just about works for inner focus but not really for the others.
Updated move …
> Reword move and ability descriptions to improve clarity

- .all-contributorsrc
- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/03_feature_requests.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- .github/pull_request_template.md
- CREDITS.md
- FEATURES.md
- INSTALL.md
- README.md
* Added `CREDITS.md` using @all-contributors bot and spec
* Updated PR and Issue templates to match usage of all-contributors spec
* Cleaned up `README.md`
* Added `FEATUES.md` as part of the `README` cleanup
* Updated `INSTALL.md` as part of the `README` cleanup
**NOTE**: I am aware the all-contributors badge doesn't work right now. It won't work until the PR is merged, because it is looking for a file in the default branch.
Fixes #2403 
* In the future, I would like to make `FEATURES.md` more image based and better organize the information presented there. I do not think a giant list of features is useful right now.
pkmnsnfrn
There is a Discord thread: https://discord.com/channels/419213663107416084/1356629819978416302
> Add CREDITS.md & FEATURES.md, rewrite README.md & INSTALL.md

- src/battle_script_commands.c
Fixes an implicit `T1_READ_PTR` in JumpIfMoveFailed by adding a failInstr argument
Also fixes minor tryworryseed duplicate `gBattlescriptCurrInstr` setting
> add fail ptr arg to JumpIfMoveFailed, fix tryworryseed

- src/pokemon.c
Fallthrough issue.
Fixes #6935.
> Fix Rage Fist evolution method

- data/battle_anim_scripts.s
Checksum matches current upcoming.
> Documented usage of `createsprite gSimplePaletteBlendSpriteTemplate`

- data/battle_anim_scripts.s
- src/battle_anim_ground.c
Checksum matches current upcoming.
> Documented usage of `createsprite gDirtPlumeSpriteTemplate`

- CONTRIBUTING.md
- docs/team_procedures/schedule.md
- Reworded a step in bug report process to be clearer
- Codified allowing documentation and credits PRs during Merge Freezes
- Removed incorrect step in PR tutorial
pkmnsnfrn
> Updated CONTRIBUTING.md and Merge Freeze definition

- data/battle_anim_scripts.s
Tried doing a single big PR that handled multiple of these, but got burned out, so I'm doing smaller PRs instead.
Checksum matches current upcoming.
> Documented usage of `createsprite gBasicHitSplatSpriteTemplate`

- .github/workflows/labels.yml
What it says on the tin.
hedara
> Added type: documentation to required labels for the label check

- src/battle_util.c
- src/data/moves_info.h
- test/battle/move_effect/bestow.c
> Fix `KNOWN_FAILING` Bestow tests

- migration_scripts/1.12/convert_trainer_battle_types.py
> Added missing root folder check in trainer battle type migration script

- src/battle_util.c
- test/battle/ability/dazzling.c
> Fixes Dazzling abilities activating on all multi hit move hits

- include/battle.h
- src/battle_util.c
- test/battle/ability/unnerve.c
> Fixes Unnerve activation not limited to 1 per switch-in

- src/battle_ai_util.c
Currently watching this be abused to beat a mon in EI's E4. Straightforward fix.
@Pawkkie
> Fix AI boosting stats into mon with Haze

- include/battle_ai_util.h
- src/battle_ai_main.c
- src/battle_ai_util.c
- test/battle/ai/ai.c
> Fixes AI repeated use of weather set up moves

- src/battle_ai_util.c
Referenced an older version of the function name.
@Pawkkie
> Fix HasBattlerSideMoveWithEffect comment

- data/battle_anim_scripts.s
Checksum matches current upcoming.
> Documented usage of `createsprite gSlideMonToOffsetSpriteTemplate`

- data/field_effect_scripts.s
- docs/STYLEGUIDE.md
- docs/team_procedures/expansion_versions.md
- docs/team_procedures/scope.md
- docs/tutorials/how_to_code_entry.md
- src/battle_controllers.c
- src/battle_message.c
- src/battle_setup.c
- src/battle_terastal.c
- src/battle_transition.c
- src/datetime.c
- src/dexnav.c
- src/evolution_scene.c
- src/field_control_avatar.c
- src/field_effect_helpers.c
- src/follower_npc.c
- src/item_use.c
- src/pokedex_area_screen.c
- src/pokedex_plus_hgss.c
- src/rtc.c
- src/scrcmd.c
- src/wild_encounter.c
- test/battle/ability/moody.c
- test/battle/ability/steam_engine.c
- test/battle/ai/ai_doubles.c
- test/battle/hold_effect/seeds.c
- test/battle/move_effect/pursuit.c
- test/battle/move_effect/roar.c
> Remove trailing whitespace

- test/battle/ai/ai_calc_best_move_score.c
The move description was vague so hopefully this one is a bit better
> Rename AI test

- src/battle_util.c
Manifested itself on the master to upcoming merge
> Prankster block check was missng the IsStatusMove check

- data/battle_scripts_1.s
Fixes #6972
Only an upcoming issue since I rewrote the script there
> Fixes weather anim damage being applied to the wrong mon

- src/overworld.c
compiled because of the preproc
> Missed ItemId_GetDescription change

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
- .github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
- .github/ISSUE_TEMPLATE/04_other_errors.yaml
- README.md
- docs/SUMMARY.md
- docs/changelogs/1.11.x/1.11.3.md
- include/constants/expansion.h
This is a release, **DO NOT SQUASH**
This is the last release before Porymap 6 support
hedara
> Expansion 1.11.3

- data/battle_scripts_1.s
- test/battle/hold_effect/eject_pack.c
> Added test coverage for regression

- data/battle_scripts_1.s
- test/battle/hold_effect/eject_pack.c
Since I closed #7002 for now (there was some stuff missing I need from upcoming) this is a temporarily fix.
Should still make it into 1.11.4 since it would be a regression otherwise.
> Update Supersweet Syrup with eject pack fix

- test/compression/smol.c
Put the majority of the compression tests behind an "off by default" config.
hedara
> Put the gen 1 compression tests behind a config

- data/battle_anim_scripts.s
- src/battle_anim_fight.c
- src/battle_anim_new.c
> Animation documentation

- include/line_break.h
- src/line_break.c
Add s naive line breaking function that just breaks when the line would be too long.
hedara
> Added naive line break

- CREDITS.md
Cleaned up table from merge
pkmnsnfrn
> Update CREDITS.md with correct line placement

- test/battle/move_effect/acupressure.c
- test/battle/move_effect/blizzard.c
- test/battle/move_effect/bulk_up.c
- test/battle/move_effect/calm_mind.c
- test/battle/move_effect/expanding_force.c
- test/battle/move_flags/always_hits_in_hail_snow.c
- Wrote missing tests for Bulk Up, Calm Mind, Expanding Force.
- Removed a duplicate blizzard test.
- Added passed randomly to the other blizzard test
> Wrote some missing tests

- include/battle_util.h
- src/battle_ai_util.c
- src/battle_controller_player.c
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/ability/anticipation.c
#7108 follow up
It didn't turn out as clean as in  #7108 but I still think it is worth it to make sure we don't fetch abilities/hold effects on the fly
> Add damage context to effectiveness multiplier

- src/palette.c
Change the definition of `DEFAULT_LIGHT_COLOR` to use the `RGB2GBA` macro for readability.
`sha1sum` of compiled ROM doesn't change.
hedara
> Use RGB values for DEFAULT_LIGHT_COLOR

- docs/tutorials/dns.md
> Applied Kasen's documentation improvements

- src/battle_script_commands.c
The condition is always true due to the move canceller catching the condition earlier.
> Removed redundant Damp check

- test/battle/gimmick/terastal.c
- test/battle/move_effect/transform.c
Rewrote the test, as it was working mechanically.
> Fixed KNOWN_FAILING Tera test

- data/battle_scripts_1.s
`MOVE_EFFECT_AFFECTS_USER` was missing
> Add missing flag for Berserk Gene

- src/item.c
- test/bag.c
Also added tests by @AlexOn1ine + 1 for berries
> Fixed TM and Berries disappearing when sorting

- include/config/overworld.h
I updated the description of `OW_OBJECT_VANILLA_SHADOWS` in response to https://github.com/rh-hideout/pokeemerald-expansion/issues/7179.
pkmnsfnfrn
> Update the description of OW_OBJECT_VANILLA_SHADOWS

- src/debug.c
> Fixed debug flag menu sound

- src/battle_controller_player.c
Calculate palette based on back sprite used by player. This prevents visual glitches if using a player sprite other than Brendan or May.
More details on issue in https://github.com/rh-hideout/pokeemerald-expansion/issues/7191
||before|after|
|-|-|-|
|still sprite|![Image](https://github.com/user-attachments/assets/06c874c1-936b-4294-a651-ec547ee481ad)|![Image](https://github.com/user-attachments/assets/e7e2fb7f-7cd3-4353-a23f-733168fed3da)|
|animation|![Image](https://github.com/user-attachments/assets/9c72292d-752d-4732-a520-06189b5710fa)|![Image](https://github.com/user-attachments/assets/52935093-d955-4492-b38e-326a994b441e)|
Fixes: #7191
> fix: use BackPickId to calculate player intro ball throw animation palette

- include/battle_controllers.h
- src/battle_controller_opponent.c
- src/battle_controller_player.c
- src/battle_controller_player_partner.c
- src/battle_controllers.c
- src/battle_main.c
- src/battle_script_commands.c
Party actions are limited to 16 actions atm. (currently at the limit)
This PR increases the limit to 256.
.cawt
> Increase party action limit

- include/battle_util.h
- src/battle_script_commands.c
- src/battle_util.c
Small clean up that should have been done when the function table was made.
Combined the Sleep/Freeze and Heal Block, Gravity, Throat Chop cancellers. Also made an enum for the return value.
> Attackcanceller clean up

- .github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
The 01 template wasn't showing up, I think this should fix that.
hedara
> Fix 01_battle_engine_bugs.yaml

- data/battle_anim_scripts.s
- include/constants/sound.h
- src/battle_anim_sound_tasks.c
- src/pokemon_sprite_visualizer.c
- src/sound.c
Added in favor of using the echo version of the cry.
https://github.com/user-attachments/assets/95b994f2-c2b6-4bed-84c2-e753b433965d
https://github.com/user-attachments/assets/cc70a5f2-3c41-4116-989b-6509312b8fa8
https://github.com/user-attachments/assets/fc201713-6708-4112-935a-d6d02b40c39c
https://github.com/user-attachments/assets/556eb25e-86a1-4c4f-9142-01c2ac69fc5d
https://github.com/user-attachments/assets/030e73f8-b380-44d2-8315-c8e276215561
https://github.com/user-attachments/assets/dcb4f2ea-ecff-4d21-a99a-4ee7e3e05a8d
https://github.com/user-attachments/assets/49143a26-2866-465c-91ff-10ec7e3bc656
It's not 100% accurate, but it gets the idea across. Further tweaks to the parameters can be done by other people.
> Added `CRY_MODE_DYNAMAX`

- include/battle_util.h
- include/constants/battle.h
- src/battle_ai_main.c
- src/battle_debug.c
- src/battle_main.c
- src/battle_script_commands.c
- src/battle_util.c
- test/battle/move_effect/mud_sport.c
- test/battle/move_effect/water_sport.c
Since those aren't abilities it's better to keep them separate.
> Use dedicated functions for Mud/Water Sport

- src/battle_script_commands.c
Fix OOB in Cmd_selectfirstvalidtarget
> Fix OOB in Cmd_selectfirstvalidtarget

- src/battle_debug.c
> Use compound strings in battle debug menu

- src/battle_ai_util.c
Fix incorrect status in beneficial ability Guts check which is preventing Upcoming from building
grintoul
> Fix incorrect status in beneficial ability Guts check

- src/battle_ai_util.c
> Added missing braces

- test/battle/ability/overcoat.c
> Add Overcoat Tests

- src/battle_ai_main.c
- test/battle/ai/ai_doubles.c
After You previously simply was mildly incentivized if the ally was slower than one opponent.
It now will try to After You a Trick Room setter.
> AI uses After You to help set up Trick Room.

- src/battle_ai_switch_items.c
Oversight on my part, forgot this ability existed.
@Pawkkie
> Fix choice AI not seeing Gorilla Tactics

- src/battle_script_commands.c
- src/pokedex_plus_hgss.c
Frees some battle data before going into the pokedex after catching a mon, going to the "Do you want to nickname mon" after showing the HGSS pokedex runs out of heap otherwise.
hedara
> Fix HGSS dex running out of heap

- src/battle_controllers.c
- src/battle_main.c
No conflicts.
Pawkkie wanted this.
hedara
> master to upcoming 2, 2025-07-12

- include/battle_main.h
- src/battle_debug.c
- src/battle_main.c
Adds instant win option in the battle debug menu
I'm not sure if there is a better way but this one seems straightforward at least.
> Instant Win option in Battle Debug

- src/battle_ai_switch_items.c
> Fix AI_DoesChoiceEffectBlockMove typo

- src/battle_controllers.c
- src/pokeball.c
aka #6821 aftermath
https://github.com/user-attachments/assets/09964e3e-7f2c-46d1-8251-120543b711f6
fixes #7315, #7311
mudskipper13
> battle intro: fix issues with follower slide-in and wild shiny mon

- src/battle_end_turn.c
- src/battle_message.c
Also backports a change from #7277 to master that fixes Frostbite inflicted by an ability displaying a random message.
PhallenTree
> Fixes Grassy Terrain healing when Heal Blocked/Semi-Invulnerable

- tools/trainerproc/main.c
Adds the key `Macro` to `trainerproc`, which will add the value entered exactly as it's written to the `.h` file.
This bypasses the checks for required field on the trainer, so the user has to make sure the required fields are covered either in the trainer or the entered macro.
Feature use-case being brought up here
https://discord.com/channels/419213663107416084/1077168246555430962/1384954677434519582
hedara
> Add `Macro` key to trainerproc

- tools/preproc/asm_file.cpp
Tested with
```diff
-enum CmdVarious
+enum __attribute__((packed)) CmdVarious
```
Followed by
```sh
make build/modern/data/battle_scripts_1.o
```
Closes #7304
> preproc: Support __attribute__ in enums

- src/battle_util.c
Adds Missing break in ABILITY_TERAFORM_ZERO
> Adds Missing break in ABILITY_TERAFORM_ZERO

- src/battle_ai_main.c
(I forgot this in #7342 thanks @iriv24 for catching)
@Pawkkie
> Add missing break

- include/data.h
- src/battle_ai_main.c
Enables users to set AI flag combinations for Partner trainers for multibattles. Also fixed battler3 in 2vs1 multibattles not having correct AI flags set.
Fixed BattleAI_SetupFlags so that battler3 in 2v1 multibattles has correct AI flags set.
Fixed BattleAI_SetupFlags so that battler2 has correct AI flags set from the partner trainer struct
Changed SanitizeTrainerId to not sanitize Battle Partner trainer IDs
Changed GetTrainerStructFromId to return Battle Partner trainer struct for Battle Partner trainer IDs
BattleAI_SetupFlags previously only sets battler3 AI flags to match battler1 AI flags if TRAINER_BATTLE_PARAM.opponentB != 0. In Doubles, TRAINER_BATTLE_PARAM.opponentB is set to 0, however in 2vs1 multis it is set to 0xFFFF, meaning battler3 flags are set to the battle flags for …
> Multibattle Partner AI Flags and 2vs1 battler3 AI Flags fix

- src/battle_debug.c
This will show the chosen move if battler is not planning to switch out.
> Show chosen move in the battle debug menu

- src/battle_controller_player.c
player controller just checked if gimmick was usable in general but not on specific move for z moves
> Fix Incompatible Z-Move Activation

- src/battle_util.c
Follow up for #7002. 
I forgot to remove this snippet
> Remove leftover code

- src/pokenav_main_menu.c
Not LZ compressed, and not palette data.
hedara
> Changed incorrect comment

- tools/trainerproc/main.c
The message at the top of the generated `src/data/trainers.h` file wasn't updated in #7154. This PR updates it.
hedara
> Update trainer.h usage warning

- test/battle/ability/normalize.c
The existing tests didn't really make sense, rewritten to better reflect the test title.
hedara
> Clean up some Normalize tests to make them make sense

- data/battle_scripts_1.s
- test/battle/move_effect/leech_seed.c
> Fixes Leech Seed recovery not applying behind Sub

- src/overworld.c
> Fixed compile issue `OW_TIMES_OF_DAY` is `GEN_3`

- include/battle_ai_util.h
- src/battle_ai_main.c
- src/battle_ai_util.c
Corrected Flower Veil call, brought in the mold breaker effects, and accounted for Mist.
wildvenonat
> Fiddling with CanLowerStat.

- include/battle.h
Someone in the EI Discord asked what this did.
It literally does nothing.
Thanks Kildie!
@Pawkkie
> Remove funcResult from AiThinkingStruct

- src/battle_ai_main.c
- test/battle/move_effect/rototiller.c
Simple AI handling for Rototiller.  Only in CheckViability, though, so while it could later use handling in CheckBadMove, it doesn't really matter.  The AI won't use it anyway by default.
wildvenonat
> AI uses Rototiller.

- test/battle/move_effect/dragon_cheer.c
Test that AI uses Dragon Cheer with dragon types on side, and does not without dragon types.
wildvenonat
> Test that AI uses Dragon Cheer.

- src/data/moves_info.h
> Fixed Teleport's description not being updated based on `B_TELEPORT_BEHAVIOR`

- test/battle/ability/intimidate.c
Intimidate was incorrectly spelled.
hedara
> Fixed typo in test name

- asm/macros/battle_script.inc
- data/battle_scripts_1.s
- docs/tutorials/how_to_battle_script_command_macro.md
- include/battle.h
- src/battle_main.c
- src/battle_script_commands.c
- test/battle/move_effect/octolock.c
- test/battle/move_effect/sky_drop.c
Fixes #7417
Closes  #7414
Also modified the the script command tutorial
> Fixes octolock not ending after user switched out

- src/battle_anim_effects_1.c
- test/battle/move_effect/ally_switch.c
- Ally switch leech seed battler does not get updated (added test for this)
- Ally switch attract battler does get updated (code + test)
Mechanics research from Linathan:
- Attract mechanics research: https://discord.com/channels/419213663107416084/1368163973366681712/1410389745875288207
- Leech seed mechanics research: https://discord.com/channels/419213663107416084/1368163973366681712/1404629785598234695
> Ally Switch attract battler swapping, test for leech seed

- data/battle_scripts_1.s
- include/battle_controllers.h
- include/constants/item_effects.h
- include/pokemon.h
- src/battle_anim_effects_1.c
- src/battle_controllers.c
- src/battle_script_commands.c
- src/battle_util.c
- src/data/pokemon/item_effects.h
- src/pokemon.c
- src/vs_seeker.c
- test/battle/item_effect/increase_stat.c
- test/battle/move_effect/ally_switch.c
- test/battle/move_effect/embargo.c
Don't squash. 
The `TrySwapAttractBattlerIds` needs a review since this changed going from master to upcoming
> Master to upcoming 28/08/25

- src/battle_ai_main.c
- test/battle/ai/can_use_all_moves.c
- test/battle/move_effect/flower_shield.c
AI handling for Flower Shield.
wildvenonat
> AI uses Flower Shield.

- src/data/items.h
Added missing sortType value to Douse Drive
Frankfurter0
> Added sortType to Douse Drive

- src/battle_ai_main.c
Discussed with Alex; I didn't know that FOE is always specifically the left-side battler and had written Helping Hand wrong.
wildvenonat
> Helping Hand bugfix; used FOE instead of BATTLE_OPPOSITE.

- README.md
- src/battle_ai_main.c
- src/battle_script_commands.c
- src/data/items.h
- test/battle/ai/ai_doubles.c
- test/test_runner.c
**DO NOT SQUASH**
One failing test marked as `KNOWN_FAILING`, was previously failing but masked by test runner issues.
hedara
> Master to upcoming, 2025-09-02

- data/battle_scripts_1.s
- src/battle_script_commands.c
- test/battle/move_effect/rage_fist.c
> Fixes Rage Fist for gen7 Disguise

- include/battle_ai_util.h
- src/battle_ai_main.c
- src/battle_ai_util.c
- test/battle/ai/gimmick_z_move.c
AI handling for Extreme Evoboost!  The bestest of z-moves.
Thank you to Pawkkie, Alex, and grintoul for showing me where Last Resort was actually getting its score decreased.  I will not be passing my perception checks at this time.
wildvenonat
> AI uses Extreme Evoboost.

- data/battle_scripts_1.s
- include/battle_scripts.h
- src/data/battle_move_effects.h
As of #7402 the script is not needed anymore
> Remove Uproar attack battle script

- include/config/battle.h
- src/battle_script_commands.c
SV captures look critical if the pokemon is already caught and this PR adds that feature as a config
https://github.com/user-attachments/assets/de1e3d78-9218-47dc-81f9-d323d351d9f5
Fixes #3905
Jamie (foster_harmony)
> Config for capture to appear critical if the pokemon is already caught

- src/battle_ai_main.c
Something I missed when reviewing #7698.
PhallenTree
> Fixes AI scoring when Priority moves are blocked

- asm/macros/battle_script.inc
- data/battle_scripts_1.s
- include/battle.h
- src/battle_script_commands.c
- src/battle_util.c
- src/data/battle_move_effects.h
- src/data/pokemon/teachable_learnsets.h
- test/battle/move_effect/beat_up.c
> Fixes Beat Up incorrect slots usage

- src/battle_ai_util.c
- src/battle_util.c
- test/battle/ability/levitate.c
Adds a fix for switch AI not correctly seeing Mold Breaker as hitting through Levitate.
@AlexOn1ine for "complete" Levitate fix
grintoul
> Fix for Levitate and Mold Breaker being seen correctly by switch AI, with Levitate tests

- include/field_name_box.h
- src/field_message_box.c
- src/field_name_box.c
- src/match_call.c
- src/text.c
This PR adds a change/commit that I've forgotten to add into #7697, sorry about that!
mudskipper13
> `field_name_box` smol followup

- src/data/region_map/region_map_sections.json
- src/data/region_map/region_map_sections.json.txt
Simplified region_map_entries.h by adding COMPOUND_STRINGs
Frankfurter0
> Added COMPOUND_STRINGs to region_map_entries.h

- data/battle_scripts_1.s
- src/battle_script_commands.c
- test/battle/move_effect/ohko.c
> Fixes OHKO moves calculating accuracy twice

- data/battle_scripts_1.s
- src/battle_util.c
- test/battle/hold_effect/restore_pp.c
> Fixes Leppa Berry timings

- src/battle_script_commands.c
- test/battle/form_change/faint.c
Also corrects an existing test that was faulty and marks it as known failing
Fixes #7795
bassoonian
> Fix Forecast and Flower Gift corruption

- docs/tutorials/how_to_trainer_front_pic.md
I mean, that color usage limitation was very whackly worded.
> Fixup add-new-trainer-front-pic tutorial.

- src/battle_script_commands.c
- src/battle_util.c
- test/battle/hold_effect/throat_spray.c
- test/battle/move_effect/ceaseless_edge.c
> Fixes Effects activating when move wasn't successful 

- include/constants/battle_script_commands.h
- src/battle_util.c
- test/battle/hold_effect/throat_spray.c
Only Life Orb and Shell Bell are supposed to be blocked by Sheer Force.
Also removed some of the more redundant comments.
> Fixes Throat Spray being blocked by Sheer Force

- include/battle.h
- src/battle_ai_util.c
- src/battle_controller_player.c
- src/battle_main.c
- src/battle_script_commands.c
- src/battle_util.c
- src/recorded_battle.c
The call to get a move from a position was very verbose, it was 3 deep. I think this function makes it a bit easier to use and read.
> Add func GetChosenMoveFromPosition

- src/party_menu.c
> Fix Party Menu move select name width

- include/battle_util.h
- src/battle_util.c
just changes the return type back
khbsd
> followup: AbilityBattleEffects return type is incorrect

- src/battle_script_commands.c
> Missing IsBattlerAlive checks in Opportunist/Mirror Herb

- include/battle.h
- src/battle_main.c
- src/battle_util.c
> Remove two unused bits from battle structs

- src/data/moves_info.h
Mountain Gale's PP was updated in Gen 9 but the code didn't reflect that, so this PR fixes that
Frankfurter0
> Updated Mountain Gale's PP for Gen 9

- src/overworld.c
Regression introduced in #7499 
Master:
https://github.com/user-attachments/assets/afed0f08-2dff-4d27-a705-b3423f7e16bd
Fixed (with speedup):
https://github.com/user-attachments/assets/a9672863-ee85-4440-a567-05549748a5ac
Jamie
> Fix dns palette weight 

- src/debug.c
Fixes EV display in debug menu. Previously limited to 2 digits.
#6374 
.cawt
> Fix EV display in debug menu
