src/data/pokemon_graphics/front_pic_anims.h

Due to an oversight of mine, I forgot to properly set the animations for the forms of Deoxys back when I implemented their data.
Lunos#4026

Fixed the animation of Deoxys' Attack, Defense and Speed forms

---

include/constants/pokemon_config.h
include/pokemon.h
src/data/pokemon/base_stats.h

Created configuration file with options for updated types and stats.

Updated types and stats in configuration file.

---

include/constants/item_config.h
include/constants/pokemon.h
include/item.h
include/wild_encounter.h
src/battle_main.c
src/battle_script_commands.c
src/data/items.h
src/item_use.c
src/pokemon.c
src/wild_encounter.c

Adding options for making Gen 3 fossils and Escape Rope into key items.
Moved Shiny Charm Rerolls def to config file.
Reworked effects of Heavy Ball
Added Beast Ball effect.

Item Expansion config file.

---

include/constants/species.h

Created a macro that determines if a species is an Ultra Beast.

Created macro used to detect Ultra Beasts.

---

src/data/text/move_descriptions.h

Addresses https://github.com/DizzyEggg/pokeemerald/issues/508
Lunos#4026

Fixed the descriptions of Freeze Dry and Flying Press

---

data/battle_anim_scripts.s

Changed Hurricane's animation

---

src/data/items.h

I accidentally swapped the config for fossils during the initial PR.

Fixed gen 3 fossil config

---

include/constants/item_config.h
include/global.h

Moved ITEM_EXPANSION define to global.h to fix reading from other branches like Battle Engine

---

include/constants/pokemon_config.h
include/global.h

Moved POKEMON_EXPANSION define to global.h to fix reading from other branches

---

src/battle_util.c

Implemented Guts' missing effect

---

data/battle_anim_scripts.s
src/battle_anim_new.c

CFRUs power trick animation.
**OLD:**
**NEW:**

redo power trick anim

---

include/constants/species.h
include/pokemon.h
src/data/pokemon/base_stats.h

Must be merged at the same time as #1252

Add mon flags

---

src/battle_script_commands.c

Must be merged at the same time as #1251

Removed IS_ULTRA_BEAST in favor of mon flag

---

include/constants/battle_config.h

I Improved the comment of B_STANCE_CHANGE_FAIL.
Lunos#4026

Improved the comment of B_STANCE_CHANGE_FAIL

---

src/battle_controller_player_partner.c

(i.e., Steven at Mossdeep)
Tweaks player partner AI to mega evolve if possible like other NPC's.
Modified PlayerPartnerHandleChooseMove in src/battle_controller_player_partner.c
Nam#5245

Allow player partner NPC's to mega evolve

---

src/data/pokemon/base_stats.h

Add Galarian Form mon flags

---

include/constants/battle_config.h

I corrected and shortened the comment of `B_ABILITY_WEATHER`, and I moved the Exempli Gratia from the Flag settings section to a new line because it was easier to read that way, though that change may be subjective so I could roll it back if it's not well received :eyes:
Lunos#4026

Some more small battle_config.h tweaks

---

data/battle_scripts_1.s

Title. I laid out a preprocessor directive involving Intimidate incorrectly, and this PR intends to fix it.
Lunos#4026

Fixed incorrect preprocessor directive in ASM file

---

data/battle_anim_scripts.s

Addresses some issues I brought up in #1351
**EDIT**: Before -> After
Lunos#4026

Fixed Focus Blast animation

---

spritesheet_rules.mk

This change fixes the new berries not getting properly visualized.
𝓝𝔂'𝓪𝓵𝓸𝓽𝓱𝓪-0001

Updated berries' path on spritesheet_rules.mk

---

include/constants/battle_config.h

> ExpoSneedToday at 8:30 PM
Actually since I'm away from home
Can someone PR including global.h in battle config
It fixes the duplicate defines issue
Lunos#4026

Included global.h into battle_config.h

---

include/constants/battle_config.h

Reverts rh-hideout/pokeemerald-expansion#1361

Revert "Included global.h into battle_config.h"

---

src/data/items.h
src/data/pokemon/item_effects.h
src/data/text/item_descriptions.h

Laundry list PR, is missing a few more complex changes such as flavor berries, sitrus berry, and soul dew.
any input is appreciated! :)
Hyper Potion HP 200 -> 120
Super Potion HP 50 ->60
Fresh Water HP 50 -> 30
Soda Pop HP 60 ->50
Lemonade HP 80 ->70
Energy Powder HP 50 -> 60
Energy Root HP 200 -> 120
Power Items EV gain 4 -> 8
~~apricorn balls 2,000 -> 300~~
quick/dusk ball 3,000 -> 1000
cherish/park/dream ball 10 -> 0
~~sport ball 10 -> 300~~
beast ball 10 -> 0 (gen 7)
~~sweet heart 3,000 -> 100~~
~~old gateau 350 -> 200~~
~~x attack 1,000 -> 500~~
~~x defense 2,000 -> 550~~
~~x speed/ sp. atk 1,000 -> 350~~
~~x accuracy 1,000 -> 950~~
~~x sp. def 2,000 -> 350~~
~~ability capsule 10,000 -> 1,000~~
moon stone 0 -> 2100
~~apricorns 200 -> 20~~
~~rare bone 5,000 -> 10,000~~
retro mail 0 -> …

update item effects, prices, names & descriptions

---

src/data/pokemon_graphics/front_pic_anims.h

This PR fixes a small issue in Deoxys Attack Form's animation, brought up by @kevinmc37 in #1335.
Lunos#4026

Fixed Deoxys Attack Form's animation

---

asm/macros/battle_script.inc
data/battle_scripts_2.s
src/battle_util2.c

Edit->Blank Operations->Trim Trailing Space for the win
Lunos#4026

Removed trailing spaces from various files

---

src/battle_util.c

Fixed Defeatist's check

---

src/battle_interface.c

Add apostrophe to ability pop up like in actual games:

Ability Pop Up Apostrophes

---

src/battle_util.c

Made Thousand Arrows bypass type immunity

---

src/battle_util.c

Reverts rh-hideout/pokeemerald-expansion#1453

Revert "Made Thousand Arrows bypass type immunity"

---

src/battle_script_commands.c

Title. This has been missing for well over a year now. It's time to correct that.
Lunos#4026

Added Gravity's missing acc boost

---

src/battle_util.c

Title.
I tweaked the syntax of the different `if` statements in the `HandleAction_UseMove` function that contained multiple conditions in them so they could be a bit more comfortable to read.
Any other suggestions to improve readability are welcomed.
Lunos#4026

Minor syntax tweaks to HandleAction_UseMove

---

src/battle_util.c

Fixed Punk Rock

---

src/battle_util.c
src/data/text/abilities.h

As it was brought up in #1436, Stench is missing its battle effect in the battle_engine. This PR implements it.
I also updated its description.
Lunos#4026

Implemented Stench's battle effect

---

include/constants/pokemon.h
include/pokemon.h
src/data/pokemon/base_stats.h
src/pokemon.c

- Introduce `NUM_ABILITY_SLOTS` to trivially increase the number of ability slots
- Refactored `abilityHidden` to use the 3rd element of `abilities`
Note: #1465 depends on this PR

Hidden ability refactor

---

src/battle_script_commands.c

Keen Eye evasion ignoring effect from Gen 6

---

src/pokemon.c

Fixes #1490, where Pokemon who had their hidden ability have no ability when mega evolved.
venonat#2645

Pokemon with no ability recheck first ability slot.

---

src/data/pokemon/base_stats.h

This PR complements #1493
Lunos#4026

Corrected the Wings/Feathers #2

---

src/data/items.h

Renamed Feather items
We do have enough space to put the whole word.
Jaizu#4989

Feathr > Feather

---

data/battle_scripts_1.s
src/battle_script_commands.c

Fix FlameBurst

---

src/battle_interface.c

Suggestion by Spherical Ice
It changes the abilty popup sound
bought

Change the ability popup sound

---

include/battle_util.h
src/battle_util.c

Addresses #1531 by making the ability not activate if the user is the last 'mon alive in their party.
https://user-images.githubusercontent.com/4485172/121108587-65d52000-c7e0-11eb-90e2-c0e321d57d4e.mp4
Lunos#4026

Fixed Emergency Exit

---

src/battle_gfx_sfx_util.c

Fix mon shadow when caught and learn new move

---

src/battle_util.c

Fix Imposter looplock

---

include/constants/battle_config.h
include/constants/expansion_branches.h
include/global.h

Merge at the same time as #1553 and #1554 
Resolves #1264

Fix redefinition error in battle_config.h

---

include/constants/expansion_branches.h
include/constants/pokemon_config.h
include/global.h

Merge at the same time as #1552 and #1554 
Resolves #1264

Fix redefinition error in pokemon_config.h

---

include/constants/expansion_branches.h
include/constants/item_config.h
include/global.h

Merge at the same time as #1552 and #1553
Resolves #1264

Fix redefinition error in item_config.h

---

data/battle_anim_scripts.s
src/battle_anim_mon_movement.c
src/battle_anim_utility_funcs.c

Fix Gravity's animation

---

data/battle_scripts_1.s

Addreses #1568
https://user-images.githubusercontent.com/4485172/125494479-c209e723-52cb-47b8-a2b9-ae726f185e3f.mp4
Lunos#4026

Fixed Cotton Down

---

include/battle_ai_util.h
src/battle_ai_main.c
src/battle_ai_util.c

adds some checks to make sure battler is affected by terrain instead of terrain just being present.

AI_IsTerrainAffected checks

---

src/data/pokemon_graphics/front_pic_anims.h

Assigned dummy anims to the front sprite of each Pikachu and Pichu special form

---

data/battle_scripts_1.s

Fix White Smoke affecting Shell Smash's def drop

---

src/battle_script_commands.c

Addresses #1613 
**EDIT**:
Lunos#4026

 Fixed U-turn and Choice Items interaction 

---

data/battle_scripts_1.s

Fixes the Intimidate issue #1217

Fix lag caused by ability pop-up while it's set to False

---

data/battle_scripts_1.s

Also fixes galvanize explosion + motor drive, and other similar cases.
#1614

fix galvanize explosion + lightning rod

---

src/pokemon.c

Addresses #1544
Before:
After:
Lunos#4026

Fix SPECIES_UNOWN

---

src/data/text/item_descriptions.h

See Title. In accordance with #1355

Update Mental Herb Description

---

src/battle_util.c

Turns out I broke Foul Play when adding Body Press. This PR fixes that.

Fix Foul Play

---

src/data/battle_moves.h

Now that we have a thaw flag, Scald can behave like it does in Gen 5

Scald thaw flag config for Gen 5

---

src/battle_util.c

Adds missing check for Egg in Illusion

---

src/battle_util.c

Addresses #1679.
**EDIT**: Forgot vid.
https://user-images.githubusercontent.com/4485172/134657469-7d29a96b-73b4-4ffc-9607-8524a96da4f3.mp4
**EDIT2**: I should have tested this *before* submitting the PR, but well, what can I say. I really hate doubles.
Anyway, this is working fine on that front too.
Lunos#4026

Completed Black Sludge's effect

---

src/battle_script_commands.c

Dream ball checks comatose

---

src/party_menu.c

Fixed form icon subpriority

---

src/battle_script_commands.c

It has an extra parenthesis which makes the compiler unable to build a ROM.
Lunos#4026

Fix Dream Ball's effect's code

---

include/constants/pokemon.h
src/data/pokemon/form_change_tables.h
src/party_menu.c
src/pokemon.c

Shaymin is a pain.
**EDIT**: Forgot to add, this addresses #1688.
Lunos#4026

Added a day time exclusive equivalent to `FORM_USE_ITEM`

---

src/battle_main.c

Addresses #1700
Before:
After:
Lunos#4026

Fixed Safari Zone

---

src/battle_util.c

Fixed Sleep talk being canceled by the user being asleep..

---

include/constants/item_config.h
include/constants/item_effects.h
src/data/items.h
src/data/pokemon/item_effects.h
src/pokemon.c

Resummited SBird's Sitrus Berry commit with his permission. This PR handles out of battle behavior and updates hold effect to the one used in Battle Engine.

Sitrus Berry Gen4+ heal. Credit to SBird1337

---

src/battle_util.c

Resubmitted with Fontbane's permission.

Fixed Heat Crash's power table name

---

src/battle_util.c

Fix Unnerve not canceling out type resist berries.

---

include/battle.h
include/constants/battle.h
src/battle_debug.c
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

`gStatutes3` has run out of bits, so it's time to expand.
I also moved `STATUS3_ELECTRIFIED` to status4 so #1413 can have `STATUS3_SKY_DROPPED` in `STATUS3_SEMI_INVULNERABLE`.

Add gStatutes4

---

data/battle_scripts_1.s
include/battle_scripts.h
include/constants/battle_string_ids.h
src/battle_message.c
src/battle_script_commands.c
src/battle_util.c

Adds the effect of Gorilla Tactics; it's just Choice Band but as an ability.
Addresses #1038.

Implement Gorilla Tactics

---

data/battle_anim_scripts.s

Forgot to put delay and sound effect for the charging effect.
Now it will execute properly 100% with the [preview ](https://discord.com/channels/419213663107416084/774393519569502268/90390276129963627)video.

Minor fix to Steel Beam

---

src/battle_script_commands.c

Title
Classic ghoul :D
Jaizu#2172

Fix comment typo

---

include/battle_ai_util.h
src/battle_ai_main.c
src/battle_ai_util.c

AI versions of CanPoisonType, CanBePoisoned and IsAbilityOnSide

---

src/battle_ai_main.c

Fix AI discouraging own magic guard

---

include/constants/battle_config.h
src/battle_util.c

Addresses the battle_engine side of #1805.
Lunos#4026

Added a battle config for the Soul Dew

---

include/constants/item_config.h
src/data/items.h

Complements #1863 and addresses the item_expansion side of #1805.
Lunos#4026

Added an item config for the Soul Dew

---

src/battle_util.c

Fix heat crash/heavy slam calculation

---

src/battle_script_commands.c

ChangeStatBuffs was missing a check for Big Pecks.

Fix Big Pecks

---

src/battle_util.c

according to https://bulbapedia.bulbagarden.net/wiki/King%27s_Rock

Serene Grace affects King's rock

---

include/constants/battle_config.h
src/battle_util.c

add kings rock serene grace boost config

---

src/data/pokemon_graphics/back_pic_coordinates.h

Fix Furfrou's form's backsprite coordinates

---

data/battle_anim_scripts.s

Before it was playing a random song.
(...I should stop approving PRs without testing them 🤦‍♂️)

Fixed Relic Song's SE

---

src/battle_util.c

Fix typo that caused Cherrim to get stuck in an infinite from change loop.

Fix Cherrim softlock

---

src/battle_util.c

The damage boost from these abilities should be 33%, not 25%.

Fix Dark Aura and Fairy Aura

---

include/constants/pokemon.h

I made a mistake in #1910, this PR corrects it.
Lunos#4026

Fixed an incorrect #elif

---

include/constants/item_config.h
src/data/pokemon/item_effects.h

Renamed `I_LEGACY_HEALING_ITEMS` to `I_HEALTH_RECOVERY` and also fixed its inaccurate description.
Lunos#4026

Changed I_LEGACY_HEALING_ITEMS

---

include/constants/battle_config.h
src/battle_script_commands.c
src/battle_util.c

fix rampage cancelling

---

src/battle_script_commands.c

After #1964, this is no longer needed.
Lunos#4026

Removed ITEM_ENIGMA_BERRY_E_READER usage

---

include/constants/battle_config.h
src/battle_ai_main.c
src/battle_util.c

Ice Types immune to Sheer Cold

---

src/pokemon.c

Fixes EVO_LEVEL_RAIN to actually check the level

fix EVO_LEVEL_RAIN

---

src/egg_hatch.c

Added Steam Engine's overworld effect

---

src/battle_debug.c

Originally utilized as part of #1965, as that value changer is based off BE's.
Instead of just moving up and down the number values, it increases the overall value by the selected digit. Eg: If the number 099 has the 3rd digit selected and the user presses Up, the value will increase to 100 instead of changing to 090.

Improved battle debug number value changing

---

include/constants/battle_config.h
src/battle_interface.c

Config for HP bars moving faster for higher HP amounts. Credit to Dat.H

---

src/data/pokemon/pokedex_text.h

To remain consistent with the other... I don't know, 891 entries, and also because why not
Lunos#4026

Removed weird spaces in 7 dex descriptions

---

src/battle_debug.c

Something I noticed during the master merge that was missing.

Using TAG_NONE in battle debug

---

src/data/text/item_descriptions.h

Expanded the idea of Mental Herb updating its description based on BE config.

Update to item descriptions based on configured effect.

---

data/battle_scripts_1.s
src/battle_script_commands.c

Update Role Play

---

include/reset_rtc_screen.h
src/pokemon_debug.c
src/reset_rtc_screen.c

Complements #1965 and kills 2 merge conflicts before they're born.
Lunos#4026

Fixed struct names

---

data/battle_scripts_1.s
include/constants/battle_config.h
src/battle_script_commands.c

Partly addresses #1604.
I hope we can all agree it'd be stupid to add a battle config for this :P
Lunos#4026

Multi battle updates

---

src/pokemon_debug.c

fixes the following bugs:
-const and offset data not beeing reset on form change (fixes #2022) 
-new offset values not beeing applied on normal/shiny change
https://user-images.githubusercontent.com/48356183/148211780-46e13497-c0d1-4d63-9c9e-775ec4cd5088.mp4
TheXaman#5612

fixes for pokemon_debug.c of values not beeing applied/reset

---

src/battle_util.c

Title, resolves #1873
TheXaman#5612

Yawn now uses B_SLEEP_TURNS

---

src/battle_script_commands.c

Fixed usage of B_MULTI_BATTLE_WHITEOUT

---

src/data/text/move_descriptions.h

Fixed Anchor Shot description.

---

README.md

Using the wiki's About page so people are able to find the Discord link easier.

Updated README.md in master

---

src/battle_script_commands.c
src/battle_util.c

Addresses https://github.com/rh-hideout/pokeemerald-expansion/issues/1717

[battle_engine]  Moxie interaction with spread move/follow me fix

---

src/battle_util.c

Fix harvest activation msg

---

src/battle_main.c
src/battle_script_commands.c
src/battle_util.c

Noticed some redundant uses for GetBattlerAbility, so decided to tweak how it's used.

Optimized use of GetBattlerAbility

---

src/data/text/move_descriptions.h

Rewrote the labels of the move descriptions in accordance to Pret's syntax.
SubzeroEclipse##7867

Fixed format of move descriptions' labels

---

src/item_use.c

Updated GetBallThrowableState

---

src/battle_message.c

Quick PR that fixes some of the new battle strings that were not decapitalized, unlike the rest of them.
SubzeroEclipse#7867

Decapitalization of some battle strings

---

src/battle_main.c

Noticed this from playtesting my own game.

Fix ability pop up for quick draw

---

src/battle_ai_util.c

Fix AI_WhoStrikesFirst

---

src/pokedex.c

Fixed Pokédex entry upon catch not properly handling gender differences

---

src/daycare.c

Fix MIME_JR #ifdef

---

src/party_menu.c

Now in the correct branch
Jaizu#2172

Use TM constant in CanMonLearnTMTutor

---

data/battle_anim_scripts.s
include/battle_anim.h
src/battle_anim_mon_movement.c
src/battle_anim_new.c
src/battle_anim_normal.c

Struggle Bug Anim is only affecting one target. This fixes that
OLD vs. NEW:

Fix struggle bug anim

---

src/battle_util.c

fix toxic/flame orb. use CanBeX'ed functions

---

src/battle_ai_util.c

Remove repeated ability check in battle_ai_util.c

---

src/party_menu.c

Removed ternary from CanMonLearnTMTutor

---

data/battle_anim_scripts.s

No more delay before launching the energy ball. I don't even know why did I leave that in back when I made the script.
Before | After:
Lunos#4026

Improved the special animation of Shell Side Arm

---

include/pokemon.h
src/battle_main.c
src/party_menu.c
src/pokemon.c
src/trade.c

Addresses #2057.
Supersedes #2065 so it's not a harcoded check.

Fixed Shelmet and Karrablast being able to evolve if the partner is holding an Everstone

---

src/battle_main.c

Addresses issue #2081 with a simple fix (and hopefully not an incorrect one). See attached gif for demonstration:
Agustin#1522

fixed shed shell

---

include/item_use.h
include/party_menu.h
src/data/items.h
src/item_use.c
src/party_menu.c

Included instructions in case somebody implements hidden abilities without Pokémon Expansion.

Ability Patch

---

data/battle_scripts_1.s
include/battle_scripts.h
include/constants/battle_config.h
src/battle_util.c

Adds the missing interaction between Intimidate and Rattled.

Gen 8 Intimidate triggers Rattled

---

src/party_menu.c

Reverts rh-hideout/pokeemerald-expansion#2095

Revert "Removed ternary from CanMonLearnTMTutor"

---

include/battle_util.h
src/battle_ai_main.c
src/battle_controller_opponent.c
src/battle_controller_player.c
src/battle_util.c

Prevent targeting heal blocked partner with pollen puff. Add some AI checks for healing ally under heal block

Heal Block AI and Pollen Puff Selection Prevention

---

data/battle_scripts_1.s
include/battle_scripts.h
src/battle_script_commands.c

Add popup for inner focus preventing flinching
g

add inner focus ability popup msg

---

include/battle.h
include/constants/pokemon.h
src/battle_main.c
src/battle_script_commands.c
src/pokemon.c

Added framework for non-level related battle evolutions and specific functionality for Galarian Farfetch'd's evolution method (even though I'm realizing G-Farfetch'd isn't included in the battle_engine).
Agustin#1522

Gen 8 Evolution Mechanics (Battle Engine)

---

include/constants/battle_config.h
src/battle_main.c

Pokemon that qualify for evolution after battle will evolve even if the player loses.

Allow evolutions after whiting out

---

include/battle_gfx_sfx_util.h
src/battle_controller_link_opponent.c
src/battle_controller_link_partner.c
src/battle_controller_opponent.c
src/battle_controller_player.c
src/battle_controller_player_partner.c
src/battle_controller_recorded_opponent.c
src/battle_controller_recorded_player.c
src/battle_controller_wally.c
src/battle_gfx_sfx_util.c

Removes the IsMoveWithoutAnimation function and edits all functions that call it.

Remove IsMoveWithoutAnimation

---

data/battle_scripts_1.s

Addresses https://github.com/rh-hideout/pokeemerald-expansion/issues/2149

Fix terrain move softlock

---

src/pokemon.c

Syntax fixes for Toxel's evo methods

---

src/data/text/item_descriptions.h

Currently, it goes out of bounds.
Before -> After
Lunos#4026

Fixed Pokéblock Case's description

---

data/battle_scripts_1.s
include/constants/battle_config.h
src/battle_ai_main.c
src/battle_ai_util.c
src/data/battle_moves.h

- Used [this commit](https://github.com/rh-hideout/pokeemerald-expansion/commit/e7d5ebb3b652173f0da69f06a4df0e3fc2f62ab3) as a reference for the Charge change.
- Added Growth's Atk. raise to the its configuration, as that was also introduced in Gen 5.
- Also organized config for moves that change stats into their own category.

Config for Charge raising Sp. Def., adjusted Growth's config

---

src/battle_ai_main.c

Fix AI logic check in `GetAiLogicData` per https://discord.com/channels/419213663107416084/774393519569502268/993732927227695205

fix GetAiLogicData logic

---

include/constants/battle_config.h
src/battle_util.c

Config for Explosion halving defense

---

src/item.c

Should have been done back in #1906 but I'm dudumb 😂 
Lunos#4026

Removed global and unused IsPinchBerryItemEffect

---

src/battle_ai_main.c

Corrected usage of B_PRANKSTER_DARK_TYPES in AI_CheckBadMove

---

src/battle_ai_main.c

Supercedes #1756 , as it was targeted to master instead of BE and it hasn't been touched in months.

Small AI fixes by mrgriffin

---

include/constants/battle_config.h
src/battle_util.c

Based on [these](https://github.com/rh-hideout/pokeemerald-expansion/commit/143cb7ad3512fba621ce50fe287700f2a9c3f555) [commits](https://github.com/rh-hideout/pokeemerald-expansion/commit/63355d6a3b11ee8701b436290685f1bb8bbf9e24).

Config for Gen 3 faint switch mechanics

---

src/battle_script_commands.c

Fixed Heal Ball not always healing caught Pokémon

---

src/battle_controller_opponent.c

The AI was using only the first move, and soft locking when the first move's PP ends

Fix the AI

---

data/battle_scripts_1.s

Using B_WAIT_TIME_LONG for new battle scripts

---

src/battle_z_move.c

B_WIN constants in battle_z_move.c

---

src/party_menu.c

Addresses https://github.com/rh-hideout/pokeemerald-expansion/issues/2094 by implementing the fix mentioned [here](https://github.com/rh-hideout/pokeemerald-expansion/issues/2094#issuecomment-1108703871) by [@PepaPigHS](https://github.com/PeppaPigHS).

Fix tm/hm compatibility

---

src/battle_util.c

ENDTURN_WISH resets gBattleStruct->turnSideTracker

---

src/battle_interface.c

Ability pop-up displays properly long abilities

---

src/battle_script_commands.c

Fixed critical capture fields not using TRUE or FALSE

---

src/battle_script_commands.c

Included PR #2219 that was accidentally merged into BE

---

src/battle_script_commands.c

Fixed Net Ball Gen 7+ multiplier

---

include/config.h

A very basic change that I don't see anyone wanting to turn off.

Enable BUGFIX by default

---

src/pokemon_storage_system.c

Removed unused local var in SetMonFormPSS

---

data/battle_scripts_1.s

Dragon Tail Weak Armor fix

---

include/constants/battle_config.h
src/battle_script_commands.c

Ultra Ball's multiplier was defaulting to Great Ball's which in turn defaulted to Net Ball's if its conditions were met.

Fixed ball multiplier fallthroughs

---

README.md

Updating readme with links to documentation and credits list.
I've linked the wiki so anybody can update their credited implementations, documentation as needed

update readme with credits, wiki links

---

src/pokemon.c

Small syntax fix for CanLearnTeachableMove

---

src/data/items.h

This change reflects the original prices used in Pokémon let's go pikachu/eevee
JaizuFangaming#2172

Fix Lure prices

---

src/battle_interface.c

Fixed ability pop ups

---

src/battle_util.c

Fixed the hero duo's abilities

---

src/battle_ai_switch_items.c

Noticed this after merging, but added missing brackets

fix ai switch semi invulnerable

---

include/party_menu.h
src/party_menu.c

 Fixed typo in BoxMonKnowsMove 

---

src/battle_z_move.c

Fixed Z-Moves showing the wrong type in battle

---

src/debug.c
src/field_specials.c

Fixes an issue where the PC's option descriptions field message would remain open after closing the PC, and also gives access to the PC item storage.
Lunos#4026

Modified the debug menu's PC access

---

src/battle_arena.c

Added missing Bide exception to Battle Arena Mind Points

---

src/battle_script_commands.c

Multiplied all uses of `ballMultiplier` by 10 to allow using Hisuian ball modifiers.

Changed ballMultiplier to account for future Hisuian ball multipliers

---

src/data/pokemon/level_up_learnsets.h

This was brought up at some point during the past month, and I even made a branch for it but I guess I never PR'd it so I just remade it again, but basically, there's no longer a reason to keep these commented out now that there aren't separate feature branches.
Lunos#4026

Uncommented evo moves for each species

---

src/battle_main.c

Fixed Z-Move not being cleared if Pokémon faints

---

src/main.c
src/pokemon_debug.c

Replaced all instances of a busy-wait for VBlank, which removes performance issues in regard to speedups in emulators as well as extra/unnecessary battery drain on hardware.
Crater#7777

Replaced busy-wait loops

---

src/battle_util.c

Fixed CanFling

---

src/item.c

Complements a commit in #2379.
Lunos#4026

Actually removed ItemId_GetId

---

data/battle_scripts_1.s
include/constants/battle_config.h
include/constants/battle_move_effects.h
src/data/battle_moves.h

Also made these instances like this (Hyperspace Fury, Aura Wheel) do what happens in [official games](https://youtu.be/ONpqY6D_iis?t=112).

Config for Dark Void being only usable by Darkrai

---

src/battle_util.c

Fixes issue #2448 
Single line fix
Haven't tested extensively, but regular Berries work and Bug Bite w/ Berries also works. I believe this line was missing by accident (you can look at the merged Bug Bite PR #2433 to see that this line was deleted and never replaced).
eatthepear#9846

Fix Berries that were broken after Bug Bite fix

---

sound/cry_tables.inc

Fix cry table alignment due to missing placeholder Enamorus Therian cry

---

src/party_menu.c

This QoL feature was implemented in the main games starting from SwSh and was missing from the expansion.
I think we can all agree that there isn't a need to add a preproc config for this.
Lunos#4026

Allow Lv100 'mons to access level based evos

---

src/battle_util.c

I noticed this potential mistake and decided to correct it.
Lunos#4026

Updated TryChangeBattleTerrain

---

src/debug.c

Set FLAG_SYS_POKEMON_GET when debug gifting yourself a Pokémon
Set FLAG_SYS_POKEMON_GET when debug gifting yourself a Pokémon
Jasper#5206

Set FLAG_SYS_POKEMON_GET when debug gifting yourself a Pokémon

---

include/battle.h

After #2452, I noticed that the SpecialStatus struct was not properly optimized in terms of padding.

Reorganized SpecialStatus struct to minimize padding.

---

include/battle.h
src/battle_main.c

Updated SIDE constant usages

---

.github/calcrom/calcrom.pl
graphics_file_rules.mk
include/fieldmap.h
include/gba/isagbprint.h
src/data/pokemon_graphics/front_pic_anims.h
src/decoration.c
src/field_camera.c
src/shop.c
src/tileset_anims.c

SHA1 before and after the merge: D037AD4918CA7982E7128B1258ADBCE9212CB8A2

I'll make your face the greatest in Hoenn! Or else you will DIE. (Pret merge 2022/12/16)

---

src/wild_encounter.c

Fixed B_DOUBLE_WILD_CHANCE becoming 1% less than what's set

---

asm/macros/battle_script.inc
data/battle_scripts_1.s
include/constants/battle_script_commands.h
include/constants/battle_string_ids.h
src/battle_message.c
src/battle_script_commands.c

Closes #2515
[mGBA_20221214_120013490.webm](https://user-images.githubusercontent.com/4485172/207630965-2d81d2ff-4f49-4c40-9300-7f1cd78e79fc.webm)
Lunos#4026

Fixed Speed Swap's effect

---

data/battle_scripts_1.s

Closes #2536 and #2537.
Lunos#4026

Fixed some issues of the Intimidate's rework

---

src/battle_ai_util.c

Fix faulty gBaseStats reference

---

src/battle_script_commands.c

Made Clear Body and similar abilities be normally affected by their own stat stage reductions

---

src/pokemon.c

Fixed Eggs sometimes reading garbage graphic data.

---

include/config/battle.h

I made a small oopsie back in #2470, lmao. This PR corrects it.
Lunos#4026

Updated B_DOUBLE_WILD_CHANCE

---

data/maps/BattleFrontier_Lounge7/scripts.inc

Fixed right Frontier move tutor not loading their move list correctly.

---

src/battle_script_commands.c

Updated HOLD_EFFECT_ZOOM_LENS check

---

data/scripts/repel.inc

Fixed reusable repels/lures function forcefully using items while menu config is on

---

include/config/battle.h
src/battle_util.c

Config to restore Gen 3's damage reduction to multi target moves

---

include/config/pokemon.h
src/daycare.c

Config for ball inheritence when breeding

---

src/battle_script_commands.c

Fix flame burst hitting semi-invulnerable partner

---

include/constants/items.h
src/battle_util.c
src/data/graphics/items.h
src/data/item_icon_table.h
src/data/items.h
src/data/text/item_descriptions.h

Added item data for the effects made in #2471 .
No icons for now.
Punching Glove's no-contact effect is only supposed to work with punching moves, so I also fixed it.

Added some Gen9 item data and fixed Punching Glove's effect

---

include/constants/daycare.h
src/daycare.c

Implements Destiny Knot daycare effect
Jaizu#0001

Implement Destiny Knot

---

include/battle_gfx_sfx_util.h
src/battle_anim_effects_3.c
src/battle_gfx_sfx_util.c

This doesn't fully implement Transform with latest gen mechanics neither should be the final fix.
This is only make so the game doesn't show a broken sprite, likle #2617 shows. Feel free to make a better fix.
Before the fix
Now
Scenario that doesn't break anymore but should be handled with a better fix:
Jaizu#0001

Fix Transform's interaction with Gender Differences

---

data/battle_anim_scripts.s

Fixed bugged Strange Steam animation
Description
Added a delay `delay 0x1` in `StrangeSteamCloud`
I also changed launchtemplate to createsprite in StrangeSteamCloud but the delay was still needed.
https://user-images.githubusercontent.com/93446519/217114085-9ccf9601-2d19-45e4-9d2b-6492a2875404.mp4

Fix Strange Steam anim

---

data/battle_scripts_1.s
include/battle_scripts.h
include/constants/battle_string_ids.h
src/battle_message.c
src/battle_util.c

Fix for #2627
Also created a new string for this.

Damp shows ability pop-up when reacting with Aftermath

---

include/pokemon.h

Fix SpeciesInfo(base stats) struct offset labels

---

data/battle_anim_scripts.s

Fix Spacial Rend animation

---

src/expansion_intro.c

Fixes an issue brought up by missiri#4895. The fix was proved by Tustin2121#6219. I'm just PR'ing it on their behalf.
Before:
https://user-images.githubusercontent.com/4485172/218807128-b7badf50-bd42-49ce-bfa4-d9a03e79e9fd.mp4
After:
Lunos#4026

Fixed glitchy-looking water drops in the game's intro

---

data/battle_scripts_1.s

fix follow me working in singles

---

src/battle_gfx_sfx_util.c
src/battle_main.c
src/battle_script_commands.c
src/reshow_battle_screen.c

Fixes https://github.com/rh-hideout/pokeemerald-expansion/issues/2614
Eggs gfx are not loaded, their sprite are invisible, they're marked as absent, and they cannot get experience. I think this should cover all of the possible cases.

Fix 1 vs 2 battles with eggs

---

data/battle_scripts_1.s
include/constants/battle_script_commands.h
src/battle_script_commands.c

Fix Mirror Armor against Clear Body

---

include/battle.h
src/battle_script_commands.c

Fixes #2402
Works for 2 parties of 6 Greninjas

Fix Battle Bond activating multiple times in battle

---

src/battle_ai_main.c

Due to #2700, a new case is needed for Howl AI

Add howl AI check for #2700

---

src/party_menu.c

Fixed evolutions that use held items to evolve not working when using Rare Candies

---

data/battle_anim_scripts.s

Incorporates #2785 to master branch, fixing critical graphical issues caused by certain electric move animations.

Version 1.4.1 (hotfix)

---

data/scripts/debug.inc

Sorry Teala, I have shit to do.

Set link tutorial as complete when using Cheat Start

---

data/scripts/debug.inc

Updates the string in the debug warning to match the new location of the file.
See title.
Jasper#5206

Update overworld_config.h reference in the debug system

---

src/debug.c

debug menu to give items based on max quantity and map number 3digits display

---

src/data/battle_moves.h

Fixed Wring Out's power

---

test/ability_intimidate.c
test/hold_effect_eject_button.c

Added tests for Eject Button. The source for the tests was bulbagarden.
One additional test for intimidate was added to test a bug.

Tests for Eject Button

---

data/battle_scripts_1.s
test/ability_intimidate.c

Fixes #2837 still works in double and adrenaline orb works.
#Tennis4004

Fixes weirdly set value for eject buttons etc

---

src/battle_util.c
src/battle_z_move.c
src/pokemon.c

Fixed erroneous uses of non e-reader Enigma Berries

---

src/battle_script_commands.c
src/battle_setup.c
src/battle_tower.c
src/match_call.c

Adds the missing cases for `F_TRAINER_PARTY_EVERYTHING_CUSTOMIZED` in
```
GetSumOfEnemyPartyLevel
GetTrainerMoneyToGive
FillPartnerParty
PopulateSpeciesFromTrainerParty
```

Adds missing cases for 'Everything Customized'

---

test/move_effect_dire_claw.c
test/move_effect_tri_attack.c

Added KNOWN_FAILING to Dire Claw and Tri Attack's force-bruted RNG failing tests

---

src/battle_script_commands.c

Fixed instances of gSideTimers not using side constants

---

src/battle_main.c

fix an oversight that caused battles to continuesly be double battles

---

include/battle_interface.h
src/battle_interface.c

Closes #2887
Also removes unused/old function.
Pikachu#1631

Fix safari zone

---

.github/pull_request_template.md

Added a little nudge that PRs with images are more likely to get accepted quicker ^^;

Improved PR Template

---

src/party_menu.c

I can't believe all the tracking and time reading code just for this fix lol
Fixes #2917
Pikachu#1631

Fix Rare Candies

---

include/config/battle.h

Changes config settings for animations.

Set new animations as default

---

include/config/battle.h

Extremely important PR for v1.5, kappa.
Lunos#4026

Fixed typo in include/config/battle.h

---

src/battle_script_commands.c

Title.
Before:
After:
Fixes #2966 

Fixed Mimikyu's Disguise not breaking

---

src/battle_debug.c

Before and After:
Extra image to make sure Frostbite is shown correctly:
Fixes #2977 

Fixed Frostbite icon appearing in AI Party menu for mon without ailment

---

data/battle_scripts_1.s

Added `setgraphicalstatchangevalues` in `BattleScript_SpeedBoostActivates`.
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/841f30a3-679a-440a-9998-c5311b836859
Fixes #3030

Fixes Speed Boost animation

---

src/data/battle_moves.h

Updated preproc config for Diamond Storm

---

gflib/string_util.c
gflib/string_util.h
include/union_room_chat.h
src/easy_chat.c
src/union_room_chat.c

First part of #2567. Ported from #2363.

Easy Chat always shows words in uppercase

---

src/battle_anim.c

Fix Light Of Ruin freeze and potentially other move anims

---

data/battle_anim_scripts.s

Added `ANIM_TAG_WHIP_HIT` in the Grassy Glide script which was needed for `GrassPledgeMiddleFountain` 
Before:
After:
rainonline

Fix Small Grassy Glide anim bug

---

data/battle_scripts_1.s

Fix disobedience wrong move effect issue

---

src/battle_interface.c

Fixes #3053
Fixes #2991
Fixes #2925
Fixes the real reason why the moves stopped working after the mega indicator refactor(as ghoul noticed earlier). I modified the code, so it doesn't create 12 sprites(3 for 4 battlers), but just 1 per battler and then changes the indicator icon on the fly to mega/omega/alpha.
I tested it on a 2v2 and it worked fine, hopefully there won't be any hidden issues this time.
#3084 is still worth merging though.

Change Mega evo sprites from 3per battler to 1 per battler

---

src/battle_interface.c

Fixes #2921
This time setting master as a base, since it's a bug fix.

Fix ability pop-up properly updating text

---

include/battle.h
src/battle_debug.c
src/battle_util.c
src/battle_z_move.c

Fixes #2979
As Eduardo noticed, there isn't much of a need for an effect override now that all of the items are present in one branch.

Remove debug item effect override

---

include/test_runner.h
test/test_runner_battle.c
tools/mgba-rom-test-hydra/main.c

Failed test names are now displayed on the test totals.
Due to how `Test_ExitWithResult` is handled, I can't quite figure out how to show show the corresponding file/line as well.

Failed tests are now listed in the total

---

src/random.c

On modern only we need to include `alloca.h`.
Replaced modulus with a multiply and shift.

Shuffle fixes/improvements

---

src/battle_message.c

Fix trainer slide messages appearing for frontier trainers

---

include/config.h

I think it's about time to do this.

Set GEN_LATEST to GEN_9

---

include/pokemon.h

Nothing was using it, despite what the comment suggested.

Reverted BattleMove power to u8

---

src/battle_script_commands.c

Nothing major, just a small pro-readability and total-line-number-reducing change.
Lunos#4026

Updated Cmd_jumpifsideaffecting

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml

Updated versions for issue templates

---

src/battle_util.c
src/battle_z_move.c

Allow Z-Moves to be selected after Mega Evolution

---

src/battle_controller_player.c
src/battle_interface.c

Moved the Ball Icon one pixel.  https://discord.com/channels/419213663107416084/774393519569502268/1144410312473329805
Made pushing B undo holding the button to throw the ball if the ball was not yet thrown. 
https://discord.com/channels/419213663107416084/774393519569502268/1144742829697028186
devolov

Poké Ball shortcut tweaks

---

src/battle_gfx_sfx_util.c
src/battle_util.c

Fixes some inconsistent or missing uses of gActiveBattler
Closes #3257

Some gActiveBattler Fixes

---

src/battle_script_commands.c
src/data/battle_moves.h

Fixes #3167
Fixes #3224
Mainly Beat Up but I sneaked in a Chloroblast fix

Fixes Beat Up + Chloroblast

---

data/battle_anim_scripts.s

Fix Magnet Rise animation

---

src/battle_script_commands.c
test/battle/ability/battle_bond.c

Fixes #2431
Adds tests for Battle Bond

Battle bond tests and small fix

---

src/battle_controller_player_partner.c

I forgot to update one part of the switch logic for the ai vs ai functionality.

Fix ai vs ai battles switch issue

---

include/item.h
src/data/items.h

We already removed the unused `ItemId_GetId`, so might as well removed the unused field itself.

Removed unused itemId field

---

src/battle_util.c

The PR wasn't solved properly so I'm reverting it.
No force push this time.

Revert "Implement Enigma Berry's hold effect"

---

src/battle_util.c
test/battle/hold_effect/enigma_berry.c

Implement Enigma Berry's hold effect + tests

---

src/battle_util.c
test/battle/move_effect/bug_bite.c
test/battle/move_effect/fling.c

Bug bite/Fling enigma berry interaction & tests

---

data/battle_anim_scripts.s
src/battle_anim_new.c

Had these 2 for a while. Decided to finally PR since I don't know if I make more in the near future.
Bitter Blade:
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/c9dedc5a-a322-4564-a2e3-05ffd5703985
Double Shock:
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/9852c24e-db78-4f1b-b649-df0bf3d4d510
I don't feel strongly about them so if someone makes better ones they can be replaced.

Bitter Blade and Double Shock animations

---

src/battle_util.c
test/battle/ability/toxic_debris.c

Fixes Toxic Debris activating when the ability user faints + Test

Fix Toxic Debris after user faints

---

src/battle_script_commands.c
src/battle_util.c

GetBattlerHoldEffect usage optimizations

---

data/battle_scripts_1.s
test/battle/hold_effect/berserk_gene.c

Fix Berserk gene issue in double battles

---

data/battle_scripts_1.s
test/battle/ability/contrary.c

Fix Intimidate Contrary in double battles

---

src/party_menu.c

Implements Repeated Medicine (https://github.com/pret/pokeemerald/wiki/Repeated-Field-Medicine-Use) with support for EXP Candies (and Dynamax Candy).
Jasper#5206

Implement Repeated Medicine feature

---

src/data/pokemon/species_info.h

Fixed Bergmite/Avalugg updated egg groups

---

src/data/pokemon/species_info.h

Completed the missing changes from #3419, Zacian and Zamazenta also had their stats updated.
Converted Cresselia's #if blocks to a ternary.

Updated Zacian/Zamazenta stats to Gen 9

---

include/config/battle.h
src/battle_controller_player.c
src/battle_controller_safari.c

[Pushing B will now make the cursor move to Run in wild encounters.](https://github.com/pret/pokeemerald/wiki/Push-B-in-wild-battle-moves-to-Run)
Credit to FRLG+ from Deo for the inspiration.
(Gif is from regular Emerald, but it's the same idea in the expansion).
devolov
[Start of Discord Context](https://discord.com/channels/419213663107416084/774393519569502268/1156712441892307066)

Push B in wild battle moves to Run

---

data/battle_scripts_1.s
test/battle/move_effect/make_it_rain.c

Fixes  #3431
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/c112fbb0-5a35-45d6-a188-1d431675cb5a

Fixes Make it Rain in double battles

---

test/test_runner_battle.c

As reported by @AsparagusEduardo [here](<https://discord.com/channels/419213663107416084/1077009799293710357/1165490585793208360>).

Fix battle test estimateCost bug

---

src/battle_main.c
test/battle/trainer_control.c

Fix ModifyPersonalityForNature

---

test/battle/trainer_control.c

What title says, hopefully this is it now :T
Yes
No
karathan

fix -Wmaybe-uninitialized for ModifyPersonalityForNature test

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/03_feature_requests.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
.github/ISSUE_TEMPLATE/config.yml
INSTALL.md
data/battle_scripts_2.s
src/battle_dome.c
src/battle_interface.c
src/data/items.h
src/fieldmap.c
src/pokemon_animation.c
src/pokemon_debug.c
test/battle/hold_effect/eject_button.c
test/battle/move_effect/hydro_steam.c
test/battle/move_effect/revival_blessing.c
test/battle/move_effect/roost.c
test/battle/move_effect/teatime.c
test/battle/weather/rain.c
test/battle/weather/sunlight.c

Since pret got this merged, lets do it here
kittenchilly

Remove all trailing whitespace (master)

---

include/config/battle.h
src/battle_ai_main.c
src/battle_ai_switch_items.c
src/battle_ai_util.c
src/battle_script_commands.c

See title
Fixes #3478 
bassoonian

Adds Illuminate's Gen9 effect

---

data/battle_scripts_1.s
test/battle/move_effect/strength_sap.c

Fixes #3357
Replaces #3358
Ghoul's fix + tests

 Fix strength sap on substitute

---

test/battle/ability/weak_armor.c

Added some tests that confirmed #3492.

Additional Weak Armor tests

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
CHANGELOG.md
README.md

Changelog available in the commit changes.

Version 1.6.2

---

include/battle.h
src/battle_util.c
test/battle/ability/anger_shell.c

Fix Anger Shell activation

---

src/battle_interface.c

Fixed Dynamax's indicator not disappearing after Dynamax ends

---

.github/workflows/build.yml

CI started failing with our current setup. This fixes the issue.
Credit to @hedara90

DKA container fix

---

data/battle_anim_scripts.s
src/battle_anim_effects_1.c
src/battle_anim_water.c

Supersedes #3337
Phantom Force and Trick or Treat didn't have any animation. The rest are improvements.
All credits go to Captain-Ford
Phantom Force
Trick or Treat
Acrobatics
Head Smash
Psyshock
Charge Beam

Move animations. Credits to Captain-Ford

---

Makefile

Agbcc let us know about if an array index was initialized more than once, which is not the case in modern currently.

Added -Woverride-init Makefile flag

---

README.md

Updated README.md to point to the configs easier

---

README.md

Apparently, the current description causes people to clone pret's pokeemerald to merge the expansion into it. Hopefully this helps.

Improve project's description

---

test/battle/hold_effect/white_herb.c

Closes  #3501
Most of them fail so they are marked.

Adds White Herb tests

---

README.md

Since we don't like it when work goes uncredited, I added a small section in the README asking for credits.

Ask users for credits in README.md

---

include/random.h
src/battle_util.c
test/battle/ability/trace.c

Fixed Trace

---

include/pokemon.h
src/pokedex.c
src/pokedex_plus_hgss.c

Fixed non-HGSS dex showing 4 digits in list when National Dex is disabled

---

include/constants/form_change_types.h

Should be param1 instead of param2

Fixed FORM_CHANGE_ITEM_USE_MULTICHOICE documentation

---

src/data/pokemon/species_info.h

Fixes H Sneasel's type

---

include/config/battle.h
src/battle_script_commands.c

Add Gen5 Imprison config

---

src/debug.c

Adds the move reminder to the debug menu
Fixes #2398 
bassoonian

Add Move Reminder to debug menu + organization

---

src/battle_bg.c

Fixed a regression that happened in #2417.

Fixed LoadChosenBattleElement documentation

---

src/data/pokemon/form_change_table_pointers.h

Solgaleo and Lunala are part of the same family :)

Fixed bad use of family defines

---

include/constants/species.h

No spoilers besides mon count.

Reserved Species IDs for Indigo Disk

---

ld_script.ld

Fixed ld_script.ld artifact from a previous pret version

---

.github/pull_request_template.md

Thinking about it, it could be improved.

Broader description for PR template

---

data/battle_anim_scripts.s

Fix Fiery Wrath anim

---

test/battle/move_effect/ivy_cudgel.c

Fixed Ivy Cudgel test name

---

src/battle_controller_player_partner.c

like the title says. TryShinyAnimation was missing in Controller_PlayerPartnerShowIntroHealthbox

Add TryShinyAnimation to Player Partner Send out

---

data/battle_scripts_1.s
src/battle_script_commands.c
test/battle/move_effect/roost.c
test/battle/move_effect/telekinesis.c

Fixes #3679
Also corrects the string used.
And fixes one Roost known failing.

fix telekinesis not working

---

test/battle/item_effect/escape.c
test/battle/item_effect/restore_pp.c
test/battle/item_effect/revive.c
test/battle/item_effect/throw_ball.c

This PR adds the last tests and `TO_DO` tests needed to review #3524.
Tests that have been added as `TO_DO` are tests that either aren't possible to write right now, or that I don't know if they *can* be written currently.
lunos4026

Added last CannotUseItemsInBattle tests

---

src/debug.c

fix debug menu toggling first flag

---

src/battle_tower.c

Regression caused by https://github.com/rh-hideout/pokeemerald-expansion/pull/3592/commits/fe1bad68b4e7fe37de7a33b5cdab5ef6314d1a00
graiondilach

Prevent infinite loop.

---

data/battle_scripts_1.s
include/battle_scripts.h
include/constants/battle_string_ids.h
src/battle_message.c
src/battle_util.c
test/battle/ability/hospitality.c

Adds Ability Hospitality

---

src/overworld.c

Clear Sky Battle & Dynamax flags upon whiteout

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
CHANGELOG.md
README.md
docs/changelogs/1.7.1.md
include/constants/expansion.h

1.7.1 master changes because oops

---

Makefile
include/crt0.h
include/gba/defines.h
ld_script.ld
ld_script_modern.ld
ld_script_test.ld
src/crt0.s
src/main.c
src/reload_save.c

Reverts rh-hideout/pokeemerald-expansion#3877

Revert "Allocate initialized sections for EWRAM and IWRAM"

---

src/pokemon_summary_screen.c

Fix summary screen nature colours after mints

---

include/pokemon.h
src/battle_ai_util.c
src/battle_util.c
src/data/battle_moves.h
test/battle/move_effect/clanging_scales.c

Reverted #3976 from master to add it here.

Renamed healBlockBanned to healingMove

---

src/data/battle_moves.h

- Revert Sky Attack critboost.
- Revert Crunch nerf.
- Restore Burning Jealousy accuracy.
graiondilach

Revert accidental move changes.

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
CHANGELOG.md
README.md
docs/changelogs/1.7.2.md
docs/changelogs/template.md
include/constants/expansion.h

Changelog in `docs/changelogs/1.7.2.md`.
Also added changelog template and updated issue templates to specify between unreleased master and latest release.

Version 1.7.2

---

src/berry.c

Fix a typo in the Berry Exp. config setup.

---

src/data/pokemon/teachable_learnsets.h

Removes several illegal moves from teachable learnsets
Partially fixes (but not completely) #4027 
bassoonian

Remove faulty teachable learnset moves

---

src/battle_ai_util.c
src/battle_script_commands.c
test/battle/ability/corrosion.c

Fixes ability Corrosion

---

src/data/items.h

Proposal of item description adjustment.

Adjusted item description alignment

---

src/battle_util.c
test/battle/ability/emergency_exit.c

Fixes test description + small fix follow up

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
CHANGELOG.md
README.md
docs/changelogs/1.7.2.md
docs/changelogs/1.7.3.md
docs/changelogs/template.md
include/constants/expansion.h

Changelog in `docs/changelogs/1.7.3.md`.
Also fixed title in 1.7.2 changelog

Version 1.7.3

---

data/battle_scripts_1.s

Fixes Eerie Spell double pp and message drop

---

src/battle_util.c

Fix disobedience not resetting multihit moves

---

.github/pull_request_template.md

This will make it much easier to credit them in the changelogs.

Added credits section to PR template

---

src/battle_main.c
src/battle_script_commands.c
test/battle/ability/opportunist.c

Fixes Opportunist accumulating stat changes

---

gflib/malloc.c
include/constants/metatile_labels.h
src/battle_anim_ghost.c
src/berry_blender.c
src/contest_effect.c
src/decompress.c
src/decoration.c
src/dodrio_berry_picking.c
src/map_name_popup.c
src/mini_printf.c
src/slot_machine.c
tools/gbagfx/convert_png.c
tools/jsonproc/jsonproc.cpp

Pret merge 2024/02/10.
- SHA1 before merge: `b58a8fc0de85151116651b595b8c6aee57fa7985`
- SHA1 after merge: `aa80b892f696975188f4c837f84862d0ed6ae0aa`
- Confirmed that the change was after a new UBFIX in `HideMapNamePopUpWindow`.

Pret merge 2024/02/10

---

include/config/battle.h
src/battle_script_commands.c
test/battle/move_effect/uproar.c

Adds config for Soundproof change during Uproar status

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
CHANGELOG.md
README.md
docs/changelogs/1.7.4.md
include/constants/expansion.h

Changelog in `docs/changelogs/1.7.4.md`.
Small stopgap before 1.8.0, which will release as soon as it's ready instead of waiting for the full 2-week cycle.

Version 1.7.4

---

data/battle_scripts_1.s
test/battle/ability/mirror_armor.c
test/battle/ability/tangling_hair.c
test/battle/move_effect/rage_fist.c

Fixes Tangling Hair, Rocky Helmet interaction

---

include/data.h
include/pokemon.h
src/battle_ai_main.c
src/battle_bg.c
src/battle_controller_opponent.c
src/battle_controller_player_partner.c
src/battle_dome.c
src/battle_main.c
src/battle_message.c
src/battle_script_commands.c
src/battle_setup.c
src/battle_tower.c
src/battle_transition.c
src/data/trainers.h
src/frontier_util.c
src/match_call.c
src/pokemon.c
src/pokenav_match_call_data.c
src/pokenav_match_call_list.c

Made all Trainer data accesible via inline functions to avoid out-of-bounds access.
Also unified Dome Brain data access with the rest of the Frontier Brain data access, and tested in-game to make sure it doesn't break anything.
Fixes #4215 

Trainer data encapsulation

---

src/battle_ai_main.c
src/battle_main.c

Fixes #4221 and flags in ai vs ai battle

AI sets up double flags correctly

---

include/config/battle.h

Credit to BrandonXL on Discord for finding this

Fixed config comment

---

src/battle_ai_util.c

Found this while doing the changelog.

Fixed AI considering Mold Breaker but not Turboblaze/Teravolt for flinch-related decisions

---

src/data/pokemon/species_info/gen_1.h

Fixed P_FOOTPRINTS not compiling when set to false

---

ld_script_modern.ld

Fixed in https://github.com/pret/pokeemerald/pull/1978

gHeap can go in the middle of ram

---

gflib/malloc.c
src/pokedex_cry_screen.c

Pret merge 07.03.2024
- SHA1 before merge: 2C956078BAF6F46A96C7A673E1EECAAD002B8485
- SHA1 after    merge: 2C956078BAF6F46A96C7A673E1EECAAD002B8485

Pret merge 07.03.2024

---

include/battle.h
src/battle_main.c

Fixes #4265 by computing quick claw/quick draw random percentages up front

fix repeated quick claw/quick draw checks

---

include/metaprogram.h

Improve error message with unsupported cpp

---

README.md

Fix 1.7.3 reference in README.md

---

src/main.c

Desynchronization can occur otherwise.
roseareazero

Do not do VBlankIntrWait if using the wireless adapter

---

include/pokemon.h

In #4281, I forgot to adjust the padding for species flags.
Thank you @Bassoonian for letting me know of this.

Fixed species flag padding

---

INSTALL.md

Fixed a typo in the python install instructions for WSL1 and msys2. Fixed formatting for python install instructions for WSL1.
Incorrect/misformatted install instructions
ravepossum

Small fixes to Python install instructions

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
CHANGELOG.md
README.md
docs/changelogs/1.8.1.md
include/constants/expansion.h

Version 1.8.1 (hotfix)

---

src/battle_main.c

Fixes #4297
@Bassoonian was right and found the bug's cause

fix broken battle arena gfx

---

include/battle_z_move.h
src/battle_script_commands.c
src/battle_util.c
src/battle_z_move.c

Fixes #4283
I'd like to write a test for Z Mirror-Move before this gets merged though. And maybe some generic tests for Z-moves. I'm not 100% familiar with the code and how they work, so I hope I didn't break anything here.

Fix Z mirror move

---

src/battle_controller_player.c
src/battle_interface.c

Fixes Soft Level Cap issue

---

test/battle/ability/defiant.c

Missing Defiant tests

---

README.md

Hopefully this will help with users to not fall into this trap.

Clarify to not use the "Download ZIP" option

---

migration_scripts/convert_parties.py

Fix trainer_starting_status_definition

---

Makefile

See Discord discussion and troubleshooting ([here](https://discord.com/channels/419213663107416084/1172105648373248060/1227603723803693117) and down)
Fix courtesy of @mrgriffin

Makes trainerproc OSX-compatible

---

src/battle_script_commands.c
test/battle/move_effect/stuff_cheeks.c

Fixes bug preventing Belch from usage after Stuff Cheeks

---

data/battle_scripts_1.s
src/battle_util.c
test/battle/move_effect/cud_chuw.c

Fixes Cud Chuw

---

src/battle_util.c
test/battle/hold_effect/eject_pack.c

Credits to @skolgrahd for the find and fix
Test fails without the fix

Fixes Eject Pack softlocking the game

---

.github/ISSUE_TEMPLATE/01_battle_engine_bugs.yaml
.github/ISSUE_TEMPLATE/02_battle_ai_issues.yaml
.github/ISSUE_TEMPLATE/04_other_errors.yaml
CHANGELOG.md
README.md
docs/changelogs/1.8.0.md
docs/changelogs/1.8.2.md
docs/changelogs/template.md
include/constants/expansion.h

Draft until certain PRs are merged and when the changes to the README are approved

Version 1.8.2

---

src/battle_ai_switch_items.c
test/battle/ai.c

Fix and test provided by @Pawkkie

Fix bug infinite loop when player mon has only status moves

---

include/constants/battle_ai.h
src/battle_ai_main.c
src/battle_ai_switch_items.c

When I merged PR #4405 I didn't review it carefully enough so this is a small follow up.

Couple comment changes 

---

src/daycare.c

This fixes potential issues regarding ability inheritance for species/abilities past 255.

Fixed data types for Ability inheriting

---

src/wild_encounter.c

Found by Rahtak on Discord.
This caused cases such as encountering Kadabra instead of Wailmer.

Fixed data type for generated fishing species

---

src/data/moves_info.h

Fixes Will-O-Wisp's capitalization in gMovesInfo

---

include/data.h
src/battle_tower.c

Fixes Steven's trainer class string being messed up (and some other hypothetical errors)
Fixes #4398 
bassoonian

Partner fixes

---

src/battle_interface.c

Fix ABILITY_POPUP not respecting abilityPopupOverwrite in tests

---

src/pokemon.c

[See Discord for context](<https://discord.com/channels/419213663107416084/774393519569502268/1231949812094472235>).
Also makes some very minor formatting changes.

Fix GiveBoxMonInitialMoveset_Fast

---

src/data/items.h

https://discord.com/channels/419213663107416084/774393519569502268/1232372639562072084

Fix typo in Rotom Catalogue

---

src/data/abilities.h

Make Fur Coat breakable

---

asm/macros/event.inc
src/script_pokemon_util.c
test/pokemon.c

Adds `checkteratype` and `setteratype` as scripting commands.
Fixes #4436 
bassoonian

Add checkteratype setteratype

---

data/battle_scripts_1.s

Fixed Future Sight script whitespace

---

test/battle/hold_effect/eject_pack.c

Improve Eject Pack test names

---

src/party_menu.c

Fixes #4254 
Credit to @LOuroboros for the fix.

Fixed Flute Items being consumed in battle

---

src/battle_ai_util.c
test/battle/move_effect/hit_set_remove_terrain.c

Fixed Steam Roller AI check affecting Terrain setting effects

---

src/pokedex.c
src/pokedex_plus_hgss.c

Removed stellar type from pokedex search

---

src/item_icon.c

Also made the style more consistent by using multiple return points at every step.
duke5614

Rewrote GetItemIconPicOrPalette (again) to factor in customized HM counts

---

src/battle_gfx_sfx_util.c

Fixes #4483
Does not fix `#4485`
duke5614

HandleSpeciesGfxDataChange uses the correct battler index

---

include/battle_ai_main.h
include/battle_ai_util.h
src/battle_ai_main.c
src/battle_ai_util.c
test/battle/ai.c

Added missing effect checks in `AI_IsMoveEffectInMinus`.
Some evasion and accuracy increasing effects were incorrectly handled.
Contrary self stat reduction checks were run but they were completely cancelled in `IncreaseStatUpScore` afterwards.
duke5614

Stat stage related AI fixes

---

src/debug.c

Fix debug ability u8

---

include/config/pokemon.h
src/daycare.c

Step 1: find out egg cycles were shortened in SwSh
Step 2: make a PR
Step 3: ???
Step 4: profit
bassoonian

Add egg cycle length config

---

src/battle_anim_smokescreen.c
src/pokemon.c

Also moved a comment back where it belongs.
duke5614

Restore sassy nature's original effect

---

src/battle_script_commands.c

Please merge my OCD induced change.

BS_SetGlaiveRush formatting

---

data/battle_scripts_1.s

Fixed HITMARKER_PASSIVE_DAMAGE script whitespace

---

src/data/abilities.h

Title. Redirected to master :^)

Updated Disguise to be a Breakable Ability

---

data/battle_scripts_1.s
test/battle/ability/intimidate.c

Fixes #4627 but only in upcoming for now. The fix was made possible by  #4061 that was merged yesterday. I'll try to pr a hacky solution for master tomorrow.

Fixes Neutralizing Gas / Intim interaction freezing the game

---

src/battle_main.c
test/battle/ability/ate_abilities.c

Adjusts the code a bit and the switch statement should make it more clear how to add a new ate ability.

Adjust Ate-Ability code a bit to make it more readable

---

include/battle_ai_util.h
src/battle_ai_main.c
src/battle_ai_switch_items.c
src/battle_ai_util.c

`AI_IS_SLOWER` and `AI_IS_FASTER`comparisons are used a lot in the AI code so I've made functions `AI_IsSlower` and `AI_IsFaster` to avoid writing the comparison each time.

Adds AI_IsFaster and AI_IsSlower functions

---

src/battle_controller_player.c

In battle move details UI shows the corrent move's description

---

src/battle_script_commands.c

AI got the wrong calc when the global was used.

replace gCurrentMove with move in CalcCritChanceStageArgs

---

test/battle/ability/gale_wings.c

This is being PR'd by itself because it needs some features from upcoming, I have another bigger test PR coming but it'll get pointed to master like my current one :)
@Pawkkie

Gale Wings test

---

docs/book.toml

Ensure `fix_links.py` is applied after includes, so that it's able to affect `README.md`/`INSTALL.md`/`CHANGELOG.md`.
leo60228

Ensure correct mdBook preprocessor ordering

---

src/battle_util.c
test/battle/move_effect_secondary/thrash.c

Also removes incorrect assumes in 2 tests.
duke5614

Rampage moves always confuse on final turn 

---

include/list_menu.h

Fixes #4721
@RavePossum
@sneed69
bassoonian

Fix opening the debug menu in a Poké Center resetting the game on upcoming

---

src/data/items.h

Fix Hyper Potion price

---

asm/macros/event.inc
include/constants/battle_setup.h
src/battle_setup.c

Adds 1 vs 2 macro
